### ISSUE TITLE
ubuntu 18.04 python binding install error

### ISSUE THREAD

**Issue by yngweijs** [JonathanSalwan/Triton#1008]
I successfully install the triton on ubuntu 18.04, but when i import triton and create context with "ctx = triton.TritonContext()", i got the following error: "AttributeError: module 'triton' has no attribute 'TritonContext'".

**Comment by JonathanSalwan** [comment]
how did you installed triton?

**Comment by yngweijs** [comment]
Here is my install instructions:
```
git clone https://github.com/JonathanSalwan/Triton.git
cd Triton
mkdir build
cd build
cmake ..
sudo make -j2 install
```

**Comment by JonathanSalwan** [comment]
And can you provide all the cmake output? I'm pretty sure the triton you installed to Python packages is not the one you compiled from `cmake`. Did you never used `pip install triton`? Because the pip package is not our triton.
