### ISSUE TITLE
Trace Broken at Jmp Inst

### ISSUE THREAD

**Issue by cxm95** [JonathanSalwan/Triton#1009]
Hi! There are some interesting findings during my using the Triton with Pin tracer. 

I used cbBefore as `INSERT_POINT.BEFORE` cb function, and print all instructions. 
However, when running some binaries with glibc, the target of jmp instruction missed in trace.

I found 7 broken jmp inst in glibc and other libraries during a single exec and this also happened in execution of other binaries. 
There is no pattern so I don't know how to debug it.

Sample here:
```asm
0x7fff72d327cc: jb 0x7fff72d327e1
0x7fff72d327ce: jmp [0x7fff72d32488] [094488: mov esi, cs:dword_3ED92C]
0x7fff7346253e: test rax, rax
0x7fff73462541: je 0x7fff73462550
```
```asm
0x7fff72d3ba3a: pop rbp
0x7fff72d3ba3b: mov rdi, rax
0x7fff72d3ba3e: jmp [0x7fff72cbf160] [021160: jmp cs:off_3EB0D8]
0x4842a9: mov qword ptr [rsp + 8], rax
0x4842ae: lea rsi, [rip + 0x231cf]
```

Env: 
Kernel version:  4.15.0-128-generic
Pin version: 71313
Triton version: 1b32e67cab2a0b6e623695dcaacf627c03985a13 (newest)

**Comment by cxm95** [comment]
Traces are also found broken at some Call Inst.
Sample: 
```asm
0x7fff72d29846: call 0x7fff72cbf160
0x7fff72d2984b: add qword ptr [rbx + 8], r15
```

**Comment by JonathanSalwan** [comment]
Hi,

I'm not sure it's related to Triton. I've also noticed this kind of behavior using Pin, it's probably due to DBI design.

**Comment by JonathanSalwan** [comment]
To confirm this, you should try to print instructions using Pin only and see if the Pin's trace differs from the Triton tracer one.
