### ISSUE TITLE
ARM32 IT/ITE Insturctions Support

### ISSUE THREAD

**Issue by black-binary** [JonathanSalwan/Triton#1010]
There are some IT/ITE instructions in the program that I'm looking into. But Triton failed to deal with these instructions. Then I found that IT/ITE instruction's sematic building function is not implemented. 

https://github.com/JonathanSalwan/Triton/blob/1b32e67cab2a0b6e623695dcaacf627c03985a13/src/libtriton/arch/arm/arm32/arm32Semantics.cpp#L98-L146

**Comment by SweetVishnya** [comment]
@JonathanSalwan, it may somehow switch architecture Thumb/non-Thubm for disassembly.

**Comment by black-binary** [comment]
> 
> 
> @JonathanSalwan, it may somehow switch architecture Thumb/non-Thumb for disassembly.

Oh, I forgot to say that I enabled the Thumb mode. It's correct to disassemble these instructions in Thumb mode.

**Comment by JonathanSalwan** [comment]
Indeed we are aware of that and currently ITx instructions are not supported due to the Triton design where instructions are handle one by one and not by block.

**Comment by black-binary** [comment]
@JonathanSalwan The ITx instructions only change CPSR bits [26:25] and [15:10]. So if we maintain the symbolic and concrete values of these bits, I think it's possible to implement ITx instruction in Triton. However, it will be a little bit hard and costly to implement. So my current workaround is to replace IT instructions with B{cond} and it works well.

**Comment by black-binary** [comment]
BTW, I'm currently working on adding some commonly used instructions semantics of ARM32, but I'm not sure how to add a unit test for them. The unit tests .py files seem like were generated by some scripts. It there any documents about the tests? :)

**Comment by JonathanSalwan** [comment]
> The unit tests .py files seem like were generated by some scripts. It there any documents about the tests? :)

They have been added by hand :)

**Comment by cnheitman** [comment]
`IT` instruction is not supported yet for the reasons already discussed. However, 
we've been dealing with it manually (and individually), as shown in this test script: 
https://github.com/JonathanSalwan/Triton/blob/master/src/testers/arm32/crypto_test/crypto_test-thumb-Os-run.py#L219
