### ISSUE TITLE
How to use Triton for taint analysis

### ISSUE THREAD

**Issue by misalungi** [JonathanSalwan/Triton#1013]
Hi,

I have a C++ project with several files. I want to use Triton to analyze taint propagation of one of my variables in all the files.
How should I pass my variable to Triton taint functions?
After adding Triton functions to my code, should I simply compile the code or there is a command to do taint analysis?

Thanks! 

@JonathanSalwan

**Comment by JonathanSalwan** [comment]
Do you means like Klee? Triton is not working like Klee at all, it analyzes binary code. [Examples here](https://github.com/JonathanSalwan/Triton/tree/master/src/examples)
