### ISSUE TITLE
Appveyor is deleting build artifacts making it impossible to access precompiled binaries

### ISSUE THREAD

**Issue by MrSynAckSter** [JonathanSalwan/Triton#1015]
You have currently configured the Appveyor artifacts to delete every two months.

You build less frequently than this.

Therefore, in the Windows build instructions where it suggests that I can download pre-compiled artifacts:
"However, if you prefer to directly download precompiled libraries, check out our AppVeyor's artefacts" 

I cannot actually do this since the build artifacts are deleted. 

![triton-come-on](https://user-images.githubusercontent.com/61598769/121288826-fb8cb000-c8b1-11eb-9677-752010519944.PNG)

**Comment by SweetVishnya** [comment]
@JonathanSalwan, can we rsync some amount of latest nightly builds and releases to a ftp server?

**Comment by JonathanSalwan** [comment]
> @JonathanSalwan, can we rsync some amount of latest nightly builds and releases to a ftp server?

That's a good point. Meanwhile i've [rebuild artifacts](https://ci.appveyor.com/project/JonathanSalwan/triton/builds/39532441).

**Comment by SweetVishnya** [comment]
Also, we should have some Python bindings installation docs for both Linux and Windows (#1018).

**Comment by JonathanSalwan** [comment]
> Also, we should have some Python bindings installation docs for both Linux and Windows (#1018).

If you have some doc about Windows, i'll take it :)

**Comment by SweetVishnya** [comment]
I do not use python bindings myself(

**Comment by JonathanSalwan** [comment]
I'm colsing this, ping me if you want to rebuilt artefact
