### ISSUE TITLE
Do triton work with aslr ? 

### ISSUE THREAD

**Issue by kaitogon** [JonathanSalwan/Triton#1020]
Hi I have a question please ? I am working in my python module to test the generated PE  code_coverage written in C and to generate asm instruction do I need to deal with aslr or triton and ida disassembler are not affected by aslr ?

Another question please ? If I close the ida and reopen it, do the addresses of asm instructions change ? And do I need to re-define them in my triton python script ? 
And thank u for your response

**Comment by SweetVishnya** [comment]
Triton uses fixed addresses you provide for instruction.

**Comment by kaitogon** [comment]
okay and to get the assembly instructions and addresses for each instruction do I need to use a disassembler ?

**Comment by SweetVishnya** [comment]
Triton has a capstone disassembler inside, you can just provide raw opcodes.

**Comment by kaitogon** [comment]
okay I understand. Thank you

**Comment by kaitogon** [comment]
Last question please ? Do I need to disable aslr to work with ida and triton ? for disassembly opcodes ? 
and thank u for your response

**Comment by JonathanSalwan** [comment]
do not care about aslr. Just provide address of IDA's instructions to Triton that's all.

**Comment by kaitogon** [comment]
okay thank you for your help. Now I understand
