### ISSUE TITLE
What does the TritonExecution.run do ?

### ISSUE THREAD

**Issue by kaitogon** [JonathanSalwan/Triton#1021]
Hi I have a question please ? I have read the (Code coverage using a dynamic symbolic execution) and the triton blog (https://triton.quarkslab.com/blog/Code-coverage-using-dynamic-symbolic-execution/) and the question is what does  TritonExecution.run("bad !", 0x400480, 0x40061B, ["main", "check"]) do in the code: 

175. if __name__=='__main__':
176.   TritonExecution.run("bad !", 0x400480, 0x40061B, ["main", "check"])

and what is the role of these addresses (0x400480,0x40061B) in this function ? and thank you for your response

**Comment by JonathanSalwan** [comment]
This blog post is not up-to-date. If you want to investigate about code coverage. See this [example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/code_coverage_crackme_xor.py).

**Comment by kaitogon** [comment]
okay interesting thank's for the information !
