### ISSUE TITLE
What does the address of the serial pointer mean ?

### ISSUE THREAD

**Issue by kaitogon** [JonathanSalwan/Triton#1022]
Hi I am looking in the code coverage code in python in the examples directory in triton master folder, and I see this code: 

    # Define the address of the serial pointer. The address of the serial pointer
    # must be the same that the one hardcoded into the targeted function. However,
    # the serial pointer (here 0x900000) is arbitrary.
    Triton.setConcreteMemoryValue(0x601040, 0x00)
    Triton.setConcreteMemoryValue(0x601041, 0x00)
    Triton.setConcreteMemoryValue(0x601042, 0x90)

the question is what does the serial pointer mean ?

**Comment by JonathanSalwan** [comment]
Please do not open issue as soon as you have a question related to your Triton usage. Ask on IRC. Github issues are used from real issues related to the internal Triton's components.

For your question, the target use a serial pointer to compute the password. You just have to reverse the crackme to understand what going on.

**Comment by kaitogon** [comment]
Okay I will see this in ida. Thank you for your response !

**Comment by kaitogon** [comment]
Do you mean by  IRC gitter ?
