### ISSUE TITLE
Taint Analysis with fuzzing with triton ?

### ISSUE THREAD

**Issue by kaitogon** [JonathanSalwan/Triton#1025]
Hi I have a question please ? I am fuzzing a simple program and I want to know if the input that I provide simply can maybe reach a function or a block of code ? And if this is possible with triton can I do that with complex or very big applications ? 

The problem that is that I reached the IRC channel at #qb_triton at freenode server but no one respond. And thank you for your help again

**Comment by kaitogon** [comment]
I have a last question please ? Are the same functions of triton working on both Linux and Windows binaries for binary analysis ?

**Comment by SweetVishnya** [comment]
Triton does taint analysis and yes it works with complex programs on both Linux and Windows. You can read the docs to get more info.

https://triton.quarkslab.com/documentation/

**Comment by kaitogon** [comment]
okay understood thanks for your response sir ! The question was because I read a book that talks about binary analysis and triton
but only in linux.

**Comment by SweetVishnya** [comment]
Is there a book about Triton?) wow! can u give a link?

**Comment by kaitogon** [comment]
okay sur the book talks about practical binary analysis (tools which are pin and triton are included you can see the table of content of chapters) triton is in chapter 13 and the book talks a lot about low level and assembly programming.
here is the book if u want to read: https://drive.google.com/file/d/1afbSPPGdH66259LKD_lWC88lKxtz_-am/view?usp=sharing
here is the link in amazon: https://www.amazon.fr/Practical-Binary-Analysis-Instrumentation-Disassembly/dp/1593279124

**Comment by JonathanSalwan** [comment]
Please do not share books that are not open sourced. First, It's just a matter of respect for the author that did hard job to write this book. Second, Github is not a warez platform for such things. That's why, I edited your comment and I removed the link to the book.

**Comment by kaitogon** [comment]
okay I understand.

**Comment by JonathanSalwan** [comment]
I have to delete this thread because of the github history of edited comment
