### ISSUE TITLE
not found symvar3

### ISSUE THREAD

**Issue by sh4m2hwz** [JonathanSalwan/Triton#1027]
full code:
https://pastebin.com/iMnwjA1Z
code.bin(*it is fragment*): b"\xB0\x55\x48\x0F\xC1\xD8\x48\xF7\xD3\x18\xC7\x66\x0F\xA4\xDA\x08\x30\xF4\x0F\xC8\x69\xC8\x31\x46\x00\x00\x66\x52\x44\x0F\x38\xF0\x04\x24\x44\x09\xC1\x41\xF7\xD1\x44\x31\xC9\x7C\xFE\xFF\xC2"

fragments  details:
 (*execute in interpretator*)
`>>> from solve import *
>>> SymCtx = {
...             "symRbx":None,
...             "mem":None,
...             "symMemRsp2":None
...             }
>>> 
>>> t,SymCtx = init(SymCtx)
symbolize:  [@0x7fffffffde40]:16 bv[15..0]
>>> status,unsupInsn,SymCtx = load(t,SymCtx)
0x400078: mov al, 0x55
0x40007a: xadd rax, rbx
0x40007e: not rbx
0x400081: sbb bh, al
0x400083: shld dx, bx, 8
0x400088: xor ah, dh
0x40008a: bswap eax
0x40008c: imul ecx, eax, 0x4631
0x400092: push dx
0x400094: movbe r8d, dword ptr [rsp]
0x40009a: or ecx, r8d
0x40009d: not r9d
0x4000a0: xor ecx, r9d
0x4000a3: jl 0x4000a3
>>> model1,model2 = getBranchModels(t,SymCtx)
>>> model1
{0: SymVar_0:64 = 0xd6c30227}
>>> model2
{0: SymVar_0:64 = 0x928662f}
>>>>t.getSymbolicVariables()
{0: SymVar_0:64, 3: SymVar_3:16}
>>> 
>>> SymCtx["mem"]
[@0x7fffffffde40]:16 bv[15..0]`

how to correct symbolize memory [rsp+2] after push dx?

**Comment by JonathanSalwan** [comment]
> how to correct symbolize memory [rsp+2] after push dx?

```python
rsp = ctx.getConcreteRegisterValue(ctx.registers.rsp)
mem = MemoryAccess(rsp + 2, CPUSIZE.QWORD) # QWORD if you want to symbolize a 64-bits memory access
ctx.symbolizeMemory(mem)
```

If you do not see any `SymVar_3` into your model, it means that the variable does not infer to the results.

**Comment by sh4m2hwz** [comment]
`
>>> c = t.getPathConstrains()
>>> c = c[0]
>>> hex(c.getTakenAddress())
'0x4000a5'
>>> c.getBranchConstraints()
[{'isTaken':False,'srcAddr':4194467,'dstAddr':4194467,'constraint:(= (bvxor ref!73 ref!71) (_ bv1 1)))}, {'isTaken':True,'srcAddr':4194467,'dstAddr':4194469,'constraint':(not (= (bvxor ref!73 ref!71) (_ bv1 1))))}]
>>> m1,m2 = c.getBranchConstraints()[0]['constraint'],c.getBranchConstraints()[1]['constraint']
>>> t.getModel(m1),t.getModel(m2)
({0: SymVar_0:64 = 0x928662f}, {0: SymVar_0:64 = 0xd6830025})
>>> NoTakenVars  = extractVarsModel(t,m1,SymCtx)
>>> TakenVars  = extractVarsModel(t,m2,SymCtx)
>>> isBranchTaken1 = emulate(t,NoTakenVars,SymCtx)
>>> isBranchTaken2 = emulate(t,TakenVars,SymCtx)
>>> isBranchTaken1
True
>>> isBranchTaken2
False
`
Why is m1 which refers to isTaken: False going to address 4194467 when emulating JL?
