### ISSUE TITLE
I need the pre builds binaries of Triton from version 0.1 to 0.6 ?

### ISSUE THREAD

**Issue by kaitogon** [JonathanSalwan/Triton#1028]
Hi I need the pre builds triton binaries (dll and py and lib etc.) from version 0.1 to version 0.6 if this is possible?
I went to appveyor but it delete every month ?

**Comment by RobinDavid** [comment]
Why would you need previous versions of Triton?

**Comment by kaitogon** [comment]
I am working on some of my binary for testing and I am reading this tutorial: https://triton.quarkslab.com/files/sstic2015_slide_fr_saudel_salwan.pdf and after that I import triton I try to use the 
 triton.startAnalysisFromSymbol('check') command but it gives me AttributeError: 'module' object has no attribute 'startAnalysisFromSymbol'. Please I need these older versions to work around because I want to do some testing for some binaries that I have created and compiled. I know that the latest version is good but for me I think that I need some older versions to use triton.  And thank you.

**Comment by RobinDavid** [comment]
Ok, that is a very old API I guess. I don't even remember it. Triton have no knowledge of symbols or anything, it sole input are instruction opcodes to execute. If you want to resolve symbols to addresses, you have to use ad-hoc libraries (such as: https://lief.quarkslab.com//doc/latest/api/python/elf.html#symbol ).

**Comment by kaitogon** [comment]
okay is there a possibility to taint a specific function and then see if there is a condition that the user can handle to reach the function with triton ?

**Comment by kaitogon** [comment]
just a last question ? Is it not possible to get the older version ? I mean if you have it ?

**Comment by kaitogon** [comment]
I try to compile but it gives errors

**Comment by RobinDavid** [comment]
No, taint is a data-flow analysis thus you either taint memory or registers. Testing the reachability of a function could not be resolved through tainting etc. Triton is too low-level to resolve easily such problems. I would recommend trying another framework (like Angr).

No I don't have it.

**Comment by kaitogon** [comment]
okay thank you for your support

**Comment by JonathanSalwan** [comment]
`triton.startAnalysisFromSymbol('check')` comes from the Pintool module i made to port Pin's API to Python bindings. This is very old but still [present](https://github.com/JonathanSalwan/Triton/blob/master/src/tracer/pin/bindings.cpp#L542). However you can not compile the Pintool module to Windows. This module is only available to Linux and Python 2.7.

**Comment by JonathanSalwan** [comment]
Regarding `.dll` from 0.1 to 0.6 we do not have. First because Triton on windows was born around v0.5, then Appveyor comes from later i think.

**Comment by JonathanSalwan** [comment]
> I would recommend trying another framework (like Angr).

who would have thought i will say this but robin is right! If you are looking to deal with binary and not instructions, I recommend to use a sovereign framework like [miasm](https://github.com/cea-sec/miasm).

**Comment by kaitogon** [comment]
okay I understand. thanks again
