### ISSUE TITLE
Issue when decoding ARM32 instructions with CONSTANT_FOLDING optimization activated

### ISSUE THREAD

**Issue by RobinDavid** [JonathanSalwan/Triton#1029]
Hi djo!

You are probably busy atm but I am encountering an issue on ARM32 in thumb mode with the constant folding optim.
Here is a small snippet to reproduce:

```python
from triton import *
ctx = TritonContext(ARCH.ARM32)
ctx.setThumb(True)
ctx.setMode(MODE.CONSTANT_FOLDING, True)
ctx.processing(Instruction(b"\x00#")) # movs r3, #0
```

That raises the exception: **TypeError: IteNode::init(): Must take a logical node as first argument.**

I have not investigated yet what can be the issue, but I will probably do it when having a few spare time.

**Comment by JonathanSalwan** [comment]
I'm gone since few hours that you already give me some work :D. Looks like a bug indeed. Maybe @cnheitman you have some idea?

**Comment by RobinDavid** [comment]
Ahah, that's exactly what I said on IRC ^^. "That moment you find a bug in Triton just after djo left, and you realize that you might wait 14 months" :')

**Comment by cnheitman** [comment]
hmm, not really sure what's going on. I'll take a look.

**Comment by JonathanSalwan** [comment]
Got the bug.

```patch
diff --git a/src/libtriton/ast/astContext.cpp b/src/libtriton/ast/astContext.cpp
index 34d6ae1e..e0c11eeb 100644
--- a/src/libtriton/ast/astContext.cpp
+++ b/src/libtriton/ast/astContext.cpp
@@ -847,11 +847,11 @@ namespace triton {
         throw triton::exceptions::Ast("AstContext::ite(): Not enough memory.");
       node->init();
 
-      if (this->modes->isModeEnabled(triton::modes::CONSTANT_FOLDING)) {
-        if (node->isSymbolized() == false && node->isLogical() == false) {
-          return this->bv(node->evaluate(), node->getBitvectorSize());
-        }
-      }
+      //if (this->modes->isModeEnabled(triton::modes::CONSTANT_FOLDING)) {
+      //  if (node->isSymbolized() == false && node->isLogical() == false) {
+      //    return this->bv(node->evaluate(), node->getBitvectorSize());
+      //  }
+      //}
 
       return this->collect(node);
     }
```

I'm not sure I'm right with the `CONSTANT_FOLDING` optimization on `ITE` nodes. Actually do we have to perform the optimization on `ITE` nodes? I don't think so... (Its children are already optimized)

**Comment by RobinDavid** [comment]
Hum not sure to understand the code of the condition. But for ``ITE`` node, if the condition appears to be a constant you can evaluate it and return directly either children1 or children2 depending on whether the condition is true or not. That can prune the ``ITE`` node which is preferable.

**Comment by SweetVishnya** [comment]
> Hum not sure to understand the code of the condition. But for `ITE` node, if the condition appears to be a constant you can evaluate it and return directly either children1 or children2 depending on whether the condition is true or not. That can prune the `ITE` node which is preferable.

Seems like a great optimization for AST_OPTIMIZATIONS mode. I should definitely find a time and make a PR. This is a good enhancement, but it won't fix an issue)

Moreover, I do not remember whether Triton folds constant logical expressions. Btw, we do not use CONSTANT_FOLDING in Sydr because we have some heuristics on ASTs to detect left array bound. These heuristics break when CONSTANT_FOLDING is enabled.

**Comment by RobinDavid** [comment]
Yes, indeed maybe more in the AST_OPTIMIZATION mode. I shall double check but I think it folds constant logical expressions.
What is the left array bound detection ?

**Comment by SweetVishnya** [comment]
We analyze memory address AST and try to detect array start from it. We use that in out of bounds security predicate when we try to write below the array start.

**Comment by cnheitman** [comment]
It seems the way conditional instructions are generated is conflicting with the `CONSTANT_FOLDING` optimization. The current implementation reuses the node that represents the condition of the instruction in multiple expressions (such as the computation of the flags). For example, the instruction `movs r3, #0` is represented by the following expressions:

```
(define-fun ref!0 () (_ BitVec 32) (ite (= (_ bv1 1) (_ bv1 1)) (_ bv0 32) (_ bv0 32))) ; MOV(s) operation - 0x0: movs r3, #0
(define-fun ref!1 () (_ BitVec 1) (ite (= (_ bv1 1) (_ bv1 1)) ((_ extract 31 31) ref!0) (_ bv0 1))) ; Negative flag - 0x0: movs r3, #0
(define-fun ref!2 () (_ BitVec 1) (ite (= (_ bv1 1) (_ bv1 1)) (ite (= ref!0 (_ bv0 32)) (_ bv1 1) (_ bv0 1)) (_ bv0 1))) ; Zero flag - 0x0: movs r3, #0
(define-fun ref!3 () (_ BitVec 32) (_ bv2 32)) ; Program Counter - 0x0: movs r3, #0
```

In this case, the condition node (`(= (_ bv1 1) (_ bv1 1))`) is reused in the computation of Negative and Zero flags.

The first expression is folded correctly, but when it tries to fold the second one it is refering to the folded node instead of the original node.

One solution is to use fresh copy of the condition node for each expression. I'll try this solution, test it and see how it goes.

**Comment by SweetVishnya** [comment]
You can create an expression for condition, this expression will be folded. Later you can create refrerence node for this expression and reuse the reference.

**Comment by cnheitman** [comment]
I pushed a commit for this: https://github.com/JonathanSalwan/Triton/commit/15a515b53236a99d37abf8029cbfbf3d0e9fa2c2.

I think about the approach you mention @SweetVishnya. However, it requires a little bit of refactoring and the current one seems to work fine as well.

**Comment by JonathanSalwan** [comment]
Thanks @cnheitman for this sexy patch! I've just pushed an unittest for this issue. @RobinDavid if everything are ok for you, you can close this issue :)

Cheers mans!

**Comment by SweetVishnya** [comment]
> Yes, indeed maybe more in the AST_OPTIMIZATION mode.

@RobinDavid, working on it!
