### ISSUE TITLE
BUG: pushPathConstraint incorrect compute dstAddr

### ISSUE THREAD

**Issue by sh4m2hwz** [JonathanSalwan/Triton#1030]
bug:
pushPathConstraint src 155 (https://triton.quarkslab.com/documentation/doxygen/classtriton_1_1engines_1_1symbolic_1_1PathManager.html#a8eb4c5780b23bbda1ac6894d728bfedb):

(*fragment pushPathConstraint*)

       /* Pushs constraints of a branch instruction to the path predicate. */
       void PathManager::pushPathConstraint(const triton::arch::Instruction& inst, const triton::engines::symbolic::SharedSymbolicExpression& expr) {
         triton::engines::symbolic::PathConstraint pco;
         triton::uint64 srcAddr = 0;
         triton::uint64 dstAddr = 0;// remember this field
         triton::uint32 size    = 0;
  
         triton::ast::SharedAbstractNode pc = expr->getAst();
         if (pc == nullptr)
           throw triton::exceptions::PathManager("PathManager::pushPathConstraint(): The node cannot be null.");
  
         /* If PC_TRACKING_SYMBOLIC is enabled, Triton will track path constraints only if they are symbolized. */
         if (this->modes->isModeEnabled(triton::modes::PC_TRACKING_SYMBOLIC) && !pc->isSymbolized())
           return;
  
         /* If ONLY_ON_TAINTED is enabled and the expression untainted, Triton will skip the storing process. */
         if (this->modes->isModeEnabled(triton::modes::ONLY_ON_TAINTED) && !expr->isTainted)
           return;
  
         /* Basic block taken */
         srcAddr = inst.getAddress(); 
         dstAddr = pc->evaluate().convert_to<triton::uint64>(); // what is evaluate ()? remember z3 is to perform calculations in the resulting model from the solver, but in triton this is a simplification and calculations of ast belonging to some variable (it doesn't matter symbolic or concrete, the triton builds ast and then calculates ast) what is pc-> evaluate ()? this is ast relative to program counter (x86, long mode: rip). pc is always known because there are 3 types of instructions without nesting, what forms a CFG or CDG are sequence instructions, condition branch instructions, uncondition branch instructions. in this case, you need to take the address from the operand of the instruction that is not sequential in execution, or if the indirect branch, change getPathPredicate, getPathPredicate (takenAddress), where takenAddress -> is the address of the transition
         size    = pc->getBitvectorSize();
  
         if (size == 0)
           throw triton::exceptions::PathManager("PathManager::pushPathConstraint(): The node size cannot be zero.");
  
         if (pc->getType() == triton::ast::ZX_NODE)
           pc = pc->getChildren()[1];
  
         /* Setting the thread id */
         pco.setThreadId(inst.getThreadId());
  
         /* Multiple branches */
         if (pc->getType() == triton::ast::ITE_NODE) {
           /* Condition */
           triton::ast::SharedAbstractNode cond = pc->getChildren()[0];
  
           /* Then */
           triton::uint64 bb1 = pc->getChildren()[1]->evaluate().convert_to<triton::uint64>();
           triton::ast::SharedAbstractNode bb1pc = cond;
  
           /* Else */
           triton::uint64 bb2 = pc->getChildren()[2]->evaluate().convert_to<triton::uint64>();
           triton::ast::SharedAbstractNode bb2pc = this->astCtxt->lnot(cond);
  
           /* Branch A */
           pco.addBranchConstraint(
             bb1 == dstAddr, /* is taken ? (the address of the next instruction is not compared correctly) */ 
             srcAddr,        /* from       */
             bb1,            /* to         */
             bb1pc           /* expr which must be true to take the branch */
           );
  
           /* Branch B */
           pco.addBranchConstraint(
             bb2 == dstAddr, /*is taken ? (the address of the next instruction is not compared correctly)*/
             srcAddr,        /* from       */
             bb2,            /* to         */
             bb2pc           /* expr which must be true to take the branch */
           );
  
           this->pathConstraints.push_back(pco);
         }
py prove:

```
>>> t,SymCtx = init(SymCtx)
symbolize:  [@0x7fffffffde42]:64 bv[63..0]
>>> pc = entry_address
>>> insns,count = get_decoded_insns(address=pc)
>>> insn = None
>>> for i in range(count):
...     insn = Instruction()
...     insn.setAddress(pc)
...     insn.setOpcode(insns[pc])
...     t.processing(insn)
...     print(insn)
...     if insn.isBranch():
...             break
...     AstNodeRip = t.getRegisterAst(t.registers.rip)
...     pc = AstNodeRip.evaluate()
... 
True
0x400078: mov al, 0x55
True
0x40007a: xadd rax, rbx
True
0x40007e: not rbx
True
0x400081: sbb bh, al
True
0x400083: shld dx, bx, 8
True
0x400088: xor ah, dh
True
0x40008a: bswap eax
True
0x40008c: imul ecx, eax, 0x4631
True
0x400092: push dx
True
0x400094: movbe r8d, dword ptr [rsp]
True
0x40009a: or ecx, r8d
True
0x40009d: not r9d
True
0x4000a0: xor ecx, r9d
True
0x4000a3: jl 0x40008c
>>> insn
0x4000a3: jl 0x40008c
>>> expr = insn.getSymbolicExpressions()
>>> expr
[(define-fun ref!76 () (_ BitVec 64) (ite (= (bvxor ref!73 ref!71) (_ bv1 1)) (_ bv4194444 64) (_ bv4194469 64))) ; Program Counter - 0x4000a3: jl 0x40008c]
>>> expr
[(define-fun ref!76 () (_ BitVec 64) (ite (= (bvxor ref!73 ref!71) (_ bv1 1)) (_ bv4194444 64) (_ bv4194469 64))) ; Program Counter - 0x4000a3: jl 0x40008c]
>>> expr[0]
(define-fun ref!76 () (_ BitVec 64) (ite (= (bvxor ref!73 ref!71) (_ bv1 1)) (_ bv4194444 64) (_ bv4194469 64))) ; Program Counter - 0x4000a3: jl 0x40008c
>>> expr = expr[0]
>>> srcAddr = insn.getAddress()
>>> pc = expr.getAst()
>>> pc
(ite (= (bvxor ref!73 ref!71) (_ bv1 1)) (_ bv4194444 64) (_ bv4194469 64))
>>> pc.evaluate
<built-in method evaluate of AstNode object at 0x7f4037ff2970>
>>> pc.evaluate()
4194469
>>> hex(pc.evaluate())
'0x4000a5'
>>> cond = pc.getChildren()
>>> cond = pc.getChildren()[0]
>>> cond
(= (bvxor ref!73 ref!71) (_ bv1 1))
>>> cond.evaluate()
0
>>> pc.getChildren()
[(= (bvxor ref!73 ref!71) (_ bv1 1)), (_ bv4194444 64), (_ bv4194469 64)]
>>> pc.getChildren()[1]
(_ bv4194444 64)
>>> pc.getChildren()[1].evaluate()
4194444
>>> hex(pc.getChildren()[1].evaluate())
'0x40008c'
>>> hex(pc.getChildren()[2].evaluate())
'0x4000a5'
>>> t.simplify(pc.getChildren()[1])
(_ bv4194444 64)
>>> bb1 = pc.getChildren()[1].evaluate()
>>> bb2 = pc.getChildren()[2].evaluate()
>>> bb1
4194444
>>> bb2
4194469
>>> dstAddr = pc.evaluate()
>>> print(bb1,dstAddr,bb1 == dstAddr)
4194444 4194469 False
>>> 
```

links:
used funcs: https://pastebin.com/iMnwjA1Z

**Comment by JonathanSalwan** [comment]
I don't understand where is the bug. What i understand from you output is:

```
bb1 = 4194444
bb2 = 4194469
cond = 0 (not taken)
pc = 4194469
ast = if cond then bb1 else bb2
```

For me everything looks ok.

**Comment by sh4m2hwz** [comment]
> dstAddr = pc-> evaluate (). convert_to <triton :: uint64> ()
 This is the destination of the transition, it is assigned the address of the next instruction
 > srcAddr = inst.getAddress ();
 This is the address of the branch instruction (unconditional or conditional)
 1)> triton :: ast :: SharedAbstractNode cond = pc-> getChildren () [0];
  2)> triton :: uint64 bb1 = pc-> getChildren () [1] -> evaluate (). Convert_to <triton :: uint64> ();
 3)> triton :: ast :: SharedAbstractNode bb1pc = cond;
  4)> triton :: uint64 bb2 = pc-> getChildren () [2] -> evaluate (). Convert_to <triton :: uint64> ();
 5)> triton :: ast :: SharedAbstractNode bb2pc = this-> astCtxt-> lnot (cond);
 We get symbolic expressions (formulas) that contain all the dependencies in the path predicate and describe it (predicate condition): code fragments (1,3,5).
 Snippets of code: 2,4 - this is to get the addresses of a potential change in the instruction pointer or go to bb1 (true branch) or to bb2 (false branch)

 1)> pco.addBranchConstraint (
          bb1 == dstAddr, / * is taken?  (the address of the next instruction is not compared correctly) * /
          srcAddr, / * from * /
          bb1, / * to * /
          bb1pc / * expr which must be true to take the branch * /
        );

        / * Branch B * /
  2)> pco.addBranchConstraint (
          bb2 == dstAddr, / * is taken?  (the address of the next instruction is not compared correctly) * /
          srcAddr, / * from * /
          bb2, / * to * /
          bb2pc / * expr which must be true to take the branch * /
        );

 Let's remember what dstAddr is - this is the address of the next instruction. With our eyes we execute the code:
 Remember dstAddr has an address value that refers to $ + sizeof (current_insn).  $ is the current address (i.e. the conditional branch instruction) sizeof is a function that returns the size of the instruction in bytes, in this case current_insn is a conditional branch instruction, like JCC in x86.  Now what does bb1 matter?  It matters encoded instructions in relocation (if you take conditional branching instructions, they are not capable of transitions between segments in x86, there are only near transitions, within a segment these are absolute jumps, that is, a value is extracted and assigned to the instruction pointer if 64 bit mode,  then it expands symbolically, and relative jumps or short ones that form the effective transition address from rip / eip + rel8, this is intel or amd documentation) so the problem is that when the comparison operator "==" is false, and when pco.addBranchConstraint is called  if you look at the code there is "this-> branches.push_back (std :: make_tuple (taken, srcAddr, dstAddr, pc));"  is adding to the heap and changing the position pointer to the element this-> branches [n + 1] => where n is the starting position and +1 is push.  Accordingly, when retrieving values ​​when TritonContext () is called. GetBranchConstraints () [0] [0] ["isTaken"] is false, because the first push is a false statement that has a true transition and the second is a true statement, but a false transition.  In triton, the logic is not entirely described, it is in the dock what isTaken is, but studying the assembler or architecture, you can understand that i "sTaken == True" this means the jump will be to the address specified in the instruction when the constraint is true.

**Comment by JonathanSalwan** [comment]
> Let's remember what dstAddr is - this is the address of the next instruction. With our eyes we execute the code:
Remember dstAddr has an address value that refers to $ + sizeof (current_insn). $ is the current address (i.e. the conditional branch instruction) sizeof is a function that returns the size of the instruction in bytes, in this case current_insn is a conditional branch instruction, like JCC in x86.

I don't understand why you say that=/. `dstAddr` is the [concrete evaluation of the PC expression](https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/engines/symbolic/pathManager.cpp#L175) not the `+ sizeof(current_insn)`.

> what is evaluate ()? remember z3 is to perform calculations in the resulting model from the solver, but in triton this is a simplification and calculations of ast belonging to some variable (it doesn't matter symbolic or concrete, the triton builds ast and then calculates ast) what is pc-> evaluate ()? this is ast relative to program counter (x86, long mode: rip). pc is always known because there are 3 types of instructions without nesting, what forms a CFG or CDG are sequence instructions, condition branch instructions, uncondition branch instructions. in this case, you need to take the address from the operand of the instruction that is not sequential in execution, or if the indirect branch, change getPathPredicate, getPathPredicate (takenAddress), where takenAddress -> is the address of the transition

We do not use z3 to evaluate AST. AST are evaluated by Triton and we use the concrete state to evaluate symbolic values. Also, regarding near/long jumps, capstone provides the final virtual address when disassembling an opcode with its current address position. Example, let's disassemble the `jz 3` instruction. Here we have a relative position (`3`) from the current instruction address. When providing the address of the instruction (`0x40000`), Capstone will translate the relative position (`current_pos + 3`) by its final virtual address `0x40003`. So when evaluating our PC expression, `dstAddr` is the final fixed virtual address.

```python
>>> from triton import *
>>> 
>>> ctx = TritonContext()
>>> ctx.setArchitecture(ARCH.X86_64)
>>> 
>>> inst = Instruction(b"\x74\x01") # jz 3
>>> inst.setAddress(0x40000)
>>> 
>>> ctx.disassembly(inst)
>>> print(inst)
0x40000: je 0x40003
>>> 
>>> op = inst.getOperands()[0]
>>> op
0x40003:64 bv[63..0]
>>> hex(op.getValue())
'0x40003'
```

Is there something I misunderstand?
