### ISSUE TITLE
Triton installation on Ubuntu with multiple python versions

### ISSUE THREAD

**Issue by tosanjay** [JonathanSalwan/Triton#1036]
Hello,
I have Ubuntu 18.04 with Python 2.7 and 3.8 installed. When I started building Triton it complained that I do not have python 2.7 (though I had). I did some manual editing of CMakeList.txt file to enforce it to find python 2.7 version. With that, I could build Triton. HOwever, when I run it with my python script, somehow internally, it is again interpreting the python script with python3 as I do get error for print statement mentioning the there should be a "bracket" around! Is there any solution to enforce triton to use python 2.7?
Note: the command  "`which python`" indeed returns the right python 2.7 executable path, which means when one runs
"`python script.py`", it is python 2.7 that is invoked.

**Comment by SweetVishnya** [comment]
You can build with `-DPYTHON_VERSION 2.7`. Also check the shebang in your python script `#!/usr/bin/env python`.

**Comment by tosanjay** [comment]
Thank you @SweetVishnya. I could build with that cmake option. However, now I am getting another error.

```
C: Tool (or Pin) caused signal 11 at PC 0x7f5affc01c71
/home/workdir/pin-2.14/source/tools/Triton/build/triton: line 20: 24825 Segmentation fault      LD_BIND_NOW=1 $PIN_BIN_PATH -ifeellucky -t $PINTOOL_PATH -script $1 -- ${@:2}
```

I think my environment Ubuntu 18.04 with kernel 5.4.0-80-generic is not compatible :(

**Comment by JonathanSalwan** [comment]
Pin is really outdated. They officially support the Kernel v3 and have an option `-ifeellucky` when running Pin on Kernel v4. I'm not sure there is an option `-ifeelverylucky` for v5 :). However maybe this crash occurs on our side, did you tried to debug and find the root cause?

**Comment by tosanjay** [comment]
> However maybe this crash occurs on our side, did you tried to debug and find the root cause?

aha.. I didn't even thought about that part. I just assumed it was due to incompatibility. Let me dig that then. I will update here. thank you
