### ISSUE TITLE
Loss of symbolic information when setting memory in a callback

### ISSUE THREAD

**Issue by jordan9001** [JonathanSalwan/Triton#1037]
I have a non-intuitive behavior that I wanted to document here.

Script:
```python
from triton import *

def setMemCb(ctx, mem, val):
    addr = mem.getAddress()
    sz = mem.getSize()
    print(f"Setting @{addr:x} {sz:x} {val:x}")
    print(f"Existing val {ctx.getConcreteMemoryAreaValue(addr, 8)}")
    print(f"Existing symbolic expression {ctx.simplify(ctx.getMemoryAst(mem), True)}")
    ctx.setConcreteMemoryAreaValue(addr, b'22222222')

ctx = TritonContext(ARCH.X86_64)

ctx.addCallback(CALLBACK.SET_CONCRETE_MEMORY_VALUE, setMemCb)

ctx.setConcreteRegisterValue(ctx.registers.rbx, 0x2000)
ctx.setConcreteRegisterValue(ctx.registers.rax, 0x3131313131313131)
ctx.symbolizeRegister(ctx.registers.rax, "rax_symbol")

opcodes = bytes.fromhex("488903") # mov [rbx], rax
ins = Instruction(0x1000, opcodes)

if not ctx.processing(ins):
    print("Error processing instruction")


print(f"Is symbolized {ctx.isMemorySymbolized(MemoryAccess(0x2000, 8))}, value {ctx.getConcreteMemoryAreaValue(0x2000, 8)}")
```
Output:
```
Setting @2000 8 3131313131313131
Existing val b'\x00\x00\x00\x00\x00\x00\x00\x00'
Existing symbolic expression rax_symbol
Is symbolized False, value b'11111111'
```

Expected Output:
EITHER
```
Setting @2000 8 3131313131313131
Existing val b'\x00\x00\x00\x00\x00\x00\x00\x00'
Existing symbolic expression None
Is symbolized True, value b'11111111'
```
OR
```
Setting @2000 8 3131313131313131
Existing val b'11111111'
Existing symbolic expression rax_symbol
Is symbolized False, value b'22222222'
```

The callback is getting called when the symbolic information has been applied, but the concrete value has not. I am not sure if this is a bug, but it is not intuitive to use at first.
I am happy to help fix this, if you let me know what your preferred solution would be.

Thank you!

**Comment by SweetVishnya** [comment]
Setting concrete memory from api concretizes corresponding memory bytes. You should update concrete state when it is not already defined.

**Comment by jordan9001** [comment]
I agree. But the concrete state of the memory is still out of sync with the symbolic state when you are in the callback.
It is strange as a user to have the memory get concretized, but not with the bytes that I specified.

Now that I know it's behavior, it is not a problem for me. But it was not intuitive at first, and I had to spend a bit of time tracking down why my analysis was not working. It may be worth changing when the callback gets run to before the symbolic information is applied to the memory, or to after the concrete value is applied to the memory.

**Comment by SweetVishnya** [comment]
callback is called before instruction interpretation

**Comment by SweetVishnya** [comment]
With current callback implementation u can have both old value and new value in argument `val`.

**Comment by jordan9001** [comment]
I think that sounds like a good idea.

Would it be possible in `symbolicEngine.cpp` to call `this->architecture->setConcreteMemoryValue` before `this->addMemoryReference`?

That would fix the inconsistency that I am seeing, and cause the callback to be called before the symbolic expression is applied to the memory.

**Comment by JonathanSalwan** [comment]
Hey,

I'm back on this thread. I've started thinking and i'm not sure it's a good idea to call `setConcreteMemoryValue` before `addMemoryReference`. For example, let's consider the following prototypes of those functions:

* `addMemoryReference(addr, expr);`
* `setConcreteMemoryValue(addr, expr->evaluate());`

We start by assigning the `expr` to a memory cell at the address `addr`. Then, we evaluate the concrete value of the `expr` and we assign this value to the concrete state. Thus we have a synchronization between the symbolic and the concrete state.

If we call `setConcreteMemoryValue` before `addMemoryReference` and if the user change the concrete value assigned into his callback, then `expr->evaluate()` is no more valid when `addMemoryReference` is called.

**Comment by asevergreen** [comment]
Hi, I'm still a little confused. I want to record the original symbolic expression when setting memory in a callback. At this time the concrete value is still the original, but the symbolic expression has been updated. Is there any way to do what I want? Thank you very much!
