### ISSUE TITLE
A problem occurred during installation 

### ISSUE THREAD

**Issue by wjcif11** [JonathanSalwan/Triton#1040]
/home/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton/src/libtriton/arch/arm/arm32/arm32Specifications.cpp: In member function 'triton::uint32 triton::arch::arm::arm32::Arm32Specifications::capstoneInstructionToTritonInstruction(triton::uint32) const':
/home/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton/src/libtriton/arch/arm/arm32/arm32Specifications.cpp:342:45: error: 'ARM_INS_ERET' is not a member of 'triton::extlibs::capstone'
             case triton::extlibs::capstone::ARM_INS_ERET:
                                             ^~~~~~~~~~~~
/home/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton/src/libtriton/arch/arm/arm32/arm32Specifications.cpp:342:45: note: suggested alternative: 'ARM_INS_REV'
             case triton::extlibs::capstone::ARM_INS_ERET:
                                             ^~~~~~~~~~~~
                                             ARM_INS_REV
/home/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton/src/libtriton/arch/arm/arm32/arm32Specifications.cpp:378:45: error: 'ARM_INS_HVC' is not a member of 'triton::extlibs::capstone'
             case triton::extlibs::capstone::ARM_INS_HVC:
                                             ^~~~~~~~~~~
/home/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton/src/libtriton/arch/arm/arm32/arm32Specifications.cpp:378:45: note: suggested alternative: 'ARM_INS_SVC'
             case triton::extlibs::capstone::ARM_INS_HVC:
                                             ^~~~~~~~~~~
                                             ARM_INS_SVC
src/libtriton/CMakeFiles/triton.dir/build.make:240: recipe for target 'src/libtriton/CMakeFiles/triton.dir/arch/arm/arm32/arm32Specifications.cpp.o' failed
make[2]: *** [src/libtriton/CMakeFiles/triton.dir/arch/arm/arm32/arm32Specifications.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1148: recipe for target 'src/libtriton/CMakeFiles/triton.dir/all' failed
make[1]: *** [src/libtriton/CMakeFiles/triton.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

I don't know how to solve it, can it help me

**Comment by SweetVishnya** [comment]
Try building with latest [capstone](https://github.com/aquynh/capstone).

**Comment by JonathanSalwan** [comment]
Yes you need capstone 4.0.2.

**Comment by wjcif11** [comment]
Thank you
