### ISSUE TITLE
dynamic taint analysis

### ISSUE THREAD

**Issue by wjcif11** [JonathanSalwan/Triton#1041]
Can Triton use taint analysis to extract system call graphs?

**Comment by JonathanSalwan** [comment]
Nop. Triton only spreads taint from given trace.

**Comment by wjcif11** [comment]
> Nop. Triton only spreads taint from given trace.

Do you think it would be difficult to expand this function, or do you have any ideas

**Comment by JonathanSalwan** [comment]
> Do you think it would be difficult to expand this function, or do you have any ideas

Just to remind that Triton is not a tool but a lib. So there is no such features and you have to dev it on your own :). For such thing your tool may be something like:

* Load and parse binary segments using lief ([example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/small_x86-64_symbolic_emulator.py#L382-L392))
* Emulate the binary and its external functions ([example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/small_x86-64_symbolic_emulator.py#L382-L392))
* Taint the user input ([example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/forward_tainting.py))
* Perform a symbolic exploration to cover all its states/paths/edges/blocks or whatever ([example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/code_coverage_crackme_xor.py))
* During the exploration save all sub tainted instructions by path
* Once the exploration is done, craft the call graph using for example [graphviz](https://renenyffenegger.ch/notes/tools/Graphviz/examples/index)

I think it's possible to do what you are looking for but there is a non negligible amount of code to provide ^^

**Comment by wjcif11** [comment]
> > Do you think it would be difficult to expand this function, or do you have any ideas
> 
> Just to remind that Triton is not a tool but a lib. So there is no such features and you have to dev it on your own :). For such thing your tool may be something like:
> 
> * Load and parse binary segments using lief ([example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/small_x86-64_symbolic_emulator.py#L382-L392))
> * Emulate the binary and its external functions ([example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/small_x86-64_symbolic_emulator.py#L382-L392))
> * Taint the user input ([example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/forward_tainting.py))
> * Perform a symbolic exploration to cover all its states/paths/edges/blocks or whatever ([example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/code_coverage_crackme_xor.py))
> * During the exploration save all sub tainted instructions by path
> * Once the exploration is done, craft the call graph using for example [graphviz](https://renenyffenegger.ch/notes/tools/Graphviz/examples/index)
> 
> I think it's possible to do what you are looking for but there is a non negligible amount of code to provide ^^

Thanks a lot , I will try my best to finish it.

**Comment by wjcif11** [comment]
> > Do you think it would be difficult to expand this function, or do you have any ideas
> 
> Just to remind that Triton is not a tool but a lib. So there is no such features and you have to dev it on your own :). For such thing your tool may be something like:
> 
> * Load and parse binary segments using lief ([example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/small_x86-64_symbolic_emulator.py#L382-L392))
> * Emulate the binary and its external functions ([example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/small_x86-64_symbolic_emulator.py#L382-L392))
> * Taint the user input ([example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/forward_tainting.py))
> * Perform a symbolic exploration to cover all its states/paths/edges/blocks or whatever ([example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/code_coverage_crackme_xor.py))
> * During the exploration save all sub tainted instructions by path
> * Once the exploration is done, craft the call graph using for example [graphviz](https://renenyffenegger.ch/notes/tools/Graphviz/examples/index)
> 
> I think it's possible to do what you are looking for but there is a non negligible amount of code to provide ^^

I have another question, In the process of dynamic taint, whether Triton can only extract instructions about system calls, or expand this function is not complex.

**Comment by JonathanSalwan** [comment]
Actually Triton only takes as input **one** instruction at time. When the user provide several instructions it simulates a trace execution. So technically you know when you provide a system call instruction to Triton and you just have to save them. However, to determine if a given instruction is a syscall you may do something like this:

```python
>>> from triton import *

>>> ctx = TritonContext(ARCH.X86_64)
>>> inst = Instruction(b"\x0f\x05")
>>> ctx.processing(inst)
True

>>> print(inst)
0x0: syscall

>>> inst.getType() == OPCODE.X86.SYSCALL
True
```

**Comment by IamHuskar** [comment]
> > Do you think it would be difficult to expand this function, or do you have any ideas
> 
> Just to remind that Triton is not a tool but a lib. So there is no such features and you have to dev it on your own :). For such thing your tool may be something like:
> 
> * Load and parse binary segments using lief ([example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/small_x86-64_symbolic_emulator.py#L382-L392))
> * Emulate the binary and its external functions ([example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/small_x86-64_symbolic_emulator.py#L382-L392))
> * Taint the user input ([example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/forward_tainting.py))
> * Perform a symbolic exploration to cover all its states/paths/edges/blocks or whatever ([example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/code_coverage_crackme_xor.py))
> * During the exploration save all sub tainted instructions by path
> * Once the exploration is done, craft the call graph using for example [graphviz](https://renenyffenegger.ch/notes/tools/Graphviz/examples/index)
> 
> I think it's possible to do what you are looking for but there is a non negligible amount of code to provide ^^

thank you.  take a note

**Comment by wjcif11** [comment]
收到
