### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by lkpama** [JonathanSalwan/Triton#1056]
I see that Triton needs Python 3.6 in the cmake file, but pintool needs Python 2.7. Can it be installed and run normally？

**Comment by JonathanSalwan** [comment]
https://github.com/JonathanSalwan/Triton/issues/915#issuecomment-633189235

**Comment by lkpama** [comment]
> [#915 (comment)](https://github.com/JonathanSalwan/Triton/issues/915#issuecomment-633189235)

Sorry, but don't Triton need Python 3.6？

**Comment by JonathanSalwan** [comment]
You can compile Triton with python 2.7, 3.5, 3.6, 3.7 and 3.8. Only the pin part needs Triton with python 2.7. So if you want to use the Pin tracer you need to compile Triton in 2.7

**Comment by JonathanSalwan** [comment]
`cmake -DPYTHON_VERSION=2.7 -DPINTOOL=on`

**Comment by lkpama** [comment]
got it
