### ISSUE TITLE
TypeError when running examples

### ISSUE THREAD

**Issue by njayinthehouse** [JonathanSalwan/Triton#1057]
When I try to run the examples, I get a TypeError.
```
» python3.8 ir.py
Traceback (most recent call last):
  File "ir.py", line 72, in <module>
    Triton.processing(inst)
TypeError: x8664Cpu::disassembly(): Invalid operand.
```
Seems related to #752, but reinstalling didn't help.

**Comment by JonathanSalwan** [comment]
Be sure to remove all triton includes and lib. As well to not have multiple capstone version installed on your system

**Comment by njayinthehouse** [comment]
I found a workaround for now, so I won't be testing this any time soon, so feel free to close this issue if you deem it appropriate.
