### ISSUE TITLE
how to change fp32 to int8

### ISSUE THREAD

**Issue by Chenhait** [JonathanSalwan/Triton#1061]
hi, I convert a onnx model, and use triton server to infer.
however, the data and the model not in the same computer.
the input and output of ONNX model are fp32, it is too big to transmit.
so, I want to change the input and output to  int8.
is it possible?
thank you very much if any advance!!

**Comment by JonathanSalwan** [comment]
Hey,

By `fp32` are you mean that your SMT expressions are on single-precision floating-point logic? If it's the case, i'm not sure the SMT format accepts to convert expressions from an `fp32` logic to a `bv` logic.

**Comment by JonathanSalwan** [comment]
> so, I want to change the input and output to int8. is it possible?

Also, if you want to force the output of Triton to print `int8` expressions, this is not possible. All our semantics are hardcoded to be on the `bv` logic (QF_BV SMT theory).

**Comment by Chenhait** [comment]
> > so, I want to change the input and output to int8. is it possible?
> 
> Also, if you want to force the output of Triton to print `int8` expressions, this is not possible. All our semantics are hardcoded to be on the `bv` logic (QF_BV SMT theory).

your advance is very important!!!thank you!!!

**Comment by JonathanSalwan** [comment]
Np :), feel free to close this thread if you think you have your answers.

Cheers,
