### ISSUE TITLE
Problem with VERSION.dll while using pin with triton on windows 10

### ISSUE THREAD

**Issue by mehdighninoudev** [JonathanSalwan/Triton#1065]
Hi I have used this command to execute pin with triton module:
..\..\pin -t "C:\Users\User\AppData\Local\Programs\Python\Python36\triton.dll" -script examples\pin\callback_syscall.py -- main.exe

but I am getting an error: E: Failure to open DLL file VERSION.dll

what kind of solution can I do to resolve the problem and run pin with triton successfuly without having to copy all necessary dlls from c:\windows\system32 and subfolders of system32 ?

**Comment by mehdighninoudev** [comment]
and thank u again for your response

**Comment by JonathanSalwan** [comment]
I'm sorry to tell you that Triton is not working with Pin on Windows =/.

**Comment by mehdighninoudev** [comment]
Okay I understand. Thank again you for your clarification
