### ISSUE TITLE
Returns all possible models

### ISSUE THREAD

**Issue by JonathanSalwan** [JonathanSalwan/Triton#107]
Like the `getModel()` function, create a function `getModels(limit=0)` which returns all possible models of an expression. If the `limit` is undef (0), there is no limit of models returned.

**Comment by 0vercl0k** [comment]
Maybe of interest:
https://github.com/0vercl0k/z3-playground/blob/master/z3tools.py#L83 :)

Cheers,
0vercl0k

2015-06-27 4:41 GMT-07:00 Jonathan Salwan <notifications@github.com>:
