### ISSUE TITLE
Removing things, adding others and new cmake 

### ISSUE THREAD

**Issue by JonathanSalwan** [JonathanSalwan/Triton#1070]
Hey folks,

We've:

* Removed the SYSCALL enums (#1069)
* Added a new SMT solver (#1062)
* Cleaning a lot the cmake files (`dev-cmake`)

Before merging all of this into `dev-v0.9`, it will be cool if some of you can pull the branch `dev-cmake` (which contains all these above updates), try to compile and then do a  `make check` to be sure that everything is fine.

Do not hesitate to reply to this thread by just saying for example: "It's ok on my system: Win64 VS19".
Currently, I've tested on:

- [x] Win32 VS19
- [x] Win64 VS19
- [x] Gentoo x64
- [x] Ubuntu 20.04 x64
- [x] macOS 10.15 x64
- [x] CentOS 6.9 x64

PS: @SweetVishnya can you try for your Sydr framework?

**Comment by SweetVishnya** [comment]
We bulid for CentOS 6.9 x64 and Windows 10 x64. Yeah, I'll verify the build. Did the building flags change for the dependencies? We have the following build process. We build all dependencies (capstone, bitwuzla, etc.) in separate build directories and install them in other install dirs (not in system). Then we specify library and include dirs in Triton cmake flags for each dependecy.

P.S. Triton README lacks of "How to build". Doxygen docs are quite old.

**Comment by cnheitman** [comment]
It's working fine on my system (Ubuntu). 

(Just one detail, I had to add the build dir to `PYTHONPATH` so tests can run properly, I didn't need that before. Other than that, everything seems fine.)

**Comment by JonathanSalwan** [comment]
@SweetVishnya

> Did the building flags change for the dependencies?

Nop, should be the same.

> P.S. Triton README lacks of "How to build". Doxygen docs are quite old.

Yeah you right...

@cnheitman 

> (Just one detail, I had to add the build dir to PYTHONPATH so tests can run properly, I didn't need that before. Other than that, everything seems fine.)

Mmmh. Can you give me the command that you executed to run tests? I will try to fix it like it was before.

**Comment by SweetVishnya** [comment]
```
CMake Warning:
  Manually-specified variables were not used by the project:

    STATICLIB
```

**Comment by SweetVishnya** [comment]
Hmm, some strange messages from our CI:

```
/builds/dse/sydr/build/triton/include/triton/archEnums.hpp:61:16: fatal error: 'triton/x86.spec' file not found
      #include "triton/x86.spec"
               ^~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by JonathanSalwan** [comment]
>  STATICLIB

Yes, the only rename we did is: `STATICLIB` -> `BUILD_SHARED_LIBS` to be cmake compliant.

> Yeah, x86.spec file is missing in installed Triton include directory.

fixed with the last commit

**Comment by cnheitman** [comment]
@JonathanSalwan 

> Mmmh. Can you give me the command that you executed to run tests? I will try to fix it like it was before.

I have to run the tests like this (no big deal):

```bash
PYTHONPATH=$(pwd)/src/libtriton make check
```

Otherwise I get this kind of errors (only fails for Python's unittests):

```
 7/41 Test  #7: UnicornAArch64Semantics ..........***Failed    0.03 sec
Traceback (most recent call last):
  File "/mnt/projects/Triton/src/testers/aarch64/unicorn_test_aarch64.py", line 6, in <module>
    from triton              import *
ModuleNotFoundError: No module named 'triton'
```

**Comment by SweetVishnya** [comment]
> > STATICLIB
> 
> Yes, the only rename we did is: `STATICLIB` -> `BUILD_SHARED_LIBS` to be cmake compliant.
> 
> > Yeah, x86.spec file is missing in installed Triton include directory.
> 
> fixed with the last commit

CentOS 6.9 x64 build and all Linux tests work fine. However, I failed to compile static library for Windows:

```
triton.lib(register.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in cache.cpp.obj
```

**Comment by SweetVishnya** [comment]
Maybe some `/MT` flags are missing?

**Comment by JonathanSalwan** [comment]
> Maybe some `/MT` flags are missing?

I know nothing on windows but the only part of code related to this is: [link](https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/CMakeLists.txt#L8-L13).

Can you copy those lines and put them into **src/libtriton/CMakeLists.txt** to see if it fixes the issue?

**Comment by SweetVishnya** [comment]
I grepped these lines on master branch.
```
./src/libtriton/CMakeLists.txt
    set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -DHAVE_ROUND /MT /MP")
    set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -DHAVE_ROUND /MTd /MP")
```

**Comment by SweetVishnya** [comment]
Oh, I suppose these are wrong lines. Need further investigation. Static is somehow defined via cmake.

**Comment by SweetVishnya** [comment]
We are missing [this](https://github.com/JonathanSalwan/Triton/blob/dev-bitwuzla/src/libtriton/CMakeLists.txt#L342) logic.

**Comment by SweetVishnya** [comment]
Trying this fix on our CI. Going to PR on success.

**Comment by SweetVishnya** [comment]
I couldn't fix Windows static build fast. I'll return to it tomorrow.

**Comment by cnheitman** [comment]
Hey @JonathanSalwan , I fixed the error I was having when running the tests (the `ctests` where failing, not the `unittests`). 

Here is the patch:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index d631b98d..734ae5c9 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -34,7 +34,7 @@ cmake_dependent_option(PYTHON_AUTOCOMPLETE  "Generate Python triton_autocomplete
 #Enable ctest
 include(CTest)
 add_custom_target(check
-    COMMAND ctest --output-on-failure
+    COMMAND PYTHONPATH=${CMAKE_CURRENT_BINARY_DIR}/src/libtriton ctest --output-on-failure
     DEPENDS triton
 )
```

**Comment by JonathanSalwan** [comment]
With the commit 531cd53ad1a47dba18845a80f569145e27d7bc0a, we added the generation of files `tritonConfig.cmake` and `tritonTargets.cmake` proposed by @mrexodia (see #1047) to help finding triton as cmake package.

**Comment by JonathanSalwan** [comment]
**todo**: When compiling as static build, the lib triton is indeed a static archive (`libtriton.a`) but still uses imported symbols from z3 and capstone. We need to use `libz3.a` and `libcapstone.a` when `BUILD_SHARED_LIBS` is `OFF`.

![2022-01-20-111121_1920x1080_scrot](https://user-images.githubusercontent.com/991046/150317677-679e4a2c-3c07-4976-a9da-f1f7a7d5b2a6.png)

**Comment by SweetVishnya** [comment]
With PR #1072 applied all our internal CI pass (static build for Windows x64 and Linux x64 + tests).

**Comment by JonathanSalwan** [comment]
Ok let's go, i will merge `dev-cmake` into `dev-v0.9` and then `master` :rocket: :rocket: :rocket:
