### ISSUE TITLE
Lifting engine

### ISSUE THREAD

**Issue by JonathanSalwan** [JonathanSalwan/Triton#1075]
I'm currently refactoring some code around AST representation. The idea is to have an engine `LiftingEngine` that can lift AST to several representations:

* SMT
* Python
* LLVM

The idea is to have an `ostream` that can be saved into a file and then executed by the targets: SMT Solvers, Python interpreter, LLVM tools. It's already partially done with the `printSlicedExpressions` function. However, this function has been removed to let place to `liftToSMT` and I still have to dev `liftToPython`. My goal at the end is to have a  `liftToLLVM` function.

**Comment by SweetVishnya** [comment]
Adopting LLVM optimizations could be very promising like [here](https://github.com/fvrmatteo/TritonASTLLVMIRTranslator)

**Comment by SweetVishnya** [comment]
Anyway, ping us, please, to verify that everything works on our side before merge. We are using `printSlicedExpressions` to dump SMT queries (for instance, to submit them to SMT-Comp).

**Comment by JonathanSalwan** [comment]
> Anyway, ping us, please, to verify that everything works on our side before merge. We are using `printSlicedExpressions` to dump SMT queries (for instance, to submit them to SMT-Comp).

Yep i will. `::printSlicedExpressions` as been moved to `API::liftToSMT`.

**Comment by JonathanSalwan** [comment]
> Adopting LLVM optimizations could be very promising like [here](https://github.com/fvrmatteo/TritonASTLLVMIRTranslator)

Yep, this is also how we [broke](https://github.com/JonathanSalwan/Tigress_protection) some Tigress protections

**Comment by SweetVishnya** [comment]
> > Adopting LLVM optimizations could be very promising like [here](https://github.com/fvrmatteo/TritonASTLLVMIRTranslator)
> 
> Yep, this is also how we [broke](https://github.com/JonathanSalwan/Tigress_protection) some Tigress protections

Nice. Applying LLVM optimization during DSE is good student research project (coursework/thesis). Maybe, we find time to benchmark it some day.

**Comment by SweetVishnya** [comment]
Moreover, I sometimes use Python representation as a more readable than SMT.

**Comment by JonathanSalwan** [comment]
Yep I agree, I do the same with Python repr. The only thing i blame is the number of 0xffffff involved in this syntax. Anyway, I will let the Python syntax.

**Comment by JonathanSalwan** [comment]
@SweetVishnya, ok i'm done with this feature. Can you tell me if everything is ok on your side with Sydr? In your case you just have to use `liftToSMT` instead of `printSlicedExpressions`. LLVM is not involved by default, so it should be ok for your compile. However, if you want to compile with the LLVM interface:

```
$ cmake -DLLVM_INTERFACE=ON -DLLVM_INCLUDE_DIRS=$(llvm-config --includedir) -DLLVM_LIBRARIES=$(llvm-config --libfiles) ..
```

**Comment by SweetVishnya** [comment]
@JonathanSalwan, ok, i'll check.

**Comment by SweetVishnya** [comment]
Everything works fine on our side after #1077
