### ISSUE TITLE
Synthesis returning None?

### ISSUE THREAD

**Issue by khang06** [JonathanSalwan/Triton#1081]
Hi, I wanted to test the expression synthesis feature on a real target, but I haven't been able to get it to synthesize the expressions properly. Namely, it always returns None. The examples work fine, so I think it's an issue with my code, but I can't exactly figure out what I did wrong...

```Python
from triton import *
import lief

BASE_STACK = 0x9fffffff

CONCRETIZED_REGIONS = {
    (0x18270EC40, 0x18270EC58),
    (0x18270ECE0, 0x18270EE28),
    (0x18270EC20, 0x18270EC38)
}

if __name__ == "__main__":
    ctx = TritonContext(ARCH.X86_64)
    ctx.setMode(MODE.ALIGNED_MEMORY, True)
    ctx.setMode(MODE.CONSTANT_FOLDING, True)
    ctx.setMode(MODE.AST_OPTIMIZATIONS, True)
    ctx.setAstRepresentationMode(AST_REPRESENTATION.PYTHON)

    binary = lief.parse("UnityPlayer.dll")
    base = binary.imagebase
    print(f"Base addr {hex(base)}")

    # load required sections
    for sec in binary.sections:
        if sec.name == ".text" or sec.name == ".rdata":
            addr = base + sec.virtual_address
            size = sec.size
            name = sec.name
            print(f"Loading {name} from {hex(addr)}-{hex(addr + size)}")
            ctx.setConcreteMemoryAreaValue(addr, sec.content)
    
    # concretize required .data regions
    for start, end in CONCRETIZED_REGIONS:
        print(f"Concretizing user region from {hex(start)}-{hex(end)}")
        data = binary.get_section(".data")
        offset = base + data.virtual_address
        print(len(data.content[start - offset:end - offset]))
        ctx.setConcreteMemoryAreaValue(start, data.content[start - offset:end - offset])
    
    # set up stack
    ctx.setConcreteRegisterValue(ctx.registers.rbp, BASE_STACK)
    ctx.setConcreteRegisterValue(ctx.registers.rsp, BASE_STACK)

    # symbolize input
    ctx.symbolizeRegister(ctx.registers.ecx, "input")

    # emulate
    print("Emulating")
    pc = 0x1801DA250
    count = 0
    while pc and pc < 0x190000000: # sanity check...
        opcodes = ctx.getConcreteMemoryAreaValue(pc, 16)
        instr = Instruction()
        instr.setOpcode(opcodes)
        instr.setAddress(pc)

        if not ctx.processing(instr):
            print(f"Failed to process instruction at {hex(pc)}")
            break
        print(instr)

        count += 1
        pc = ctx.getConcreteRegisterValue(ctx.registers.rip)
    print(f"Ended emulation at {hex(pc)} after {count} instructions")
    eax = ctx.getRegisterAst(ctx.registers.eax)
    ast = ctx.getAstContext()
    print(ast.unroll(eax))
    print(ctx.synthesize(ast.unroll(eax)))
```

My output:
```
...
0x181c2f80a: rol rcx, 0x10
0x181c2f80e: test cx, 0xffff
0x181c2f813: bnd jne 0x181c2f818
0x181c2f816: bnd ret
0x1801da379: add rsp, 0x20
0x1801da37d: mov eax, edi
0x1801da37f: lea rsp, [rbp + 8]
0x1801da383: pop rbx
0x1801da384: pop rdi
0x1801da385: pop rsi
0x1801da386: pop rbp
0x1801da387: ret
Ended emulation at 0x0 after 1058 instructions
((((((~((((((input & 0xff)) << 8 | ((input >> 8) & 0xff)) << 8 | ((input >> 16) & 0xff)) << 8 | ((input >> 24) & 0xff))) & 0xffffffff) & 0xd7848ce1) | ((((((input & 0xff)) << 8 | ((input >> 8) & 0xff)) << 8 | ((input >> 16) & 0xff)) << 8 | ((input >> 24) & 0xff)) & 0x287b731e)) ^ 0xf4f0e35f) + 0xfffffffd) & 0xffffffff)
None
```
The target binary can be found at [UnityPlayer.zip](https://github.com/JonathanSalwan/Triton/files/8006772/UnityPlayer.zip)

**Comment by JonathanSalwan** [comment]
If it returns `None`, it means that we did not managed to synthesis the given expression.

**Comment by JonathanSalwan** [comment]
I try to simplify your expression by hand and i think it is:

```(input ^ 0x23746fbe) + 0xfffffffd``` equivalent to ```(input ^ 0x23746fbe) - 3)```

**Comment by JonathanSalwan** [comment]
Wait no, i think it's more something like this:

```(reverse(input) ^ 0x23746fbe) + 0xfffffffd```

**Comment by JonathanSalwan** [comment]
Thanks for this example because it's pretty interesting.

So to resume: `ctx.synthesize` returned `None` because it was not able to synthesis your expression. Why? because it did not found the `bswap32` behavior, which is normal because it's not one of our operators. This is a pretty good example because it raises a new question: should we support the `bswap` operator? I still have think about it but so far i see no reason to not supporting it and if we can break concrete examples like this, it's full bonus :).

**Comment by khang06** [comment]
Yeah, that synthesis seems about right; I got the same result after reversing it by hand myself. I think supporting bswap is a good idea, since it doesn't look too hard to match. Also, unsurprisingly, LLVM optimizations were able to fully simplify the input. I wonder how well a LLVM <-> synthesis loop would work on more complex inputs...

**Comment by JonathanSalwan** [comment]
> Also, unsurprisingly, LLVM optimizations were able to fully simplify the input. I wonder how well a LLVM <-> synthesis loop would work on more complex inputs...

Yeah LLVM does so much voodoo things :). I'm wondering, did you convert to LLVM using the new feature `ctx.liftToLLVM`? Or did you convert it by yourself? Just to know if `liftToLLVM` works well as it's still experimental.

**Comment by khang06** [comment]
Yep, I just used liftToLLVM.

**Comment by JonathanSalwan** [comment]
Cool. btw if you have others expressions that you reversed and want to share to improve the synthesis. Feel free :)

**Comment by khang06** [comment]
I would, but a lot of the interesting obfuscated behavior on this binary tends to be quite loop heavy by nature so I haven't really figured out how to effectively apply something like this to it yet. This function just happened to be a perfect fit for a simple test. A while ago, I was able to apply Miasm to figure out and patch the obfuscated branches, but not much more than that. I tried looking into the Tigress examples but they don't seem to be updated (e.g. using Triton -> Arybo -> LLVM)

**Comment by JonathanSalwan** [comment]
I've added the `bswap` operator. So now we can synthesize the mba :)

```python
>>> from triton import *
>>> 
>>> def mba(x):
...     a = ((~((((((x & 0xff)) << 8 | ((x >> 8) & 0xff)) << 8 | ((x >> 16) & 0xff)) << 8 | ((x >> 24) & 0xff)))) & 0xd7848ce1)
...     b = ((((((x & 0xff)) << 8 | ((x >> 8) & 0xff)) << 8 | ((x >> 16) & 0xff)) << 8 | ((x >> 24) & 0xff)) & 0x287b731e)
...     return ((( a | b ) ^ 0xf4f0e35f) + 0xfffffffd)
... 
>>> ctx = TritonContext(ARCH.X86_64)
>>> ast = ctx.getAstContext()
>>> ctx.setAstRepresentationMode(AST_REPRESENTATION.PYTHON)
>>> 
>>> x = ast.variable(ctx.newSymbolicVariable(32, "x"))
>>> n = mba(x)
>>> print(ctx.synthesize(n))
(((bswap(x, 32) ^ 0x23746fbe) + 0xfffffffd) & 0xffffffff)
```
