### ISSUE TITLE
[question] Why including capstone differently in Windows

### ISSUE THREAD

**Issue by illera88** [JonathanSalwan/Triton#1087]
Hi there!

I've always seen the followin at https://github.com/JonathanSalwan/Triton/blob/1b32e67cab2a0b6e623695dcaacf627c03985a13/src/libtriton/includes/triton/externalLibs.hpp#L32-L39

Why do you do the include this way?  I haven't seen any documentation on capstone end to do so.
Why are the arm headers not needed to be included in windows?

Thanks

**Comment by JonathanSalwan** [comment]
Mmmh, i do not remember why i did this but it was probably for a good reason :D. Reading this,  it looks like on windows there were only one header while on linux/osx multiple ones. Maybe it was the case several years ago and not relevant today.

Does this works for you like this? Do you have to add other includes by yourself on windows?

**Comment by JonathanSalwan** [comment]
@illera88 is the patch ok for you? Indeed, i don't remember why i did this but make more sense now.

**Comment by illera88** [comment]
yeah, that makes more sense :)
