### ISSUE TITLE
[build] Build failure on OSX

### ISSUE THREAD

**Issue by JackBoosY** [JonathanSalwan/Triton#1089]
Hi guys,
I met a build issue on our OSX pipeline test:
```
[51/59] : && /Library/Developer/CommandLineTools/usr/bin/c++ -pthread -g -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -static src/examples/cpp/CMakeFiles/ir.dir/ir.cpp.o -o src/examples/cpp/ir  src/libtriton/libtriton.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libz3.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libcapstone.a && :
FAILED: src/examples/cpp/ir 
: && /Library/Developer/CommandLineTools/usr/bin/c++ -pthread -g -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -static src/examples/cpp/CMakeFiles/ir.dir/ir.cpp.o -o src/examples/cpp/ir  src/libtriton/libtriton.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libz3.a  /Users/vagrant/Data/installed/x64-osx/debug/lib/libcapstone.a && :
ld: library not found for -lcrt0.o
```

After some invesgations, I found a same isue in stackoverflow:
https://stackoverflow.com/questions/3801011/ld-library-not-found-for-lcrt0-o-on-osx-10-6-with-gcc-clang-static-flag

The related code is:
https://github.com/JonathanSalwan/Triton/blob/ebd74c52eb01ff9b51e478fe40c010edd4dfe731/src/examples/cpp/CMakeLists.txt#L6

Should it be:
```cmake
    if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        set(CMAKE_EXE_LINKER_FLAGS "-static")
    endif()
```
?
I don't know whether gnu need this.

Related: https://github.com/microsoft/vcpkg/pull/23111

Thanks,
Jack

**Comment by JonathanSalwan** [comment]
On linux we need this for a static compile. However, those lines are just for tests. Maybe we can ignore them for Windows and OSX if it facilitate the compile.

**Comment by mrexodia** [comment]
As a general rule it makes everything a lot easier if you never touch a CMAKE_ variable in your CMakeLists.txt. Instead pass these on the command line in your CI. You can also use CMake presets, but I’m not too familiar with those…
