### ISSUE TITLE
Consider lifting load, phi, call to symbolic variables

### ISSUE THREAD

**Issue by archercreat** [JonathanSalwan/Triton#1095]
Hello!
Currently `LLVMToTriton` throws on `LoadInst`, `PHINode` and `CallInst` instructions. It would be great, if you made them symbolic instead. That way, it would be possible to lift llvm-ir that was generated by external tool.
If you okay with this, i'll make pr on a weekend :)

**Comment by JonathanSalwan** [comment]
Thanks for your feedback. Yep we can do that.
