### ISSUE TITLE
many unit test failure appear during compilation 

### ISSUE THREAD

**Issue by csgaee** [JonathanSalwan/Triton#1099]
![image](https://user-images.githubusercontent.com/29278636/154812171-b423690d-56b5-4a16-b157-61ffa377608d.png)

in the notepad window it show the log of compilation output, and appearing that root cause is failure to import triton ??

**Comment by JonathanSalwan** [comment]
And where is the `triton.pyd` package?

**Comment by csgaee** [comment]
in `\build\src\libtriton\Release`  and i can manually load triton into python interpreter through 
`sys.path.append(r"..\build\src\libtriton\Release")`

but when i try to run the basic example from the github page 
and reaching this specific line
` ctx.getModel(rcx_expr.getAst() == 0xdead)`
make the interpreter to leave .. which make me doubt that something went wrong

**Comment by csgaee** [comment]
sorry the issue about this line 
`ctx.getModel(rcx_expr.getAst() == 0xdead)`
is because of me mixing different libz3.dll versions

**Comment by JonathanSalwan** [comment]
So everything is ok? Maybe you can move the triton.pyd  to your site-packages so that you can avoid sys.path.append?

**Comment by csgaee** [comment]
@JonathanSalwan  yep .. quick test and every thing seems to be perfect ... very thnx for your effort and help :)
