### ISSUE TITLE
'triton' command line tool

### ISSUE THREAD

**Issue by vm2p** [JonathanSalwan/Triton#1100]
Hi,

I'm using a project that requires the usage of a `triton` command line tool. However, building the Triton project only generates a dynamic library. I've looked at the sources to see if there was a special make instruction to create a tool but I couldn't find anything. 

While searching online, I found that such Triton tool could be installed under Pin tools. I also found online instructions to add `DPINTOOL=on` to the `cmake` command but `cmake` doesn't find `DPINTOOL`.

Is this `triton` command line tool something that existed previously but that is no longer maintained?

Thank you!

**Comment by JonathanSalwan** [comment]
Hey victor,

Triton has always been a library. This library takes as input opcodes, and those opcodes can come from any kind of tools like Pin for example. So, years ago we linked the triton library to a pintool (this is what you call the triton command line tool). However, this pintool was outdated and not maintained anymore so we removed the pintool of this repository. The commit that has removed the pintool is this [one](https://github.com/JonathanSalwan/Triton/commit/9117cec52fe19da7d23cfb4ef367f418dcc66ac4) and the last version of Triton that uses the pintool is this [one](https://github.com/JonathanSalwan/Triton/tree/e84b8a0aaf8104d4e158140d4768660d3c8deb57). If you want to use it, you have to download Pin 2.x (not working on Pin 3) and clone the commit e84b8a0aaf8104d4e158140d4768660d3c8deb57 into `pin/source/tools/`. Then `mkdir build ; cd build ; cmake -DPINTOOL=on -DKERNEL4=on ..`
