### ISSUE TITLE
[question] Updating Ponce to Triton v0.9

### ISSUE THREAD

**Issue by illera88** [JonathanSalwan/Triton#1101]
Hey @JonathanSalwan 👋 

I'm updating Ponce to the latest version of Triton and I found a couple things that do not compile anymore (you changed the API).

- https://github.com/illera88/Ponce/blob/master/src/context.cpp#L106: Here both `x86_ie` and `x86_fz` seem not to longer exist in Triton. How can I refactor that code?
- https://github.com/illera88/Ponce/blob/master/src/solver.cpp#L57: It seems you deleted `printSlicedExpressions` API. Why? What can I used instead?

Thank you

**Comment by JonathanSalwan** [comment]
Hey @illera88,

> https://github.com/illera88/Ponce/blob/master/src/context.cpp#L106: Here both x86_ie and x86_fz seem not to longer exist in Triton. How can I refactor that code?

Use `x86_sse_ie` and `x86_sse_fz` instead of `x86_ie` and `x86_fz`.

> https://github.com/illera88/Ponce/blob/master/src/solver.cpp#L57: It seems you deleted printSlicedExpressions API. Why? What can I used instead?

```patch
std::stringstream ss;
ss << "(set-logic QF_AUFBV)" << std::endl;
-api.printSlicedExpressions(ss, api.newSymbolicExpression(final_expr), true);
+api.liftToSMT(ss, api.newSymbolicExpression(final_expr), true);
msg("[+] Formula:\n%s\n\n", ss.str().c_str());
```

**Comment by illera88** [comment]
Cool!

Thanks

**Comment by illera88** [comment]
I have one last question:
You have seem to remove the `enable` method for both the taint and symbolic engines and now I can't do this:
```
api.getTaintEngine()->enable(cmdOptions.use_tainting_engine);
api.getSymbolicEngine()->enable(true);
```
https://github.com/illera88/Ponce/blob/master/src/triton_logic.cpp#L195-L196

How should I use the Triton API now in that case?

Thanks

**Comment by JonathanSalwan** [comment]
Hey @illera88,

I've removed the possibility to enable/disable the taint/symbolic engine to boost performance. In fact:

* If you do not want the taint engine, just do not taint data, it's better than disabling it.
* The symbolic engine never could be deactivated. With `<=v0.8` when you do `api.getSymbolicEngine()->enable(false)`, in fact we kept the symbolic engine on, did a snapshot, processed the instruction and then restored the snapshot. Taking a snapshot had a big cost.  If you do not want to keep symbolic expressions alive, just use an mode that removes them. For example you can use the mode `ONLY_ON_SYMBOLIZED` and symbolize nothing. (writing this answer let me thing that I can provide a mode called `CONCRETIZE_EVERYTHING`).

Back to your code, you can simply remove those lines:

```patch
//If we are in taint analysis mode we enable only the tainting engine and disable the symbolic one
-api.getTaintEngine()->enable(cmdOptions.use_tainting_engine);
-api.getSymbolicEngine()->enable(true);
```

Btw, your comment does not match the code you wrote: `api.getSymbolicEngine()->enable(true);`. Maybe it's `enable(false)`? So the patch could be:

```patch
//If we are in taint analysis mode we enable only the tainting engine and disable the symbolic one
-api.getTaintEngine()->enable(cmdOptions.use_tainting_engine);
-api.getSymbolicEngine()->enable(true);
+api.setMode(triton::modes::ONLY_ON_SYMBOLIZED, true); // If we symbolize nothing, none of expression will be kept alive.
```

**Comment by illera88** [comment]
Yeah, that made not much sense. I deleted both lines.

But a little bit further down I have the following:
https://github.com/illera88/Ponce/blob/master/src/triton_logic.cpp#L204-L205
```
    api.setMode(triton::modes::ONLY_ON_SYMBOLIZED, cmdOptions.use_symbolic_engine);
    api.setMode(triton::modes::ONLY_ON_TAINTED, cmdOptions.use_tainting_engine);
```
Ponce allows to let the user decide if he wants to use the leaner and faster tainting engine or the slower but feature rich symbolic one. Do those two lines make sense? Because for what I see in the mode comments both modes seem to only apply to the symbolic engine:

```
ONLY_ON_SYMBOLIZED,             //!< [symbolic] Perform symbolic execution only on symbolized expressions.
ONLY_ON_TAINTED,                //!< [symbolic] Perform symbolic execution only on tainted instructions.
```
Should I just do `api.setMode(triton::modes::ONLY_ON_SYMBOLIZED, true);` since it does not apply to the taint engine and it makes sense to only do symbolic execution on symbolic instructions right?

**Comment by illera88** [comment]
Another question: what is the point of using `triton::modes::ONLY_ON_TAINTED` on the symbolic engine?

**Comment by JonathanSalwan** [comment]
Pretty similar with light different behavior.

* `ONLY_ON_SYMBOLIZED`: keeps expressions (AST) that contain at least a symbolic variable.
* `ONLY_ON_TAINTED`: keeps all expressions (AST) of an instructions if the instruction is tainted.

The subtility is: `xor symvar/tainted, symvar/tainted` contains a symbolic variable but are is tainted as the result is zero.

**Comment by illera88** [comment]
Thanks!

Closing again
