### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by helloobaby** [JonathanSalwan/Triton#1109]
-- Compiling with Z3 SMT solver
Z3_INCLUDE_DIR=Z3_INCLUDE_DIR-NOTFOUND
Z3_INCLUDE_DIRS=
Z3_LIBRARY=Z3_LIBRARY-NOTFOUND
Z3_LIBRARIES=
CMake Error at CMakeModules/LibFindMacros.cmake:75 (message):
  Required library Z3 NOT FOUND.

  Install the library (dev version) and try again.  If the library is already
  installed, use ccmake to set the missing variables manually.
Call Stack (most recent call first):
  CMakeModules/FindZ3.cmake:40 (libfind_process)
  CMakeLists.txt:105 (find_package)

I have already install z3
PS D:\Triton\build> pip freeze
boto==2.49.0
debugpy==1.0.0rc2
tornado==6.1
unicorn==1.0.3
urllib3==1.26.8
z3-solver==4.8.14.0

**Comment by JonathanSalwan** [comment]
You just have to define `Z3_INCLUDE_DIRS` and `Z3_LIBRARIES`.

`cmake -DZ3_LIBRARIES=/your/path -DZ3_INCLUDE_DIRS=/your/path`

**Comment by helloobaby** [comment]
This works, thanks a lot
