### ISSUE TITLE
cpp examples error

### ISSUE THREAD

**Issue by helloobaby** [JonathanSalwan/Triton#1110]
https://github.com/JonathanSalwan/Triton/blob/55b2bd538a2f389b201c2a9717f9316a90613be0/src/examples/cpp/constraint.cpp#L52

this line raise access violation,is this intentional?

I am a beginner of Triton,  sorry to bother you again

**Comment by JonathanSalwan** [comment]
This is probably an issue with your capstone version. Do you use capstone 4.0.2 ? Do you have multiple capstone version on your system ? Does the linked capstone library is the same as the one used for compiling triton ?

**Comment by helloobaby** [comment]
i use capstone 5.0(latest). do i have to use 4.0.2?

**Comment by helloobaby** [comment]
I solve the problem . 
now i use https://github.com/capstone-engine/capstone/releases/tag/4.0.2
