### ISSUE TITLE
Build with vs 2022 on Windows

### ISSUE THREAD

**Issue by stanley101music** [JonathanSalwan/Triton#1115]
Hello Triton Team,

I'm following the installation guide in README and trying to build the compiled library (libTriton), which I can use in my c++ pintool.
I've downloaded the following dependencies
* boost: 1.78.0
* capstone: 4.0.2
* python: 3.9
* z3: 4.8.15

And my install command is
```
cmake -G "Visual Studio 17 2022" -DBOOST_ROOT="D:/boost_1_78_0" -DPYTHON_INCLUDE_DIRS="C:/Users/stanl/AppData/Local/Programs/Python/Python39/include" -DPYTHON_LIBRARIES="C:/Users/stanl/AppData/Local/Programs/Python/Python39/libs/python39.lib" -DZ3_INCLUDE_DIRS="D:/z3-4.8.15-x64-win/include" -DZ3_LIBRARIES="D:/z3-4.8.15-x64-win/bin/libz3.lib" -DCAPSTONE_INCLUDE_DIRS="D:/capstone-4.0.2-win64/include" -DCAPSTONE_LIBRARIES="D:/capstone-4.0.2-win64/capstone.lib"
```
The vs .sln file is generated successfully. However, when I tried to build the solution with options
* "Release x64"
* /NODEFAULTLIB (for "triton" project)

I got lots of unresolved external symbol errors that I couldn't figure out how to solve it
```
LNK 2001: unresolved external symbol "void __cdecl `eh vector destructor iterator'(void *,unsigned __int64,unsigned __int64,void (__cdecl*)(void *))" (??_M@YAXPEAX_K1P6AX0@Z@Z)
LNK 2001: unresolved external symbol _purecall
...
```
I'd like to know if it's possible to build with vs 2022 and which step I'm missing or doing wrong.

Thank you!

**Comment by mrexodia** [comment]
I don’t think you will be able to build triton with `/NODEFAULTLIB`. It uses many C++ library features.

**Comment by mrexodia** [comment]
That’s probably because you’re building Triton with /MD instead of /MT, but I don’t think what you want is easily possible unfortunately.

**Comment by JonathanSalwan** [comment]
If you only want to use the taint engine you can disable z3 as well as Python and use our new wide-integer multi precision library to avoid boost.

`cmake -DBOOST_INTERFACE=off -DPYTHON_BINDINGS=off -DZ3_INTERFACE=off ..`

Then if you want to compile Triton as static library: 

`cmake -DBOOST_INTERFACE=off -DPYTHON_BINDINGS=off -DZ3_INTERFACE=off -DBUILD_SHARED_LIBS=off ..`

**Comment by stanley101music** [comment]
Thanks, I've successfully built the static `triton.lib` with the following command and option `Release`, `/MT`
```
cmake -DBOOST_INTERFACE=off -DPYTHON_BINDINGS=off -DZ3_INTERFACE=off -DCAPSTONE_INCLUDE_DIRS="D:/capstone-4.0.2-win64/include" -DCAPSTONE_LIBRARIES="D:/capstone-4.0.2-win64/capstone.lib" -DBUILD_SHARED_LIBS=off ..
```

**Comment by stanley101music** [comment]
Not sure if it's related, but I create a project and test whether the library generated by the previous steps is available.
The content of source file is taken from `Triton\src\examples\cpp\taint_reg.cpp` and the compiled options are
* `Release`
* `x86`
* `/MT`
* Other Include directory
  * `D:\Triton\build\src\libtriton\includes` (This only includes `triton/config.hpp` and `triton/version.hpp`)
  * `D:\Triton\src\libtriton\includes` (All the other `.hpp` files are included here)
* Other dependency
  * `D:\Triton\build\src\libtriton\Release\triton.lib` (This is the static library generated by the previous steps)

With these settings I got some unresolved external symbol errors
* `_cs_open`
* `_cs_close`
* `_cs_option`
* `_cs_disasm`
* `_cs_free`

Are these errors due to the wrong settings of the project or because the generated static library failed

**Comment by stanley101music** [comment]
Sorry for the stupid questions. I've successfully linked the 32-bit static library.
If anyone is interested, here's how I did it.
### Build command and options for 32-bit static library
* `cmake -DCMAKE_GENERATION_PLATFORM=Win32 -DBOOST_INTERFACE=off -DPYTHON_BINDINGS=off -DZ3_INTERFACE=off -DCAPSTONE_INCLUDE_DIRS="D:/capstone-4.0.2-win32/include" -DCAPSTONE_LIBRARIES="D:/capstone-4.0.2-win32/capstone.lib" -DBUILD_SHARED_LIBS=off ..`
* `Release`
* `MT`
### Properties for the project using the generated 32-bit static library
* `Release`
* `MT`
* C/C++: Inclusion
  * `Triton/build/src/libtriton/includes`
  * `Triton/src/libtriton/includes`
* Linker: other dependencies
  * `capstone-4.0.2-win32/capstone.lib`
  * `Triton/build/src/libtriton/Release/triton.lib`

**Comment by JonathanSalwan** [comment]
Thanks for letting us know your solution. It will probably help others ppls.
