### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by sikoushixinyou** [JonathanSalwan/Triton#1119]
Hi ，thanks for reading my issue
When I execute `cmake ..` I get the following error.
CMake Error at /snap/cmake/1070/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PythonLibs (missing: PYTHON_INCLUDE_DIRS) (Required is at
  least version "3.6")
Call Stack (most recent call first):
  /snap/cmake/1070/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /snap/cmake/1070/share/cmake-3.23/Modules/FindPythonLibs.cmake:310 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:54 (find_package)
How should i fix this error？

**Comment by JonathanSalwan** [comment]
> `Could NOT find PythonLibs (missing: PYTHON_INCLUDE_DIRS)`

So you have to define `PYTHON_INCLUDE_DIRS` and `PYTHON_LIBRARIES`.

```
cmake \
  -DPYTHON_LIBRARIES=/your/path/to/python/libpython3.x.so \
  -DPYTHON_INCLUDE_DIRS=/your/path/to/python/include
```
