### ISSUE TITLE
BasicBlock class

### ISSUE THREAD

**Issue by JonathanSalwan** [JonathanSalwan/Triton#1121]
Introducing basic blocks could bring cool features in the future. Currently i'm adding this to perform dead code elimination but it can be used in the future to represent CFG for example.

**Comment by JonathanSalwan** [comment]
First example.

## Disassembling and print a basic block

```cpp
using namespace triton::arch;

// Creating the block
BasicBlock block = BasicBlock({
  Instruction((unsigned char *)"\x89\xd0", 2),      /* mov   eax, edx  */
  Instruction((unsigned char *)"\x80\xf4\x99", 3),  /* xor   ah, 0x99  */
  Instruction((unsigned char *)"\x85\xc0", 2),      /* test  eax, eax  */
  Instruction((unsigned char *)"\x74\x08", 2),      /* jz    10        */
});

// Disassemble the block
api.disassembly(block);

// Print the block
std::cout << block << std::endl;

// Result:
// 0x0: mov eax, edx
// 0x2: xor ah, 0x99
// 0x5: test eax, eax
// 0x7: je 0x11
```

## Disassembling an instruction and add it to the block

```cpp
// Create an instruction
auto i = Instruction((unsigned char *)"\x90", 1); /* nop */

// Disass the instruction
api.disassembly(i);

// Add it 3 times to the block
block.add(i);
block.add(i);
block.add(i);

// Print the block
std::cout << block << std::endl;

// Result
// 0x0: mov eax, edx
// 0x2: xor ah, 0x99
// 0x5: test eax, eax
// 0x7: je 0x11
// 0x9: nop
// 0xa: nop
// 0xb: nop
```

## Disassembling a block from a base address

```cpp
api.disassembly(block, 0x1000);
std::cout << block << std::endl;

// Result
// 0x1000: mov eax, edx
// 0x1002: xor ah, 0x99
// 0x1005: test eax, eax
// 0x1007: je 0x1011
// 0x1009: nop
// 0x100a: nop
// 0x100b: nop
```

## Process a block

```cpp
// Removing the instruction JE in order to not have instruction after a branch instruction
// Note that I could have also removed NOPs instead of the the JE.
block.remove(3);

// Process the block
// processing() raises an exception if there are instructions after a branch instruction.
// You can also execute a block which do not contains branch instruction.
api.processing(block);
```

**Comment by JonathanSalwan** [comment]
@SweetVishnya, when implementing this I remembered those [lines](https://github.com/JonathanSalwan/Triton/blob/243026c9c1e07a5ca834c4aaf628d1079f6a85ea/src/libtriton/arch/architecture.cpp#L250-L284) you added months ago. I know you use those methods and I'm wondering if we can return a `BasicBlock` instead of a `std::vector`. Then, you can deal with the block and if you want to get instructions you can call `BasicBlock::getInstructions()` which [returns](https://github.com/JonathanSalwan/Triton/blob/3f206a9c816d5aaa271776ac7146071ef04bfc48/src/libtriton/includes/triton/basicBlock.hpp#L65) a `std::vector<triton::arch::Instruction>&`.

**Comment by SweetVishnya** [comment]
> @SweetVishnya, when implementing this I remembered those [lines](https://github.com/JonathanSalwan/Triton/blob/243026c9c1e07a5ca834c4aaf628d1079f6a85ea/src/libtriton/arch/architecture.cpp#L250-L284) you added months ago. I know you use those methods and I'm wondering if we can return a `BasicBlock` instead of a `std::vector`. Then, you can deal with the block and if you want to get instructions you can call `BasicBlock::getInstructions()` which [returns](https://github.com/JonathanSalwan/Triton/blob/3f206a9c816d5aaa271776ac7146071ef04bfc48/src/libtriton/includes/triton/basicBlock.hpp#L65) a `std::vector<triton::arch::Instruction>&`.

Actually, we do not use that method :P We manage memory mapped files and get single instruction after insruction from it and manually call processing instruction-level.
