### ISSUE TITLE
ModuleNotFoundError: No module named 'triton'

### ISSUE THREAD

**Issue by sikoushixinyou** [JonathanSalwan/Triton#1122]
After I finished the installation according to the following steps, 

tzy@tzy-virtual-machine:~/Triton/build$ cmake ..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Compiling with Python bindings
-- Compiling with Z3 SMT solver
-- Found Z3 include directory: /usr/include
-- Found Z3 library: /usr/lib/libz3.so
-- Compiling with Capstone
-- Found CAPSTONE include directory: /usr/include
-- Found CAPSTONE library: /usr/lib/libcapstone.so
-- Compiling with Boost headers
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tzy/Triton/build
tzy@tzy-virtual-machine:~/Triton/build$ make -j3
Consolidate compiler generated dependencies of target triton
[  1%] Linking CXX shared library libtriton.so
[ 86%] Built target triton
Consolidate compiler generated dependencies of target taint_reg
Consolidate compiler generated dependencies of target info_reg
[ 86%] Built target python-triton
Consolidate compiler generated dependencies of target ir
[ 88%] Linking CXX executable taint_reg
[ 89%] Linking CXX executable info_reg
[ 90%] Linking CXX executable ir
[ 91%] Built target ir
Consolidate compiler generated dependencies of target simplification
[ 92%] Built target taint_reg
[ 93%] Built target info_reg
Consolidate compiler generated dependencies of target constraint
[ 94%] Linking CXX executable simplification
Consolidate compiler generated dependencies of target ctest_api
[ 95%] Linking CXX executable constraint
[ 96%] Linking CXX executable ctest_api
[ 97%] Built target simplification
[ 98%] Built target constraint
[100%] Built target ctest_api
tzy@tzy-virtual-machine:~/Triton/build$ sudo make install
[ 86%] Built target triton
[ 86%] Built target python-triton
[ 89%] Built target taint_reg
[ 91%] Built target info_reg
[ 93%] Built target ir
[ 95%] Built target simplification
[ 97%] Built target constraint
[100%] Built target ctest_api
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/local/lib/cmake/triton/tritonTargets.cmake
-- Installing: /usr/local/lib/libtriton.so
-- Up-to-date: /usr/local/include/triton/aarch64.spec
-- Up-to-date: /usr/local/include/triton/aarch64Cpu.hpp
-- Up-to-date: /usr/local/include/triton/aarch64Semantics.hpp
-- Up-to-date: /usr/local/include/triton/aarch64Specifications.hpp
-- Up-to-date: /usr/local/include/triton/api.hpp
-- Up-to-date: /usr/local/include/triton/archEnums.hpp
-- Up-to-date: /usr/local/include/triton/architecture.hpp
-- Up-to-date: /usr/local/include/triton/arm32.spec
-- Up-to-date: /usr/local/include/triton/arm32Cpu.hpp
-- Up-to-date: /usr/local/include/triton/arm32Semantics.hpp
-- Up-to-date: /usr/local/include/triton/arm32Specifications.hpp
-- Up-to-date: /usr/local/include/triton/armOperandProperties.hpp
-- Up-to-date: /usr/local/include/triton/ast.hpp
-- Up-to-date: /usr/local/include/triton/astContext.hpp
-- Up-to-date: /usr/local/include/triton/astEnums.hpp
-- Up-to-date: /usr/local/include/triton/astPythonRepresentation.hpp
-- Up-to-date: /usr/local/include/triton/astRepresentation.hpp
-- Up-to-date: /usr/local/include/triton/astRepresentationInterface.hpp
-- Up-to-date: /usr/local/include/triton/astSmtRepresentation.hpp
-- Up-to-date: /usr/local/include/triton/bitsVector.hpp
-- Up-to-date: /usr/local/include/triton/bitwuzlaSolver.hpp
-- Up-to-date: /usr/local/include/triton/callbacks.hpp
-- Up-to-date: /usr/local/include/triton/callbacksEnums.hpp
-- Up-to-date: /usr/local/include/triton/comparableFunctor.hpp
-- Up-to-date: /usr/local/include/triton/coreUtils.hpp
-- Up-to-date: /usr/local/include/triton/cpuInterface.hpp
-- Up-to-date: /usr/local/include/triton/cpuSize.hpp
-- Up-to-date: /usr/local/include/triton/dllexport.hpp
-- Up-to-date: /usr/local/include/triton/exceptions.hpp
-- Up-to-date: /usr/local/include/triton/externalLibs.hpp
-- Up-to-date: /usr/local/include/triton/immediate.hpp
-- Up-to-date: /usr/local/include/triton/instruction.hpp
-- Up-to-date: /usr/local/include/triton/irBuilder.hpp
-- Up-to-date: /usr/local/include/triton/liftingEngine.hpp
-- Up-to-date: /usr/local/include/triton/liftingToDot.hpp
-- Up-to-date: /usr/local/include/triton/liftingToLLVM.hpp
-- Up-to-date: /usr/local/include/triton/liftingToPython.hpp
-- Up-to-date: /usr/local/include/triton/liftingToSMT.hpp
-- Up-to-date: /usr/local/include/triton/llvmToTriton.hpp
-- Up-to-date: /usr/local/include/triton/memoryAccess.hpp
-- Up-to-date: /usr/local/include/triton/modes.hpp
-- Up-to-date: /usr/local/include/triton/modesEnums.hpp
-- Up-to-date: /usr/local/include/triton/operandWrapper.hpp
-- Up-to-date: /usr/local/include/triton/oracleEntry.hpp
-- Up-to-date: /usr/local/include/triton/pathConstraint.hpp
-- Up-to-date: /usr/local/include/triton/pathManager.hpp
-- Up-to-date: /usr/local/include/triton/register.hpp
-- Up-to-date: /usr/local/include/triton/semanticsInterface.hpp
-- Up-to-date: /usr/local/include/triton/shortcutRegister.hpp
-- Up-to-date: /usr/local/include/triton/solverEngine.hpp
-- Up-to-date: /usr/local/include/triton/solverEnums.hpp
-- Up-to-date: /usr/local/include/triton/solverInterface.hpp
-- Up-to-date: /usr/local/include/triton/solverModel.hpp
-- Up-to-date: /usr/local/include/triton/symbolicEngine.hpp
-- Up-to-date: /usr/local/include/triton/symbolicEnums.hpp
-- Up-to-date: /usr/local/include/triton/symbolicExpression.hpp
-- Up-to-date: /usr/local/include/triton/symbolicSimplification.hpp
-- Up-to-date: /usr/local/include/triton/symbolicVariable.hpp
-- Up-to-date: /usr/local/include/triton/synthesisResult.hpp
-- Up-to-date: /usr/local/include/triton/synthesizer.hpp
-- Up-to-date: /usr/local/include/triton/taintEngine.hpp
-- Up-to-date: /usr/local/include/triton/tritonToBitwuzla.hpp
-- Up-to-date: /usr/local/include/triton/tritonToLLVM.hpp
-- Up-to-date: /usr/local/include/triton/tritonToZ3.hpp
-- Up-to-date: /usr/local/include/triton/tritonTypes.hpp
-- Up-to-date: /usr/local/include/triton/uintwide_t.h
-- Up-to-date: /usr/local/include/triton/x86.spec
-- Up-to-date: /usr/local/include/triton/x8664Cpu.hpp
-- Up-to-date: /usr/local/include/triton/x86Cpu.hpp
-- Up-to-date: /usr/local/include/triton/x86Semantics.hpp
-- Up-to-date: /usr/local/include/triton/x86Specifications.hpp
-- Up-to-date: /usr/local/include/triton/z3Solver.hpp
-- Up-to-date: /usr/local/include/triton/z3ToTriton.hpp
-- Up-to-date: /usr/local/include/triton/version.hpp
-- Up-to-date: /usr/local/include/triton/config.hpp
-- Up-to-date: /usr/local/lib/cmake/triton/tritonConfig.cmake
-- Up-to-date: /usr/local/lib/cmake/triton/tritonConfigVersion.cmake
-- Installing: /usr/local/lib/python3.8/site-packages/triton.so
tzy@tzy-virtual-machine:~/Triton/build$ make check

I tried to run the case（`./small_x86-64_symbolic_emulator.py ./samples/sample_1 hello`）,but the following error message appeared.

Traceback (most recent call last):
  File "./small_x86-64_symbolic_emulator.py", line 50, in <module>
    from triton     import TritonContext, ARCH, MemoryAccess, CPUSIZE, Instruction, OPCODE, MODE
ModuleNotFoundError: No module named 'triton'

How should i fix this error？ Thanks for your time.

**Comment by JonathanSalwan** [comment]
Is `./small_x86-64_symbolic_emulator.py` executed with `python3.8` ?

**Comment by sikoushixinyou** [comment]
> 是`./small_x86-64_symbolic_emulator.py`用你的`python3.8`?
Yes, it is python3.8.

**Comment by JonathanSalwan** [comment]
Can you display the full trace of the cmake because i'm not sure python bindings was compiled into your `/usr/local/lib/python3.8/site-packages/triton.so`

**Comment by sikoushixinyou** [comment]
Yes, it is python3.8.

**Comment by sikoushixinyou** [comment]
tzy@tzy-virtual-machine:~/Triton/build$ cmake ..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Compiling with Python bindings
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3.6") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found suitable version "3.8.10", minimum required is "3.6") 
-- Compiling with Z3 SMT solver
-- Found Z3 include directory: /usr/include
-- Found Z3 library: /usr/lib/libz3.so
-- Compiling with Capstone
-- Found CAPSTONE include directory: /usr/include
-- Found CAPSTONE library: /usr/lib/libcapstone.so
-- Compiling with Boost headers
-- Found Boost: /usr/local/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found suitable version "1.78.0", minimum required is "1.55.0")  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tzy/Triton/build

**Comment by JonathanSalwan** [comment]
Can you print the result of `$ locate python3.8` ?

**Comment by JonathanSalwan** [comment]
In fact, make sure `triton.so` is installed in the good directory of your `site-packages`. I see `/usr/local/lib/python3.8/site-packages/triton.so` but is the path valid for your python interpreter ?

**Comment by sikoushixinyou** [comment]
tzy@tzy-virtual-machine:~/Triton/build$ locate python3.8 | grep site-packages
/usr/local/lib/python3.8/site-packages
/usr/local/lib/python3.8/site-packages/triton.so

**Comment by sikoushixinyou** [comment]
Thank you very much!
This is a problem with my python interpreter path. Now,I can run the sample(small_x86-64_symbolic_emulator.py) correctly.
