### ISSUE TITLE
Using Triton to evaluate the overhead due to taint analysis engine

### ISSUE THREAD

**Issue by sikoushixinyou** [JonathanSalwan/Triton#1123]
Hi, I want to use Triton to design a tool that can evaluate the overhead due to taint analysis engine(just like libdft,it apply DFT on the application being executed, but does not use any of the API functions to define data sources and sinks).How should I use Triton to accomplish a tool that provides similar functionality？Can you give me some pointers？

**Comment by JonathanSalwan** [comment]
Well, you juste have to emulate your target with triton, then first do:

```
time()
run()
time()
```

and then,

```
time()
taint_your_data()
run()
time()
```

To emulate a code, [here](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/small_x86-64_symbolic_emulator.py) an example and [there](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/forward_tainting.py#L112) for tainting example,

**Comment by sikoushixinyou** [comment]
I imitated the example to load a binary program, but what should I do when processing() return false. If an instruction(Triton don't supports it),should skip this instruction and execute the next instruction？

**Comment by JonathanSalwan** [comment]
Well, if you do that the correctness of the emulation may be comprised.

**Comment by JonathanSalwan** [comment]
Actually, it depend of the instructions. Maybe it's behavior can be emulated too or just skipped if not such important.

**Comment by sikoushixinyou** [comment]
When processing() return false,how to get the next instruction.
`pc = Triton.getConcreteRegisterValue(Triton.registers.rip)`can't get the nex tinstruction.The process runs into a loop and it gets killed by my Linux.

**Comment by JonathanSalwan** [comment]
`pc = inst.getNextAddress()`

**Comment by sikoushixinyou** [comment]
I have defined a emulate function like below, but it gets stuck in an infinite loop.
```python
def emulate(pc):
    while pc:
        # Fetch opcode
        opcode = Triton.getConcreteMemoryAreaValue(pc, 16)

        # Create the Triton instruction
        instruction = Instruction()
        instruction.setOpcode(opcode)
        instruction.setAddress(pc)

        # Process
        flag = Triton.processing(instruction)
        if flag == True:  
            pc = Triton.getConcreteRegisterValue(Triton.registers.rip)
        if flag == False:  #skip
        	pc = instruction.getNextAddress()

    debug('Instruction executed: %d' %(count))
    return

**Comment by JonathanSalwan** [comment]
Can't tell you what going on without seeing the assembly code executed. But i bet you fetched `00 00` opcode which is a valid x86 binary code (`add byte ptr [rax], al`). This is typical behavior when you fetch uninitialized memory.

**Comment by sikoushixinyou** [comment]
Here is my complete code, which I use to analyze a simple example binary(it just printf hello).But I find after emulate `0x1088: call qword ptr [rip + 0x2f52]` ,the `pc` become `0` and exit the while loop. Am I doing something wrong?
```python

from __future__ import print_function
from triton     import TritonContext, ARCH, MemoryAccess, CPUSIZE, Instruction, OPCODE, MODE

import sys
import string
import random

Triton = TritonContext()


# Script options
DEBUG = True

# Memory mapping
BASE_STACK = 0x9fffffff



# Emulate the binary.
def emulate(pc):
    count = 0
    while pc:
        # Fetch opcode
        opcode = Triton.getConcreteMemoryAreaValue(pc, 16)

        # Create the Triton instruction
        instruction = Instruction()
        instruction.setOpcode(opcode)
        instruction.setAddress(pc)

        # Process
        flag = Triton.processing(instruction)
        count += 1
        print(instruction)

        # Next
        if flag == True:
            pc = Triton.getConcreteRegisterValue(Triton.registers.rip)
            print(pc)
        if flag == False:
            pc = instruction.getNextAddress()
            print("Unsupported instruction")
            print(pc)

    debug('Instruction executed: %d' %(count))
    return


def loadBinary(path):
    import lief
    # Map the binary into the memory
    binary = lief.parse(path)
    phdrs  = binary.segments
    for phdr in phdrs:
        size   = phdr.physical_size
        vaddr  = phdr.virtual_address
        #debug('Loading 0x%06x - 0x%06x' %(vaddr, vaddr+size))
        Triton.setConcreteMemoryAreaValue(vaddr, list(phdr.content))
    return binary


def debug(s):
    if DEBUG:
        print('[Triton] %s' %(s))
    return


if __name__ == '__main__':
    # Set the architecture
    Triton.setArchitecture(ARCH.X86_64)

    # Set a symbolic optimization mode
    Triton.setMode(MODE.ALIGNED_MEMORY, True)

    # AST representation as Python syntax
    #setAstRepresentationMode(AST_REPRESENTATION.PYTHON)


    # Load the binary
    binary = loadBinary(sys.argv[1])


    # Define a fake stack
    Triton.setConcreteRegisterValue(Triton.registers.rbp, BASE_STACK)
    Triton.setConcreteRegisterValue(Triton.registers.rsp, BASE_STACK)

    # Let's emulate the binary from the entry point
    debug('Starting emulation')
    emulate(binary.entrypoint)
    debug('Emulation done')

    sys.exit(0)

##The result is as follows
[Triton] Starting emulation
0x1060: endbr64
pc : 4196
0x1064: xor ebp, ebp
pc : 4198
0x1066: mov r9, rdx
pc : 4201
0x1069: pop rsi
pc : 4202
0x106a: mov rdx, rsp
pc : 4205
0x106d: and rsp, 0xfffffffffffffff0
pc : 4209
0x1071: push rax
pc : 4210
0x1072: push rsp
pc : 4211
0x1073: lea r8, [rip + 0x166]
pc : 4218
0x107a: lea rcx, [rip + 0xef]
pc : 4225
0x1081: lea rdi, [rip + 0xc1]
pc : 4232
0x1088: call qword ptr [rip + 0x2f52]
pc : 0
[Triton] Instruction executed: 12
[Triton] Emulation done

**Comment by JonathanSalwan** [comment]
> Here is my complete code,

Looks like my [example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/small_x86-64_symbolic_emulator.py) as a bootstrap but without parts of the code that will solve your issue...

> But I find after emulate 0x1088: call qword ptr [rip + 0x2f52] ,the pc become 0 and exit the while loop.

This is what happen if you do not emulate the code of external functions. `printf` is not in your binary code, it's in `libc`. You have to emulate it. Basically, the parts of the code you removed from my example.

> Am I doing something wrong?

Just keep my example as it is, without removing part of code.

**Comment by sikoushixinyou** [comment]
I use the [example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/small_x86-64_symbolic_emulator.py) to test your sample_1.c. I found that when compiling it with dynamic linking, the tests ran as expected. But using static linking to compile it and then testing it will end up in an infinite loop.

**Comment by JonathanSalwan** [comment]
Probably because some instructions are not supported and you skipped them or because you did not handled syscall.
