### ISSUE TITLE
ADC/SBB semantics for flags

### ISSUE THREAD

**Issue by SweetVishnya** [JonathanSalwan/Triton#1124]
Flags semantics for adc/sbb are the same as for add/sub. Does this magic work? Do we consider a case when overflow occurs due to carry flag cf=1 and simple add does not cause an overflow? (a + b does not overflow when a + b + 1 overflows)

https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/arch/x86/x86Semantics.cpp#L3028

**Comment by JonathanSalwan** [comment]
I remembered running the qemu-ir test suits via the Pin tracer with success on this but maybe we could double check and add unit tests with unicorn.

**Comment by JonathanSalwan** [comment]
Mmmh, according to the [intel manual](http://shell-storm.org/x86doc/ADC.html):

> The ADC instruction does not distinguish between signed or unsigned operands. Instead, the processor evaluates the result for both data types and sets the OF and CF flags to indicate a carry in the signed or unsigned result, respectively.

**Comment by JonathanSalwan** [comment]
Mmmmh, everything looks good in fact. `OF` and `CF` are correctly defined. Can you confirm or give me a counter example?

**Comment by SweetVishnya** [comment]
I still haven't found time to check it. But let's believe that everything is ok.
