### ISSUE TITLE
How could I use pin in new version?

### ISSUE THREAD

**Issue by killkeven** [JonathanSalwan/Triton#1126]
Hi,
I found the new version of Triton remove the pin tool, how could I use Triton for dynamic binary analysis? Is there any other lib or api in Triton I can use to analyse a ELF file in JIT mod?
Thank you!

**Comment by JonathanSalwan** [comment]
I made another [example](http://shell-storm.org/repo/Notepad/qbdi_with_triton.txt) using [QBDI](https://qbdi.quarkslab.com/) and Triton. My example relies on an old qbdi version, now you can directly do `import pyqbdi` on Python. However, the API should be same.

Hope it can help,
