### ISSUE TITLE
record original symbolic expression in a memory callback

### ISSUE THREAD

**Issue by asevergreen** [JonathanSalwan/Triton#1127]
Hi, I want to record the original symbolic expression when setting memory in a callback. At this time the concrete value is still the original, but the symbolic expression has been updated. Is there any way to do what I want? Thank you very much!
Same question as #1037, but I didn't get a response there.

**Comment by JonathanSalwan** [comment]
>  Is there any way to do what I want?

Currently it is not possible to do that with the Triton's API. However it could be possible on your side by recording memory expression. However, let me few weeks to thing about if we can add a callback before symbolic expressions assignment.

**Comment by asevergreen** [comment]
Thanks for your suggestion, it works for me!
By the way, I think the memory's callback is called before processing the instruction, so its concrete value is still the original value, but why the symbolic expression has been updated? Has the instruction been processed at this point?

**Comment by JonathanSalwan** [comment]
> but why the symbolic expression has been updated? 

We start by [assigning](https://github.com/JonathanSalwan/Triton/blob/5c8ea9b2be4e7236c09c23ed029a47698e514b3b/src/libtriton/engines/symbolic/symbolicEngine.cpp#L925-L940) the `expr` to memory cells at the appropriate address. Then, we evaluate the concrete value of the `expr` and we [assign](https://github.com/JonathanSalwan/Triton/blob/5c8ea9b2be4e7236c09c23ed029a47698e514b3b/src/libtriton/engines/symbolic/symbolicEngine.cpp#L959) this value to the concrete state. 

> Has the instruction been processed at this point?

Kind of, it is actually in process of processed :).
