### ISSUE TITLE
How to get the byte level taint relationship for an instruction?

### ISSUE THREAD

**Issue by vancaho** [JonathanSalwan/Triton#1129]
Hi, I want to use triton to retrieve the taint relationship of instructions. For example, for the instruction `mov dword ptr [edx], ebx` where `edx=0xbf87a0ca`, I want to ask which is the source for  the address `0xbf87a0ca`. From the semantics of the instruction, the answer will be the `0-7` bits of ebx register. But from the symbolic expressions of the instruction, I can only know that `ebx` is the source, which is 4 bytes, but not the byte level precision.

Similarly, if I want to know which memory is the source of `bl` register for the instruction `mov ebx, dword ptr [eax + ecx - 4]` where `eax=0x9d24144` and `ecx=0x6`. How to do it with triton?

Thanks very much

**Comment by JonathanSalwan** [comment]
Hey this is not possible with the taint engine. We perform a over-approximation tainting. However you can symbolize a memory cell at byte level and then get your `bl` expression which will contains your 8-bit symbolic variable. Tainting something and symbolize something is pretty similar if you want to mark/follow a reg/mem.

**Comment by vancaho** [comment]
Hi, I test your suggestion with the following codes:
```
from triton import *

ctx = TritonContext(ARCH.X86)
inst = Instruction()
inst.setAddress(0xb770b186)
inst.setOpcode(b"\x8b\x5c\x08\xfc")  # mov ebx, dword ptr [eax + ecx - 4]
inst.setThreadId(0)

# set ecx to 6
ctx.setConcreteRegisterValue(ctx.getRegister(REG.X86.ECX),6)
ctx.symbolizeRegister(ctx.getRegister(REG.X86.ECX))

# set eax to 164774212
ctx.setConcreteRegisterValue(ctx.getRegister(REG.X86.EAX),164774212)
ctx.symbolizeRegister(ctx.getRegister(REG.X86.EAX))

# set memory 164774214 to 186
ctx.setConcreteMemoryValue(MemoryAccess(164774214,1),186)
ctx.symbolizeMemory(MemoryAccess(164774214,1))

# set memory 164774215 to 16
ctx.setConcreteMemoryValue(MemoryAccess(164774215,1),16)
ctx.symbolizeMemory(MemoryAccess(164774215,1))

# set memory 164774216 to 187
ctx.setConcreteMemoryValue(MemoryAccess(164774216,1),187)
ctx.symbolizeMemory(MemoryAccess(164774216,1))

# set memory 164774217 to 17
ctx.setConcreteMemoryValue(MemoryAccess(164774217,1),17)
ctx.symbolizeMemory(MemoryAccess(164774217,1))

ctx.processing(inst)
for symexp in inst.getSymbolicExpressions():
    print(symexp)

print("Symbolic Expression for bl is:", ctx.getSymbolicExpression(ctx.getSymbolicRegister(ctx.getRegister(REG.X86.BL)).getId()))
print("Symbolic Expression for bh is:", ctx.getSymbolicExpression(ctx.getSymbolicRegister(ctx.getRegister(REG.X86.BH)).getId()))
print("Symbolic Expression for ebx is:", ctx.getSymbolicExpression(ctx.getSymbolicRegister(ctx.getRegister(REG.X86.BH)).getId()))
```
However it seems that the `getSymbolicRegister` only retrieve the symbolic expressions of the parent reg.

**Comment by vancaho** [comment]
Hi, I test your suggestion with the following codes:
```
from triton import *

ctx = TritonContext(ARCH.X86)
inst = Instruction()
inst.setAddress(0xb770b186)
inst.setOpcode(b"\x8b\x5c\x08\xfc")  # mov ebx, dword ptr [eax + ecx - 4]
inst.setThreadId(0)

# set ecx to 6
ctx.setConcreteRegisterValue(ctx.getRegister(REG.X86.ECX),6)
ctx.symbolizeRegister(ctx.getRegister(REG.X86.ECX))

# set eax to 164774212
ctx.setConcreteRegisterValue(ctx.getRegister(REG.X86.EAX),164774212)
ctx.symbolizeRegister(ctx.getRegister(REG.X86.EAX))

# set memory 164774214 to 186
ctx.setConcreteMemoryValue(MemoryAccess(164774214,1),186)
ctx.symbolizeMemory(MemoryAccess(164774214,1))

# set memory 164774215 to 16
ctx.setConcreteMemoryValue(MemoryAccess(164774215,1),16)
ctx.symbolizeMemory(MemoryAccess(164774215,1))

# set memory 164774216 to 187
ctx.setConcreteMemoryValue(MemoryAccess(164774216,1),187)
ctx.symbolizeMemory(MemoryAccess(164774216,1))

# set memory 164774217 to 17
ctx.setConcreteMemoryValue(MemoryAccess(164774217,1),17)
ctx.symbolizeMemory(MemoryAccess(164774217,1))

ctx.processing(inst)
for symexp in inst.getSymbolicExpressions():
    print(symexp)

print("Symbolic Expression for bl is:", ctx.getSymbolicExpression(ctx.getSymbolicRegister(ctx.getRegister(REG.X86.BL)).getId()))
print("Symbolic Expression for bh is:", ctx.getSymbolicExpression(ctx.getSymbolicRegister(ctx.getRegister(REG.X86.BH)).getId()))
print("Symbolic Expression for ebx is:", ctx.getSymbolicExpression(ctx.getSymbolicRegister(ctx.getRegister(REG.X86.BH)).getId()))
```
However it seems that the `getSymbolicRegister` only retrieve the symbolic expressions of the parent reg.

**Comment by vancaho** [comment]
I test the `isRegisterTainted` function, and find that triton only considers the taint state of the parent registers. 
```
opcodes = b"\x8A\x18"
ctx = TritonContext(ARCH.X86)
inst = Instruction()


inst.setOpcode(opcodes)  # mov    bl,BYTE PTR [eax]
# set eax to 164774212
ctx.setConcreteRegisterValue(ctx.getRegister(REG.X86.EAX),164774212)
ctx.symbolizeRegister(ctx.getRegister(REG.X86.EAX))

# set memory 164774214 to 186
ctx.setConcreteMemoryValue(MemoryAccess(164774212,1),186)
ctx.symbolizeMemory(MemoryAccess(164774212,1))
ctx.setTaintMemory(MemoryAccess(164774212,1), True)

ctx.processing(inst)
for sym_exp in inst.getSymbolicExpressions():
    print(sym_exp)
print(ctx.isRegisterTainted(ctx.getRegister(REG.X86.BL)))
print(ctx.isRegisterTainted(ctx.getRegister(REG.X86.BH))
```
It outputs that `bl` and `bh` registers are both tainted

**Comment by SweetVishnya** [comment]
Unfortunately, Triton has parent register size granularity in symex. Enabling AST_OPTIMIZATIONS mode may help in some situations for extracting part of concatenated formulas.

**Comment by JonathanSalwan** [comment]
Maybe something like this might help you:

```python
expr = ctx.getRegisterAst(ctx.registers.rax)
vars = ast.search(expr, AST_NODE.VARIABLE)
print(f"Symvars that is in your expr: {vars}")

model = ctx.getModel(expr != expr.evaluate())
for k, v in model.items():
    print(f"Symvars that influence your expr result: {v}")
```

**Comment by JonathanSalwan** [comment]
Maybe something like this might help you:

```python
expr = ctx.getRegisterAst(ctx.registers.rax)
vars = ast.search(expr, AST_NODE.VARIABLE)
print(f"Symvars that is in your expr: {vars}")

model = ctx.getModel(expr != expr.evaluate())
for k, v in model.items():
    print(f"Symvars that influence your expr result: {v}")
```

**Comment by vancaho** [comment]
I'm using triton 0.9 now, but I cannot find the ast.search function

**Comment by vancaho** [comment]
> Maybe something like this might help you:
> 
> ```python
> expr = ctx.getRegisterAst(ctx.registers.bl)
> vars = ast.search(expr, AST_NODE.VARIABLE)
> print(f"Symvars that is in your expr: {vars}")
> 
> model = ctx.getModel(expr != expr.evaluate())
> for k, v in model.items():
>     print(f"Symvars that influence your expr result: {v}")
> ```

I'm using triton 0.9 now, but I cannot find the ast.search function

**Comment by JonathanSalwan** [comment]
Yeah sorry I should have post the full code:

```python
# ...
ctx = TritonContext()
# ...
ast  = ctx.getAstContext()
vars = ast.search(expr, AST_NODE.VARIABLE)
# ...
```

**Comment by vancaho** [comment]
> 



> Maybe something like this might help you:
> 
> ```python
> expr = ctx.getRegisterAst(ctx.registers.bl)
> vars = ast.search(expr, AST_NODE.VARIABLE)
> print(f"Symvars that is in your expr: {vars}")
> 
> model = ctx.getModel(expr != expr.evaluate())
> for k, v in model.items():
>     print(f"Symvars that influence your expr result: {v}")
> ```

Thanks for your reply. 
I tried your approach, and I can get the src value which influence the dest expr. 
But how to get the src symvar value if the dest of the instruction is a memory area of multi bytes.
For example,  for the instruction `mov dword ptr [esp + 8], esi` where `esp=0x080480000`,
If I want to fix the value of `0x080480000` and `0x080480001` and `0x080480002` and only change `0x080480003`, how to get the origin value of `esi`?  I use the `and` operator in `getModel()`, it seems that I cannot hold the values for `0x080480000` and `0x080480001` and `0x080480002`.

```
sym_exp0 = ctx.getMemoryAst(MemoryAccess(0x08040000,1))
value0= ctx.getConcreteMemoryValue(MemoryAccess(0x08040000,1))

sym_exp1 = ctx.getMemoryAst(MemoryAccess(0x08040001,1))
value1 = ctx.getConcreteMemoryValue(MemoryAccess(0x08040001,1))

sym_exp2 = ctx.getMemoryAst(MemoryAccess(0x08040002,1))
value2 = ctx.getConcreteMemoryValue(MemoryAccess(0x08040002,1))

sym_exp3 = ctx.getMemoryAst(MemoryAccess(0x08040003,1))
value3 = ctx.getConcreteMemoryValue(MemoryAccess(0x08040003,1))

model = ctx.getModel(sym_exp0==value0 and sym_exp1==value1 and sym_exp2==value2 and sym_exp3 !=value3)
```
