### ISSUE TITLE
bswap wrong semantics

### ISSUE THREAD

**Issue by archercreat** [JonathanSalwan/Triton#1131]
https://github.com/JonathanSalwan/Triton/blob/262c306a22ed0b24247e2e53e37bc9b1fe650286/src/libtriton/arch/x86/x86Semantics.cpp#L3769

According to https://www.felixcloutier.com/x86/bswap `When the BSWAP instruction references a 16-bit register, the result is undefined.`

In reality the 16 bit register gets zeroed out:

```
rdi = 0xdeadbeefcafebabe
bswap di
rdi == 0xdeadbeefcafe0000
```

**Comment by JonathanSalwan** [comment]
Yeah, i've already saw this but as it is undefined I left bswaping the word :D. Do you have an user case when your target check this behavior?

**Comment by archercreat** [comment]
Not really, I've just found out about this behavior in capstone (it marks `bswap` operand access as `CS_AC_INVALID`) which makes my tool go nuts so I decided to report it here as well :)

**Comment by mrexodia** [comment]
People are 100% checking this behavior. It might be undefined, but it’s a common anti-emulation trick.

**Comment by JonathanSalwan** [comment]
@archercreat can you give me the opcode for a `bswap di` please?

**Comment by JonathanSalwan** [comment]
Thanks guys, looks good now. Merged in `master` and `dev-v0.1`

**Comment by mrexodia** [comment]
Btw, useful tool for quick assembling: https://disasm.pro

**Comment by JonathanSalwan** [comment]
I usually use this one http://shell-storm.org/online/Online-Assembler-and-Disassembler, not much 2.0 but it works :)
