### ISSUE TITLE
Instruction printing in SMT dump is broken

### ISSUE THREAD

**Issue by SweetVishnya** [JonathanSalwan/Triton#1133]
Hi!

It seems that new smt lifting broke code from #982 that was printing assembly for SMT formulas.

**Comment by JonathanSalwan** [comment]
Yes, I removed this because it was to huge in the comment and it looked like more a hack than a feature :). Now you have a dedicated method for that.

```cpp
const std::string& SymbolicExpression::getComment() ; print only comment
const std::string& SymbolicExpression::getDisassembly() ; print the disassembly of the instruction origin
```

**Comment by SweetVishnya** [comment]
We used it for dumping SMT formulas that we pass to solver. Thus, we could see which instructions produced [SMT formulas](https://clc-gitlab.cs.uiowa.edu:2443/SMT-LIB-benchmarks/QF_BV/-/blob/master/20210219-Sydr/master/cjpeg/predicate_1191.smt2). What is the proper way for doing it now?

We have the following code:

```
api_->liftToSMT(s, expr, assert_);
```

**Comment by JonathanSalwan** [comment]
Yes sure we can do that.

**Comment by SweetVishnya** [comment]
Ok, I'll compose a code for that.

**Comment by JonathanSalwan** [comment]
B.
