### ISSUE TITLE
Important Update: processing and buildSemantics do not return a boolean value anymore.

### ISSUE THREAD

**Issue by JonathanSalwan** [JonathanSalwan/Triton#1135]
In order to fix #872 I had to change the return value of `processing` and `buildSemantics` methods. Now, they return an enum (`triton::arch::exception_e`) instead of a boolean value. The enum is the following:

```cpp
/*! Types of exceptions */
enum exception_e {
  NO_FAULT = 0,     /*!< Succeed, no fault.                       */
  FAULT_DE,         /*!< Fault raised: Divide-by-zero.            */
  FAULT_BP,         /*!< Fault raised: Breakpoint.                */
  FAULT_UD,         /*!< Fault raised: Instruction not supported. */
  FAULT_GP,         /*!< Fault raised: General Protection Fault.  */
};
```

If the execution succeed, `processing` and `buildSemantics` return `NO_FAULT`. Then, for example, if a `div edx` is executed where `edx = 0`, a `FAULT_DE` is returned. It's better than just returning `false` if something wrong happened. This way, we have more information about what failed.

Note that if on your tools you have a code like this:

```c
bool your_function(triton::api& api) {
  /* ... */
  bool ret = api.processing(instruction);
  return ret;
}
```

And you do not want to break your tools by returning a `triton::arch::exception_e`, you can keep the same behavior by doing this:

```c
bool your_function(triton::api& api) {
  /* ... */
  bool ret = api.processing(instruction);
  return ret == triton::arch::NO_FAULT;
}
```

**Comment by JonathanSalwan** [comment]
cc @illera88 for Ponce
cc @SweetVishnya for Sydr
cc @cnheitman for TritonDSE

**Comment by mrexodia** [comment]
Respect Jonathan, you’re working really hard on this project!
