### ISSUE TITLE
Python bindings for `tritonToZ3` segfault

### ISSUE THREAD

**Issue by jordan9001** [JonathanSalwan/Triton#1136]
```py
from triton import *

ctx = TritonContext(ARCH.X86_64)

astctx = ctx.getAstContext()

ast = astctx.bvtrue()

astctx.tritonToZ3(ast)
```

The above can produce a crash when the python bindings do the `Z3_translate`

I think it might have to do with how the `z3.main_ctx().ctx.value` context is used?

**Comment by JonathanSalwan** [comment]
Hey,

Is your `libz3.so` is the same that used for the compile and link of the `libtriton.so` ?

Also maybe related to: https://github.com/JonathanSalwan/Triton/issues/1024

**Comment by jordan9001** [comment]
Hmm, I think it is related to that issue. Thank you

```py
import triton

# in maps:
# /usr/lib64/libz3.so.4.8.14.0

import z3

# in maps:
# /mnt/A/jay_home/.local/lib/python3.9/site-packages/z3/lib/libz3.so
# /usr/lib64/libz3.so.4.8.14.0
```

**Comment by JonathanSalwan** [comment]
Is `~/.local/lib/python3.9/site-packages/z3/lib/libz3.so` the same that `/usr/lib64/libz3.so.4.8.14.0` ? Also, make sure that Triton used at the compile the include of z3 4.8.14.0 (if you have multiple z3 versions).

**Comment by jordan9001** [comment]
No, the file is different, not symlink'd. But both are version `4.8.14.0` though.

**Comment by cnheitman** [comment]
I had this issue before. You have to make sure that `triton.so` uses `~/.local/lib/python3.9/site-packages/z3/lib/libz3.so` (either by pointing to it when compiling Triton with `-DZ3_LIBRARIES=~/.local/lib/python3.9/site-packages/z3/lib/libz3.so` or setting `LD_LIBRARY_PATH=~/.local/lib/python3.9/site-packages/z3/lib` so it uses the correct one when it loads).
