### ISSUE TITLE
Wiki - python example: symbolicExpression -> symbolicElements

### ISSUE THREAD

**Issue by Jinmo** [JonathanSalwan/Triton#114]
In Examples.md (wiki) line 180, there is an error.
```python
    for se in instruction.symbolicExpressions:
        print '\t -> ', se.expression
    print
```
to
```python
    for se in instruction.symbolicElements:
        print '\t -> ', se.expression
    print
```
In Class_Instructions.md line 11,
```python
    for se in instruction.symbolicExpressions:
        print se.expression
```
to
```python
    for se in instruction.symbolicElements:
        print se.expression
```
In line 46,
* **symbolicExpressions** (list of [SymbolicExpression](https://github.com/JonathanSalwan/Triton/wiki/Class_SymbolicExpression))

to
* **symbolicElements** (list of [SymbolicExpression](https://github.com/JonathanSalwan/Triton/wiki/Class_SymbolicExpression))

Because there is no element named 'symbolicExpressions' in instruction class.

**Comment by JonathanSalwan** [comment]
Hey, 

Did you pulled the last version of Triton? I have renamed the SymbolicElement to SymbolicExpression yesterday :)

**Comment by Jinmo** [comment]
OMG! Thanks!
