### ISSUE TITLE
Add support for building Python Wheel packages

### ISSUE THREAD

**Issue by JonathanSalwan** [JonathanSalwan/Triton#1145]
This refers to #1144.

### Pending tasks

- [ ] LLVM support (WIP: Linux and MacOS ok)
- [ ] Bitwuzla support (WIP: Linux and MacOS ok)
- [x] ~~Artifacts on Linux with all Python versions~~
- [x] ~~Artifacts on Windows with all Python versions~~
- [x] ~~Artifacts on macOS with all Python versions~~
- [x] ~~Supporting Triton's Interfaces~~

Any help on the following will be much appreciated! :

### Building the `.whl` by default

```console
$ python -m build --wheel
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools >= 40.8.0, wheel)
* Getting dependencies for wheel...
running egg_info
creating triton_library.egg-info
[...]
* Installing packages in isolated environment... (wheel)
* Building wheel...
running bdist_wheel
running build
running build_ext
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
[...]
adding 'triton_library-1.0.0.dist-info/WHEEL'
adding 'triton_library-1.0.0.dist-info/top_level.txt'
adding 'triton_library-1.0.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Successfully built triton_library-1.0.0-cp39-cp39-linux_x86_64.whl
```

### Building the `.whl` with a specific interface

```console
$ LLVM_INTERFACE=On python -m build --wheel
```

By default, interfaces are defined as:

 - Z3_INTERFACE: `On`
 - LLVM_INTERFACE: `Off`
 - BITWUZLA_INTERFACE: `Off`
 - BOOST_INTERFACE: `Off`

### Installing the package with pip

```console
$ pip install . --user
Processing /home/jonathan/Works/Tools/Triton
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: triton-library
  Building wheel for triton-library (setup.py) ... done
  Created wheel for triton-library: filename=triton_library-1.0.0-cp39-cp39-linux_x86_64.whl size=1518902 sha256=aeb378b42f39a7bff36bc2037aca1fd3fd94d37227609ebd719d6f7afde95ccb
  Stored in directory: /tmp/pip-ephem-wheel-cache-xtz2872_/wheels/07/e0/9a/c02c3eac5862a6b34ec58c12793c45a3eb9827de1c9308c2e3
Successfully built triton-library
Installing collected packages: triton-library
Successfully installed triton-library-1.0.0
```

**Comment by JonathanSalwan** [comment]
@cnheitman, I think there were a bug around `cmake_args` on Linux. Commit 450a345fca636402a2c4b5149f78e8434a4e79fb fixes it. However, with this patch there is another issue when calling `copy_file`. The commit 404484112f6003ef7375b1d6287b431658424a17 fixes it but I do not know if it breaks something else. Is defining `CMAKE_LIBRARY_OUTPUT_DIRECTORY` important?

**Comment by cnheitman** [comment]
Hey @JonathanSalwan o/ 

Nice!

Indeed, there was a bug there '^^. I just built the `.whl` for both Ubuntu and Windows and it works fine. Replying to your question, no, `CMAKE_LIBRARY_OUTPUT_DIRECTORY` does not seem necessary, so let's remove it.

An update on the Bitwuzla support. I tried building it on Windows and I ran into some issue (bitwuzla/bitwuzla/issues/30). To summarize, they are updating the Windows build (code and doc) and it'll be ready in a week or two. I'll work on it again once it's ready. (Btw, I have already built Bitwuzla statically on Linux I'll add it to the `python.yml` when I have the Windows part working so we generate `.whl` supporting the same libraries on both OSs.)

**Comment by JonathanSalwan** [comment]
I've cleaned up CI files. There were duplicates of jobs over different files. Now there is only one `linux.yml` file that supports wide-integer as a matrix and enables LLVM + Bitwuzla. Thus, I've removed the files: `llvm.yml`, `bitwuzla.yml` and `wide-integer.yml`. I've also renamed `cmake.yml` to `vcpkg.yml` which is more explicit.

**Comment by JonathanSalwan** [comment]
Linux and Windows artifacts for different Python version have been generated with [success](https://github.com/JonathanSalwan/Triton/actions/runs/2590138927).

**Comment by cnheitman** [comment]
Awesome @JonathanSalwan :D I'll add support for Bitwuzla in Linux later today.

**Comment by JonathanSalwan** [comment]
Artifacts for macOS are [ok](https://github.com/JonathanSalwan/Triton/actions/runs/2592372869)

**Comment by JonathanSalwan** [comment]
LLVM support for Linux and macOS is ok.

**Comment by n0thing2speak** [comment]
m1 chip,macOS 12.4, python3.10.5 arm64 version,it can be compiled successfully, but the following error occurs when using it
```python
Python 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:07:06) [Clang 13.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import triton
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: initialization of triton did not return an extension module
```

**Comment by cnheitman** [comment]
How did you build it exactly? What interfaces did you turn on?

**Comment by n0thing2speak** [comment]
> I think this might be the reason for the python installed in miniconda? I compiled and installed it successfully with the system's python, and I don't know why.

Here is the cmds:
```
git clone https://github.com/JonathanSalwan/Triton
cd Triton
mkdir build ; cd build
cmake .. -DCMAKE_INSTALL_PREFIX="$PREFIX" \
  -DCMAKE_C_COMPILER=gcc-12 \
  -DCMAKE_CXX_COMPILER=g++-12 \
  -DBOOST_ROOT=$(brew --prefix boost) \
  -DPYTHON_LIBRARY=/Users/freedom/mambaforge/lib/libpython3.10.dylib \
  -DPYTHON_INCLUDE_DIR=/Users/freedom/mambaforge/include/python3.10
make -j8 
cd ..
python -m build --wheel
cd dist 
pip install triton_library-1.0.0rc1-cp310-cp310-macosx_12_0_arm64.whl --user
```
This command will have the above problem in python installed by conda, but it is nothing wrong in python with Xcode version

**Comment by cnheitman** [comment]
First, you don't need to run `cmake` by your own for building the `whl` package, `python -m build --wheel` take care of that. So, you only need to type:
```bash
git clone https://github.com/JonathanSalwan/Triton
cd Triton
python -m build --wheel
cd dist 
pip install triton_library-1.0.0rc1-cp310-cp310-macosx_12_0_arm64.whl --user
```
I think the problem might be related to the python library that is being linked to triton. Can you send me the output of `python -m build --wheel` (at some point it runs `cmake` which print information about which python lib is using).

**Comment by n0thing2speak** [comment]
In fact, when I don't run CMake, I get a bunch of errors. 
Sorry, I uninstalled the miniconda environment, and now the python installed from brew runs very well, do you need the arm64 wheel? I uploaded it belo
[triton_library-1.0.0rc1-cp39-cp39-macosx_12_0_arm64.whl.zip](https://github.com/JonathanSalwan/Triton/files/9274099/triton_library-1.0.0rc1-cp39-cp39-macosx_12_0_arm64.whl.zip)
w

**Comment by cnheitman** [comment]
Hey! An update on this issue.

* Linux: I tweaked and fixed the building process. I did some testing and it's working fine.
* macOS: I fixed the packaging process. Now it adds to the final `whl` package all the libs it needs to run on its own. I haven't tested it yet but it should be working fine.
* Windows: I have a working building process which includes Z3 and Bitwuzla. I also managed to add to the final `whl` all the libs it needs to run on its own. There are two pending issues to solve. First, I have this script working locally. I haven't added it to the CI yet (building Bitwuzla is complex and adding it to the CI is not straightforward). Second, I'm still working on adding LLVM support. I have disabled the CI for Windows for now. I tested the package I have so far (Z3 + Bitwuzla) and it's working fine.

Btw, I'll do a PR with these changes once the CI on my fork finish running.

**Comment by cnheitman** [comment]
Hey o/ Another update.

* Windows: I managed to compile LLVM and build the `whl` package successfully. Now, the windows version of the package have support for Z3, Bitwuzla and LLVM. For now, I will build the package locally (that is, I will not add it to CI). The reason for this is: 1) Bitwuzla is complex to build on Windows, and 2) the only way to add LLVM support was to building it from scratch, which requires a lot of cpu time and disk. That being say, the package is already on PyPI and working for Python 3.8, 3.9 and 3.10 (same for the Linux one).
* macOS: The package is ready but I still need to check they are working properly. Once I do that I'll push them to PyPI.

**Comment by JonathanSalwan** [comment]
You rockz @cnheitman !

**Comment by cnheitman** [comment]
Last update on this issue.
* The packages for both Linux and Windows are working and on PyPI for Python 3.8, 3.9 and 3.10 with support for Z3, Bitwuzla and LLVM. It can be installed by running `pip install triton-libray`.
* The packages for Linux are generated using Github Actions. The packages for Windows are generated locally by me until I find a way to automatize it (complex setup).
* The packages for mac are still pending (they need some tweaking). I'll open a new issue for it.

**Comment by patrafter1999** [comment]
Hi @cnheitman, 

Any update on this Mac M1 bug? I still have the following.

```
(ai) ~/Downloads/triton/Triton:$ pip install . --user
Processing /Users/jsmith/Downloads/triton/Triton
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: triton-library
  Building wheel for triton-library (setup.py) ... done
  Created wheel for triton-library: filename=triton_library-1.0.0rc4-cp311-cp311-macosx_15_0_arm64.whl size=1556537 sha256=9a3a844dc12115622bffc0090691672964c2d5cd8907afddee4d13cd74d9f7fc
  Stored in directory: /private/var/folders/l7/wnf9k67s0w33rvzchxqh6_gw0000gn/T/pip-ephem-wheel-cache-zxfzsdfq/wheels/64/d9/a5/7fbd6ee6809b0b3316be9c753bd2108e7aebc0d27c3440c9b8
Successfully built triton-library
Installing collected packages: triton-library
Successfully installed triton-library-1.0.0rc4
(ai) ~/Downloads/triton/Triton:$ python 
Python 3.11.9 (main, Apr 19 2024, 11:43:47) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import triton
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: initialization of triton did not return an extension module
>>> 
```

**Comment by cnheitman** [comment]
Hi, @patrafter1999. Unfortunately, there is still no news on this. Currently, you have to build it on your own for Mac.

**Comment by JonathanSalwan** [comment]
> Hi, @patrafter1999. Unfortunately, there is still no news on this. Currently, you have to build it on your own for Mac.

@patrafter1999, you can adapt this following command to your setup if you want to compile it on your own for M1.

```
cmake -DCAPSTONE_INCLUDE_DIRS=/Users/jonathan/Works/Tools/capstone-5.0.1/include/ \
      -DCAPSTONE_LIBRARIES=/Users/jonathan/Works/Tools/capstone-5.0.1/libcapstone.a \
      -DCAPSTONE_VERSION_HEADER=/Users/jonathan/Works/Tools/capstone-5.0.1/include/capstone/capstone.h \
      -DCMAKE_INSTALL_PREFIX=/opt/homebrew/ \
      -DPYTHON_EXECUTABLE=/opt/homebrew/bin/python3.12 \
      -DPYTHON_LIBRARIES=/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/libpython3.12.dylib \
      -DPYTHON_INCLUDE_DIRS=/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12/ \
      -DLLVM_INTERFACE=ON \
      -DCMAKE_PREFIX_PATH=/Users/jonathan/Works/Tools/llvm-project-14.0.0/build \
      -DBITWUZLA_INTERFACE=ON \
      -DBITWUZLA_INCLUDE_DIRS=/Users/jonathan/Works/Tools/bitwuzla/bitwuzla-0.4.0/install/include/ \
      -DBITWUZLA_LIBRARIES="/Users/jonathan/Works/Tools/bitwuzla/bitwuzla-0.4.0/install/lib/libbitwuzla.dylib" \
      -DBOOST_INTERFACE=OFF \
      ..
```
