### ISSUE TITLE
How to dry run an instruction?

### ISSUE THREAD

**Issue by hexpell** [JonathanSalwan/Triton#1161]
Before processing an instruction to change the state of the CPU, I want to inspect the instruction that if it's reading or writing any memory address, get the concrete memory address value and perform some other actions, for example populate the memory region with some concrete value from some trace data etc.

But I found it difficult to do this with Triton, specifically to get the MemoryAccess without changing the state of the CPU. Basically what I want is `TritonContext::processing(inst)` but a "dryrun" version. I tried using `TritonContext::disassembly(inst)` but it doesn't populate the MemoryAccess states, until I call processing:

```py
from triton import *
ctx = TritonContext()
ctx.setArchitecture(ARCH.X86_64)
ctx.setMode(MODE.ALIGNED_MEMORY, True)
ctx.setAstRepresentationMode(AST_REPRESENTATION.PYTHON)

# Setup stack
ctx.setConcreteRegisterValue(ctx.registers.rsp, 0x7fffffff)
ctx.setConcreteRegisterValue(ctx.registers.rbp, 0x7fffffff)

inst = Instruction(0x401110, b"\x55") #  push   rbp
ctx.disassembly(inst)

inst
# 0x401110: push rbp

inst.isMemoryWrite()
# False

inst.getStoreAccess()
# []

ctx.processing(inst)
inst.isMemoryWrite()
# True

inst.getStoreAccess()
# [([@0x7ffffff7]:64 bv[63..0], 0x7fffffff)]
```

**Comment by JonathanSalwan** [comment]
> for example populate the memory region with some concrete value from some trace data etc.

This [code](http://shell-storm.org/repo/Notepad/qbdi_with_triton.txt) illustrates that way to use Triton with a DBI and it's the same concept that if you want to synch with a Trace or whatever. The idea is to define a memory callback (see `addCallback()` and `mem_read()` in the previous code) and sync registers at every processing (see `synch_regs`).

That's it. There is no `dryrun` way of what you are looking for.

Hope it help

**Comment by hexpell** [comment]
That's what I'm looking for. Thanks for the quick response!
