### ISSUE TITLE
Pass execCallbacks argument from Python binding

### ISSUE THREAD

**Issue by hexpell** [JonathanSalwan/Triton#1162]
When I'm in read memory callback for example, I want to set the concrete memory value without triggering the memory write callback I registered. It would be useful if the Python binding has the execCallbacks parameter for me to specify this behavior.

**Comment by SweetVishnya** [comment]
You may define a global variable for that purpose.

**Comment by JonathanSalwan** [comment]
>  It would be useful if the Python binding has the execCallbacks parameter for me to specify this behavior.

Indeed. I'm in vacation atm but as soon as I came back I will add this feature. Meanwhile, maybe you can try what @SweetVishnya suggest?

**Comment by hexpell** [comment]
Yes, I'm already using a global variable as workaround, but since this may be a helpful feature, and already available in C++, I thought would be nice to have in Python binding too.

**Comment by mrexodia** [comment]
You could consider spending a few minutes adding it to the python bindings and sending a pull request 😉

**Comment by JonathanSalwan** [comment]
merged
