### ISSUE TITLE
Feature: provide target cmdline to python script

### ISSUE THREAD

**Issue by Jinmo** [JonathanSalwan/Triton#117]
I found sys.argv is not there, and I couldn't obtain the command line in normal way.
So it seems good to provide a command line to python script..

**Comment by JonathanSalwan** [comment]
> So it seems good to provide a command line to python script..

Yes you're right but we cannot use the `sys.argv` feature for the reason that we already are in the command line of Pin.

In reality the `$ ./triton /foo.py ./binary.efl` command, looks like this: `$ ./pin -t libtriton.so -script foo.py -- ./binary.elf`.

So, if we send an argument to our Python script, the command looks like this:

`$ ./pin -t libtriton.so -script foo.py arg1 arg2 -- ./binary.elf`.

And unfortunately, `arg1` and `arg2` are not Pin's options, so Pin raises an exception.

I'm open to any kind of sexy features which will allows the user to use command line for its Triton script :).

I close this issue but feel free to reopen it if you think there is a sexy way to do that :)
