### ISSUE TITLE
Unable to pass additional arguments to callbacks

### ISSUE THREAD

**Issue by archercreat** [JonathanSalwan/Triton#1170]
Hello! I could not find a way to pass additional arguments to instrumentation callbacks (e.g. get/set concrete memory).
Usually I do it with bind:
```
api.addCallback(triton::callbacks::callback_e::GET_CONCRETE_MEMORY_VALUE, 
  std::bind(&my_class::read_memory_cb, this, std::placeholder::_01, std::placeholder::_02);
```
But bind doesn't work with `addCallback` api. Is there another way to do this?

**Comment by JonathanSalwan** [comment]
Hey,

yes this is something that is missing. It's been I while that I think about passing an argument as `void*`. I will do it as soon as possible (~3 weeks). Meanwhile, an ugly possibility could be to to put your arg in a global variable.

**Comment by aris-bb** [comment]
You can use a lambda to capture your custom argument like this:
```cpp
void my_class::fn()
{
  auto get_memory_callback = [this](triton::Context& ctx, const triton::arch::MemoryAccess& mem)
  {

  };

  ctx->addCallback
  (
	  triton::callbacks::GET_CONCRETE_MEMORY_VALUE,
	  triton::callbacks::getConcreteMemoryValueCallback{ get_memory_callback, &get_memory_callback }
  );
}
```

**Comment by archercreat** [comment]
Hey! Sorry for the long reply, I got sick.. The example that @aris-bb gave is sufficient for me.

**Comment by JonathanSalwan** [comment]
I hope you recovered well!

> he example that @aris-bb gave is sufficient for me.

Let's close this issue then
