### ISSUE TITLE
Triton source porting for windows.

### ISSUE THREAD

**Issue by dhxkgozj** [JonathanSalwan/Triton#118]
i want triton source porting for windows.

used visual studio 2012.

triton manual is not found for windows install. and i started porting. but many bug is occurring.
especially Unimplemented __int128_t
How can use the Triton from the windows?

**Comment by JonathanSalwan** [comment]
Hey,

Currently I have not tried to port Triton on Windows, I'm focusing on the OSX side and even on OSX there is a lot of issues :( like the `stdgnu++11` and `libstdc++` and others shits like that.

To answer your question, I don't know. I think if you want to port Triton on Windows there will be a lot of code modifications but it will be an awesome pull request if you manage to compile Triton on Windows :)

I will close this issue but feel free to reopen if you have some suggestions to solve this issue.

**Comment by JonathanSalwan** [comment]
Btw, maybe you can deal with: 

* https://msdn.microsoft.com/en-us/library/ayeb3ayc.aspx
* https://msdn.microsoft.com/en-us/library/25537780.aspx
* https://msdn.microsoft.com/en-us/library/26232t5c.aspx

**Comment by dhxkgozj** [comment]
thank you for answer
