### ISSUE TITLE
[Symbolic Array] Unnecessary memory read callbacks

### ISSUE THREAD

**Issue by hexpell** [JonathanSalwan/Triton#1187]
The new symbolic memory array model is very cool. I can't wait to use it. But I noticed it's making unnecessary memory read callbacks:

(Using dev-array branch)

```
from triton import *

ctx = TritonContext()
ctx.setArchitecture(ARCH.X86)
ctx.setMode(MODE.ALIGNED_MEMORY, True)
ctx.setMode(MODE.ONLY_ON_SYMBOLIZED, True)
ctx.setMode(MODE.MEMORY_ARRAY, True)

ctx.setConcreteRegisterValue(ctx.registers.esp, 0x1000)
ctx.setConcreteRegisterValue(ctx.registers.ebp, 0xabcd)

def mem_read_cb(ctx, mem):
    print('mem_read(0x{:08X})'.format(mem.getAddress()))

ctx.addCallback(CALLBACK.GET_CONCRETE_MEMORY_VALUE, mem_read_cb)

X86_CODE32 = b'\x55' # push ebp

inst = Instruction(0, X86_CODE32)
ctx.processing(inst)
```

```
mem_read(0x00000FFF)
mem_read(0x00000FFE)
mem_read(0x00000FFD)
mem_read(0x00000FFC)
mem_read(0x00000FFC)
mem_read(0x00000FFD)
mem_read(0x00000FFE)
mem_read(0x00000FFF)
```

Related to #1185

**Comment by JonathanSalwan** [comment]
Thx @hexpell to have given a try to this new memory model, I really appreciate it! Thx to let me know about this behavior, I will fix it. Note that we will probably have a lot of weird behaviors like this as it's still very experimental and as it's a new memory model I have to handle a lot of new things like this. I'm currently reading all the code of Triton where memory are handle and check if it might imply issues. It will take time to verify everything so do not hesitate to post issues like this one if you still continue to test the array memory :).

**Comment by JonathanSalwan** [comment]
Fixed in `dev-array`. Thx again!
