### ISSUE TITLE
Feature: assign symbol for memory/register state before starting analysis in python binding

### ISSUE THREAD

**Issue by Jinmo** [JonathanSalwan/Triton#119]
I wanted to track the symbolic flow from initial memory state (I mean, the reg/mem state before startAnalysis), but it wasn't possible in python. Here is my case.

ex) I tried to track my un-hexed input (after skipping sscanf because it was faster). So I started analysis after doing sscanf. But the initial memory state(which was user input) was not symbolic, so I could only track the flow after "one" operation for the memory (by convertMem(Reg)ToSymVar).

I think it will be useful for doing some analysis based on some assumptions.

**Comment by romainthomas** [comment]
Yes this problem was reported here : [Issue 109](https://github.com/JonathanSalwan/Triton/issues/109)

**Comment by Jinmo** [comment]
Thanks!
