### ISSUE TITLE
AArch64 System Registers

### ISSUE THREAD

**Issue by soyasoya5** [JonathanSalwan/Triton#1195]
Currently system registers and the `MSR/MRS` instructions are not supported. 

```py
code = [
    b"\x54\xD0\x3B\xD5", #    mrs x20, tpidr_el0
]

**Comment by soyasoya5** [comment]
Unrelated to this issue, code below throws `EXCEPTION.FAULT_UD`

```py
code = [ 
    b"\x00\xE4\x00\x6F, #          MOVI  V0.2D, #0
]
```

**Comment by JonathanSalwan** [comment]
can you open a new thread for this one?

**Comment by JonathanSalwan** [comment]
I've added [system registers](https://github.com/JonathanSalwan/Triton/blob/dev-v1.0/src/libtriton/includes/triton/aarch64.spec#L296-L1032) and `MSR`, `MRS` instructions. Looks good to me but you must use Capstone 5.x to enjoy the decoding of system registers.

**Comment by soyasoya5** [comment]
LGTM, tested & works for me
