### ISSUE TITLE
AArch64 MOVI reg, #imm throws exception

### ISSUE THREAD

**Issue by soyasoya5** [JonathanSalwan/Triton#1196]
Code below throws `EXCEPTION.FAULT_UD` when it shouldn't

```py
from triton import *

ctx = TritonContext(ARCH.AARCH64)
inst = Instruction(0x1000, b"\x00\xE4\x00\x6F")  #  MOVI  V0.2D, #0
assert ctx.processing(inst) == EXCEPTION.NO_FAULT # AssertionError
```

_Originally posted by @soyasoya5 in https://github.com/JonathanSalwan/Triton/issues/1195#issuecomment-1296272282_

**Comment by JonathanSalwan** [comment]
Patched. If it's ok, you can close this thread :)
