### ISSUE TITLE
help me please for compiling

### ISSUE THREAD

**Issue by xSanx** [JonathanSalwan/Triton#1203]
![cmake](https://user-images.githubusercontent.com/46198990/200163188-cca9eb21-23da-453b-aa8c-c0a6c4ee39c0.jpg)
then
![compiling](https://user-images.githubusercontent.com/46198990/200163198-0a909fcb-ddc3-4208-a547-419f643c2523.jpg)

**Comment by JonathanSalwan** [comment]
Compile bitwuzla as shared library or use position independent code. See https://github.com/JonathanSalwan/Triton/pull/1199

**Comment by xSanx** [comment]
> Compile bitwuzla as shared library or use position independent code. See #1199

./configure.sh && cd build && make -- share    ?

**Comment by JonathanSalwan** [comment]
````
git clone https://github.com/bitwuzla/bitwuzla
cd bitwuzla
./contrib/setup-cadical.sh
./contrib/setup-btor2tools.sh
./contrib/setup-symfpu.sh
./configure.sh --shared
sudo make -C build install
```
