### ISSUE TITLE
Q:  Is it possible to extend Triton with microcontroller Archs

### ISSUE THREAD

**Issue by MFaisalZaki** [JonathanSalwan/Triton#1218]
I was wondering if it is possible to extend Triton to add Z80 microprocessor architecture or different AVR architectures?

**Comment by JonathanSalwan** [comment]
Yes it's possible. Here is a [guideline](https://blog.quarkslab.com/triton-v08-and-armv7-a-guideline-for-adding-new-architectures.html) to add new architectures.

**Comment by MFaisalZaki** [comment]
@JonathanSalwan, thanks for your reply, and keep up a great job.
