### ISSUE TITLE
attack_vmp in x32 bit mode

### ISSUE THREAD

**Issue by Alexi0n** [JonathanSalwan/Triton#1219]
Hi!
Happy New Year!
I wanted to know if there is a script attack_vmp.py for 32 (x86) modes? 
as well as how to install a Triton for Windows with parameters:
$ cmake -DLLVM_INTERFACE=ON -DCMAKE_PREFIX_PATH=$(llvm-config --prefix) -DBITWUZLA_INTERFACE=ON .. (as in Linux)
Thank you and have a good time! ;)

**Comment by cnheitman** [comment]
Hi! Regarding Triton installation on Windows, keep in mind that now you can do it using pip: `pip install triton-library`. So, if you are only going to work in Python, there is no need for manual compilation.

**Comment by JonathanSalwan** [comment]
> I wanted to know if there is a script attack_vmp.py for 32 (x86) modes?

Unfortunately not but it should not be such difficult to adapt it (_note that it is also just a PoC_).
