### ISSUE TITLE
Examples in C++

### ISSUE THREAD

**Issue by OSPFvX** [JonathanSalwan/Triton#1223]
Hello everyone!!

Where can I see examples of writing deobfuscators using triton in c++?
There are catastrophically few examples in C++ in the examples folder

**Comment by JonathanSalwan** [comment]
At least there are some...

**Comment by OSPFvX** [comment]
> At least there are some...

If I figure out Triton, there may be more examples ;)
Even a whole deobfuscator =)
But so far everything is going very tight

**Comment by JonathanSalwan** [comment]
https://github.com/JonathanSalwan/Triton/wiki#deobfuscation

**Comment by OSPFvX** [comment]
How can I output a synthesis string if it is not converted?
https://ibb.co/HT6PQgL
https://ibb.co/HgBvJyS

I get a "magnificent nothing" when I output it this way, otherwise what I get in synthesis is not converted
```
ctx.setAstRepresentationMode(ast::representations::PYTHON_REPRESENTATION);
printf("\nOut: %s",(string)ctx.synthesize(al,NULL,NULL,NULL));
```

**Comment by OSPFvX** [comment]
I beat that bitch!
EXAMPLE USING TRITON IN OBSUCATED CODE ON C++(rewritten code from here https://github.com/JonathanSalwan/Triton/issues/1074(specifically - chapter "Working on obfuscated trace (emulate the code)"))
https://pastebin.com/LZjqJf00 - Triton using example on c++

@JonathanSalwan 
Please add to the examples folder so the location!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!:
https://github.com/JonathanSalwan/Triton/tree/master/src/examples/cpp
