### ISSUE TITLE
在mac M2上安装报错

### ISSUE THREAD

**Issue by keapoa** [JonathanSalwan/Triton#1251]
编译是成功的，但调用时候出错。
<img width="536" alt="WeChat45f21cb083f0fc88777fae9c7030f893" src="https://github.com/JonathanSalwan/Triton/assets/24380711/6f917641-1518-4caa-8742-8d056022ad75">

**Comment by JonathanSalwan** [comment]
you have to verify that your libz3 is well loaded by Python.
