### ISSUE TITLE
Is `processing` noexcept?

### ISSUE THREAD

**Issue by illera88** [JonathanSalwan/Triton#1252]
Hi,

I'm wondering if the method [processing](https://github.com/JonathanSalwan/Triton/blob/e2faa65f07891d2635619864343d82ac289a7361/src/libtriton/context/context.cpp#L588) from context should be `noexcept`. I believe so since the method now returns an error code. 

I'm asking because of [this](https://github.com/illera88/Ponce/pull/136) 

Thanks

**Comment by SweetVishnya** [comment]
I think I've [seen](https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/arch/arm/aarch64/aarch64Semantics.cpp#L1188) it throwing exceptions.

**Comment by illera88** [comment]
Shouldn't it better be no except since it's already returning an error? Otherwise we should wrap `processing` under a try/catch and that impacts performance on a function call that it's called on every single instruction.

Regards

**Comment by SweetVishnya** [comment]
> Shouldn't it better be no except since it's already returning an error? Otherwise we should wrap `processing` under a try/catch and that impacts performance on a function call that it's called on every single instruction.
> 
> Regards

cc @JonathanSalwan, @cnheitman

**Comment by illera88** [comment]
I did not bench it. I just thought it would never except since it's already returning an error code and my next thought was that having to try/catch will slow things down. Also doing some grepping in the code I didn't see any instance of `processing` being wrapped in a try/catch.

In any case, I don't have any specific data to backup that the code will slow down by adding a try/catch so I'm closing the ticket. 


Thanks guys!
