### ISSUE TITLE
Undefined symbols for architecture x86_64:   "triton::Context::setConcreteRegisterValue"

### ISSUE THREAD

**Issue by vancaho** [JonathanSalwan/Triton#1257]
Hi, I want to use libtriton in my project.
I copied the code in example\cmake, and add  a line to set concrete value for `rax`, however it reports a link error:
```
Undefined symbols for architecture x86_64:
  "triton::Context::setConcreteRegisterValue(triton::arch::Register const&, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<512ul, 512ul, (boost::multiprecision::cpp_integer_type)0, (boost::multiprecision::cpp_int_check_type)0, void>, (boost::multiprecision::expression_template_option)0> const&, bool)", referenced from:
      _main in myproject.cpp.o
ld: symbol(s) not found for architecture x86_64
```
How to resolve this error?

Here are the source code:
``` cpp
// This is an example about how to compile Triton using its config file.
// See the CMakeLists.txt from this directory.

#include <iostream>
#include <triton/context.hpp>

int main(int ac, const char *av[]) {
  /* Triton's context */
  triton::Context ctx ;
  ctx.setArchitecture(triton::arch::ARCH_X86_64);


  ctx.setConcreteRegisterValue(ctx.registers.x86_rax,0);
  /* Symbolize rax */
  ctx.symbolizeRegister(ctx.registers.x86_rax);

  /* Process an instruction (inc rax) */
  triton::arch::Instruction inst = triton::arch::Instruction(0x40000, "\x48\xff\xc0", 3);
  ctx.processing(inst);

  /* Display instruction's expressions */
  std::cout << inst << std::endl;
  for (const auto& se : inst.symbolicExpressions) {
    std::cout << "    -> " << se << std::endl;
  }

  return 0;
}

```
Here is the cmakelists.txt file:
```
# This is an example about how to compile Triton using its config file.
cmake_minimum_required(VERSION 3.20)
project(myproject)
set(CMAKE_CXX_STANDARD 14)
find_package(triton REQUIRED CONFIG)
link_libraries(${TRITON_LIBRARIES})

add_executable(myproject
    myproject.cpp
)
```

**Comment by JonathanSalwan** [comment]
Are you compiling on M1? If you are on an Apple silicon, make sure the triton library is compiled in arm64 and x86_64. Or make sure your triton tool is compiled with the same arch than the library. It looks like your libtriton does not have x86_64 symbol because it's probably compiled on arm64 and your try to compile your tool on x64?

**Comment by vancaho** [comment]
No, the CPU is Intel. I compiled triton according to the tutorial.

**Comment by JonathanSalwan** [comment]
Can you do "$ file /usr/local/lib/libtriton.dylib" ?

**Comment by vancaho** [comment]
> 

Yeah, it outputs:
```
libtriton git:(master) ✗ file /usr/local/lib/libtriton.dylib
/usr/local/lib/libtriton.dylib: Mach-O 64-bit dynamically linked shared library x86_64
```

**Comment by JonathanSalwan** [comment]
Mmmmh, maybe there is something wrong with Boost definition. When compiling Triton, you have the choice to compile with `boost::multiprecision` or with `wide_integer` (`-DBOOST_INTERFACE=ON|OFF`). How did you compiled the `libtriton`? Maybe the triton library is compiled without boost whereas your triton tool wants to link with boost definition?

**Comment by vancaho** [comment]
If I can remember, I compile triton using the following command. The os is `macos 13.4 (22F66)`
```
$ git clone https://github.com/JonathanSalwan/Triton
$ cd Triton
$ mkdir build ; cd build
$ cmake ..
$ make -j3
$ sudo make install
```

**Comment by vancaho** [comment]
Yeah, I recompiled triton with the `-DBOOST_INTERFACE=ON` option, then it really works. Thanks very much Jonathan!
