### ISSUE TITLE
How to use  C++ `getModel()` function?

### ISSUE THREAD

**Issue by vancaho** [JonathanSalwan/Triton#1259]
Hi, I want to use `Context::getModel()` function in c++. For example, if `dst_reg_sym_ast` is the ast of a `register` I want to get a model of `dst_reg_sym_ast = 0x41414141`.

 With `python`, I can write: `model = self._context.getModel(dst_reg_sym_ast == 0x41414141)`. But with C++, the above code is not usable. I looked up `Context::getModel()` in the documentation, but cannot find an example.

**Comment by JonathanSalwan** [comment]
https://github.com/JonathanSalwan/Triton/blob/master/src/examples/cpp/constraint.cpp#L67-L73

**Comment by JonathanSalwan** [comment]
We did not overloaded operators in C++. So, you have to craft the constraint using `AstContext`.

**Comment by vancaho** [comment]
Thanks very much. That is very helpful. If I want to set value for a memory cell, how to write the code?

**Comment by JonathanSalwan** [comment]
`ctx.setConcreteMemoryValue(triton::arch::MemoryAccess(0x11223344, triton::size::dword), 0xdeadbeef);`

**Comment by vancaho** [comment]
Sorry, I asked the wrong question. What I mean is I want to get a model for a memory cell. For example, I want to get a model for setting 0x11223344 to 0xdeadbeef.

**Comment by JonathanSalwan** [comment]
Common guy, I'm not ChatGPT :D

```cpp
auto mem = ctx.getSymbolicMemory(triton::arch::MemoryAccess(0x11223344, 4));
auto ast = ctx.getAstContext();
auto constraint = ast->equal(mem, ast->bv(0xdeadbeef, 4));
auto model = ctx.getModel(constraint);
```
