### ISSUE TITLE
Unit Test: UnicornX86Semantics (Failed)

### ISSUE THREAD

**Issue by nbruns1** [JonathanSalwan/Triton#1264]
Hello,

the UnicornX86Semantics Unit Tests fails with the following message:

[KO] vpxor ymm0, ymm0, ymm1
	Invalid instruction (UC_ERR_INSN_INVALID)

**Comment by mrexodia** [comment]
From what I remember the ymm instructions are unsupported by unicorn, so this error makes sense. In the past there was a decoding error and it was (incorrectly) treated as an xmm instruction but that has since been fixed.

**Comment by cnheitman** [comment]
Hi @nbruns1 . Do you happen to have Unicorn `v2.0.1-post1` installed? If so, try downgrade to version `2.0.0` (`python -m pip install unicorn==2.0.0`). That should fix the issue.

**Comment by nbruns1** [comment]
Thanks, @mrexodia @cnheitman. Installing unicorn 2.0.0 fixed the issue.
