### ISSUE TITLE
assembly question

### ISSUE THREAD

**Issue by xSanx** [JonathanSalwan/Triton#1270]
install bitwuzla:
![Снимок экрана 2023-08-15 010141](https://github.com/JonathanSalwan/Triton/assets/46198990/5f8da2b4-489a-4806-92f6-e3ef2469e473)

but use $ cmake -DLLVM_INTERFACE=ON -DCMAKE_PREFIX_PATH=$(llvm-config --prefix) -DBITWUZLA_INTERFACE=ON ..
![2](https://github.com/JonathanSalwan/Triton/assets/46198990/bceda681-811a-4bc7-859a-dc39cda9bd4f)

**Comment by JonathanSalwan** [comment]
You probably have to provide `DBITWUZLA_INCLUDE_DIRS` and `DBITWUZLA_LIBRARIES` directories. Below, the build script of my setup:

```
#!/bin/sh

cd build
cmake -DCAPSTONE_INCLUDE_DIRS=/Users/jonathan/Works/Tools/capstone-5.0-rc2/include/ \
      -DCAPSTONE_LIBRARIES=/Users/jonathan/Works/Tools/capstone-5.0-rc2/libcapstone.5.dylib \
      -DCAPSTONE_VERSION_HEADER=/Users/jonathan/Works/Tools/capstone-5.0-rc2/include/capstone/capstone.h \
      -DCMAKE_INSTALL_PREFIX=/opt/homebrew/ \
      -DPYTHON_EXECUTABLE=/opt/homebrew/bin/python3 \
      -DPYTHON_LIBRARIES=/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/libpython3.11.dylib \
      -DPYTHON_INCLUDE_DIRS=/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11/ \
      -DLLVM_INTERFACE=ON \
      -DCMAKE_PREFIX_PATH=/Users/jonathan/Works/Tools/llvm-project-14.0.0/build \
      -DBITWUZLA_INTERFACE=ON \
      -DBITWUZLA_INCLUDE_DIRS=/Users/jonathan/Works/Tools/bitwuzla/install/include \
      -DBITWUZLA_LIBRARIES=/Users/jonathan/Works/Tools/bitwuzla/install/lib/libbitwuzla.dylib \
      -DBOOST_INTERFACE=OFF \
      ..
```

**Comment by xSanx** [comment]
> You probably have to provide `DBITWUZLA_INCLUDE_DIRS` and `DBITWUZLA_LIBRARIES` directories. Below, the build script of my setup:
> 
> ```
> #!/bin/sh
> 
> cd build
> cmake -DCAPSTONE_INCLUDE_DIRS=/Users/jonathan/Works/Tools/capstone-5.0-rc2/include/ \
>       -DCAPSTONE_LIBRARIES=/Users/jonathan/Works/Tools/capstone-5.0-rc2/libcapstone.5.dylib \
>       -DCAPSTONE_VERSION_HEADER=/Users/jonathan/Works/Tools/capstone-5.0-rc2/include/capstone/capstone.h \
>       -DCMAKE_INSTALL_PREFIX=/opt/homebrew/ \
>       -DPYTHON_EXECUTABLE=/opt/homebrew/bin/python3 \
>       -DPYTHON_LIBRARIES=/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/libpython3.11.dylib \
>       -DPYTHON_INCLUDE_DIRS=/opt/homebrew/opt/python@3.11/Frameworks/Python.framework/Versions/3.11/include/python3.11/ \
>       -DLLVM_INTERFACE=ON \
>       -DCMAKE_PREFIX_PATH=/Users/jonathan/Works/Tools/llvm-project-14.0.0/build \
>       -DBITWUZLA_INTERFACE=ON \
>       -DBITWUZLA_INCLUDE_DIRS=/Users/jonathan/Works/Tools/bitwuzla/install/include \
>       -DBITWUZLA_LIBRARIES=/Users/jonathan/Works/Tools/bitwuzla/install/lib/libbitwuzla.dylib \
>       -DBOOST_INTERFACE=OFF \
>       ..
> ```

thanks... I tried to register the paths Bitwuzla in the setup.py, but without result...
