### ISSUE TITLE
update the latest version of capstone

### ISSUE THREAD

**Issue by cctv130** [JonathanSalwan/Triton#1272]
Hi friends, today I tried to build, using the latest dependencies, and found the error
The enum for the arm architecture has been modified in the new capstone version, while the arm64 enum still exists
![1692240414466](https://github.com/JonathanSalwan/Triton/assets/133784576/17217a14-d5c4-4fb6-89c3-3f1786a925a8)

**Comment by cctv130** [comment]
capstone next branch include arm.h:
typedef enum CondCodes {
  // Meaning (integer)          Meaning (floating-point)
  ARMCC_EQ, // Equal                      Equal
  ARMCC_NE, // Not equal                  Not equal, or unordered
  ARMCC_HS, // Carry set                  >, ==, or unordered
  ARMCC_LO, // Carry clear                Less than
  ARMCC_MI, // Minus, negative            Less than
  ARMCC_PL, // Plus, positive or zero     >, ==, or unordered
  ARMCC_VS, // Overflow                   Unordered
  ARMCC_VC, // No overflow                Not unordered
  ARMCC_HI, // Unsigned higher            Greater than, or unordered
  ARMCC_LS, // Unsigned lower or same     Less than or equal
  ARMCC_GE, // Greater than or equal      Greater than or equal
  ARMCC_LT, // Less than                  Less than, or unordered
  ARMCC_GT, // Greater than               Greater than
  ARMCC_LE, // Less than or equal         <, ==, or unordered
  ARMCC_AL, // Always (unconditional)     Always (unconditional)
  ARMCC_UNDEF = 15, // Undefined
} ARMCC_CondCodes;

capstone v4 or v5 branch   include arm.h:
/// ARM condition code
typedef enum arm_cc {
	ARM_CC_INVALID = 0,
	ARM_CC_EQ,            ///< Equal                      Equal
	ARM_CC_NE,            ///< Not equal                  Not equal, or unordered
	ARM_CC_HS,            ///< Carry set                  >, ==, or unordered
	ARM_CC_LO,            ///< Carry clear                Less than
	ARM_CC_MI,            ///< Minus, negative            Less than
	ARM_CC_PL,            ///< Plus, positive or zero     >, ==, or unordered
	ARM_CC_VS,            ///< Overflow                   Unordered
	ARM_CC_VC,            ///< No overflow                Not unordered
	ARM_CC_HI,            ///< Unsigned higher            Greater than, or unordered
	ARM_CC_LS,            ///< Unsigned lower or same     Less than or equal
	ARM_CC_GE,            ///< Greater than or equal      Greater than or equal
	ARM_CC_LT,            ///< Less than                  Less than, or unordered
	ARM_CC_GT,            ///< Greater than               Greater than
	ARM_CC_LE,            ///< Less than or equal         <, ==, or unordered
	ARM_CC_AL             ///< Always (unconditional)     Always (unconditional)
} arm_cc;

**Comment by cnheitman** [comment]
I think we can update this but once the new version is released.

**Comment by JonathanSalwan** [comment]
I've tested with the last version of capstone which has been released on August 2023 (5.0.1) and everything is working fine.

**Comment by JonathanSalwan** [comment]
I've no book in mind but I recommend to read academic papers on [Google Scholar](https://scholar.google.fr/scholar?q=symbolic+execution&hl=en&as_sdt=0%2C5&as_vis=1&as_ylo=&as_yhi=). The very first paper talking about symbolic execution is [Symbolic Execution and Program Testing](https://dl.acm.org/doi/pdf/10.1145/360248.360252) from James C. King.
