### ISSUE TITLE
Linux Kernel dynamic taint analysis

### ISSUE THREAD

**Issue by amita1101** [JonathanSalwan/Triton#1277]
Can I do dynamic tainting on Linux Kernel's latest versions using the Triton tool? is it possible to explore all the paths?

**Comment by JonathanSalwan** [comment]
With taint analysis alone you can't explore all paths. For exploring, you have to generate good inputs and for generating good inputs you have to rely on symbolic execution. In theory you can do everything you want but in practice it's ambitious to explore all paths. Especially on a whole kernel. However, specific and well defined parts of a kernel yes.

**Comment by amita1101** [comment]
Hello dear,

Thank you for your quick response.

I'm working on vulnerability detection using dynamic taint analysis in the
real word application binaries and Linux kernel and drivers. I'm working
using the Triton tool. I learn to use this tool using examples and CTFs.
Can you please tell me the basic steps for this task? if you have any blog
or example of dynamic taint analysis of any real-world application which is
built in C programming language. Can you please provide me with any
real-world example of the triton tool for dynamic taint analysis?  I need
the source code of those real-world examples.

I have already done dynamic taint analysis of other simple C executables
using this tool. Now I need to do tainting of real-world applications like
firefox, adobe reader, ms world, gzip , kernel build, or any Linux driver.

Please help if you can.

Thanks & Regards
Amita Jangid
MNIT, Jaipur
