### ISSUE TITLE
No "rflags" register in x86_64 architecture

### ISSUE THREAD

**Issue by vancaho** [JonathanSalwan/Triton#1280]
Hi, when I call  `ctx->getRegister("rflags")`
it throws:
```
terminate called after throwing an instance of 'triton::exceptions::Cpu'
  what():  x8664Cpu::getRegister(): Invalid register for this architecture.
```
I read the documentation at `https://triton-library.github.io/documentation/doxygen/py_REG_page.html`, there is no `rflags` register for x86_64 architecture, and there are `eflags` registers for both `x86` and `x86_64` register.

Is there anything wrong? Should there be a `rflags` in `x86_64`?

**Comment by JonathanSalwan** [comment]
it's the same thing. `rflags` has its 32msb [reserved](https://en.wikipedia.org/wiki/FLAGS_register). In another words, only `eflags` is used in i386 or x86_64.

**Comment by JonathanSalwan** [comment]
I'm closing this issue, feel free to continue this thread if you have any questions.
