### ISSUE TITLE
bitwuzla error: no matching function

### ISSUE THREAD

**Issue by cctv130** [JonathanSalwan/Triton#1281]
![1693360009429](https://github.com/JonathanSalwan/Triton/assets/133784576/db150741-f47a-4cf1-9b50-09d6f40feacd)

**Comment by JonathanSalwan** [comment]
We just ported few days ago Bitwuzla 0.1.x on our branch `dev-v0.1`. Can you pull this branch and try again?

**Comment by cctv130** [comment]
> We just ported few days ago Bitwuzla 0.1.x on our branch `dev-v0.1`. Can you pull this branch and try again?



ok, I modified the code locally, bitwuzla_term_value_get_str_fmt and now I have meet this problem

![1693361764862](assets/1693361764862-20230830131609-bmzwooq.png)

**Comment by cctv130** [comment]
> We just ported few days ago Bitwuzla 0.1.x on our branch `dev-v0.1`. Can you pull this branch and try again?

ok, I modified the code locally, bitwuzla_term_value_get_str_fmt and now I have meet this problem
![image](https://github.com/JonathanSalwan/Triton/assets/133784576/54aeea1e-9f30-4e9a-bf25-4ff86b27720e)

**Comment by cctv130** [comment]
> We just ported few days ago Bitwuzla 0.1.x on our branch `dev-v0.1`. Can you pull this branch and try again?

ok ，now I have meet this problem
![image](https://github.com/JonathanSalwan/Triton/assets/133784576/54aeea1e-9f30-4e9a-bf25-4ff86b27720e)

**Comment by cctv130** [comment]
> We just ported few days ago Bitwuzla 0.1.x on our branch `dev-v0.1`. Can you pull this branch and try again?
Unfortunately, even switching to the dev1 branch did not compile. Instead, I found a function, bitwuzla_term_value_get_str_fmt, which seemed to have the same function as bitwuzla_term_value_get_str()

I modified the bitwuzla_term_value_get_str_fmt function locally and it compiled to 99% even though there were other errors

![image](https://github.com/JonathanSalwan/Triton/assets/133784576/a612ae82-178f-4c2c-9ead-9a444cca5d83)

**Comment by cctv130** [comment]
> We just ported few days ago Bitwuzla 0.1.x on our branch `dev-v0.1`. Can you pull this branch and try again?



Unfortunately, even switching to the dev1 branch did not compile. Instead, I found a function, bitwuzla_term_value_get_str_fmt, which seemed to have the same function as bitwuzla_term_value_get_str()

I modified the bitwuzla_term_value_get_str_fmt function locally and it compiled to 99% even though there were other errors

![1693381240675](https://github.com/JonathanSalwan/Triton/assets/133784576/cef4892f-0329-4db7-9324-2dab0a68aa11)

**Comment by cctv130** [comment]
> We just ported few days ago Bitwuzla 0.1.x on our branch `dev-v0.1`. Can you pull this branch and try again?


![1693381750720](https://github.com/JonathanSalwan/Triton/assets/133784576/079aadff-d1dc-4718-bbad-e262d0fc795e)
![1693381723636](https://github.com/JonathanSalwan/Triton/assets/133784576/cd206664-ab8a-4c27-9bce-298639046b34)
![1693381784632](https://github.com/JonathanSalwan/Triton/assets/133784576/f4410f3d-aba8-4c42-9a0a-63f0a6e528e0)

**Comment by cctv130** [comment]
> We just ported few days ago Bitwuzla 0.1.x on our branch `dev-v0.1`. Can you pull this branch and try again?
 triton and python-triton is build success，Below there is an error, do not know how to solve
![1693383066606](https://github.com/JonathanSalwan/Triton/assets/133784576/a622897a-e1c3-47b1-ba58-5ce7868b48b6)

**Comment by cctv130** [comment]
> We just ported few days ago Bitwuzla 0.1.x on our branch `dev-v0.1`. Can you pull this branch and try again?
A temporary solution to add the following comments, I can compile successfully
#add_subdirectory(examples)
![1693393520151](https://github.com/JonathanSalwan/Triton/assets/133784576/e57d4bfd-b80c-4cef-b3f1-6504bdfd71ba)

**Comment by cnheitman** [comment]
Hi @cctv130 . What version of Bitwuzla did you use? The compilation is working fine with v0.1.0.

**Comment by cctv130** [comment]
> Ok. I see they release v0.2.0 last week. I'll try it and update the code accordingly.

thank you.

**Comment by cnheitman** [comment]
PR #1286 solves this issue.

**Comment by cctv130** [comment]
> PR #1286 solves this issue.

thank you
