### ISSUE TITLE
python setup.py install bug

### ISSUE THREAD

**Issue by cctv130** [JonathanSalwan/Triton#1282]
triton was successfully installed on wsl, but triton showed two

![1693662303292](https://github.com/JonathanSalwan/Triton/assets/133784576/af77e7c1-939f-43e9-9c85-129f5916bcbf)

**Comment by cnheitman** [comment]
@cctv130 How did you exactly build the package to get this error?

**Comment by cctv130** [comment]
> @cctv130 How did you exactly build the package to get this error?

I ran python setup.py install after setting the environment variables in wsl on windows, and this error occurred.

**Comment by cctv130** [comment]
> @cctv130 How did you exactly build the package to get this error?

My impression is that he was able to use import triton, but two appeared

**Comment by cctv130** [comment]
@cnheitman Can you see if you can solve this problem？

**Comment by cnheitman** [comment]
I tested the wheel package both on Linux and Windows and I did not had this issue. I did not tried WSL, though, but I assume it shouldn't be much different.

Could you list the files under your Python's `site-packages` folder?

**Comment by cctv130** [comment]
@cnheitman 
![1694749043128](https://github.com/JonathanSalwan/Triton/assets/133784576/3270884c-033a-4351-a65e-bae496cd9797)

**Comment by cnheitman** [comment]
You should have something like this on your folder:

```        
triton_library-1.0.0rc2.dist-info
triton_library.libs
triton.cpython-311-x86_64-linux-gnu.so
```

Instead you have `triton_library-1.0.0rc2-py3.11-linux-x86_64.egg`, which was generated by `python setup.py install`

This is the result of not properly building the Python Wheel package. For that you should run:

```bash
export Z3_INCLUDE_DIRS=<path/to/z3/include>
export Z3_LIBRARIES=<path/to/z3/lib>
export CAPSTONE_INCLUDE_DIRS=<path/to/capstone/include>
export CAPSTONE_LIBRARIES=<path/to/capstone/lib>
export BITWUZLA_INTERFACE=On
export BITWUZLA_INCLUDE_DIRS=<path/to/bitwuzla/include>
export BITWUZLA_LIBRARIES=<path/to/bitwuzla/lib>
export LLVM_INTERFACE=ON
export CMAKE_PREFIX_PATH=$(llvm-config --prefix)

python -m build --wheel --outdir /tmp/triton-linux_x86_64
pip install /tmp/triton-linux_x86_64/*.whl
```

You'll have to adapt the above commands to WSL (in case it's needed).

**Comment by cctv130** [comment]
@cnheitman I think I should switch to ubuntu now, there are too many bugs on windows.

**Comment by cctv130** [comment]
@cnheitman After I took the time to test it today, it was my fault, thank you very much.
