### ISSUE TITLE
Old cmake in dockerfile (release build 0.9)

### ISSUE THREAD

**Issue by mostobriv** [JonathanSalwan/Triton#1284]
Running `docker build .` inside of the triton directory (unpacked zip archive from last available release) falls with error when `cmake` is used to build triton project.

![image](https://github.com/JonathanSalwan/Triton/assets/15954313/77a8c191-2505-4f13-be44-1773c1e093bf)

I guess the problem is that ubuntu:20.04 doesn't have 3.20+ cmake in official reps. And also instead of just copy source directory inside of docker image to build, new version of triton sources being cloned from github.

**Comment by cnheitman** [comment]
Hi! This happens because you are using release 0.9 and the dockerfile is pulling the latest master, which has updated CMake files (in comparison with the dockerfile used in release 0.9).

You can try checking out `master` or `dev-v1.0`, this problem should not happen with the latest code.

**Comment by cnheitman** [comment]
I'll close this. In case of another related question, please re-open.
