### ISSUE TITLE
alternative pintools

### ISSUE THREAD

**Issue by xSanx** [JonathanSalwan/Triton#1285]
advise an alternative PinTools? VMProtect-devirtualization

**Comment by JonathanSalwan** [comment]
Maybe:

* qbdi https://github.com/QBDI/QBDI
* dynamorio https://dynamorio.org/

**Comment by xSanx** [comment]
> Maybe:
> 
> * https://github.com/QBDI/QBDI
> * https://dynamorio.org/

if driver windows/linux? and how necessary is "mr" (memory read) for optimization in triton?

**Comment by JonathanSalwan** [comment]
For driver/kernel you can use Qemu or an hypervisor (dump pages and emulate them offline)

**Comment by xSanx** [comment]
when intel pine is running, memory read (mr) is logged... this necessary for the effect of raising the code in llvm?

**Comment by JonathanSalwan** [comment]
I think all DBI provide such callbacks.

**Comment by xSanx** [comment]
debuggers? example windbg script?

**Comment by JonathanSalwan** [comment]
I've never used windbg, however with gdb/lldb you can put breakpoints wherever you want, then dump memory and registers and start emulating code with Triton from the dump. You can also use debugger as tracer using ptrace but that's quite slow. There are infinite ways to analyse binaries :)

**Comment by xSanx** [comment]
I do not know how to implement a dump  mr instruction in the debugger ))))

**Comment by xSanx** [comment]
is there a command for gdb for memory read callback?

**Comment by JonathanSalwan** [comment]
I don't think there are memory callbacks in gdb. However, you can ptrace and directly read memory. Within gdb it's like doing `si` + `x/x addr`
