### ISSUE TITLE
Taint resulting from a dereference

### ISSUE THREAD

**Issue by namreeb** [JonathanSalwan/Triton#1292]
In this snippet, if `r8` is tainted, I would expect `ecx` to also be tainted, but it does not seem to be.  Is this intentional?

```
0x1416e4abe: movzx ecx, byte ptr [r8 - 5]
0x1416e4ac3: cmp cl, 0xe8
0x1416e4ac6: je 0x1416e4b70
```

**Comment by JonathanSalwan** [comment]
It depends of the taint propagation strategy. By default, the taint is spread if the memory cells that is read is tainted. If you want to spread the taint if the memory index is tainted you have to enable this mode:

```python
ctx.setMode(MODE.TAINT_THROUGH_POINTERS, True)
```

**Comment by namreeb** [comment]
Sorry, I missed that.  Thank you for your time!  I can confirm this is working for me.
