### ISSUE TITLE
Is Anyone Build Triton In Rust bindings

### ISSUE THREAD

**Issue by yujack008** [JonathanSalwan/Triton#1324]
I want to use rust code.

**Comment by RobinDavid** [comment]
Nobody does as far as I know, but feel free to write it and to do a PR ! We would be very grateful. Thanks!

**Comment by JonathanSalwan** [comment]
Yep, there is no rust bindings for the moment but feel free to push patch for this feature. I will close this thread for now as that looks like a very long term feature.
