### ISSUE TITLE
How to complement condition instruction.

### ISSUE THREAD

**Issue by yujack008** [JonathanSalwan/Triton#1327]
i want to change B.NE instruction to other branch.

and which api to judge a instruction is condition instruction?

and how to get condition instruction target address？

**Comment by JonathanSalwan** [comment]
> and which api to judge a instruction is condition instruction?

* `instruction.isBranch()`
* `instruction.isConditionTaken()`
* `instruction.isControlFlow()`

> and how to get condition instruction target address?

https://triton-library.github.io/documentation/doxygen/py_PathConstraint_page.html
