### ISSUE TITLE
Incompatible with Python-3.11

### ISSUE THREAD

**Issue by yurivict** [JonathanSalwan/Triton#1334]
```
In file included from /wrkdirs/usr/ports/sysutils/triton/work/Triton-0.9/src/libtriton/bindings/python/init.cpp:8:
/wrkdirs/usr/ports/sysutils/triton/work/Triton-0.9/src/libtriton/includes/triton/pythonBindings.hpp:12:10: fatal error: 'longintrepr.h' file not found
#include <longintrepr.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```

Version: 0.9
FreeBSD 14.0

**Comment by JonathanSalwan** [comment]
Can you give me the output of your `cmake ..` as well as where `longintrepr.h` is located on your system.

**Comment by yurivict** [comment]
Here is the [log](https://pkg-status.freebsd.org/beefy22/data/140amd64-default/28444692ea26/logs/triton-0.9_1.log).
longintrepr.h is located here: /usr/local/include/python3.11/cpython/longintrepr.h

**Comment by yurivict** [comment]
The latest master branch revision has it fixed though.
This is a matter of making a release.
