### ISSUE TITLE
is there an equivalrent of angr's CALLLESS option?

### ISSUE THREAD

**Issue by 4aaa** [JonathanSalwan/Triton#1344]
Hello!
May i ask something?
is there an equivalent of angr's CALLLESS option to skip all calls? 

cuz its extrememely bothering to simulate syscalls when u analyze big functions.

and I dont believe u have to handle every single ones in each analysis.

Thanks.

**Comment by JonathanSalwan** [comment]
Mmmh, there is no notion of function/cfg in Triton. The input of Triton is only one instruction. So, yeah you have to handle syscalls behaviour if you want to emulate them. However, using a DBI or a tracer can allow you to skip whatever you want and to synchronize the triton context.

**Comment by 4aaa** [comment]
Thanks for the response!
So you mean DBI or a tracer, I have to trace what the syscalls changed in terms of RFlags, whatever registers and memories and  update the triton context, is that even possible?
No mean to bother you but can you just tell me the possible DBI lib or tracer that would be useful for this purpose?
cuz I believe you've done it before

**Comment by JonathanSalwan** [comment]
Sure it's possible. With a DBI and or a tracer you can easily setup watchpoint on every instruction or basic block. Then, you just have to synch contexts. Here is an example with the QBDI https://shell-storm.org/repo/Notepad/qbdi_with_triton.txt. The idea is the same whatever the DBI or tracer you use. Hope it can help :)

**Comment by 4aaa** [comment]
Thanks a lot
you are very helpful, man! :sob:
I'll reference the example u gave and try it! 
Thanksss for good project with warm support!
