### ISSUE TITLE
Incorrect CMake dependency management

### ISSUE THREAD

**Issue by psi-func** [JonathanSalwan/Triton#1348]
Triton uses its own CMake scripts to search for dependencies, moreover, variables with the CS_VERSION_MAJOR project version are created for capstone, on which the project build further depends
If Triton is used together with the package manager (conan), the search can be changed automatically and custom scripts will not be run, there will be no variables and, for example, this condition will break CMake

```cmake
if(${CS_VERSION_MAJOR} GREATER_EQUAL 5)
```
![Screenshot from 2024-08-08 16-30-42](https://github.com/user-attachments/assets/f98bf30d-c528-4407-b50d-bcd23e97e693)

**Comment by JonathanSalwan** [comment]
what do you suggest?

**Comment by psi-func** [comment]
I found that support for capstone < 5 is deprecated
```cmake
find_package(CAPSTONE 5 REQUIRED)
```

**Comment by psi-func** [comment]
I suggest using standard CMake variables

> what do you suggest?

Using standard CMake variables `CAPSTONE_VERSION_MAJOR`

**Comment by mrexodia** [comment]
A few years ago I added support for both capstone and Z3 to be found using `find_package` without requiring a custom find module on all platforms:

- https://github.com/capstone-engine/capstone/pull/1841
- https://github.com/Z3Prover/z3/pull/5555

This means that at least those custom find modules can be removed.

> If Triton is used together with the package manager (conan), the search can be changed automatically and custom scripts will not be run, there will be no variables and, for example, this condition will break CMake

This is incorrect behavior though, you should not override a custom find module unless you provide a supported interface...

**Comment by psi-func** [comment]
`find_package` function is the interface for searching dependencies.
It can work in both modes (Config and Module) You can control it through `CMAKE_FIND_PACKAGE_PREFER_CONFIG` variable
It's ok to use this option in package managers. Custom module is an interface too which must declare some standard variables
*_LIBRARIES *_INCLUDE_DIRS etc. NOT custom variables like `CS_VERSION_MAJOR`

**Comment by mrexodia** [comment]
The custom find module in Triton was created before I added actual package support for capstone. So correctly override this from a package manager you should be compatible with whatever interface Triton made up at the time. According to the [documentation](https://cmake.org/cmake/help/latest/manual/cmake-developer.7.html#find-modules) there are no limitations to this interface:

> The primary task of a find module is to determine whether a package is available, set the <PackageName>_FOUND variable to reflect this and provide **any variables, macros and imported targets required to use the package**. A find module is useful in cases where an upstream library does not provide a [config file package](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#config-file-packages).

That being said, I will create a pull request to remove the custom find modules and then this issue can be closed.
