### ISSUE TITLE
LDRSW semantic error? producing weird zero_extend

### ISSUE THREAD

**Issue by 0x9047** [JonathanSalwan/Triton#1350]
Taking the example from #1310.

```
from triton import *
ctx = TritonContext(ARCH.AARCH64)
ctx.setConcreteMemoryAreaValue(0x400000+0x30, b'\x72\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
inst = Instruction(0x400000, b'\x91\x01\x00\x98') # ldrsw x17, #0x30
ctx.processing(inst)
x17 = ctx.getSymbolicRegisters()[REG.AARCH64.X17]
x17
```

The output is

```
(define-fun ref!0 () (_ BitVec 64) ((_ zero_extend 4294967264) ((_ sign_extend 32) (concat (_ bv0 8) (_ bv0 8) (_ bv0 8) (_ bv0 8) (_ bv0 8) (_ bv0 8) (_ bv0 8) (_ bv114 8))))) ; LDRSW operation - LOAD access
```

Why is there a zero_extend with a strange operand? I couldn't find it anywhere near https://github.com/JonathanSalwan/Triton/blob/0648bb9d22c487eda2cc633e353606c6d20d7f87/src/libtriton/arch/arm/aarch64/aarch64Semantics.cpp#L3416

And when I try to simplify it with `ctx.simplify(x17.getAst(), True, True)`, an exception is raised: Z3Solver::evaluate(): invalid zero_extend application

Sorry if I'm doing it wrong. Could you point me in the right direction? Thanks a lot.

**Comment by 0x9047** [comment]
I'm not sure, maybe this?

```
          auto node1 = this->astCtxt->sx(dst.getBitSize() - 32, this->astCtxt->extract(31, 0, op));
```

**Comment by JonathanSalwan** [comment]
Nice catch, thx!
