### ISSUE TITLE
Getting segfault while running CPP example with capstone-5.0

### ISSUE THREAD

**Issue by awanish-pandey** [JonathanSalwan/Triton#1355]
While running any of the example, I am getting seg fault. While debugging, I noticed that we are getting _NULL_ in _detail_ variable of the `diassembly()` function.

`  /* Detail information */

  530  triton::extlibs::capstone::cs_detail* detail = insn->detail; // always NULL
`
What can be the possible reason for this?

**Comment by JonathanSalwan** [comment]
Are you sure Capstone 5.0.1 headers are used during the compile and the same library is used at runtime? All [CIs](https://github.com/JonathanSalwan/Triton/actions) are ok on our side.

**Comment by awanish-pandey** [comment]
My bad. I was using capstone5.0.0
Now it is working as expected. Thanks
