### ISSUE TITLE
Linking issues with capstone

### ISSUE THREAD

**Issue by N0fix** [JonathanSalwan/Triton#1384]
I followed instructions to build Triton:
```
# build capstone locally using capstone v5.0 documentation (https://github.com/capstone-engine/capstone/blob/next/BUILDING.md)
# In capstone dir:
cmake -B build -DCMAKE_BUILD_TYPE=Release # For debug build change "Release" to "Debug"
cmake --build build
cmake --install build --prefix "<install-prefix>"

# Then build triton:
mkdir build ; cd build
cmake ..
make -j3
```

But `make` command fails with a linker error:
```
[ 87%] Building CXX object src/libtriton/CMakeFiles/triton.dir/bindings/python/utils.cpp.o
[ 88%] Linking CXX shared library libtriton.so
/usr/bin/ld: /usr/local/lib/libcapstone.a(X86IntelInstPrinter.c.o): warning: relocation against `arch_masks' in read-only section `.text'
/usr/bin/ld: /usr/local/lib/libcapstone.a(ARMInstPrinter.c.o): relocation R_X86_64_PC32 against symbol `cs_mem_free' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [src/libtriton/CMakeFiles/triton.dir/build.make:1590: src/libtriton/libtriton.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:1018: src/libtriton/CMakeFiles/triton.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

From what I have seen from capstone, the lib **is** compiled with `fPIC`, and I am unsure what happens here. I believe something is conflicting between capstone and Triton.
Also, I was able to build Triton just fine before I built and installed `bitwuzla`. Since I built and installed it, even though I do not include it in cmake options (using `-DBITWUZLA_INTERFACE=on`), linking fails with the above error.

Am I missing something obvious or is something wrong in the compilation pipeline ?

**Comment by N0fix** [comment]
For the record: solved the issue by compiling capstone using `./make.sh` instead of the official cmake build.

**Comment by japkettu** [comment]
I had the same problem. I solved it by compiling capstone:
`cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON`
