### ISSUE TITLE
taint_runtime_memory.py generate segfault.

### ISSUE THREAD

**Issue by cheesechoi** [JonathanSalwan/Triton#142]
I was modify some print syntax

def cafter(instruction):
    print 'test2'
    print '%#x: %s' %(instruction.address, instruction.assembly)
    for se in instruction.symbolicExpressions:
        print se.getId()
        if se.isTainted() == True:
            print 'tainted'#'\t -> %s%s%s' %(GREEN, se.getAst(), ENDC)
        else:
            print 'untainted'#'\t -> %s' %(se.getAst())
    print

It generate buf like this.

test2
0x4005bd: cmp dword ptr [rbp-0x4], 0x4
27
untainted
...
31
untainted
32
C: Tool (or Pin) caused signal 11 at PC 0x7f117a25dda6
./triton: line 20: 40349 Segmentation fault      (core dumped) $PIN_BIN_PATH -t $TRITON_LIB_PATH -script $1 -- ${@:2}
root@ubuntu:~/git/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton#

**Comment by romainthomas** [comment]
Did you pull the last version ?

**Comment by JonathanSalwan** [comment]
Hey, this bug (#135) has been fixed yesterday with this commit db5488f705e1e83e64e7d984a31cc44b76869293 :)

**Comment by cheesechoi** [comment]
Oh my.. I was pull yesterday... Thanks!
