### ISSUE TITLE
Add IARG_BRANCH_TAKEN into Instruction class

### ISSUE THREAD

**Issue by cheesechoi** [JonathanSalwan/Triton#176]
I try to analyze (or fuzz) some program with random input.
To check whether branch instruction is jump or not, I have to check all flags which affect to jump.

Do you have a plan to write code like xxx::isJump() / xxx::JumpCheck() on branch instruction ?
If I write code, Where is a good point to write jmp decision code ?

**Comment by JonathanSalwan** [comment]
The **instruction.getOpcodeCategory()** returns the [opcode category](http://triton.quarkslab.com/documentation/api/IDREF/OPCODE_CATEGORY/). Maybe you can deal with COND_BR and UNCOND_BR to check if it's a jump or not?

Example:

With UNCOND_BR

```python
if instruction.getOpcodeCategory() == IDREF.OPCODE_CATEGORY.UNCOND_BR:
     print '%#x %s' %(instruction.getAddress(), instruction.getDisassembly())
```

```console
0x40057c jmp 0x4005bd
0x4005b7 jmp 0x4005c8
0x400450 jmp qword ptr [rip+0x200bc2]
0x40045b jmp 0x400440
0x400446 jmp qword ptr [rip+0x200bc4]
0x7f38c844effb jmp 0x7f38c84b57f0
0x7f38c8443e91 jmp 0x7f38c8443ea2
0x7f38c84502fa jmp 0x7f38c84501c7
0x7f38c845021a jmp 0x7f38c8450178
0x7f38c845029e jmp 0x7f38c844fe90
0x7f38c8450f55 jmp 0x7f38c8450ee0
0x7f38c8450f55 jmp 0x7f38c8450ee0
0x7f38c8450f55 jmp 0x7f38c8450ee0
0x7f38c8450f55 jmp 0x7f38c8450ee0
0x7f38c8450f55 jmp 0x7f38c8450ee0
0x7f38c844f5b5 jmp 0x7f38c844f540
0x7f38c8450c0f jmp rax
0x7f38c844f01b jmp 0x7f38c844f02b
0x7f38c844f086 jmp 0x7f38c844f053
0x7f38c844641f jmp 0x7f38c844638a
[...]
```

And with  COND_BR:

```python
if instruction.getOpcodeCategory() == IDREF.OPCODE_CATEGORY.COND_BR:
     print '%#x %s' %(instruction.getAddress(), instruction.getDisassembly())
```

```console
0x4005dd jz 0x4005e6
0x4005c1 jle 0x40057e
0x4005b0 jz 0x4005b9
0x400600 jnz 0x40060e
0x7fd0662a7518 jnbe 0x7fd0662a7580
0x7fd0662a752b jz 0x7fd0662a7531
0x7fd0662912d0 jnz 0x7fd066291339
0x7fd0662912e6 jz 0x7fd06629132d
0x7fd0662912f4 jz 0x7fd0662912ff
0x7fd066291303 jz 0x7fd06629131b
0x7fd066291341 jnz 0x7fd066291400
0x7fd06629a4e0 jz 0x7fd06629a546
0x7fd06629a4f4 jz 0x7fd06629a5c0
0x7fd06629a505 jbe 0x7fd06629a550
0x7fd06629a55d jz 0x7fd06629a540
0x7fd06629b15c jnz 0x7fd06629b2c0
0x7fd06629b167 jz 0x7fd06629b1b8
0x7fd06629b1bd jz 0x7fd06629b2e0
0x7fd06629be39 jz 0x7fd06629be40
0x7fd06629be43 jz 0x7fd06629be4f
0x7fd06628ee53 js 0x7fd06628ee98
0x7fd0663007f5 jnbe 0x7fd066300810
0x7fd06630080a jnbe 0x7fd066300824
0x7fd06628ee67 js 0x7fd06628ee98
0x7fd06628ee77 jz 0x7fd06628eef0
0x7fd06628ef15 jnbe 0x7fd06628ef30
0x7fd06628ef25 jnle 0x7fd06628ee83
0x7fd066309850 jnb 0x7fd066309853
0x7fd06628eec0 jz 0x7fd06628eedb
0x7fd06629bdc5 jz 0x7fd06629bdcb
0x7fd06629bdd5 jnz 0x7fd06629bde8
0x7fd06629be5f jnz 0x7fd06629be3b
0x7fd06629b1ca jnz 0x7fd06629b31a
0x7fd06629b1d7 jz 0x7fd06629b2a8
0x7fd06629b204 jnle 0x7fd06629b178
0x7fd06629b210 jz 0x7fd06629b178
[...]
```

**Comment by cheesechoi** [comment]
Oh, Maybe I explained wrong.
When instruction is at jump code, I want know where RIP will go (jump or not).
So I have to check condition flags to know that, but it's a little annoying because condition varies by jump mode(jg, jle, jz, jnz,....).

**Comment by JonathanSalwan** [comment]
Mmmh. Well to do that (if i understood correctly :)) you have to check the RIP expression and get its childs from its AST.

If the instruction isn't a branch, the RIP expression will look like this ```RIP = dst_addr``` (there is one child) and if the instruction is a branch, the RIP expression will look like this ```RIP = if expr then dst_addr1 else dst_addr2```

@romainthomas is currently working on a code coverage tool and he deal with this feature to cover branches. Check out his [tool](https://github.com/romainthomas/Triton/blob/feature/codeCoverage/tools/code_coverage.py)

**Comment by JonathanSalwan** [comment]
PS: by evaluating the AST expression with the *evaluateAST()* function, you may know if the branch will be taken or not

**Comment by cheesechoi** [comment]
Oh Thanks for the tip. @romainthomas  's tool code is so insteresting!

And umm.. I tried to check **evaluateAST()** through *semanticsTesting.py*, but It seems to have some bug when called evaluateAST(expr) if expr has symbolic variable like 'SymVar_0'. Can you check [this](https://github.com/cheesechoi/Triton/blob/master/cheese/tester/semanticsTesting.py) code ?
I'd like to test another **evaluateAST()** examples, but there is only one example... I'm sorry for asking so many questions.

**Comment by JonathanSalwan** [comment]
Yep, you can't evaluate (compute) an expression if it contains a symbolic variable. Makes sense because the formula needs concrete values to provide a result :)

So, what we do when we evaluate an expression is to check if the symbolic variable contains a concrete value. A concrete value is available only if the symbolic variable come from [a register](https://github.com/JonathanSalwan/Triton/blob/master/src/smt2lib/z3AST.cpp#L416) or [a memory](https://github.com/JonathanSalwan/Triton/blob/master/src/smt2lib/z3AST.cpp#L409). If the symbolic variable come from an *[Expr](https://github.com/cheesechoi/Triton/blob/master/cheese/tester/semanticsTesting.py#L45)* we raise [an exception](https://github.com/JonathanSalwan/Triton/blob/master/src/smt2lib/z3AST.cpp#L423).

I think in your case you should use the function *convertRegToSymVar()* instead of using the *[convertExprToSymVar](https://github.com/cheesechoi/Triton/blob/master/cheese/tester/semanticsTesting.py#L45)* function :)

**Comment by Pyraun** [comment]
Hi everyone, I was wondering if going through the IR to get this information is not too costly.
Pin has the IARG_BRANCH_TAKEN that can be passed to a callback. This boolean seems to give exactly what @cheesechoi want, it says if the current jump taken or not.
Forward this information to the user could be a more lightweight alternative than process a formula.
Besides, There is also the problem that meets @cheesechoi , what do we do if the expression is not
a constant ? The only way to get through this is to query the SMT solver... and that's also costlier than
storing a boolean.

**Comment by JonathanSalwan** [comment]
@Pyraun  indeed, it may be a good idea :)

**Comment by cheesechoi** [comment]
Thanks all :) I'll do it both way tonight.

**Comment by cheesechoi** [comment]
I will note [Fix 177](https://github.com/JonathanSalwan/Triton/commit/9f5d8b7d423991fa83ac727f40c182d7cce53b55) seems to relate this. And if I write nice code using IARG_BRANCH_TAKEN I will request some review :)

**Comment by JonathanSalwan** [comment]
Currently there are isBranch(), getAddress() and getNextAddress() available. We have to create a **isBranchTaken()** based on the IARG_BRANCH_TAKEN. If I get some time today, I will commit this feature :)

**Comment by cheesechoi** [comment]
Yoooooo

**Comment by JonathanSalwan** [comment]
**isBranchTaken()** and **getBranchTargetAddress()** are now available. Check out the description [here](http://triton.quarkslab.com/documentation/api/class-Instruction/).
