### ISSUE TITLE
Memory leak when restoring the context

### ISSUE THREAD

**Issue by JonathanSalwan** [JonathanSalwan/Triton#196]
When we restore a context *A* to *B* via **restoreSnapshot()**, we should free all allocations (symExpr, SymVar, etc) between *A* and *B*.

Take a look [here](https://github.com/JonathanSalwan/Triton/blob/588285e9d920551828e36f34483fe2413d6284aa/src/engines/snapshot/snapshotEngine.cpp#L59).

Test case: Try to cover all BBs from the @0vercl0k's [fsm obfuscated crackme](http://doar-e.github.io/blog/2013/08/24/regular-expressions-obfuscation-under-the-microscope/).

`$ ./triton ./tools/code_coverage.py ./samples/crackmes/crackme_regex_fsm_obfuscated a`

**Comment by JonathanSalwan** [comment]
Close but still related to #141.

**Comment by 0ca** [comment]
I've tried the example with the patch applied
`./triton ./tools/code_coverage.py ./samples/crackmes/crackme_regex_fsm_obfuscated a`

And now Triton consumes less memory indeed. But now after a while executing the program it shows this error:
```Traceback (most recent call last):
  File "./tools/code_coverage.py", line 200, in mainAnalysis
    od = OrderedDict(sorted(TritonExecution.input.dataAddr.items()))
  File "/usr/lib/python2.7/collections.py", line 52, in __init__
    self.__update(*args, **kwds)
  File "/usr/lib/python2.7/_abcoll.py", line 540, in update
    if isinstance(other, Mapping):
  File "/usr/lib/python2.7/abc.py", line 141, in __instancecheck__
    subtype in cls._abc_negative_cache):
  File "/usr/lib/python2.7/_weakrefset.py", line 75, in __contains__
    return wr in self.data
RuntimeError: maximum recursion depth exceeded in cmp```
And it is still consuming quite memory ~18 GB (idk if it is memory leak or not)

**Comment by JonathanSalwan** [comment]
Hey,

About the "maximum recursion depth exceeded in cmp", it's Python specific. So, we have two possible solutions:

* Redesign the code coverage without recursion.
* Implement the code coverage in C++ (as internal tool) and offer Python bindings.

About the memory leak. I know where is the root cause but there is no trivial fix for this =/. I'm currently working in a small garbage collector for AST nodes which should fix this issue. I hope this patch will be push soon :).

Cheers,

**Comment by 0ca** [comment]
Hi, 
I can't understand where is the recursion in this code. Where is it?

I guess it's related with some internals things.

Thank you!

**Comment by romainthomas** [comment]
As indicated in the error, Python use recursive function to sort `dataAddr` dictionary [code_coverage.py#L200](https://github.com/JonathanSalwan/Triton/blob/master/tools/code_coverage.py#L200) and for the obfuscated crackme, the dictionary which contains the mapping memory address => value seems to be huge.

As @JonathanSalwan we will implement the code coverage tool in C++ to do so optimizations.

**Comment by 0ca** [comment]
I don't think the problem is there, dataAddr in the `crackme_regex_fsm_obfuscated` always has a len of 7-8 elements. I removed the sorting part just to try:

I changed this:
```
        od = OrderedDict(sorted(TritonExecution.input.dataAddr.items()))
        for k,v in od.iteritems():
```
For:
```
        #od = OrderedDict(sorted(TritonExecution.input.dataAddr.items()))
        for i in TritonExecution.input.dataAddr.items():
            k, v = i
```

And now the recursion error is in other part:
```
    newInput = deepcopy(TritonExecution.input)
  File "/usr/lib/python2.7/copy.py", line 166, in deepcopy
    issc = issubclass(cls, type)
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

I still think is something related with some internal stuff. There is no recursion in that code.

Thanks for the help ;)

**Comment by JonathanSalwan** [comment]
It should be work.

**Comment by 0ca** [comment]
Yep, no more recursion problems. Great job! :)

The memory consumption is much better now. But I think there is still a small memory leak.
I was executing the code coverage with the crackme `./samples/crackmes/crackme_regex_fsm_obfuscated` for 1.5h (a lot) until the program used all the RAM and crashed.

I was thinking that the problem was a big worklist but it's not. The worklist keeps small around ~40 items all the time. So apparently there is no reason for this memory consumption right?

Thank you for your work.
