### ISSUE TITLE
Error starting analysis from symbol

### ISSUE THREAD

**Issue by 0ca** [JonathanSalwan/Triton#199]
Hi!

I have a problem with one of the examples. `./examples/callback_after.py`. I modified the example to start the analysis in the `_start` symbol instead of the `main`:
`startAnalysisFromSymbol('_start')`

But when I execute the following something unexpected happens: 
`./triton ./examples/callback_after2.py ./samples/crackmes/crackme_xor elite`

I can not see any of the instructions of the main function, but these instructions are executed (I can see the Win in the output). I can only see the instructions and expresions from the `_start` function and some libraries functions.
`./triton ./examples/callback_after2.py ./samples/crackmes/crackme_xor elite | grep 4005ca`
Returns no instructions at that position, only an assignment.
The address of the `main` function in the `crackme_xor` is `0x4005ca`.

I found this doings other tests but I think this is the easiest way to reproduce it.

I tried with others binaries and it worked as expected showing the `_start` and the `main` instructions.

How could I fix it? Thank you!

**Comment by JonathanSalwan** [comment]
Hey,

Mmmhh, you're right and I really don't know why Pin calls the [RTN_InsertCall](https://github.com/JonathanSalwan/Triton/blob/bccfc5d9986e34b0130b780f82cc71dfb95e2526/src/main.cpp#L323) at this point (0x400533) =/.

> How could I fix it?

Not yet, but I will try to figure out as soon as possible.

**Comment by JonathanSalwan** [comment]
Related to #206
