### ISSUE TITLE
Triton not hitting all the instructions

### ISSUE THREAD

**Issue by 0ca** [JonathanSalwan/Triton#206]
Hi!

I was doing some tests with `strcmp`, to see how it is the best way to manage it during code coverage. But I found that Triton in some cases is not hitting all the instructions.

I used this code:
```
#include <stdio.h>

int main(int argc, const char **argv)
{
    if (strcmp(argv[1], "1") == 0)
        printf("1\n");
    return 0;
}
```
I launched it with the callback after:
`./triton ./examples/callback_after.py ./samples/others/strcmp 0`

And I saw in the output the following:
```
0x400470: jmp qword ptr [rip+0x200bb2]
	 -> #64 = (concat ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv64 8)) ((_ extract 7 0) (_ bv4 8)) ((_ extract 7 0) (_ bv118 8))) ; RIP

0x400476: push 0x2
	 -> #65 = (bvsub ((_ extract 63 0) #53) (_ bv8 64)) ; Aligns stack
	 -> #66 = ((_ extract 63 56) (_ bv2 64)) ; byte reference
	 -> #67 = ((_ extract 55 48) (_ bv2 64)) ; byte reference
	 -> #68 = ((_ extract 47 40) (_ bv2 64)) ; byte reference
	 -> #69 = ((_ extract 39 32) (_ bv2 64)) ; byte reference
	 -> #70 = ((_ extract 31 24) (_ bv2 64)) ; byte reference
	 -> #71 = ((_ extract 23 16) (_ bv2 64)) ; byte reference
	 -> #72 = ((_ extract 15 8) (_ bv2 64)) ; byte reference
	 -> #73 = ((_ extract 7 0) (_ bv2 64)) ; byte reference
	 -> #75 = (_ bv4195451 64) ; RIP

0x40047b: jmp 0x400440
	 -> #76 = (_ bv4195392 64) ; RIP

0x7fa7aaf0865a: call rax
	 -> #77 = (bvsub ((_ extract 63 0) #65) (_ bv8 64)) ; Aligns stack
	 -> #78 = ((_ extract 63 56) (_ bv140358104155740 64)) ; byte reference
	 -> #79 = ((_ extract 55 48) (_ bv140358104155740 64)) ; byte reference
	 -> #80 = ((_ extract 47 40) (_ bv140358104155740 64)) ; byte reference
	 -> #81 = ((_ extract 39 32) (_ bv140358104155740 64)) ; byte reference
	 -> #82 = ((_ extract 31 24) (_ bv140358104155740 64)) ; byte reference
	 -> #83 = ((_ extract 23 16) (_ bv140358104155740 64)) ; byte reference
	 -> #84 = ((_ extract 15 8) (_ bv140358104155740 64)) ; byte reference
	 -> #85 = ((_ extract 7 0) (_ bv140358104155740 64)) ; byte reference
	 -> #87 = ((_ extract 63 0) #47) ; RIP
```
The next instruction after `0x40047b: jmp 0x400440` it would be at `0x400440` right? But not, I don't know why but Triton is skipping 0x400440 and it is jumping to `0x7fa7aaf0865a`.

Why is this happening?
What do you think is the best way to manage strcmp? Detecting it and converting the arguments to SE?

Thank you!

**Comment by 0ca** [comment]
Maybe it's related with https://github.com/JonathanSalwan/Triton/issues/199?

**Comment by JonathanSalwan** [comment]
I don't find the root cause yet, but it's probable that is the same issue.

**Comment by JonathanSalwan** [comment]
For this case, it's a classical behavior of Pin. When a branch is taken, the `after` callback is not called.

However, in your first example: 

```
0x40047b: jmp 0x400440
0x7fa7aaf0865a: call rax
```

The address `0x400440` is never called in both `before` or the `after` callback. After some quick "investigations", it's seems that `0x400440` is on the plt and `0x7fa7aaf0865a` is the targeted address. 

This is probably a classical behavior of the internal engine of Pin between the binary and its libraries. Anyway, even if you don't see the `0x400440` address, it should not disturb you :).

My 2 cts :),

PS: Thanks alot for all your tests and your feedback, we really appreciate your help :).

**Comment by 0ca** [comment]
Okay.

Then I have a problem. I want to use the tainted engine in the code coverage to only evaluate the conditions where some of the SE for that condition are tainted.

I can't use the tainted engine in the before callbacks, right? So I need to use the after callbacks and I am not going to stop in the taken jmps. 

I am not sure how to solve this. Maybe using the before callback and for each SE check if some of the references inside the SE is tainted?

Ps: Very welcome, thank you for your fast answers.

**Comment by JonathanSalwan** [comment]
> I can't use the tainted engine in the before callbacks, right? 

Use `IDREF.CALLBACK.BEFORE_SYMPROC`.

**Comment by 0ca** [comment]
Ok, thank you very much!

**Comment by 0ca** [comment]
Hi, 
What I want is to know if a condition is using tainted values. I cannot do it in the AFTER, so the idea is do it in the BEFORE callback. But in the BEFORE the method isTainted is not working.

The example `examples/taint_runtime_memory.py` uses the callback AFTER. But as we talked, it is not completely correct because is skipping the conditional jmps. So what would it be the correct approach to check if an instruction in tainted?

**Comment by JonathanSalwan** [comment]
```
$ cat private/0ca.py

from triton import *

def cbeforeSymProc(instruction):
    if instruction.getAddress() == 0x40058b:
        rax = getRegValue(IDREF.REG.RAX)
        taintMem(rax)

def cbefore(instruction):
    print '%#x: %s' %(instruction.getAddress(), instruction.getDisassembly())
    if instruction.isBranch():
        if isRegTainted(IDREF.FLAG.ZF):
            print 'tainted'

if __name__ == '__main__':
    startAnalysisFromSymbol('check')
    addCallback(cbeforeSymProc, IDREF.CALLBACK.BEFORE_SYMPROC)
    addCallback(cbefore, IDREF.CALLBACK.BEFORE)
    runProgram()

$ ./triton ./private/0ca.py ./samples/crackmes/crackme_xor ea
0x40056d: push rbp
0x40056e: mov rbp, rsp
0x400571: mov qword ptr [rbp-0x18], rdi
0x400575: mov dword ptr [rbp-0x4], 0x0
0x40057c: jmp 0x4005bd
0x4005bd: cmp dword ptr [rbp-0x4], 0x4
0x4005c1: jle 0x40057e
0x40057e: mov eax, dword ptr [rbp-0x4]
0x400581: movsxd rdx, eax
0x400584: mov rax, qword ptr [rbp-0x18]
0x400588: add rax, rdx
0x40058b: movzx eax, byte ptr [rax]
0x40058e: movsx eax, al
0x400591: sub eax, 0x1
0x400594: xor eax, 0x55
0x400597: mov ecx, eax
0x400599: mov rdx, qword ptr [rip+0x200aa0]
0x4005a0: mov eax, dword ptr [rbp-0x4]
0x4005a3: cdqe 
0x4005a5: add rax, rdx
0x4005a8: movzx eax, byte ptr [rax]
0x4005ab: movsx eax, al
0x4005ae: cmp ecx, eax
0x4005b0: jz 0x4005b9
tainted
0x4005b9: add dword ptr [rbp-0x4], 0x1
0x4005bd: cmp dword ptr [rbp-0x4], 0x4
0x4005c1: jle 0x40057e
0x40057e: mov eax, dword ptr [rbp-0x4]
0x400581: movsxd rdx, eax
0x400584: mov rax, qword ptr [rbp-0x18]
0x400588: add rax, rdx
0x40058b: movzx eax, byte ptr [rax]
0x40058e: movsx eax, al
0x400591: sub eax, 0x1
0x400594: xor eax, 0x55
0x400597: mov ecx, eax
0x400599: mov rdx, qword ptr [rip+0x200aa0]
0x4005a0: mov eax, dword ptr [rbp-0x4]
0x4005a3: cdqe 
0x4005a5: add rax, rdx
0x4005a8: movzx eax, byte ptr [rax]
0x4005ab: movsx eax, al
0x4005ae: cmp ecx, eax
0x4005b0: jz 0x4005b9
tainted
0x4005b2: mov eax, 0x1
0x4005b7: jmp 0x4005c8
0x4005c8: pop rbp
loose
$
```

But, I don't really like this way, because, you have to check all flags at a branch instruction to know if this branch is controllable. So, let me still some minutes for a new patch :). I will spread the taint on RIP. Then, at a branch instruction if `isRegTainted(IDREF.REG.RIP) == true`, it means, that it's a controllable branch.

**Comment by JonathanSalwan** [comment]
With the last patch (39c30710c60ee6cdaf829ee843417091799d018f) it should work like this:

```
def cbefore(instruction):
    print '%#x: %s' %(instruction.getAddress(), instruction.getDisassembly())
    if instruction.isBranch() and isRegTainted(IDREF.REG.RIP):
        print 'tainted'
```

**Comment by 0ca** [comment]
Oh, beautiful!

Thanks man!
