### ISSUE TITLE
Problems setting a register

### ISSUE THREAD

**Issue by 0ca** [JonathanSalwan/Triton#207]
Hi, 

I am trying to use the function `setRegValue` to modify the value of a registry in a program. But I am having issues.

For example I modified the example `examples/callback_before.py` and I inserted a line to modify the register RSI (this register is never used in the main function):
```
def my_callback_before(instruction):
    print 'TID (%d) %#x %s' %(instruction.getThreadId(), instruction.getAddress(), instruction.getDisassembly())
    setRegValue(IDREF.REG.RSI, 0)
    print 'RSI modified'
```
Then I executed: `./triton ./examples/callback_before.py ./samples/crackmes/crackme_xor a`

But the last line `print 'RSI modified'` is never reached. The output is like this:
```
TID (0) 0x40056d push rbp
TID (0) 0x40056d push rbp
TID (0) 0x40056d push rbp
TID (0) 0x40056d push rbp
TID (0) 0x40056d push rbp
TID (0) 0x40056d push rbp
TID (0) 0x40056d push rbp
TID (0) 0x40056d push rbp
TID (0) 0x40056d push rbp
TID (0) 0x40056d push rbp
TID (0) 0x40056d push rbp
TID (0) 0x40056d push rbp
TID (0) 0x40056d push rbp
TID (0) 0x40056d push rbp
TID (0) 0x40056d push rbp
TID (0) 0x40056d push rbp
TID (0) 0x40056d push rbp
TID (0) 0x40056d push rbp
TID (0) 0x40056d push rbp
TID (0) 0x40056d push rbp
TID (0) 0x40056d push rbp
RuntimeError
```

Should I use `setRegValue` inside other callback? Or is it a bug?

Thank you!

**Comment by JonathanSalwan** [comment]
As `setRegValue` uses `PIN_ExecuteAt` and as you use it inside a `BEFORE` callback, the `RIP` is not yet updated and your callback is recalled when the `setRegValue()` occurs. It's a Pin specific behavior. I  recommend you to use it in a `AFTER` callback.

**Comment by 0ca** [comment]
I also tried in the after callback:

```
def my_callback_after(instruction):
    print '%#x: %s' %(instruction.getAddress(), instruction.getDisassembly())
    setRegValue(IDREF.REG.RSI, 0)
    print 'RSI modified'
```
But the print line is never reached. 

And I also tried in a IDREF.CALLBACK.ROUTINE_ENTRY, in the code coverage example, and it doesn't work. I think there is some kind of problem with this.

Thank you for the quick answer ;)

**Comment by JonathanSalwan** [comment]
As I said, `PIN_ExecuteAt` changes the control flow of the jited code. That's why you can't reach anything after calling the `setRegValue` function. This is a classical behavior of Pin but I can understand that for a Triton user it's a weird behavior.

I will try to call the `PIN_ExecuteAt` function after that the Python environment has been executed but it will still be recommended to use the `setRegValue()` function just before a `return` like this:

```
def my_callback_after(instruction):
    if (instruction.getAddress() == 0x.......)
        setRegValue(IDREF.REG.X, Y)
        return
```

**Comment by 0ca** [comment]
Ok, thank you! I was a bit confused about this.

**Comment by JonathanSalwan** [comment]
With the last patch, when you use the `setRegValue()` function, the `PIN_ExecuteAt` occurs after your python env. Anyway, as  `PIN_ExecuteAt` re-execute the current jited context, it's recommended to use the `setRegValue()` function inside an `AFTER` callback.
