### ISSUE TITLE
Question: How to manage strlen, strcmp?

### ISSUE THREAD

**Issue by 0ca** [JonathanSalwan/Triton#210]
Hi, 

I am trying Triton with a test C code using the `strlen` call.
```
#include <stdio.h>
#include <string.h>

int main(int argc, const char **argv)
{
    int len;
    len =  strlen(argv[1]);
    //for (len = 0; argv[1][len] != 0; len++);
    if (len == 4)
        printf("Correct len\n");
    else
        printf("Len is not correct\n");
    return 0;
}
```
My goal is to do code coverage and reach the `printf("Correct len\n");`. With my own implementation of strlen `for (len = 0; argv[1][len] != 0; len++);` it works.  

But if I use the glibc `strlen` it doesn't work. The problem is `strlen` implementation in 64 bits uses a lot of FPU instructions, unsupported in Triton:
```
0x7fc7c384fac0: pxor xmm8, xmm8
0x7fc7c384fac5: pxor xmm9, xmm9
0x7fc7c384faca: pxor xmm10, xmm10
0x7fc7c384facf: pxor xmm11, xmm11
0x7fc7c384fad4: mov rax, rdi
0x7fc7c384fad7: mov rcx, rdi
0x7fc7c384fada: and rcx, 0xfff
0x7fc7c384fae1: cmp rcx, 0xfcf
0x7fc7c384fae8: jnbe 0x7fc7c384fb50
0x7fc7c384faea: movdqu xmm12, xmmword ptr [rax]
0x7fc7c384faef: pcmpeqb xmm12, xmm8
0x7fc7c384faf4: pmovmskb edx, xmm12
0x7fc7c384faf9: test edx, edx
0x7fc7c384fafb: jz 0x7fc7c384fb01
0x7fc7c384fafd: bsf eax, edx
0x7fc7c384fb00: ret 
```
```
Unsuported Semantics
=============================================================
pxor: 8
pmovmskb: 5
pcmpeqb: 5
bsf: 2
cmpxchg: 1
```
 
What do you think is the best approach? Implement these FPU instructions? Detect the use of strlen and convert directly to SE?

Thank you.

**Comment by JonathanSalwan** [comment]
The best way is to implement theses semantics. **pxor**, **pmovmskb** and **cmpxchg** will be easy to dev, **pcmpeqb** will be boring and **bsf**/**bsr** not trivial :(.

I suggest first to fix the *32bits* branch before to continue the *master* one.
