### ISSUE TITLE
Building with gcc 5.3.0

### ISSUE THREAD

**Issue by romainthomas** [JonathanSalwan/Triton#228]
When building Triton with gcc 5.3.0 we get this error
```E: Unable to load Triton/build/libtriton.so: Triton/build/libtriton.so: undefined symbol: _ZN10LEVEL_BASE9StringDecB5cxx11Emjc```

**Comment by kreaseck** [comment]
Just got this same error when attempting to build a different tool ... any luck in finding a solution to this?  
I am using gcc 5.2.0 on CentOS to attempt to build that tool, which builds/runs fine using gcc 4.7 on Ubuntu 14.04....

**Comment by JonathanSalwan** [comment]
Into the file `pin/source/tools/Config/makefile.unix.config` at line 84 (`TOOL_CXXFLAGS_NOOPT :=`) add the flag `-fabi-version=2`.

Looks like this for me:

```
APP_CXXFLAGS_NOOPT :=
TOOL_CXXFLAGS_NOOPT := -DBIGARRAY_MULTIPLIER=1 -Wall -Werror -Wno-unknown-pragmas -fabi-version=2
DLL_CXXFLAGS :=
ENABLE_DEPRECATED := -DPIN_DEPRECATED_WARNINGS=0
```

**Comment by kreaseck** [comment]
Thanks, I will try that.
