### ISSUE TITLE
Allow the user to create a new expression and to assign the expr to a register

### ISSUE THREAD

**Issue by JonathanSalwan** [JonathanSalwan/Triton#230]

**Comment by illera88** [comment]
Hi Jonathan. As I said this is a blocker for us. Can you point me where should I look to help you out with this??

thanks!

**Comment by JonathanSalwan** [comment]
```python
def callback(instruction):
    ....
    se = createSymExpr(bv(1234, 64))              # Create a new symbolic expression
    assignSymExprToReg(se, IDREF.REG.RAX)         # Assign an expression to a register
    ....
```

**Be careful**, use the `assignSymExprToReg()` function if you know what you are doing. The symbolic expression (`se`) **must** be aligned to the targeted size register. In this example, `se` must be an expression aligned to `IDREF.CPUSIZE.REG_BIT` (64-bits). On 32-bits the expression must be aligned to 32-bits and for SSE registers, the expression must be aligned to 128-bits. Otherwise, you will probably get a `sort mismatch` error when you will solve the expression.
