### ISSUE TITLE
    if se.isTainted() == True: OverflowError: long too big to convert

### ISSUE THREAD

**Issue by liuyuer** [JonathanSalwan/Triton#239]
I am running it in a 64-bit env.

**Comment by JonathanSalwan** [comment]
What build number do you have?

`cat <triton src>/.build_number`

Because it's works well for me.

`$ ./triton examples/taint_runtime_memory.py ./samples/crackmes/crackme_xor a`

**Comment by liuyuer** [comment]
This is my command:
sudo ./triton ./triton examples/taint_runtime_memory.py ./samples/ir_test_suite/ir

build_number is 763

**Comment by JonathanSalwan** [comment]
It works well for me. Did you tried to recompile triton from scratch ?

`rm -rf build ; mkdir build ; cd build ; cmake .. ; make`

**Comment by liuyuer** [comment]
I rebuild , and this issue is intermittent

I run it 10 times. There are 4 failures.

sudo ./triton ./liuyuer/taint_runtime_memory.py ./samples/ir_test_suite/ir | grep "Overflow:"



>>> for i in range(0,10):
...     print i,'-'*30
...     os.system('./1.sh')
... 
0 ------------------------------
256
1 ------------------------------
Traceback (most recent call last):
  File "./liuyuer/taint_runtime_memory.py", line 23, in cafter
    if se.isTainted() == True:
OverflowError: long too big to convert
256
2 ------------------------------
256
3 ------------------------------
256
4 ------------------------------
Traceback (most recent call last):
  File "./liuyuer/taint_runtime_memory.py", line 23, in cafter
    if se.isTainted() == True:
OverflowError: long too big to convert
256
5 ------------------------------
256
6 ------------------------------
256
7 ------------------------------
256
8 ------------------------------
Traceback (most recent call last):
  File "./liuyuer/taint_runtime_memory.py", line 23, in cafter
    if se.isTainted() == True:
OverflowError: long too big to convert
256
9 ------------------------------
Traceback (most recent call last):
  File "./liuyuer/taint_runtime_memory.py", line 23, in cafter
    if se.isTainted() == True:
OverflowError: long too big to convert
256

**Comment by JonathanSalwan** [comment]
Ok I got it. Actually, you used this script on the wrong binary. As you can see, I'm looking for the address `0x40058b` which corresponds to a `movzx eax, byte ptr [rax]`. Then, I get the address contained into `RAX` and I taint the memory.

```python
# 0x40058b: movzx eax, byte ptr [rax]
#
# When the instruction located in 0x40058b is executed,
# we taint the memory that RAX holds.
def cbeforeSymProc(instruction):
    if instruction.getAddress() == 0x40058b:
        rax = getRegValue(IDREF.REG.RAX)
        taintMem(rax)
```

If you use this script to the `./samples/ir_test_suite/ir` binary, at the address 0x40058b RAX makes  no sense.

```
$ gdb ./samples/ir_test_suite/ir
gdb-peda$ b *0x40058b                                                                                                                                                                                                                          
Breakpoint 1 at 0x40058b

gdb-peda$ r
Breakpoint 1, 0x000000000040058b in check ()

gdb-peda$ i r rax
rax            0x3ddc9ebbed34ca00       0x3ddc9ebbed34ca00
```

So, you taint a random address which some time returns -1 when we try to convert the address to a PyLong.

**Comment by liuyuer** [comment]
I changed your code to another address: 400587

def cbeforeSymProc(instruction):

    if instruction.getAddress() == 0x400587:
        rax = getRegValue(IDREF.REG.RAX)
        taintMem(rax)


I used IDA pro to find out the address:

.text:0000000000400576                 push    rbp
.text:0000000000400577                 mov     rbp, rsp
.text:000000000040057A                 sub     rsp, 40h
.text:000000000040057E                 mov     rax, fs:28h
.text:0000000000400587                 mov     [rbp+var_8], rax
.text:000000000040058B                 xor     eax, eax
.text:000000000040058D                 mov     dword ptr [rbp+var_42+2], 11111111h
.text:0000000000400594                 mov     dword ptr [rbp+var_42+6], 22222222h



Why I can't taint the rax at 400587?

**Comment by JonathanSalwan** [comment]
Git pull, I pushed a patch before my previous answer.

**Comment by liuyuer** [comment]
Will do it. Thanks a lot, bro.

**Comment by liuyuer** [comment]
Looks perfect! Awesome man!
