### ISSUE TITLE
Differents errors while compiling on Mac OS X

### ISSUE THREAD

**Issue by Xumeiquer** [JonathanSalwan/Triton#264]
I am using Mac OS X El Capitan 10.11.2 and I am not able to compile Triton successfully. I have install all the requiered libraries though `port` and I have downloaded Pin from the intel web site. After following the instructions I could not compile Triton because the import files are not develop for Mac OS X. In terms to fix that I have updated them, see the git diff below. Moreover, and after fixing that issue, I got an linker error, that I am not able to fix.

'''"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -dynamic -dylib -arch x86_64 -dylib_install_name @rpath/libpintool.dylib -macosx_version_min 10.11.0 -o libpintool.dylib -L/Users/XXXX/Downloads/pin-2.14-71313-clang.5.1-mac/source/tools/Triton/../../../intel64/lib -L/Users/XXXX/Downloads/pin-2.14-71313-clang.5.1-mac/source/tools/Triton/../../../intel64/lib-ext -L/Users/XXXX/Downloads/pin-2.14-71313-clang.5.1-mac/source/tools/Triton/../../../extras/xed-intel64/lib -headerpad_max_install_names --hash-style=sysv -Bsymbolic CMakeFiles/pintool.dir/src/tracer/pin/bindings.cpp.o CMakeFiles/pintool.dir/src/tracer/pin/callbacks.cpp.o CMakeFiles/pintool.dir/src/tracer/pin/context.cpp.o CMakeFiles/pintool.dir/src/tracer/pin/init.cpp.o CMakeFiles/pintool.dir/src/tracer/pin/main.cpp.o CMakeFiles/pintool.dir/src/tracer/pin/snapshot.cpp.o CMakeFiles/pintool.dir/src/tracer/pin/trigger.cpp.o CMakeFiles/pintool.dir/src/tracer/pin/utils.cpp.o -lpin -lxed -lpindwarf -ldl libtriton.dylib /usr/lib/libpython2.7.dylib /usr/local/lib/libz3.dylib /usr/local/lib/libcapstone.dylib -rpath /Users/XXXX/Downloads/pin-2.14-71313-clang.5.1-mac/source/tools/Triton/../../../intel64/lib -rpath /Users/XXXX/Downloads/pin-2.14-71313-clang.5.1-mac/source/tools/Triton/../../../intel64/lib-ext -rpath /Users/XXXX/Downloads/pin-2.14-71313-clang.5.1-mac/source/tools/Triton/../../../extras/xed-intel64/lib -rpath /Users/XXXX/Downloads/pin-2.14-71313-clang.5.1-mac/source/tools/Triton/build -lc++ -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/lib/darwin/libclang_rt.osx.a
ld: unknown option: --hash-style=sysv'''

Do you have any suggestions how to link against Pin on Mac OS X?

Git diff:
diff --git a/src/libtriton/arch/x86/x8664Cpu.cpp b/src/libtriton/arch/x86/x8664Cpu.cpp
index 89b2a08..b80f51e 100644
--- a/src/libtriton/arch/x86/x8664Cpu.cpp
+++ b/src/libtriton/arch/x86/x8664Cpu.cpp
@@ -12,10 +12,12 @@
 #include <x8664Cpu.hpp>
 #include <x86Specifications.hpp>

-#ifdef \_\_unix\_\_
+#if defined(\_\_unix\_\_)
   #include <capstone/capstone.h>
-#elif \_WIN32
+#elif defined(\_WIN32)
   #include <capstone.h>
+#elif defined(\_\_APPLE\_\_) && defined(\_\_MACH\_\_)
+  #include <capstone/capstone.h>
 #endif

 #ifdef TRITON\_PYTHON\_BINDINGS
diff --git a/src/libtriton/arch/x86/x86Cpu.cpp b/src/libtriton/arch/x86/x86Cpu.cpp
index 84f7d15..04442e8 100644
--- a/src/libtriton/arch/x86/x86Cpu.cpp
+++ b/src/libtriton/arch/x86/x86Cpu.cpp
@@ -14,10 +14,12 @@
 #include <x86Cpu.hpp>
 #include <x86Specifications.hpp>

-#ifdef \_\_unix\_\_
+#if defined(\_\_unix\_\_)
   #include <capstone/capstone.h>
-#elif \_WIN32
+#elif defined(\_WIN32)
   #include <capstone.h>
+#elif defined(\_\_APPLE\_\_) && defined(\_\_MACH\_\_)
+  #include <capstone/capstone.h>
 #endif

 #ifdef TRITON\_PYTHON\_BINDINGS
diff --git a/src/libtriton/bindings/python/utils.cpp b/src/libtriton/bindings/python/utils.cpp
index 758c286..7f16e72 100644
--- a/src/libtriton/bindings/python/utils.cpp
+++ b/src/libtriton/bindings/python/utils.cpp
@@ -17,6 +17,9 @@
   #include <python2.7/longintrepr.h>
 #elif \_WIN32
   #include <Python.h>
+#else
+  #include <Python.h>
+  #include <longintrepr.h>
 #endif

diff --git a/src/libtriton/includes/api.hpp b/src/libtriton/includes/api.hpp
index 93da088..f50c0b6 100644
--- a/src/libtriton/includes/api.hpp
+++ b/src/libtriton/includes/api.hpp
@@ -21,9 +21,11 @@
 #include "tritonTypes.hpp"

 #ifdef TRITON\_PYTHON\_BINDINGS
-  #ifdef \_\_unix\_\_
+  #if defined(\_\_unix\_\_)
     #include <python2.7/Python.h>
-  #elif \_WIN32
+  #elif defined(\_WIN32)
+    #include <Python.h>
+  #elif defined(\_\_APPLE\_\_) && defined(\_\_MACH\_\_)
     #include <Python.h>
   #endif
 #endif
diff --git a/src/libtriton/includes/pythonBindings.hpp b/src/libtriton/includes/pythonBindings.hpp
index 698530f..a92ef7b 100644
--- a/src/libtriton/includes/pythonBindings.hpp
+++ b/src/libtriton/includes/pythonBindings.hpp
@@ -10,9 +10,11 @@
 #ifndef TRITONPYTHONBINDINGS\_H
 #define TRITONPYTHONBINDINGS\_H

-#ifdef \_\_unix\_\_
+#if defined(\_\_unix\_\_)
   #include <python2.7/Python.h>
-#elif \_WIN32
+#elif defined(\_WIN32)
+  #include <Python.h>
+#elif defined(\_\_APPLE\_\_) && defined(\_\_MACH\_\_)
   #include <Python.h>
 #endif

diff --git a/src/libtriton/includes/pythonObjects.hpp b/src/libtriton/includes/pythonObjects.hpp
index d9a20bd..bb64a51 100644
--- a/src/libtriton/includes/pythonObjects.hpp
+++ b/src/libtriton/includes/pythonObjects.hpp
@@ -21,9 +21,11 @@
 #include "symbolicExpression.hpp"
 #include "symbolicVariable.hpp"

-#ifdef \_\_unix\_\_
+#if defined(\_\_unix\_\_)
   #include <python2.7/Python.h>
-#elif \_WIN32
+#elif defined(\_WIN32)
+  #include <Python.h>
+#elif defined(\_\_APPLE\_\_) && defined(\_\_MACH\_\_)
   #include <Python.h>
 #endif

diff --git a/src/libtriton/includes/pythonUtils.hpp b/src/libtriton/includes/pythonUtils.hpp
index d5ac268..9b3662e 100644
--- a/src/libtriton/includes/pythonUtils.hpp
+++ b/src/libtriton/includes/pythonUtils.hpp
@@ -12,9 +12,11 @@

 #include "tritonTypes.hpp"

-#ifdef \_\_unix\_\_
+#if defined(\_\_unix\_\_)
   #include <python2.7/Python.h>
-#elif \_WIN32
+#elif defined(\_WIN32)
+  #include <Python.h>
+#elif defined(\_\_APPLE\_\_) && defined(\_\_MACH\_\_)
   #include <Python.h>
 #endif

diff --git a/src/libtriton/includes/pythonXFunctions.hpp b/src/libtriton/includes/pythonXFunctions.hpp
index a0f77ba..32c955c 100644
--- a/src/libtriton/includes/pythonXFunctions.hpp
+++ b/src/libtriton/includes/pythonXFunctions.hpp
@@ -10,9 +10,11 @@
 #ifndef TRITONXPYFUNCTION\_H
 #define TRITONXPYFUNCTION\_H

-#ifdef \_\_unix\_\_
+#if defined(\_\_unix\_\_)
   #include <python2.7/Python.h>
-#elif \_WIN32
+#elif defined(\_WIN32)
+  #include <Python.h>
+#elif defined(\_\_APPLE\_\_) && defined(\_\_MACH\_\_)
   #include <Python.h>
 #endif

diff --git a/src/libtriton/includes/symbolicOptimization.hpp b/src/libtriton/includes/symbolicOptimization.hpp
index 60452ea..be36a6c 100644
--- a/src/libtriton/includes/symbolicOptimization.hpp
+++ b/src/libtriton/includes/symbolicOptimization.hpp
@@ -12,9 +12,11 @@
 #include "tritonTypes.hpp"

 #ifdef TRITON\_PYTHON\_BINDINGS
-  #ifdef \_\_unix\_\_
+  #if defined(\_\_unix\_\_)
     #include <python2.7/Python.h>
-  #elif \_WIN32
+  #elif defined(\_WIN32)
+    #include <Python.h>
+  #elif defined(\_\_APPLE\_\_) && defined(\_\_MACH\_\_)
     #include <Python.h>
   #endif
 #endif
diff --git a/src/libtriton/includes/symbolicSimplification.hpp b/src/libtriton/includes/symbolicSimplification.hpp
index 517f980..42ea484 100644
--- a/src/libtriton/includes/symbolicSimplification.hpp
+++ b/src/libtriton/includes/symbolicSimplification.hpp
@@ -13,9 +13,11 @@
 #include "smt2lib.hpp"

 #ifdef TRITON\_PYTHON\_BINDINGS
-  #ifdef \_\_unix\_\_
+  #if defined(\_\_unix\_\_)
     #include <python2.7/Python.h>
-  #elif \_WIN32
+  #elif defined(\_WIN32)
+    #include <Python.h>
+  #elif defined(\_\_APPLE\_\_) && defined(\_\_MACH\_\_)
     #include <Python.h>
   #endif
 #endif
diff --git a/src/libtriton/includes/syscalls.hpp b/src/libtriton/includes/syscalls.hpp
index be1f48f..afcae8d 100644
--- a/src/libtriton/includes/syscalls.hpp
+++ b/src/libtriton/includes/syscalls.hpp
@@ -8,9 +8,9 @@
 #ifndef TRITON\_SYSCALLS\_H
 #define TRITON\_SYSCALLS\_H

-#ifdef \_\_unix\_\_
+#if defined(\_\_unix\_\_)

-  #ifdef \_\_APPLE\_\_
+  #ifdef \_\_APPLE\_\_ && \_\_MACH\_\_
     #include <sys/syscall.h>
   #else
     #if defined(\_\_x86\_64\_\_) || defined(\_M\_X64)
diff --git a/src/libtriton/includes/unix.hpp b/src/libtriton/includes/unix.hpp
index b7cbb67..b643751 100644
--- a/src/libtriton/includes/unix.hpp
+++ b/src/libtriton/includes/unix.hpp
@@ -8,7 +8,7 @@
 #ifndef TRITON\_UNIX\_HPP
 #define TRITON\_UNIX\_HPP

-#ifdef \_\_unix\_\_
+#if defined(\_\_unix\_\_)

 #include <syscalls.hpp>

**Comment by JonathanSalwan** [comment]
Hey,

Sorry for the lag, I was in vacation...

Your issue looks like related to this one #243.

**Comment by Xumeiquer** [comment]
Yes, it looks like a similar issue. I'll try to set up the thing on a VM as suggeted in #243.

Thanks any way.
