### ISSUE TITLE
Why this line of code in the code_coverage.py tool?

### ISSUE THREAD

**Issue by gitttt** [JonathanSalwan/Triton#267]
Line 209 in code_coverage.py:

> convertMemToSymVar(Memory(k, CPUSIZE.BYTE), "addr_%d" % k)

`convertMemToSymVar` returns an object of type `SymbolicVariable`. Yet this object is not assigned to a variable. I can't figure out what the line is suppose to do.

Same for line 215:

> convertMemToSymVar(Memory(argv1_addr + idx, CPUSIZE.BYTE), "addr_%d" % idx)

Thanks for the clarifications!

**Comment by romainthomas** [comment]
> convertMemToSymVar returns an object of type SymbolicVariable

You are right !

> Yet this object is not assigned to a variable. 

We don't need to use the returned variable in the tool. But the symbolic variable previously created will be use be in Triton's symbolic engine.

**Comment by gitttt** [comment]
Thanks for the fast reply. In general, I do understand what `convertMemToSymVar` is doing. I was just wondering what it was doing here. Do I understand your answer correctly that we don't need the two lines here in this particular code right?

**Comment by romainthomas** [comment]
`convertMemToSymVar` is just an API for the Triton's symbolic engine

If we have the following assembly code
```asm
mov        rax, QWORD PTR [0x123]
add        rax, 1
```

And we perform symbolic execution
```python
from triton import *
convertMemToSymVar(0x123, 8)
raxId    = getSymbolicRegisterId(REG.RAX)
raxExpr  = getFullAstFromId(raxId)
print raxExpr
```
We will get 
```
output = SymVar0 + 1
```

PS:
The code above doesn't work it just to show you how to use `convertMemToSymVar`

**Comment by gitttt** [comment]
Thanks for the explanation. I was not aware that `convertMemToSymVar`` has an effect even if one does not use the returned object.

Yet, the code_coverage.py works even if line 209 is commented out. Why is that?

**Comment by romainthomas** [comment]
I will take a look

**Comment by gitttt** [comment]
Hey!
I looked at the example over and over again. I am still not 100% sure what this code does:
```
        for idx, byte in enumerate(TritonExecution.input.data):
            if argv1_addr + idx not in TritonExecution.input.dataAddr: # Not overwrite the previous setting
                print "\t[0x%x] = %x %c" % (argv1_addr + idx, ord(byte), ord(byte))
                setCurrentMemoryValue(Memory(argv1_addr + idx, CPUSIZE.BYTE), ord(byte))
                convertMemToSymVar(Memory(argv1_addr + idx, CPUSIZE.BYTE), "addr_%d" % idx)
```
What do you mean by the comment "Not overwrite the previous setting"?

Is the purpose of this code to ensure that the input has always a size of 5 characters?

**Comment by gitttt** [comment]
Regarding line 209, my hypothesis is this:

The example works, i.e. it shows "win" because, in this particular example, there is no need to change the input once it was fed. In other words, once the 'e' as first character of the input is set, it need not change afterwards. So I guess another case, say if there is an additional branch if the first letter is 'x', then it may not work any more if line 209 is commented out. This is because then the first character would be set to 'x' but would not be marked as symbolic any more - it would be fixed. Then the solver would not be able to come up with the input 'e' as first character.

Is my understanding of the code correct?

I hope I managed to explain my thoughts. Please tell me if it is too confuse ...

**Comment by romainthomas** [comment]
Yes you are right.
For more details you can have a look at [SAGE](http://research.microsoft.com/en-us/um/people/pg/public_psfiles/ndss2008.pdf)

**Comment by JonathanSalwan** [comment]
Feel free to reopen if it's still not clear :)
