### ISSUE TITLE
Is there any Windows support?

### ISSUE THREAD

**Issue by farmdve** [JonathanSalwan/Triton#269]
As it was not mentioned in the docs.

And if there is, how do I build? If there isn't, what alternative do you recommend? Miasm requires special libraries which might not compile on Windows.

**Comment by romainthomas** [comment]
In fact Triton is divided in two part:
- libTriton (which contains all engines)
- A tracer which use PIN (which is used to generate a trace)

`libTriton` should work on windows but the tracer seems not working on Windows.
To only use `libTriton` you can read the first part of the installation page: [installation](http://triton.quarkslab.com/documentation/doxygen/)

We could use other DBI than `pin` like `Valgring` but we didn't (yet) implement it so if you want to do a PR about it you are welcome

**Comment by farmdve** [comment]
Alright, and is Pin required for anything other than tracing?

I am interested in using the symbolic execution properties for the purpose of deobfuscation of x86 instructions.
I can supply the instructions as a binary PE file, or standalone .bin(with raw x86 code, no headers) or even disassembled output.

**Comment by romainthomas** [comment]
In fact you can perform symbolic execution on any assembly code (x86, x86-64) with libTriton but you have to provide the assembly code. It can be from:
 - A trace from a DBI
 - Assembly code from a PE, ELF,Mach-O file
 - From a DB 
 - Raw assembly like in this example: [symbolic_emulation.py](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/symbolic_emulation.py#L68)

The PIN tracer is used for the first one but you can develop a tool which extract the assembly code from a PE file a proceeded with libTriton :)

**Comment by 0ca** [comment]
I was trying to compile the Triton pintool in Windows. But I found a lot of issues importing python and z3 in the pintool. Basically pin crashes when the pintool is loading python27.dll, this dll requires to load msvcr110.dll and there is some kind of problem loading this library with pin.

I was also trying to port the pintool to DynamoRio but I found a very similar problem, this time loading other library:
https://github.com/DynamoRIO/dynamorio/issues/1866

**Comment by farmdve** [comment]
I managed to compile libtriton, but are the Python bindings necessary? What I mean is it possible to use libTriton in native code? If yes, I am unable to find any documentation.

**Comment by 0ca** [comment]
No, they aren't necessary, you can use the C API. Look at the next example:
https://github.com/JonathanSalwan/Triton/blob/master/src/examples/cpp/ir.cpp

**Comment by JonathanSalwan** [comment]
Hey,

LibTriton may be compiled without python bindings `cmake
-DTRITON_PYTHON_BINDINGS=no` and the C++ API is the same than the python
API. All information about the API class is available [here](
http://triton.quarkslab.com/documentation/doxygen/classtriton_1_1API.html)
and some examples are available [here](
https://github.com/JonathanSalwan/Triton/tree/master/src/examples/cpp)

**Comment by JonathanSalwan** [comment]
Hey,

LibTriton may be compiled without python bindings `cmake
-DTRITON_PYTHON_BINDINGS=no` and the C++ API is the same than the python
API. All information about the API class is available [here](
http://triton.quarkslab.com/documentation/doxygen/classtriton_1_1API.html) and some examples are available [here](
https://github.com/JonathanSalwan/Triton/tree/master/src/examples/cpp)

**Comment by pfsun** [comment]
Hi @0ca 

> I was trying to compile the Triton pintool in Windows. But I found a lot of issues importing python and z3 in the pintool. Basically pin crashes when the pintool is loading python27.dll, this dll requires to load msvcr110.dll and there is some kind of problem loading this library with pin.
I was also trying to port the pintool to DynamoRio but I found a very similar problem, this time loading other library:
DynamoRIO/dynamorio#1866

I was wondering whether you finally port the pintool to DynamoRio successfully? Thanks.

**Comment by bat-serjo** [comment]
Hi Jonathan, what is the reason for skipping pintool on windows?
Maybe if you explain the issues you're facing there someone can fix them.
