### ISSUE TITLE
Bad file descriptor when redirecting output

### ISSUE THREAD

**Issue by danielschemmel** [JonathanSalwan/Triton#270]
The canonical example

    ./triton ./src/examples/pin/ir.py /usr/bin/id

works when called as shown, but fails reproducibly with

    Traceback (most recent call last):
      File "./src/examples/pin/ir.py", line 13, in mycb
        print expr
    IOError: [Errno 9] Bad file descriptor

when its output is redirected to a file like so:

    ./triton ./src/examples/pin/ir.py /usr/bin/id > out.txt

The same happens when taking a detour through cat, like so:

    ./triton ./src/examples/pin/ir.py /usr/bin/id | cat -

In either case, the point in time when it happens seems to be variable.

Running Ubuntu 14.04.3 with z3, capstone, and triton all at github master and pin 71313.

**Comment by danielschemmel** [comment]
Verified the existence of the problem on a different machine (similar ubuntu 14.04 LTS) with stable versions of capstone (3.0.4) and z3 (4.4.1).

**Comment by JonathanSalwan** [comment]
Hey,

Thanks for this feedback. Do you know if it's related to the pintool or the libTriton?

**Comment by danielschemmel** [comment]
Sadly I do not, however I do have the system running and would love to perform any debugging session that might help pinpoint the problem - however I have neither used pin, nor triton before, so my assistance is probably somewhat limited ;)

**Comment by JonathanSalwan** [comment]
Hehe :).

Okay, let me some days to determine the root cause :)

**Comment by JonathanSalwan** [comment]
Well, after some reading [[1](http://stackoverflow.com/questions/14207708/ioerror-errno-32-broken-pipe-python),[2](http://stackoverflow.com/questions/107705/disable-output-buffering),[3](https://software.intel.com/sites/landingpage/pintool/docs/71313/Pin/html/index.html)], I'm pretty sure that this issue is related to Pin internal voodoo stuffs. I don't know how Pin manages `SIGPIPE` and if we take a look at all examples described in the [Pin's doc](https://software.intel.com/sites/landingpage/pintool/docs/71313/Pin/html/index.html), all examples use a  `fopen()` to log a trace. 

If I use `fopen()` instead of `SIGPIPE` it works well:

```patch
diff --git a/src/examples/pin/ir.py b/src/examples/pin/ir.py
index 11c0215..b23ea5f 100644
--- a/src/examples/pin/ir.py
+++ b/src/examples/pin/ir.py
@@ -6,12 +6,13 @@ import sys
 from pintool import *
 from triton  import *
 
+fd = open('/tmp/a', 'w')
 
 def mycb(inst):
-    print inst
+    fd.write(str(inst))
     for expr in inst.getSymbolicExpressions():
-        print expr
-    print
+        fd.write(str(expr))
+    fd.write('\n')
     return
```

```console
$ ./triton ./src/examples/pin/ir.py /usr/bin/id
uid=1000(jonathan) gid=100(users) groups=100(users),18(audio),35(games),78(kvm),102(vboxusers),103(plugdev),982(docker),999(android)
$ ls -l /tmp/a
-rw-r--r-- 1 jonathan users 289M Feb  5 19:06 /tmp/a
$
```

I think I can't do anything against this behavior :( and I can only recommend to use `fopen` not a `SIGPIPE`.

**Comment by JonathanSalwan** [comment]
After others tests, it seems that is related to the Python part and not Pin or maybe the fact that we use both Pin + Python...

**Comment by illera88** [comment]
Pin + Python are definitely not friends...

On Fri, Feb 5, 2016 at 10:28 AM, Jonathan Salwan <notifications@github.com>
wrote:

> After others tests, it seems that is related to the Python part and not
> Pin or maybe the fact that we use both Pin + Python...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JonathanSalwan/Triton/issues/270#issuecomment-180484980>
> .
>



-- 
Alberto García Illera

GPG Public Key: https://goo.gl/twKUUv

**Comment by danielschemmel** [comment]
Another result points toward the python integration:
Running a heavily tracing example of mine or ir.py with open (using exactly your code), I seem to be able to capture the output of the target program without problems as per:

    ./triton fd-ir.py /usr/bin/id > id.out 2> id.err

**Comment by JonathanSalwan** [comment]
It seems that flush the `std::cout` resolves this issue.
