### ISSUE TITLE
When using Triton with Pin, is every executed instruction automatically "processed"?

### ISSUE THREAD

**Issue by gitttt** [JonathanSalwan/Triton#271]
I am not sure how the integration of PIN is working. In several examples, which were not using PIN, I noticed that every instruction has to 'processed', i.e. the function `processing(inst)` has to be called. This is aligned with the documentation:

> `processing(Instruction inst)`
> The main function. This function processes everything (engine, IR, optimization, state, ...) from a given instruction.

On the other hand, Triton/src/tools/code_coverage.py is using PIN. Yet, in the code, I could not find a call to `processing(inst)`. Am I right to assume that the processing  (engine, IR, optimization, state, ...) is done automatically? Or is it only done when defining a callback of type CALLBACK.BEFORE?

It could be, as the doc says:
> `CALLBACK.BEFORE`
> Defines a callback before the instruction processing. **At this point, the IR and data flow were been setup.** This callback receives the class as argument.

Thanks for the clarification!

PS: I took a look at https://github.com/JonathanSalwan/Triton/blob/master/src/examples/pin/ir.py and this supports my understanding that an instruction is automatically processed.

**Comment by JonathanSalwan** [comment]
Hey,

If you use the libTriton's API you must use the `processing()` function. If you use the Triton's pintool, the `processing()` function is done directly by the pintool (outside the python env). Take a look [here](https://github.com/JonathanSalwan/Triton/blob/243bc9043b2cca5a18a3b73fab2b7b6adb91f899/src/tracer/pin/main.cpp#L571) and [here](https://github.com/JonathanSalwan/Triton/blob/243bc9043b2cca5a18a3b73fab2b7b6adb91f899/src/tracer/pin/main.cpp#L590).

Note: `processing()` is an alias on `disassembly()` and `buildSemantics()`.

**Comment by gitttt** [comment]
I see. Thanks!
