### ISSUE TITLE
setLastMemoryValue - why last? Difference to inst.updateContext(Memory(...)) ?

### ISSUE THREAD

**Issue by gitttt** [JonathanSalwan/Triton#280]
Going through the example in `src/examples/python/symbolic_emulation_crackme_xor.py`, I noticed the two functions `setLastMemoryValue()` and `setLastRegisterValue(Register(...))`

Why the "last" in the name?

What is the difference to `inst.updateContext(Memory(...))`, e.g. as can be found in the example `src/examples/python/ir.py`

Is it that the first example is about emulation and calls `evaluateAst()` ?

I took a look at the documentation and found:

> setLastMemoryValue(Memory mem)
> Sets the last concrete value of a memory access.

What is meant by 'the last concrete value of a memory access'?
I don't understand either what you mean by 'setting a value of an access'

Thanks for your help!

**Comment by JonathanSalwan** [comment]
Hey,

"Last Memory/Register" means the last known value assigned to this memory cell or register. As libTriton is able to emulate a trace as well as setup a concrete state at specific points, in some cases, it should be good to know if we can trust the current Triton's state. In others words, the last value means the last concrete value which is known to be correct.

> I don't understand either what you mean by 'setting a value of an access'

The current cell memory value.

**Comment by gitttt** [comment]
What is the difference between `inst.updateContext(Memory(...))` and `mem.setConcreteValue()` ?
I tried to find out what the latter is about but I could not figure it out - neither via small code examples nor by looking in the docs. Sorry to ask again ...

**Comment by JonathanSalwan** [comment]
`mem.setConcreteValue()` assigns a concrete value to the `Memory` operand but **don't** synchronizes the Triton's context. 

`inst.updateContext(Memory(...))` assigns a `Memory` operand (with a concrete value) to an instruction. When this instruction will be processed (via `processing()`) the concrete value will be synchronized with the Triton's context.

Note that we also do something like this:

```python
mem = Memory(0x40000, 4)
mem.setConcreteValue(0x41424344)
inst.updateContext(mem)

[...]

processing(inst) # At this point, Triton knows that the address 0x40000 points on the value 0x41424344.
```

**Comment by gitttt** [comment]
Thank you! It is amazing to see how fast you reply. Your work is amazing !

Sent from Outlook Mobile




On Thu, Feb 11, 2016 at 11:53 AM -0800, "Jonathan Salwan" <notifications@github.com> wrote:





`mem.setConcreteValue()` assigns a concrete value to the `Memory` operand but **don't** synchronizes the Triton's context.

`inst.updateContext(Memory(...))` assigns a `Memory` operand (with a concrete value) to an instruction. When this instruction will be processed (via `processing()`) the concrete value will be synchronized with the Triton's context.

Note that we also do something like this:

```python
mem = Memory(0x40000, 4)
mem.setConcreteValue(0x41424344)
inst.updateContext(mem)

[...]

processing(inst) # At this point, Triton knows that the address 0x40000 points on the value 0x41424344.
```

---

**Comment by JonathanSalwan** [comment]
Maybe it's a bit confusing but the `Memory` object is used to represent an operand and not to represent the memory context of Triton.

**Comment by gitttt** [comment]
Ah that is a good hint. I was a bit puzzled by that.

**Comment by JonathanSalwan** [comment]
:).

`Memory`, `Register` and `Immediate` are used to represent all kinds of instruction operands.
