### ISSUE TITLE
[Help wanted] Weird behavior in taint & symbolic engine

### ISSUE THREAD

**Issue by bruce30262** [JonathanSalwan/Triton#286]
Hi, I found some weird behavior in the taint & symbolic engine, I'll try to explain it as clearly as possible (my English isn't very good)  
Here's some part of my Triton script:  
```python
from triton  import *
from smt2lib import *
from pintool import *  

# some other code.....
  
def csym(instruction):

    if instruction.getAddress() == 0x4006f0: # mov rax, qword ptr [rax*8 + 0x601080]
        raxId = getSymbolicRegisterId(REG.RAX)
        raxExpr = getFullAstFromId(raxId)
        print "rax expr:", raxExpr
        return  

def cafter(instruction):
    print
    print hex(instruction.getAddress()), instruction.getDisassembly()

    for se in instruction.getSymbolicExpressions():
        if se.isTainted() == True:
            print '\t -> %s%s%s' %(GREEN, se, ENDC)
        else:
            print '\t -> %s' %(se)

    if instruction.getAddress() == 0x4006f0: # mov rax, qword ptr [rax*8 + 0x601080]
        raxId = getSymbolicRegisterId(REG.RAX)
        raxExpr = getFullAstFromId(raxId)
        print "rax expr (cafter):", raxExpr
        sys.exit(0)

    if instruction.getAddress() == 0x4007e7: # where call scanf("%d", &id) occurs, this will run first
        rsi = getCurrentRegisterValue(REG.RSI) 

        s = convertMemoryToSymbolicVariable(Memory(rsi, CPUSIZE.REG)) 
        taintMemory(rsi)
                                                                     
        print "New symbolic variable:"                                                        
        print "[+] Concrete value: 0x%x" % (s.getConcreteValue())                             
        print "[+] Address: 0x%x" % (s.getKindValue())                                        
        print "[+] id: %d" % (s.getId())                                                      
        print "[+] name: %s" % (s.getName())   
        return
   return
```

my testing binary will call `scanf("%d", &id)` first, then call `delete(id)`  
`delete()` is a function written by me, which contains the following code blocks:  
![][1]  
  
What I did was taint & symbolize the memory address `&id` after executing `scanf("%d", &id)`.  
I expect when it ran to `mov rax, qword ptr [rax*8 + 0x601080]`, `rax`'s symbolic expression will contains the symbolic variable, and the expression will be tainted.  
But in fact I got a different result:  
```
0x4006ebL mov eax, dword ptr [rbp - 4]
   (GREEN)-> #506 = ((_ zero_extend 32) (concat ((_ extract 7 0) #486) ((_ extract 7 0) #487) ((_ extract 7 0) #488) ((_ extract 7 0) #489))) ; MOV operation
          -> #507 = (_ bv4196078 64) ; Program Counter

0x4006eeL cdqe 
   (GREEN)-> #508 = ((_ sign_extend 32) ((_ extract 31 0) ((_ extract 63 0) #506))) ; CDQE operation
          -> #509 = (_ bv4196080 64) ; Program Counter
		 
rax expr (csym): ((_ sign_extend 32) ((_ extract 31 0) ((_ extract 63 0) ((_ zero_extend 32) (concat ((_ extract 7 0) ((_ extract 31 24) ((_ extract 31 0) ((_ zero_extend 32) ((_ extract 31 0) ((_ zero_ext
end 32) (concat ((_ extract 7 0) ((_ extract 31 24) SymVar_0)) ((_ extract 7 0) ((_ extract 23 16) SymVar_0)) ((_ extract 7 0) ((_ extract 15 8) SymVar_0)) ((_ extract 7 0) ((_ extract 7 0) SymVar_0)))))))
)) ((_ extract 7 0) ((_ extract 23 16) ((_ extract 31 0) ((_ zero_extend 32) ((_ extract 31 0) ((_ zero_extend 32) (concat ((_ extract 7 0) ((_ extract 31 24) SymVar_0)) ((_ extract 7 0) ((_ extract 23 16)
 SymVar_0)) ((_ extract 7 0) ((_ extract 15 8) SymVar_0)) ((_ extract 7 0) ((_ extract 7 0) SymVar_0))))))))) ((_ extract 7 0) ((_ extract 15 8) ((_ extract 31 0) ((_ zero_extend 32) ((_ extract 31 0) ((_ 
zero_extend 32) (concat ((_ extract 7 0) ((_ extract 31 24) SymVar_0)) ((_ extract 7 0) ((_ extract 23 16) SymVar_0)) ((_ extract 7 0) ((_ extract 15 8) SymVar_0)) ((_ extract 7 0) ((_ extract 7 0) SymVar_
0))))))))) ((_ extract 7 0) ((_ extract 7 0) ((_ extract 31 0) ((_ zero_extend 32) ((_ extract 31 0) ((_ zero_extend 32) (concat ((_ extract 7 0) ((_ extract 31 24) SymVar_0)) ((_ extract 7 0) ((_ extract 
23 16) SymVar_0)) ((_ extract 7 0) ((_ extract 15 8) SymVar_0)) ((_ extract 7 0) ((_ extract 7 0) SymVar_0))))))))))))))

0x4006f0L mov rax, qword ptr [rax*8 + 0x601080]
         ( NOT GREEN )-> #510 = (concat ((_ extract 7 0) #290) ((_ extract 7 0) #291) ((_ extract 7 0) #292) ((_ extract 7 0) #293) ((_ extract 7 0) #294) ((_ extract 7 0) #295) ((_ extract 7 0) #296) ((_ extract 7 0) 
#297)) ; MOV operation 
         -> #511 = (_ bv4196088 64) ; Program Counter  

rax expr (cafter): ( Long expression and did not contain symbolic variable )
```  

As you can see, everything works fine until it ran to the instruction `mov rax, qword ptr [rax*8 + 0x601080]`.`#510` isn't a "green expression", and it  did not  contain symbolic variable. I expect the expression will be tainted, and it will contain `#508`, but it contain `#290 ~ #297` instead.  
Here's the expression of `#290 ~ #297`:  
```  
0x4006c4L mov qword ptr [rax*8 + 0x601080], rdx
         -> #290 = ((_ extract 63 56) ((_ extract 63 0) #288)) ; byte reference - MOV operation
         -> #291 = ((_ extract 55 48) ((_ extract 63 0) #288)) ; byte reference - MOV operation
         -> #292 = ((_ extract 47 40) ((_ extract 63 0) #288)) ; byte reference - MOV operation
         -> #293 = ((_ extract 39 32) ((_ extract 63 0) #288)) ; byte reference - MOV operation
         -> #294 = ((_ extract 31 24) ((_ extract 63 0) #288)) ; byte reference - MOV operation
         -> #295 = ((_ extract 23 16) ((_ extract 63 0) #288)) ; byte reference - MOV operation
         -> #296 = ((_ extract 15 8) ((_ extract 63 0) #288)) ; byte reference - MOV operation
         -> #297 = ((_ extract 7 0) ((_ extract 63 0) #288)) ; byte reference - MOV operation
         -> #299 = (_ bv4196044 64) ; Program Counter
```  
It seems that Triton somehow "ignore" the `#508` expression.  
I don't know why it behave like this, is it a bug or a feature of Triton ?  
 
Please email me ( bruce30262[at]gmail.com ) if you need the whole Triton script & testing binary  
Thanks

[1]: http://i.imgur.com/pFAF7CC.png

**Comment by JonathanSalwan** [comment]
Hey,

Everything seems good for me.

When the `mov rax, qword ptr [rax*8 + 0x601080]` instruction occurs, `RAX` must contain the **content ** of the memory access, which is, as you said, related to `mov qword ptr [rax*8 + 0x601080], rdx`.

About the tainting, at `0x4006f0L mov rax, qword ptr [rax*8 + 0x601080]`, it's normal that the `RAX` destination (first operand) is not tainted if the **content** of the memory access is not tainted.

That's not because the `RAX` base register (second operand) is tainted that the taint is spread into the first operand. However, if the instruction was a `LEA` instead of a `MOV`, your destination register (`RAX`) would been tainted (due to the `LEA` semantics).

Let me know if it's still not clear :)

**Comment by JonathanSalwan** [comment]
**PS**: If, you want find vulnerabilities like '{write, read}-what-where', you should check if operands are `OPERAND.MEM` and if the index or base register are tainted :).

**Comment by bruce30262** [comment]
Thanks for the explanation, I think I understand most of it.  
So after the line `mov rax, qword ptr [rax*8 + 0x601080]`, the reason why `rax`'s expression did not contain symbolic variable is because the **content** of the memory access did not contain symbolic variable (correct me if I misunderstand) .  This confuse me. If the memory address `mem` contains symbolic variable, why does that not make the content of `mem` ( = `[mem]`) contains symbolic variable ?  
In my view ( I'm not familiar with symbolic execution though ) , `[mem]` change whenever `mem` itself change, so I think there are some kind of "relationship" between `mem` and `[mem]` ? Can't we do something like:  
```
0x4006eb  mov rax, SymVar_0
     #1 = SymVar_0 

0x4006ee  mov rax, [rax]
     #2 = extract_value(SymVar_0)   <--  now #2 contain SymVar_0  
```    
?

**Comment by JonathanSalwan** [comment]
> [mem] change whenever mem itself change, so I think there are some kind of "relationship" between mem and [mem] ?

Nop, we must keep the difference between a content (`[mem]`) and a containing (`mem`) and this is not because `mem` is symbolic that we can access to the whole memory. That's why create a new symbolic variable is probably not a good solution.

> Can't we do something like:

Yes, you can deal with [1] but you have to check that the base register is symbolic.

```
[1]
rax = getCurrentRegisterValue(REG.RAX)
symVar = convertMemoryToSymbolicVariable(Memory(rax, REG.RAX.getSize()))
```

**Comment by JonathanSalwan** [comment]
PS: Triton doesn't support the Array Theory as symbolic expression yet. That's why what you asked is not trivial to resolve =/

**Comment by bruce30262** [comment]
Thanks for the reply, that clears things up quite a bit. Guess I'll have to deal with array's symbolic expression by myself then :p . Issue closed !
