### ISSUE TITLE
Pseudo Code

### ISSUE THREAD

**Issue by JonathanSalwan** [JonathanSalwan/Triton#287]

**Comment by illera88** [comment]
What is this issue?

**Comment by JonathanSalwan** [comment]
With @romainthomas we are trying to reconstruct the control flow of functions based on several traces. This restructuring should be *pretty printed* via an human readable language (pseudo code). That's why we have started to push the [Python representation](http://triton.quarkslab.com/documentation/doxygen/py_ast_page.html#ast_smt_python_page) of the Triton's AST (#282).

As the reconstruction of CFG/DFG are not a trivial tasks, we don't know when this feature will be closed. Currently, it's just a idea which is in a corner of our mind :).
