### ISSUE TITLE
isSymbolized and PC optimization

### ISSUE THREAD

**Issue by JonathanSalwan** [JonathanSalwan/Triton#297]
Add a flag to specify the tracking of uncontrollable branches.

**Comment by JonathanSalwan** [comment]
New optimization

* **PC_TRACKING_SYMBOLIC**<br>
Enabled, Triton will track path constraints only if they are symbolized. This optimization is enabled by default.

**Comment by 0ca** [comment]
This is a very useful optimization ;)
