### ISSUE TITLE
Functions to symbolize inputs

### ISSUE THREAD

**Issue by JonathanSalwan** [JonathanSalwan/Triton#303]
- **symbolizeRead(string filename, integer size=unlimited)**
- **symbolizeRead(integer fd, integer size=unlimited)**
- **symbolizeRecv(integer socket_port, integer size=unlimited)**
- **symbolizeArgv(integer index, integer size=unlimited)**
- **symbolizeEnvironmentVariable(string varname, integer size=unlimited)**

These functions help the user to avoid to do this kind of stuffs:

``` python
if instruction.getAddress() == XXX:
    convertXXXToSymbolicVariable(...)
```

**Comment by illera88** [comment]
This will be very useful!!

**Comment by JonathanSalwan** [comment]
Currently out of philosophy.
