### ISSUE TITLE
Symbolic Bound Memory Access

### ISSUE THREAD

**Issue by JonathanSalwan** [JonathanSalwan/Triton#305]
The memory concretization of the following instruction gives an unique address and an unique value.

```mov rax, [base+symvar*scale+disp]```

Should be useful to implement a function which returns the set/interval of possible `LOAD` addresses according to the condition of the symbolic variable (`symvar`).

**Comment by 0ca** [comment]
Hi, 

How did you fix this? Reading the commit I don't understand how this was solved.

I see that you are assigning an expression to a memory operand using the base, index, scale, etc..
 
And I realize that this function:  getLeaAst() returns you the expression for the index.

But still I can't get the bound of this index. I guess that I should use the solver to get possible solutions for that index, right?

Thank you very much!

**Comment by JonathanSalwan** [comment]
> But still I can't get the bound of this index. I guess that I should use the solver to get possible solutions for that index, right?

Yes. Something like this:

```python
from z3 import *

# Given formula F, find the model the maximizes the value of X
# using at-most M iterations.
def max(F, X, M):
    s = Solver()
    s.add(F)
    last_model = None
    i = 0
    while True:
        r = s.check()
        if r == unsat:
            if last_model != None:
                return last_model
            else:
                return unsat
        if r == unknown:
            raise Z3Exception("failed")
        last_model = s.model()
        s.add(X > last_model[X])
        i = i + 1
        if (i > M):
            raise Z3Exception("maximum not found, maximum number of iterations was reached")

x, y = Ints('x y')
F = [x > 0, x < 10]
print max(F, x, 10000)
```

From [stackoverflow](http://stackoverflow.com/a/11936760)
