### ISSUE TITLE
Unsupported x86 instructions

### ISSUE THREAD

**Issue by 0ca** [JonathanSalwan/Triton#308]
Hi, 

I was doing a test with a windows executable and I detected these unsupported instructions not generating any SE:
```C
lock btr dword ptr [eax],0
lock btr dword ptr [edx],0
lock bts dword ptr [eax],0
lock cmpxchg8b qword ptr [ebp]
repne scasd eax, dword ptr es:[edi]
rep stosd dword ptr es:[edi], eax
stosd dword ptr es:[edi],eax
stosw word ptr es:[edi], ax
```
It is not a big deal, all of these instruction where found in ntdll.dll.

If you need opcodes or more information, tell me.

**Comment by JonathanSalwan** [comment]
Hey,

Indeed, these semantics are not supported yet. A full list of supported semantics can be found [here](http://triton.quarkslab.com/documentation/doxygen/SMT_Semantics_Supported_page.html).
