### ISSUE TITLE
Using the taint engine without symbolic execution

### ISSUE THREAD

**Issue by ilovepjs** [JonathanSalwan/Triton#321]
I'm using Triton for the taint engine but right now just running tracing instructions seems to take forever. I'm wondering if it's running slowly because it's doing symbolic execution at the same time or if it's because Pin is slow or something else I'm not aware of. 

This is the command I'm running:
   
     time ./triton src/examples/pin/ir.py /usr/bin/gpg --encrypt --recipient Derp foo.txt

Should I be expecting run times of ~5 mins?

**Comment by JonathanSalwan** [comment]
It's running slowly because of the instrumentation (Pin). You can limit the instrumentation by giving range analysis or module whitelists.

> Should I be expecting run times of ~5 mins?

For a full trace of gpg, I think you have to wait more than 5 minutes.

**Comment by ilovepjs** [comment]
I was getting times of around 20 seconds with taintgrind. 

I assumed pin would be similar, but I guess that settles it :)

**Comment by JonathanSalwan** [comment]
Yep, Triton is not really optimized to perform only tainting :).
