### ISSUE TITLE
Instruction.setOpcodes() broken?

### ISSUE THREAD

**Issue by gitttt** [JonathanSalwan/Triton#323]
With a freshly cloned and built Triton I get
```
setArchitecture(ARCH.X86_64)
inst = Instruction()
inst.setOpcodes('\x48\x01\xd0')
inst.setAddress(0x1234)
print inst
1234: 
inst
1234: 
```

The doc is also not clear, does setOpcodes() require a length parameter or not?

> setOpcodes(bytes opcodes, integer size)
Sets the opcodes of the instruction.

**Comment by JonathanSalwan** [comment]
Thanks about the doc (it's fixed). After setting opcodes you must process the disass /\and engines.

```python
>>> setArchitecture(ARCH.X86_64)
>>> inst = Instruction()
>>> inst.setOpcodes('\x48\x01\xd0')
>>> inst.setAddress(0x1234)
>>> processing(inst)
>>> print inst
1234: add rax, rdx
```

**Comment by gitttt** [comment]
Oh, kind of a dumb question, sorry. At least the doc part was not so stupid :- )

**Comment by JonathanSalwan** [comment]
None question is stupid :)

**Comment by gitttt** [comment]
Thanks for cheering me up :- )
