### ISSUE TITLE
References and SMT-LIB v2 SSA form

### ISSUE THREAD

**Issue by apach301** [JonathanSalwan/Triton#327]
For instructions, operating with memory, some symbolic references generated wrong (missing counter and determination).
Example:
> 4004f1: mov dword ptr [rbp - 0x14], edi
ref!13 = ((_ extract 31 24) (_ bv1 32)) ; byte reference - MOV operation
ref!14 = ((_ extract 23 16) (_ bv1 32)) ; byte reference - MOV operation
ref!15 = ((_ extract 15 8) (_ bv1 32)) ; byte reference - MOV operation
ref!16 = ((_ extract 7 0) (_ bv1 32)) ; byte reference - MOV operation
ref!18 = (_ bv4195572 64) ; Program Counter
> 

[trace.txt](https://github.com/JonathanSalwan/Triton/files/197272/trace.txt)
[code.txt](https://github.com/JonathanSalwan/Triton/files/197278/code.txt)

**Comment by JonathanSalwan** [comment]
Are you talking about the `ref!17`? If yes, it's not a bug, this reference (17) really exist but it's not linked with the instruction. This reference is used for several internal stuffs. Basically, this reference is the concatenation of references 13, 14, 15 and 16.

**Comment by apach301** [comment]
The lack of `ref!17` don't causes errors when solving expression in SMT solver, because there is no any reference linked with `ref!17`. But in some cases it happens (example.txt): `ref!40`..`ref!45` linked with `ref!39`, which don't determined.
[example.txt](https://github.com/JonathanSalwan/Triton/files/197358/example.txt)

**Comment by JonathanSalwan** [comment]
Ok I see your point, as I said, `ref!17` like `ref!39` exist but are not linked with the instruction. I agree with you that if you try to reconstruct the SSA with your eyes that's not really possible because your `ref!39` is not printed but that's doesn't mean that the Triton's SSA doesn't work :)

If you call `getSymbolicExpressionFromId(17)` and `getSymbolicExpressionFromId(39)` at the end of the execution, you will see that these references really exist.

This behavior occurs only when the instruction contains a memory access and the semantics look like this:

- byte ref expression (linked with the instruction)
- [...]
- byte ref expression (linked with the instruction)
- concatenation of byte ref expression (**not linked** with the instruction, used for internal stuffs)
- flags expression if exist (linked with the instruction)
- control flow expression (linked with the instruction)

At the beginning, expressions like `ref!17` and `ref!39` were linked with the instruction but we decided to remove them for a reason that I forgot :). I think it was because that's make no sense to add the concatenation expression into the semantics list of the instruction.

**Comment by enzet** [comment]
I've reproduced this issue with the last version of Triton.

Here you can see that we have link to `ref!935` from the second line but it's undefined.

```lisp
ref!934 = ((_ extract 7 0) (bvadd (concat ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract       7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8))) (_ bv1 64))) ; byte reference - ADD operation
ref!936 = (ite (= (_ bv16 64) (bvand (_ bv16 64) (bvxor ((_ extract 63 0) ref!935) (bvxor (concat ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0      ) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8))) (_ bv1 64))))) (_ bv1 1) (_ bv0 1)) ; Adjust flag
```

So, Z3 fails to solve the trace if I convert it to SMT-LIB 2:

```
(error "line 3051 column 80: unknown constant ref_935")
```

**Comment by JonathanSalwan** [comment]
> So, Z3 fails to solve the trace if I convert it to SMT-LIB 2:

I'm curious to see how you send it to z3?

**Comment by enzet** [comment]
I've converted this trace to SMT-LIB 2:

```lisp
(declare-fun x934 () (_ BitVec 8))                                              
(assert (= x934 ((_ extract 7 0) (bvadd (concat ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7     0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8))) (_ bv1 64)))))
(declare-fun x936 () (_ BitVec 1))                                              
(assert (= x936 (ite (= (_ bv16 64) (bvand (_ bv16 64) (bvxor ((_ extract 63 0) x935) (bvxor (concat ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0)     (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8))) (_ bv1 64))))) (_ bv1 1) (_ bv0 1))))
```

**Comment by JonathanSalwan** [comment]
Ok I see, that's why it doesn't work. As @apach301 you try to reconstruct the SSA with your eyes.

Use: `getFullAstFromId(936)` if you want the complete AST of an expression.

**Comment by JonathanSalwan** [comment]
As I can see this legit behavior troubles some people. So, I will thinking about link the concatenation expression into the semantics list of the instruction. Just, let me few days to thinking about it.

**Comment by enzet** [comment]
OK, I see, `getFullAstFromId()` works well. But using this function I get too huge trace even for pretty simple program.

There is very simple fix I found for this issue. There was line

```
inst.addSymbolicExpression(se);
```

in the end of `SymbolicEngine::createSymbolicMemoryExpression()` function just before `return se;`. But now there is no one. If I add this line, all work well. Should I create pull request for this small patch?

**Comment by JonathanSalwan** [comment]
I know that my English is not really good but just before your first comment, I tried to explain that this feature existed some time ago and we removed it. Check the commit 66b005c21909dc87119ef28aea4cf0e49b290377

 As I said, let me few days to thinking if yes or no we want to add this feature again :)

**Comment by enzet** [comment]
OK, sorry, I just found this commit.

**Comment by JonathanSalwan** [comment]
Hehe don't worry =). However, you can send the PR which add the `inst.addSymbolicExpression(se);`. I will probably accept this PR tomorrow or this night, I have to check few things before =)
