### ISSUE TITLE
undefined symbol: Z3_solver_inc_ref

### ISSUE THREAD

**Issue by hulinghuan** [JonathanSalwan/Triton#347]
Hi everyone,

I got a dynamic library error when I try to execute
`./triton ./src/examples/pin/ir.py /usr/bin/id`
after I make the Pin. (no warning when I make Pin, and I am using Debian 8 Debian 8 Jessie)

The error is shown as follow:
E: Unable to load /home/linghuan/Tools/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton/build/libpintool.so: /home/linghuan/Tools/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton/build/libtriton.so: undefined symbol: Z3_solver_inc_ref

And here is what I got from ldd:
```
ldd build/libpintool.so 
	linux-vdso.so.1 (0x00007ffd4ebe8000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fee54aa0000)
	libtriton.so => /home/linghuan/Tools/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton/build/libtriton.so (0x00007fee54700000)
	libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007fee5417b000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fee53e70000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fee53b6f000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fee53959000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fee535ae000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fee557ea000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fee53393000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fee53176000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fee52f73000)

 % ldd build/libtriton.so
	linux-vdso.so.1 (0x00007ffdbdbdb000)
	libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007f19227a2000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1922497000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1922196000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f1921f80000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1921bd5000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f19219ba000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f192179d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1921599000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f1921396000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f19230c7000)
```

I think this problem might be very similar to this problem but I still have no idea how should I solve it and where the problem is.
https://github.com/JonathanSalwan/Triton/issues/276

Any helps are really appreciated!

Leon

**Comment by JonathanSalwan** [comment]
Hey Leon,

> I think this problem might be very similar to this problem but I still have no
> idea how should I solve it and where the problem is #276.

I'm pretty sure your problem is not related to this issue. #276 was related to the DBI internal processing.

`Z3_solver_inc_ref` comes from the Z3 library and it seems that the problem is that Z3 is not linked to your libtriton.so (according to your ldd).

Check mine: 

```
$ ldd build/libtriton.so
Password: 
        [...]
        libpython2.7.so.1.0 => /usr/lib64/libpython2.7.so.1.0 (0x00007f384c49c000)
        libz3.so => /usr/lib64/libz3.so (0x00007f384b099000)
        libcapstone.so.3 => /usr/lib64/libcapstone.so.3 (0x00007f384abe2000)
        [...]
```

Then, It also seems that `capstone` is not linked to your library. Did you installed capstone and z3 correctly ? Can you show me your install process ?

Cheers,

**Comment by hulinghuan** [comment]
Hi Jonathan,

You are right. The problem is the installation of z3 and capstone.
I reinstalled both of them, and pin works now.
(have no idea how I messed up the installation)

Thank you very much!

Leon

**Comment by JonathanSalwan** [comment]
> Thank you very much!

You're welcome :)
