### ISSUE TITLE
Unable to load pin/source/tools/Triton/build/libpintool.so

### ISSUE THREAD

**Issue by awanish-pandey** [JonathanSalwan/Triton#349]
Hi Everyone,

I installed Triton inside pin-2.14-71313-gcc.4.4.7-linux/source/tools without any error but when I run "./triton ./src/examples/pin/ir.py /usr/bin/id" it gives unable to load libpintool.so.

ldd build/libtriton.so 
	linux-vdso.so.1 =>  (0x00007fff8e7f4000)
	libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007f8b5de9a000)
	libz3.so => /usr/lib/libz3.so (0x00007f8b5cc73000)
	libcapstone.so.3 => /usr/lib/libcapstone.so.3 (0x00007f8b5c7be000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8b5c4ba000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8b5c2a4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8b5bedf000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8b5bcc1000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f8b5baa8000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8b5b8a4000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f8b5b6a1000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8b5b39b000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f8b5b193000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f8b5af84000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8b5e70a000)
Please help me out.

**Comment by JonathanSalwan** [comment]
What is the error output ?

**Comment by awanish-pandey** [comment]
E: Unable to load /home/awanish/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton/build/libpintool.so

**Comment by JonathanSalwan** [comment]
> ldd build/libtriton.so 

Your libtriton looks good. Try this:

```
$ python
>>> from triton import *
>>> setArchitecture(ARCH.X86_64)
>>> dir(REG)
```

It seems it's only related to the pintool. Can you past the ldd output of the libpintool.so?

```
$ ldd libpintool.so
```

**Comment by JonathanSalwan** [comment]
Feel free to reopen it.
