### ISSUE TITLE
RegisterOperand::setup(): You cannot set this concrete value (too big) to this register

### ISSUE THREAD

**Issue by gaa-cifasis** [JonathanSalwan/Triton#352]
Hi,

I recently installed the last revision of Triton (b770777e8f497069e56e6609d076c9c1a55ce41f) with PIN support (2.14-71313-gcc.4.4.7) and i'm getting this error:

    terminate called after throwing an instance of 'std::runtime_error'
      what():  RegisterOperand::setup(): You cannot set this concrete value (too big) to this register.
    C: Tool (or Pin) caused signal 11 at PC 0x7f1c2d5ec177

using all triton examples. A workaround is to disable this check at src/libtriton/arch/registerOperand.cpp:

    if (concreteValue > this->getMaxValue())
      throw std::runtime_error("RegisterOperand::setup(): You cannot set this concrete value (too big) to this register.");

 but i'm not sure which side effects it has. :fearful:

**Comment by JonathanSalwan** [comment]
Hey,

I've heard about this bug but I've never managed to trigger it  (I tried on several different OS) =(. If you can give me more information like, OS, gcc version, libc version, architecture, etc (a VM will be awesome). 

However, I recommend the following temporary patch which skips the test and keep a good behavior related to internal processing.

```patch
diff --git a/src/libtriton/arch/registerOperand.cpp b/src/libtriton/arch/registerOperand.cpp
index 2d33289..df60aeb 100644
--- a/src/libtriton/arch/registerOperand.cpp
+++ b/src/libtriton/arch/registerOperand.cpp
@@ -57,10 +57,10 @@ namespace triton {
       this->setHigh(std::get<1>(regInfo));
       this->setLow(std::get<2>(regInfo));
 
-      if (concreteValue > this->getMaxValue())
-        throw std::runtime_error("RegisterOperand::setup(): You cannot set this concrete value (too big) to this register.");
+      //if (concreteValue > this->getMaxValue())
+      //  throw std::runtime_error("RegisterOperand::setup(): You cannot set this concrete value (too big) to this register.");
 
-      this->concreteValue = concreteValue;
+      this->concreteValue = concreteValue & this->getMaxValue();
     }
```

**Comment by gaa-cifasis** [comment]
You can try to reproduce it using this Vagrant file: https://atlas.hashicorp.com/ubuntu/boxes/trusty64 (of course, you need to install triton, but that should only take a few minutes). I'm always using Vagrant to manage my VM so maybe it is related?

I will try your patch and let you know if i have more issues related. 

Thanks!

**Comment by JonathanSalwan** [comment]
Maybe if you can put a breakpoint into the `throw std::runtime_error` and give me the call-trace, I can try to fix the bug blindly.

**Comment by gitttt** [comment]
I updated to the most recent version today. This code throws a similar error now:

`inst.updateContext(Register(REG.RAX,    regs['rax']))`

> TypeError: RegisterOperand::setup(): You cannot set this concrete value (too big) to this register.

The value of `regs['rax']` is `-1`. Its type is `int`
It is a Ubuntu 14.04, gcc --version says:

> gcc (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4

**Comment by JonathanSalwan** [comment]
Actually, internal integer into the libTriton are 512-bits based. When you define a register or a memory cell with the value -1, it's minus 1 but on 512-bits and it's too big for `RAX` which must be -1 on 64-bits.

Indeed, it's sometime boring to define `0xffffffffffffffff`instead of -1. I will fix it.
