### ISSUE TITLE
AST_DICTIONARIES optimization can cause AST nodes with broken parents

### ISSUE THREAD

**Issue by mermakov** [JonathanSalwan/Triton#353]
Hello!

I'm currently doing some work with Triton C++ API and its use in DBI frameworks. We introduce taint by catching file-related syscalls (open and read in particular). For every read we extract destination buffer and num of bytes written and call the following functions for every individual byte:

`api.taintMemory(<addr>);`
`api.converyMemoryToSymbolicVariable(MemoryOperand(<addr>,1));`
`id = api.getSymbolicMemoryId(<addr>);`
`//extra work on id`

This worked on Pin well for our purposed but now we are moving to DynamoRIO and some tests are crashing when AST_DICTIONARIES is enabled (we use it to slow the memory usage). Unfortunately, I'm not able to debug this well since I cannot reproduce it with DynamoRIO debugging options enabled.

From what I can see from debug print, the AST_DICTIONARIES flag causes some AST nodes to be deleted right after construction leaving their children with broken pointers.

In particular, an ExtractNode is initialized with ReferenceNode as its child and is immediately deleted. Later, initialization is called for this ReferenceNode (seemingly as part of the `init()` chain caused by this [line] (https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/engines/symbolic/symbolicEngine.cpp#L515) ) and the application crashes while trying to call `init()` for its parent node.

Perhaps some additional work with AST children is required in `browseAstDictionaries()` to avoid that?

Sorry for an issue without a backtrace or anything more detailed, but I hope this might help.

**Comment by JonathanSalwan** [comment]
Hey,

> In particular, an ExtractNode is initialized with ReferenceNode as its child and is immediately deleted. 

Why it's immediately deleted? Using `AST_DICTIONARIES` no node must/should be deleted.

> Perhaps some additional work with AST children is required in browseAstDictionaries() to avoid that?

Theoretically no

**Comment by JonathanSalwan** [comment]
> In particular, an ExtractNode is initialized with ReferenceNode as its child and is immediately deleted.

To determine the root cause you must know why some `triton::ast::AbstractNode` were been deleted.

**Comment by mermakov** [comment]
My understanding is following:

We have this [call] (https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/ast/ast.cpp#L3475), which creates an ExtractNode. Its constructor calls `init()` where it sets itself as parent for child nodes.

The created node is given to `recordAstNode` which redirects to `browseAstDictionaries`. There it triggers this [line] (https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/ast/astDictionaries.cpp#L295) since the dictionary already contains the node. Thus, the newly created Node is deleted.

I have added debug print for `this` as `unsigned long` in ExtractNode construction, `init` function and `browseAstDictionaries` on `delete node`. They report the same pointer which is later accessed [here] (https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/ast/ast.cpp#L2798).

Perhaps its a hash issue and not AST_DICTIONARIES problem?

**Comment by JonathanSalwan** [comment]
> I have added debug print for this as unsigned long in ExtractNode construction,
> init function and browseAstDictionaries on delete node. They report the same
> pointer which is later accessed here.

Mmmh, interesting. Let me think about it. This is very strange because, technically if a node is already present into the `AST_DICTIONARIES` the deleted node is never used.

```cpp
if (dictionary->find(value) != dictionary->end()) {
  delete node;
  return (*dictionary)[value]; // return an available node
}
```

> Perhaps its a hash issue and not AST_DICTIONARIES problem?

Nop, hashs are not used for `AST_DICTIONARIES`.

Is it working well with Pin even with `AST_DICTIONARIES`? Are you using some threads stuff in your  DR tool? Maybe there are some concurrent access to the `triton::ast::*()` API?

**Comment by JonathanSalwan** [comment]
Can you also test without using `converyMemoryToSymbolicVariable()`?

**Comment by mermakov** [comment]
> Is it working well with Pin even with AST_DICTIONARIES?

Yes, the Pin tool is working well.

>Are you using some threads stuff in your DR tool? Maybe there are some concurrent access to the triton::ast::*() API?

I don't think that concurrence is an issue, all blocks that work with Triton API are protected by a single mutex.

> Can you also test without using converyMemoryToSymbolicVariable()?

It works properly without it. However, we need it to cover cases where our event interceptors are the first to work with the memory block.

**Comment by JonathanSalwan** [comment]
> However, we need it to cover cases where our event interceptors are the first to work with the memory block.

Yes but maybe the _issue_ may come from [here](https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/engines/symbolic/symbolicEngine.cpp#L515).

**Comment by JonathanSalwan** [comment]
It will be awesome if you can simulate and reproduce the bug with the python API to be sure that the bug comes from the libTriton and not from your DR tool. I read the code several time around the nodes and the AST management but I have not seen a potential root cause =/

**Comment by mermakov** [comment]
Ok, you were right, it turned out to be an issue within our DR implementation. We are trying to replicate the Pin implementation, but it turns out I forgot to add `Instruction::reset()` as a post-instruction instrumentation. I guess it was picking up old memory accesses and doing something wrong with them.

Sorry for taking your time.

**Comment by JonathanSalwan** [comment]
No problem. It's still interesting to get feedback maybe I should detail a bit more the API documentation. Anyway thanks to you to use libTriton =)
