### ISSUE TITLE
Does taint analysis work on Windows?

### ISSUE THREAD

**Issue by pfsun** [JonathanSalwan/Triton#362]
I wonder whether taint analysis pintool work on windows?  I saw Triton could be installed on Windows (Is it only supported by virtual studio 2015? how about 2013?). Is it taint analysis that can work on Windows? Thanks.

**Comment by JonathanSalwan** [comment]
>  I wonder whether taint analysis pintool work on windows? 

The pintool only works on Linux. However, if you have a windows tracer, you can plug the libTriton to your tracer and perform a taint analysis.

> Is it only supported by virtual studio 2015? how about 2013?

I never tried on VS2013. Dunno if VS2013 support the C++11 correctly...

> Is it taint analysis that can work on Windows? 

libTriton

Cheers,

**Comment by pfsun** [comment]
Thanks. So it is possible to use DynamoRIO  as windows tracer.

**Comment by JonathanSalwan** [comment]
> So it is possible to use DynamoRIO as windows tracer.

Yes for sure.
