### ISSUE TITLE
Compilation for windows problem! - unresolved externs - 

### ISSUE THREAD

**Issue by itspers0n4l** [JonathanSalwan/Triton#363]
Hello Triton team!

I try to compile triton on windows recently. Every thing goes well but I get a lot of  "unresolved external symbol " errors.
I attach these errors.

Best Regards
[errors.txt](https://github.com/JonathanSalwan/Triton/files/391874/errors.txt)

**Comment by JonathanSalwan** [comment]
Hey,

For more information about the compile on Windows you can check out our [AppVeyor](https://ci.appveyor.com/project/JonathanSalwan/triton/build/0.3.1310) compile script. However, if you want, you can directly download our triton.{dll, pyd}, triton.exp and triton.lib below:

* [Windows 32-bits](https://ci.appveyor.com/api/buildjobs/dtr7fvnqd1v1cu11/artifacts/triton.x86.release.7z)
* [Windows 64-bits](https://ci.appveyor.com/api/buildjobs/225hlm98d35btc66/artifacts/triton.x64.release.7z)

**Comment by itspers0n4l** [comment]
Hi ;)

Thank you for fast response!
I got those error again with your AppVeyor compile script. Can you specify these variables or other variables that are necessary?

CAPSTONE_INCLUDE_DIRS
CAPSTONE_LIBRARIES
Z3_INCLUDE_DIRS
Z3_LIBRARIES
BOOST_ROOT

Best

**Comment by JonathanSalwan** [comment]
On VS2015 I only do this and it works great:

```
$ cd build
$ cmake -G "Visual Studio 14 2015 Win64" \
-DBOOST_ROOT="C:/Users/jonathan/Works/Tools/boost_1_61_0" \
-DPYTHON_INCLUDE_DIRS="C:/Python27/include" \
-DPYTHON_LIBRARIES="C:/Python27/libs/python27.lib" \
-DZ3_INCLUDE_DIRS="C:/Users/jonathan/Works/Tools/z3-4.4.1-x64-win/include" \
-DZ3_LIBRARIES="C:/Users/jonathan/Works/Tools/z3-4.4.1-x64-win/bin/libz3.lib" \
-DCAPSTONE_INCLUDE_DIRS="C:/Users/jonathan/Works/Tools/capstone-3.0.4-win64/include" \
-DCAPSTONE_LIBRARIES="C:/Users/jonathan/Works/Tools/capstone-3.0.4-win64/capstone.lib" ..
```

Then I just open the `.sln` and generate the solution without updating any VS options.

**Comment by pfsun** [comment]
Hi, 
I also met the same problem. When I choose build Release, I got a lot of "unresolved external symbol " errors which are same with itspers0n4l. If I keep build Debug (no updating any VS option), I met one Link error: LNK1104 cannot open file 'python27_d.lib'. Do you have any suggestion?

Best

**Comment by JonathanSalwan** [comment]
I have no idea, I'm clearly not an expert on Windows. It's @0vercl0k the VS guru :). @0vercl0k are you familiar with these issues?

**Comment by illera88** [comment]
The "_d" indicates it's a debug library, so you'll want that one for your Debug configuration, and the one without the "_d" (probably) for your release configuration.

In release mode go to Configuration Properties -> Linker -> Input-> and check that the python .lib that you are including is actually python.lib and not python_d.lib. 

You can try this too:
```C
#ifdef _DEBUG
  #undef _DEBUG
  #include <Python.h>
  #define _DEBUG
#else
  #include <Python.h>
#endif
```
Good luck!

**Comment by 0vercl0k** [comment]
Interesting - I'm not really sure what's going on; it sounds you are
linking against libcpmtd.lib and it looks you have some sort of mixing
release/debug going on.

Have you tried to clean and then rebuild? Maybe VS tried to reuse the .obj
generated for Debug (if you've tried to build Debug first for example) and
gets confused?

Note that you need to have triton linking only against release libraries
(z3/capstone) and not mix everything. Let me know if you get lucky and the
above actually helps >:].

Cheers

2016-08-01 17:17 GMT-07:00 illera88 <notifications@github.com>:

**Comment by JonathanSalwan** [comment]
I close this issue. Please, feel free to reopen it or still write on it.
