### ISSUE TITLE
 No module named pintool

### ISSUE THREAD

**Issue by ucharfli** [JonathanSalwan/Triton#364]
Install.log
http://sprunge.us/NbYf

**Comment by JonathanSalwan** [comment]
>  $ python ./src/examples/pin/blacklist.py

When you use the pintool module, you must use Pin and the Triton loader like this:

```shell
$ ./triton ./src/examples/pin/blacklist.py <your_binary>
```

**Comment by ucharfli** [comment]
Thanks @JonathanSalwan
