### ISSUE TITLE
Is it possible to taint data originating from a file?

### ISSUE THREAD

**Issue by pfsun** [JonathanSalwan/Triton#366]
I wonder whether it is possible to taint data originating from a file? The input it the whole file, but I don't want to taint the whole file, and want to taint only one data from the file. Thanks.

**Comment by JonathanSalwan** [comment]
The highest level inside Triton is an instruction processing. It means that there is (atm) no abstraction about what you're asking. To do this, you must follow specific syscalls or routines like read, open, recv etc...

**Comment by pfsun** [comment]
Got it. Thanks. For Tracer Independent, you mentioned that dumping a trace into a database with all registers state and memory access.  How the database format look like? could you give me one example? thanks
