### ISSUE TITLE
Porting to other architecture

### ISSUE THREAD

**Issue by tjjh89017** [JonathanSalwan/Triton#368]
Is there any plan to port to other arch?

**Comment by JonathanSalwan** [comment]
Not at this moment. We are still focusing on symbolic optimizations to analyze real world programs.

**Comment by tjjh89017** [comment]
Is OPCode Parser designed for x86 only?
Maybe I can try to port to ARM64 architecture.

**Comment by JonathanSalwan** [comment]
To disassemble opcodes we use [capstone](http://capstone-engine.org) and to describe semantics we use our [own representation](http://triton.quarkslab.com/documentation/doxygen/py_ast_page.html). For example, [here](http://triton.quarkslab.com/documentation/doxygen/x86Semantics_8cpp_source.html) is the x86 semantics description (we don't support completely [x86](http://triton.quarkslab.com/documentation/doxygen/SMT_Semantics_Supported_page.html) yet). If you plan to add ARM64, you must describe its semantics from scratch... It's not a trivial task :).

**Comment by tjjh89017** [comment]
Ok.
I can try to do that in my free time.
Thanks a lot.
