### ISSUE TITLE
Triton is dissasembly x86_64 in x86 ?!

### ISSUE THREAD

**Issue by gaa-cifasis** [JonathanSalwan/Triton#378]
Hi,

Triton is failing after compiling it in Ubuntu Trusty (x86):

    $ ./triton ./src/examples/pin/ir.py /usr/bin/id
    ..
    804d18b: call qword ptr [rbx + rdi*4 - 0x100]
    ref!776 = ((_ zero_extend 0) (bvsub ((_ extract 63 0) ref!726) (_ bv8 64))) ; Stack alignment
    ref!777 = ((_ extract 31 24) (_ bv134533522 64)) ; Byte reference - Saved Program Counter
    ref!778 = ((_ extract 23 16) (_ bv134533522 64)) ; Byte reference - Saved Program Counter
    ref!779 = ((_ extract 15 8) (_ bv134533522 64)) ; Byte reference - Saved Program Counter
    ref!780 = ((_ extract 7 0) (_ bv134533522 64)) ; Byte reference - Saved Program Counter
    ref!781 = (concat ((_ extract 31 24) (_ bv134533522 64)) ((_ extract 23 16) (_ bv134533522 64)) ((_ extract 15 8) (_ bv134533522 64)) ((_ extract 7 0) (_ bv13453352264))) ; Temporary concatenation reference - Saved Program Counter
    ref!782 = ((_ zero_extend 32) (concat ((_ extract 7 0) (_ bv8 8)) ((_ extract 7 0) (_ bv4 8)) ((_ extract 7 0) (_ bv159 8)) ((_ extract 7 0) (_ bv144 8)))) ; Program Counter
    
    terminate called after throwing an instance of 'triton::exceptions::Disassembly'
      what():  x8664Cpu::disassembly(): Failed to disassemble the given code.
    C: Tool (or Pin) caused signal 11 at PC 0xb73f4b93
    ./triton: line 20: 20789 Segmentation fault      (core dumped) LD_BIND_NOW=1 $PIN_BIN_PATH -t $PINTOOL_PATH -script $1 -- ${@:2}

It is trying to dissasemble x86 instruction as x86_64?

**Comment by JonathanSalwan** [comment]
You probably have to define the good architecture (`ARCH.X86`) into your python script (`ir.py`).

**Comment by gaa-cifasis** [comment]
Oh, it works. Now i feel like an idiot. 

Thanks Jonathan! (as quick as always!)
