### ISSUE TITLE
How to know the registers or memory is tainting an specific instruction?

### ISSUE THREAD

**Issue by 0ca** [JonathanSalwan/Triton#380]
Hi, 

I am trying to get the operands were tainted when I found a tainted instruction, so I can easily know why the instruction is tainted.

In some cases is trivial:
```
mov eax, ebx
```
`ebx` is the only option, so if the instruction is tainted is because `ebx` was tainted

But when we have an `add` operation:
```
add eax, ebx
```
How could we know which register was tainted? eax? ebx? or both?

I know there is the `getReadRegisters` and `getStoreAccess` API but to use these functions I need to call first `buildSemantics` and by then the tainting is already applied. 

So imagine in the `add` instruction only `ebx` is tainted. After call buildSemantic `eax` and `ebx` are tainted. How could I know `ebx` was the origin of the taint?

Thanks!

**Comment by JonathanSalwan** [comment]
```cpp
#include <iostream>
#include <triton/api.hpp>
#include <triton/x86Specifications.hpp>

using namespace triton;
using namespace triton::arch;


int main(int ac, const char **av) {
  api.setArchitecture(ARCH_X86);

  // Taint origin
  api.taintRegister(TRITON_X86_REG_EBX);

  Instruction inst;
  inst.setOpcodes((unsigned char*)"\x01\xD8", 2); // add eax, ebx

  // Only disassemble the instruction
  api.disassembly(inst);

  std::cout << "Before computation" << std::endl;
  for (auto it = inst.operands.begin(); it != inst.operands.end(); it++) {
    if (api.isTainted(*it))
      std::cout << "  Tainted: " << *it << std::endl;
  }

  // Compute the instruction
  api.buildSemantics(inst);

  std::cout << "After computation" << std::endl;
  for (auto it = inst.operands.begin(); it != inst.operands.end(); it++) {
    if (api.isTainted(*it))
      std::cout << "  Tainted: " << *it << std::endl;
  }

  return 0;
}
```

```console
$ g++ -std=c++11 -ltriton taint.cpp
$ ./a.out
Before computation
  Tainted: ebx:32 bv[31..0]
After computation
  Tainted: eax:32 bv[31..0]
  Tainted: ebx:32 bv[31..0]
```

**Comment by JonathanSalwan** [comment]
> So imagine in the add instruction only ebx is tainted. After call buildSemantic eax and ebx are tainted. How could I know ebx was the origin of the taint? 

Btw, backward tainting is not possible after computing an instruction.

**Comment by 0ca** [comment]
I see I need to do it after the disassemble. Sorry I was confused ;)

**Comment by 0ca** [comment]
Umm, but still I can't do what I was trying.

If I check if the operands are tainted I can't know exactly how an instruction is tainted.

Check the next example. I have the instruction
```
mov eax, ebx
```
Where eax is tainted.

If I check the operands I will have that eax is tainted. But in this instruction `eax` is used to store the result so the instruction is not tainted.

I guess that the solution is first get a list of all the operands tainted. And after `buildSemantics` check `getReadRegisters` and `getStoreAccess` if any of the tainted operands are being used.

Is there any other solution?

**Comment by 0ca** [comment]
And if we have a conditional instruction like:
```
jz xxxx
```
In the operands we don't get the flags.

I don't know if there is a solution. I would love to have these two functions working before builtSemantics:
```
getReadRegisters 
getStoreAccess
```
But I guess that is by design happening during the building semantics phase.

Maybe I am following the incorrect path to solve this. What I want is to know why a instruction is tainted?
You can use this example:
```
;EBX and EDX are tainted at the beginning
mov eax, edx <- edx is tainted (checking the operands we could know it)
mov eax, ebx <- ebx is tainted (checking the operands we would have ebx and eax tainted, but eax is not involved in the tainted)
add eax, ecx <- eax is tainted (checking the operands works)
cmp eax, 2 <-eax is tainted (checking the operands)
jz loc_xxx <- zf is tainted (we should use getReadRegisters after buildSemantics)
```

Thank you for the help!

**Comment by JonathanSalwan** [comment]
> And if we have a conditional instruction like:
> ```
> jz xxxx
> ```
> In the operands we don't get the flags.
> I don't know if there is a solution. I would love to have these two functions working before builtSemantics:
> ``` 
> getReadRegisters 
> getStoreAccess
> ```
> But I guess that is by design happening during the building semantics phase.

You cannot get these information before creating the instruction semantics. Implicit and explicit in/out are part of the semantics not the decoding.

I see what you are trying to do and with the current design it's not possible. I see any sexy way to solve your needs. Actually, why do you want to know this?

**Comment by 0ca** [comment]
The idea is to give more info to the user to know exactly why a instruction is tainted.

**Comment by JonathanSalwan** [comment]
Maybe you should use semantics expressions to get these kinds of information. Taint is used to determine if an instruction is "controllable" only by returning a boolean. Expressions are used to determine the origin of a program point. Maybe the solution of what you are looking for is around of these expressions.
