### ISSUE TITLE
libz3.so not linked to triton.so

### ISSUE THREAD

**Issue by xrwgoogle** [JonathanSalwan/Triton#382]
It looks like libz3.so is not linked to triton.so in both the Docker auto setup or manual build. For example, after building and installing triton, running triton gives out the following exception.

raceback (most recent call last):
  File "/usr/local/google/home/xiaoranwang/Downloads/test.py", line 1, in <module>
    from triton import *
  File "/usr/local/buildtools/current/sitecustomize/sitecustomize.py", line 181, in SetupPathsAndImport
    return real_import(name, globals, locals, fromlist, level)
ImportError: /usr/local/lib/python2.7/dist-packages/triton-0.3-py2.7.egg/triton.so: undefined symbol: Z3_solver_inc_ref

I checked ldd on triton.so, and libz3.so is not linked to it somehow.

The installation of z3 was successful. I can find libz3.so in /usr/lib and z3*.h in /usr/include. 

There was one time I had to manually set Z3_INCLUDE_DIR and Z3_INCLUDE_DIRS to be /usr/include before "cmake ..", but triton build successfully after that. 

Any idea why z3 is not linked to triton.so?

**Comment by JonathanSalwan** [comment]
Your issue looks like this one #347.

> Any idea why z3 is not linked to triton.so?

Nop sorry :(
