### ISSUE TITLE
getReadRegisters for shr instruction returns incorrect registers

### ISSUE THREAD

**Issue by 0ca** [JonathanSalwan/Triton#383]
Hey,

I am using `getReadRegisters` to know which registers are symbolized in one instruction. But with the `shr` instruction I get that the registers `cf of pf sf zf` are read when by my understanding they are not:
http://x86.renejeschke.de/html/file_module_x86_id_285.html

I used this example to probe it:
```
import  sys

from triton import *
from ast    import *

function = {
  0x401000: "\xc1\xe2\x00", #  shl     edx, 0 
}



if __name__ == '__main__':

    # Set the architecture
    setArchitecture(ARCH.X86)

    enableSymbolicEngine(True)

    # Define entry point
    pc = 0x401000

    setConcreteRegisterValue(Register(REG.EDX, 0x1000))

    while pc in function:
        # Build an instruction
        inst = Instruction()

        # Setup opcodes
        inst.setOpcodes(function[pc])

        # Setup Address
        inst.setAddress(pc)

        # Process everything
        processing(inst)

        # Display instruction
        registers = inst.getReadRegisters()
        print registers

        # Next instruction
        pc = buildSymbolicRegister(REG.EIP).evaluate()

    sys.exit(0)
```

I tried to read the semantic for that instruction but I couldn't understand why this is happening.

Is this an expected behavior?
Thanks!

**Comment by JonathanSalwan** [comment]
> I tried to read the semantic for that instruction but I couldn't understand why this is happening.
> Is this an expected behavior?

Yes.

Our goal is to provide the same semantics as the Intel ISA **but** this doesn't mean that we do it in the same way as Intel. In specific cases (mainly when there are undefined behaviours assignment like in `shr`) Triton must reads specific values to provide a good semantics.

If we read the description of affected flags from your link we can read this:

> The CF flag contains the value of the last bit shifted out of the destination operand; it is undefined
> for SHL and SHR instructions where the count is greater than or equal to the size (in bits) of the 
> destination operand. The OF flag is affected only for 1-bit shifts (see "Description" above); 
> otherwise, it is undefined. The SF, ZF, and PF flags are set according to the result. If the count is 0, 
> the flags are not affected. For a non-zero count, the AF flag is undefined.

As you can read, in several cases flags may have an undefined behaviour. As we must represent semantics over arithmetical expressions, the undefined assignment must also be described. So, in Triton the undefined behaviour is just the assignment of the previous well-known value. Which results in something like this:

```
flag = <value> if <condition> else <flag>
```

The `else <flag>` is the representation of the undefined behaviour and as you can see we have to read flag. That why you get `cf of pf sf zf` when you call `getReadRegisters()`. This only mean that Triton needs to know these values to provide a good semantics.

More details below.

```
shr.cf = ((op1 >> (op2 - 1)) & 1) if op2 != 0 else shr.cf
shr.of = ((op1 >> (bvSize - 1)) & 1) if op2 == 1 else shr.of
shr.pf = [pf expression] if op2 != 0 else shr.pf
shr.sf = ((result >> (bvSize - 1)) & 1) if op2 != 0 else shr.sf
shr.zf = (result == 0) if op2 != 0 else shr.zf
```

**Comment by 0ca** [comment]
Umm, I see.

I was experimenting using only the symbolic engine and disabling the tainting one. And I used the `Instruction.isSymbolize()` to know the "controlled" instructions. But then I got a `shr` instruction symbolized because of these flags

Check the next example:
```
#!/usr/bin/env python2
## -*- coding: utf-8 -*-
##
##
import  sys

from triton import *
from ast    import *

function = {
  0x401000: "\x85\xC9", # test ecx, ecx
  0x401002: "\x74\x02", # jz +2
  0x401004: "\xc1\xe2\x00", # shr edx, 0
}

if __name__ == '__main__':

    # Set the architecture
    setArchitecture(ARCH.X86)

    enableSymbolicEngine(True)

    # Define entry point
    pc = 0x401000

    setConcreteRegisterValue(Register(REG.ECX, 0x1))
    setConcreteRegisterValue(Register(REG.EDX, 0x2))

    #ECX is symbolic
    convertRegisterToSymbolicVariable(REG.ECX)
    taintRegister(REG.ECX)

    while pc in function:
        # Build an instruction
        inst = Instruction()

        # Setup opcodes
        inst.setOpcodes(function[pc])

        # Setup Address
        inst.setAddress(pc)

        # Process everything
        processing(inst)

        # Display instruction
        print inst, inst.isSymbolized(), inst.isTainted()

        # Next instruction
        pc = buildSymbolicRegister(REG.EIP).evaluate()

    sys.exit(0)
```

All of them are mark as symbolized. But with tainting analysis only the two first instruction are set like tainted. I guess it makes sense due the undefined behavior with these flags. 

Then should I use the tainting engine and the symbolic engine together if I want to get the "real controlled" inputs?

Thanks for your time!

**Comment by JonathanSalwan** [comment]
You should only use the symbolic engine. Taint engine is now kind of useless since there is the isSymbolized() function.

**Comment by JonathanSalwan** [comment]
I think I will implement the taint engine directly based into the semantics expression because it seems that there so many confusions with it.

**Comment by 0ca** [comment]
But then I would identify like "user controlled" the `shr` instruction I mentioned in the previous example, right?
```
  0x401000: "\x85\xC9", # test ecx, ecx
  0x401002: "\x74\x02", # jz +2
  0x401004: "\xc1\xe2\x00", # shr edx, 0
```

I understand that instruction is "spreading" the zf if it isn't modified, so it is symbolized. 

But for me, a "user-controlled" instruction is that one is using symbolized registers/memory. And shr is not using the ZF, it is just leaving it unmodified in some cases, and in others cases it is modifying the ZF, but not using it.

And that is the reason I was suggesting use the taint engine, since the taint engine is identifying correctly that `shr` is not a "user-controled" instruction.

**Comment by JonathanSalwan** [comment]
mmmh ok i got your point. Yep in your case you can use both.

**Comment by JonathanSalwan** [comment]
Mmmh I think if I integrate the taint boolean directly into AST nodes like the computed value (`AbstractNode::eval`), this should fix your behaviour.

In your case: `401004: shl edx, 0 True False`

`True` happening because `isSymbolized()` don't concretizes your expressions whereas `isTainted()` does.

**Comment by 0ca** [comment]
I don't understand what it doesn't mean `isTainted()` concretizes the value, can you explain it more or send me to code/doc where is it explained?

I was looking for the isTainted implementation, and the closer I found is the `Instruction::setTaint`:
https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/arch/instruction.cpp#L215

But there it is looks like triton is using still the symbolic expressions to know if an intruction is tainted or not. It isn't that the thing you changed for this: https://github.com/JonathanSalwan/Triton/issues/379

Thank you again, and sorry for asking so much things ;)
