### ISSUE TITLE
SYSCALL_EXIT callback gets incorrect values

### ISSUE THREAD

**Issue by LeoStAmour** [JonathanSalwan/Triton#387]
I am trying to write a sys_call analysis. I have two functions, one will run on sys_call entry:

`insertCall(my_callback_syscall_entry, INSERT_POINT.SYSCALL_ENTRY)` 

and the other will run on sys_call exit:

`insertCall(my_callback_syscall_exit, INSERT_POINT.SYSCALL_EXIT)`. 

All these callback functions do is print what number sys_call was entered or exited, respectively. However, when I run the analysis, the "entered" sys_call numbers and the "exited" sys_call numbers do not match up. I have verified that the sys_call entry numbers are correct by comparing the output to strace. But the exit callback does not appear to be getting the correct values.

**Comment by JonathanSalwan** [comment]
Can you provide an example / output plz?

**Comment by LeoStAmour** [comment]
Here is the test program:

```
#include <stdlib.h>
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>
 
int main(int argc, char* argv[]) {
 
    int fd, bytes_read;
 
    char buf[10];
 
    fd = open("./input", O_RDONLY); 
 
    if(-1 == fd) {
        printf("Failed to open file `input`\n");
        exit(1);
    } else {
        printf("Opened file with fd: %d\n", fd);
    }   

    bytes_read = read(fd, &buf, 7); 
    printf("Read %x bytes to address: %p\n", bytes_read, buf);
    printf("Buffer: %s\n", buf);
    close(fd);

    return 0;
}
```

The analysis script:

```
 from triton  import *
 from pintool import *
 
 def my_callback_syscall_entry(threadId, std):
     print 'Entered system call {}'.format(getSyscallNumber(std))
 
 def my_callback_syscall_exit(threadId, std):
     print 'Exited system call {}'.format(getSyscallNumber(std))
 
 if __name__ == '__main__':
 
     # Set the architecture
     setArchitecture(ARCH.X86_64)
 
     # Start the symbolic analysis from the Entry point
     startAnalysisFromEntry()
 
     insertCall(my_callback_syscall_entry, INSERT_POINT.SYSCALL_ENTRY)
     insertCall(my_callback_syscall_exit, INSERT_POINT.SYSCALL_EXIT)
 
     # Run the instrumentation - Never returns
     runProgram()
```

And the output of `triton callback_syscall_test.py ./test`:
```
Entered system call 2
Exited system call 4
Entered system call 5
Exited system call 0
Entered system call 9
Exited system call 34168832
Entered system call 1
Opened file with fd: 4
Exited system call 23
Entered system call 0
Exited system call 7
Entered system call 1
Read 7 bytes to address: 0x7fff3247c710
Exited system call 40
Entered system call 1
Buffer: hello!
Exited system call 15
Entered system call 1

Exited system call 1
Entered system call 3
Exited system call 0
Entered system call 231
```

**Comment by JonathanSalwan** [comment]
According to the [documentation](http://triton.quarkslab.com/documentation/doxygen/py_triton_page.html):

* **getSyscallNumber(STANDARD std)**</br>
Returns the syscall number of the system call which is executed in the current context. It is a user's responsibility to make sure that the current instruction is a syscall. This function is mainly used in a SYSCALL_ENTRY INSERT_POINT.

Actually, it's my bad, I should replace the sentence "is mainly used in" by "must be used in". `getSyscallNumber()` returns the RAX value, that's why it only works on the ENTRY callback.

**Comment by LeoStAmour** [comment]
Thank you for clearing that up!

**Comment by JonathanSalwan** [comment]
As this is a Pin callback, you can read [this](http://www.cs.virginia.edu/kim/publicity/pin/docs/39028/Pin/html/group__PIN__SYSCALL__API.html#g82342da8cd54d9346482a34303b8317c) for more information.
