### ISSUE TITLE
Example running failed

### ISSUE THREAD

**Issue by valour01** [JonathanSalwan/Triton#389]
I installed triton as a pintool with the newest version of boost Z3 and capstone. My ubuntu version is 14.04 and the kernel version is  3.13.0-32-generic.

When I finished the installation, I run the example code. The result is not what I want.
When I run `./triton ./src/examples/pin/ir.py /usr/bin/id`
Output:

    terminate called after throwing an instance of 'std::runtime_error'
    what():  tracer::pintool::context::getCurrentRegisterValue(): Invalid register.
    C: Tool (or Pin) caused signal 11 at PC 0xb748cd33
    ./triton: line 20: 10238 Segmentation fault      (core dumped) LD_BIND_NOW=1 $PIN_BIN_PATH -t   $PINTOOL_PATH -script $1 -- ${@:2}

When I run `./triton ./src/examples/pin/callback_image.py ./src/samples/ir_test_suite/ir`
Output:

    ----------
    Image path:  /bin/dash
    Image base:  0xb770b000L
    Image size:  125172
    ----------
    Image path:  /lib/ld-linux.so.2
    Image base:  0xb76e9000L
    Image size:  137528
    ----------
    Image path:  /lib/i386-linux-gnu/libc.so.6
    Image base:  0xb3a6c000L
    Image size:  1763964
    ./src/samples/ir_test_suite/ir: 1: ./src/samples/ir_test_suite/ir: ELF: not found
    ./src/samples/ir_test_suite/ir: 1: ./src/samples/ir_test_suite/ir: Syntax error: end of file unexpected

When I run `./triton ./src/examples/pin/callback_routine.py  ./src/samples/vulns/testSuite`
Output:

    ./src/samples/vulns/testSuite: 1: ./src/samples/vulns/testSuite: ELF: not found
    ./src/samples/vulns/testSuite: 2: ./src/samples/vulns/testSuite: Syntax error: "(" unexpected

I really don't know what's wrong with it. Is my installation successful or not. If you need more information to find the problem, please tell me. Many Thanks

**Comment by JonathanSalwan** [comment]
> I really don't know what's wrong with it. Is my installation successful or not. If you need more information to find the problem, please tell me. Many Thanks

Just read [examples](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/pin/ir.py#L20) =).

**Comment by abhishiktvv** [comment]
@valour01  how did you resolve the issue , i'm also facing the same . please provide help .
