### ISSUE TITLE
Using Triton to analysis server

### ISSUE THREAD

**Issue by valour01** [JonathanSalwan/Triton#391]
Hi, I was new to program analysis and I select Triton to start my project because of its rich API and powerful support on DBA. 

I am trying to use Triton to analysis server like nginx or apache httpd. Now the first step is to taint the request URL. I changed the example code `callback_syscall.py` to see whether I can capture the input URL in the syscall. And I try to execute command `sudo ./triton src/examples/pin/callback_syscall.py /usr/local/nginx/sbin/nginx` but it doesn't work. Nginx will be start but the python script will end too. Could you give me some suggestions on this? Many thanks

    from triton  import *
    from pintool import *
    import urllib2
    # Output
    #
    # $ ./triton ./src/examples/pin/callback_syscall.py  ./src/samples/crackmes/crackme_xor a
    # sys_write(1, 7fb7f06e1000, 6)
    # loose
    #    

    def my_callback_syscall_entry(threadId, std):
        if getSyscallNumber(std) == SYSCALL.WRITE:
            arg0 = getSyscallArgument(std, 0)
            arg1 = getSyscallArgument(std, 1)
            arg2 = getSyscallArgument(std, 2)
            print 'sys_write(%x, %x, %x)' %(arg0, arg1, arg2)
        if getSyscallNumber(std) == SYSCALL.RECVFROM:
            print 'receive the url'    
    

    if __name__ == '__main__':    

        # Set the architecture
        setArchitecture(ARCH.X86_64)    

        # Start the symbolic analysis from the Entry point
        #startAnalysisFromEntry()    

        insertCall(my_callback_syscall_entry, INSERT_POINT.SYSCALL_ENTRY)    

        # Run the instrumentation - Never returns
        runProgram()    

        urllib2.openurl('http://localhost')

**Comment by JonathanSalwan** [comment]
> Nginx will be start but the python script will end too. Could you give me some suggestions on this? Many thanks

Probably because ngnix forks or something like that. If you want to analyse a running server, you should use the `tritonAttach` script which will target a running pid.

```console
$ sudo ./tritonAttach you_script.py <ngnix_pid>
```

**Comment by valour01** [comment]
Thanks @JonathanSalwan 

However, is the tritonAttach works the same as triton? when I  execute 'sudo ./tritonAttach you_script.py <ngnix_pid>'  The result shows `E: Pin loader can't open file /usr/local/nginx/sbin/nginx: Permission denied`  I have already use the sudo and I noticed that my nginx pid has changed(perhaps restart by PIN?) Do you have any idea on this behavior? Many thanks

**Comment by JonathanSalwan** [comment]
> However, is the tritonAttach works the same as triton?

The `triton` and `tritonAttach` scripts are aliases on `pin` and `pin -pid`. 

> The result shows E: Pin loader can't open file /usr/local/nginx/sbin/nginx: Permission denied I have already use the sudo and I noticed that my nginx pid has changed(perhaps restart by PIN?) Do you have any idea on this behavior?

This is Pin related. You should take a look to this [thread](https://beta.groups.yahoo.com/neo/groups/pinheads/conversations/topics/11244).

**Comment by valour01** [comment]
Actually, I find the reason is that pin can not attach to the progress which is running as a sudo(root) user. 

But when I use `./tritonAttach python_script.py pid` the progress will be crashed. I tried it with firefox and nginx. Both of them is crashed. I add `print test` at the python script in the `__main__ method` before any other function, but it isn't printed out so I guess the python script is not execute.  I also set the `kernel.yama.ptrace_scope = 0` so that the kernel will not prevent me to attach a progress . To this behavior, do you have any idea, is it a problem due to Pin or my bad. Thank you very much for your help
