### ISSUE TITLE
Symbolic execution for statement like "a = b && c"

### ISSUE THREAD

**Issue by hulinghuan** [JonathanSalwan/Triton#394]
Hi Triton Team,

Recently I was playing with the Triton to explore program paths using the technique introduced in:
http://triton.quarkslab.com/blog/Code-coverage-using-dynamic-symbolic-execution/

However, I have trouble to let Triton to explore a program that has the following similar statements:

```
int a;
a = b && c && d;    // e.g., b, c, and d are integer variables converted from argv[1], argv[2], argv[3].
if ( a )
    printf("Branch A\n");
else
    printf("Branch B\n");
```

The problem is, I cannot manage to let Triton to explore into the Branch A if b, c, d from the inputSeed is **not** 1,1,1.

Is there any solutions we can solve this?

Thanks!

Leon
----------------------------------
PS: I am using a modified version (to accept multiple inputs more easier) of your code_coverage.py located at:
........../pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton/src/tools/code_coverage.py

I attached my modified version of code_coverage.py in case you need to exam it.
[code_coverage.zip](https://github.com/JonathanSalwan/Triton/files/503733/code_coverage.zip)

**Comment by JonathanSalwan** [comment]
> I attached my modified version of code_coverage.py in case you need to exam it.

Thanks but can you provide your .c file too?

**Comment by hulinghuan** [comment]
Sure. Here it is.

Thanks!
[bool_assig.zip](https://github.com/JonathanSalwan/Triton/files/506720/bool_assig.zip)

**Comment by JonathanSalwan** [comment]
Ok got it. This is a specific case that Triton doesn't catches yet. Actually, to handle your case we must implement graph dependencies. The workaround is to generate all models which cover your four `atoi()` functions.

**Comment by hulinghuan** [comment]
Thanks for you help!

But what do you mean by "generate all models which cover you four atoi()"?
Do you mean generating all models for every possible combination of these four argv[1,2,3,4]?

By the way, based on my understanding, the problem is at statement "a = b && c && d".
Not at atoi() function.

Am I right?

**Comment by JonathanSalwan** [comment]
> By the way, based on my understanding, the problem is at statement "a = argv[1] && argv[2] && argv[3] && argv[4]". Not at atoi() function.

Well, here is your code:

```cpp
    int argv1 = atoi(argv[1]);
    int argv2 = atoi(argv[2]);
    int argv3 = atoi(argv[3]);
    int argv4 = atoi(argv[4]);
    int a = argv1 && argv2 && argv3 && argv4;

    if(check(a))
        [...]
```

So, if you cover all `atoi` state, you cover the `a` state. Here is an IDA view:

![2016-10-03-202541_1600x900_scrot](https://cloud.githubusercontent.com/assets/991046/19048666/9bab3e70-89a7-11e6-8e88-a1aa67e03833.png)

The goal is to reach these two green basic blocks but to do this you have to get these following state:

* argv1 != 0
* argv1 == 0 ∧ argv2 != 0
* argv1 == 0 ∧ argv2 == 0 ∧ argv3 != 0
* argv1 == 0 ∧ argv2 == 0 ∧ argv3 == 0 ∧ argv4 != 0
* argv1 == 0 ∧ argv2 == 0 ∧ argv3 == 0 ∧ argv4 == 0

**Comment by hulinghuan** [comment]
Got it. I thought the same way.

So the problem is Triton currently cannot catch the correct path condition for those statements like:
a = b && c && d

And to work around, we need to manually create path conditions to get those models from Z3 to get the next input in each iteration.

Thank you very much for the explanations.

**Comment by JonathanSalwan** [comment]
> So the problem is Triton currently cannot catch the correct path condition for those statements like:
> a = b && c && d

To be more specific, the problem is what we call graph dependencies.

![2016-10-03-224012_1600x900_scrot](https://cloud.githubusercontent.com/assets/991046/19053319/b98e0644-89ba-11e6-87f9-bbdc765feedf.png)

As we can see on the above image, the `check` function takes as argument an expression which is **not** symbolized (because `eax` is assigned with the constant 0 or 1). So, the return value of the `check` function is not symbolized.

Graph dependencies allows us to determine the impact of previous basic blocks onto next basic blocks. So, in this case, if we know that we control parents basic blocks (parents of `4006E7` and `4006EE`), we can spread the symbolization onto `eax` (because `eax` depends on our inputs even if it was assigned with a constant).

At this moment graph dependencies are not handle by Triton but it's planned =).

Cheers,

**Comment by hulinghuan** [comment]
Got it.
Appreciate for your help and such clear explanation!

Best,
Leon

**Comment by illera88** [comment]
Can you elaborate about `graph dependencies` ?

Cheers
