### ISSUE TITLE
Clarification about taint over-approximation

### ISSUE THREAD

**Issue by mermakov** [JonathanSalwan/Triton#396]
Hello!

I have a question concerning taint spread implemented in Triton. As far as I understand from documentation, we use over-approximation as it is cheap but creates a lot of output and may lead to false positives (something is tainted where it is in fact not tainted).

Here's the example from documentation that demonstrates a false-positive.

```
1 mov ax, 0x1122                ; RAX is untainted
2 mov al, byte ptr [user_input] ; RAX is tainted
3 cmp ah, 0x99                  ; can we control this comparison?
```

Recently we have ran into a problem with taint spread getting halted on some instructions. In particular, this happens on some strcmp implementations. The instructions there work with XMM registers, but here's an easier example that shows the same issue.

```
1. mov ax, <something tainted>  ; RAX is tainted
2. movb ah, 0x99                         ; RAX becomes untainted
3. cmp ax, 0x5                             ; ...
```

RAX becomes untainted because untaintRegister applies the taint to parent register. So untainting a portion of a register makes it untainted. As far as I see it, it becomes a false negative (something is not tainted where it is in fact tainted).

Am I understanding things wrong? Is untainting parent registers valid within your over-approximation concept?

Here's a (possibly) more interesting example I came up with:

```
1. mov ah, <something tainted>
2. mov al, <something untainted>
result -- Triton RAX is untainted

but

1. mov al, <something untainted>
2. mov ah, <something tainted>
result -- Triton RAX is tainted
```

@enzet

**Comment by mermakov** [comment]
Hmm, the XMM register issue is probably more tricky.

The code does something like:

```
 88e4c:       66 0f 12 0f             movlpd (%rdi),%xmm1
 88e50:       66 0f 12 16             movlpd (%rsi),%xmm2
 88e54:       66 0f 16 4f 08          movhpd 0x8(%rdi),%xmm1
 88e59:       66 0f 16 56 08          movhpd 0x8(%rsi),%xmm2
```

So first, XMM1 is tainted because it receives tainted bytes from memory [RDI], but then untainted because it receives untainted bytes from memory [RDI+8]. So it is not the problem with parent registers, but rather with `taintAssignment` used instead of `taintUnion` (see [this](https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/arch/x86/x86Semantics.cpp#L5272))

Again, this might not be an issue for your concept of taint spread.

**Comment by JonathanSalwan** [comment]
Nice catch! Indeed, should be `taintUnion` instead of `taintAssignment`. I will provide a patch tomorrow. Thanks!

**Comment by JonathanSalwan** [comment]
Can you try again and tell me if it make more sense in that way?

**Comment by mermakov** [comment]
Yes, thank you, that fixed our problems with strcmp!

What is your opinion on registers with parents (e.g. RAH, RAL)? As far as I see `mov RAH` should be treated the same way as `movlpd` (update part of the register, leave the rest unchanged). But changing the internal taint logic can lead to cases where RAH is untainted when RAX is tainted, and that can probably lead to all sorts of problems.

**Comment by JonathanSalwan** [comment]
Actually, my long term goal is to move from over-approximation to a perfect approximation which should resolve the behavior you described.
