### ISSUE TITLE
segmentation fault while running triton pin tool

### ISSUE THREAD

**Issue by abhishiktvv** [JonathanSalwan/Triton#397]
i followed all steps as in documentation and it was succesfully installed and followed the test run of ir.py but showing segmentation fault
![image](https://cloud.githubusercontent.com/assets/12431126/19100675/8f61af04-8ade-11e6-8020-35382aa83c16.png)

**Comment by abhishiktvv** [comment]
crackme_xor not running 
![image](https://cloud.githubusercontent.com/assets/12431126/19103244/61a7b148-8af3-11e6-9b55-a16fa2ce0981.png)

**Comment by JonathanSalwan** [comment]
Set the appropriate architecture `ARCH.X86` and use bash.

**Comment by abhishiktvv** [comment]
sir could you please elobrate, i'm new to this .. where should i set architecture within python script its already set
