### ISSUE TITLE
How to know if Triton supports an instruction when using ONLY_ON_SYMBOLIZED

### ISSUE THREAD

**Issue by 0ca** [JonathanSalwan/Triton#400]
Hi,

I would like to know when an instruction is not supported by Triton (p.e. some fpu instructions).

My first idea was to check if for that instruction there is any symbolic expressions, and where there aren't I know Triton doesn't support that instruction.

But I can't do that when the optimization ONLY_ON_SYMBOLIZED is enabled.

Is there other way to achieve that? Would it be possible to return a boolean in `buildSemantics` to know if the instruction is supported or not?

Thank you!

PS: I want to use this for: https://github.com/illera88/Ponce/issues/59

**Comment by JonathanSalwan** [comment]
Should be OK now.

```python
>>> inst = Instruction()
>>> inst.setOpcodes("\xF2\x0F\x58\xCA") # addsd xmm1, xmm2
>>> processing(inst)
False
>>> inst = Instruction()
>>> inst.setOpcodes("\x48\x31\xC0") # xor rax, rax
>>> processing(inst)
True
```
