### ISSUE TITLE
API for recognizing arithmetic/logic instructions

### ISSUE THREAD

**Issue by pfsun** [JonathanSalwan/Triton#404]
Hey,

I was wondering whether Triton provides API to recognize arithmetic/logic instructions? I saw there are instructions like isBranch(), but not related with arithmetic/logic instructions.

For example, if I have instruction add <reg>,<mem>. Firstly, I want to recognize the instruction is arithmetic instruction. If I want to get the concrete value for <reg> and <mem>, I can use getCurrentRegisterValue and getCurrentMemoryValue.

Thanks,
Sun

**Comment by pfsun** [comment]
One more question about API getCurrentRegisterValue(reg) and getConcreteValue().
For example, I have instruction "add edx, eax". the value of eax is 50, the value of edx is 0.
Now I do "insertCall(cbefore, INSERT_POINT.BEFORE)".
in the cbefore function, I will print the register value once in the above instruction. 
If I do "print "REG value:", getCurrentRegisterValue(REG.EDX), getCurrentRegisterValue(REG.EAX)
", the result is **0, 50**.
If I do "print "value: ", instruction.getOperands()[0].getConcreteValue(), instruction.getOperands()[1].getConcreteValue()", the result is **50, 50**.

Based on INSERT_POINT.BEFORE (Defines an insert point before the instruction processing), the value of edx should be 0. Why do getCurrentRegisterValue(reg) and getConcreteValue() get different results?

**Comment by JonathanSalwan** [comment]
Hey @pfsun,

Sorry for the lag...

> I was wondering whether Triton provides API to recognize arithmetic/logic instructions? I saw there are instructions like isBranch(), but not related with arithmetic/logic instructions.

> For example, if I have instruction add <reg>,<mem>. Firstly, I want to recognize the instruction is arithmetic instruction. If I want to get the concrete value for <reg> and <mem>, I can use getCurrentRegisterValue and getCurrentMemoryValue.

It will be not possible. The reason is that modern Intel CPU contains ~1300 instructions and the only way to do what you want is to classify all of these instructions in groups... As you can imagine I don't want to do that =D.

 > One more question about API getCurrentRegisterValue(reg) and getConcreteValue().
For example, I have instruction "add edx, eax". the value of eax is 50, the value of edx is 0.

> Now I do "insertCall(cbefore, INSERT_POINT.BEFORE)". in the cbefore function, I will print the register value once in the above instruction.

> If I do "print "REG value:", getCurrentRegisterValue(REG.EDX), getCurrentRegisterValue(REG.EAX) ", the result is 0, 50. If I do "print "value: ", instruction.getOperands()[0].getConcreteValue(), instruction.getOperands()[1].getConcreteValue()", the result is 50, 50.

> Based on INSERT_POINT.BEFORE (Defines an insert point before the instruction processing), the value of edx should be 0. Why do getCurrentRegisterValue(reg) and getConcreteValue() get different results?

What you are looking for is `BEFORE_SYMPROC`.

**Comment by pfsun** [comment]
Thanks @JonathanSalwan. I do see there are a lot of instructions(1294). Currently, I just classify part of instructions.
I will try BEFORE_SYMPROC. But I still don't understand well why getCurrentRegisterValue(reg) and getConcreteValue() get different results before the instruction processing when I use  INSERT_POINT.BEFORE?

**Comment by JonathanSalwan** [comment]
> I will try BEFORE_SYMPROC. But I still don't understand well why getCurrentRegisterValue(reg) and getConcreteValue() get different results before the instruction processing when I use INSERT_POINT.BEFORE?

This is strange but the processing of a Triton instruction is done before the processing of a Pin instruction. That's why if you are into an `INSERT_POINT.BEFORE` callback the Triton state is not equal to the CPU state. That's also why `BEFORE_SYMPROC` exist. This callback is called before the processing of a Triton instruction into an `INSERT_POINT.BEFORE` callback.

**Comment by pfsun** [comment]
Hi Jonathan, I just use BEFORE_SYMPROC and try to use the two API functions as follows:
I have instruction "0x40067f   add edx, eax". the value of edx is 0, the value of eax is 50.
def cbeforeSymProc(instruction):
    if instruction.getAddress() == 0x40067f:
    	print "BEFORE_SYMPROC: getCurrentRegisterValue()", getCurrentRegisterValue(REG.EDX), getCurrentRegisterValue(REG.EAX)
    	print "BEFORE_SYMPROC: getConcreteValue():", instruction.getOperands()[0].getConcreteValue(), instruction.getOperands()[1].getConcreteValue()

The output is:
BEFORE_SYMPROC: getCurrentRegisterValue() 50 0
BEFORE_SYMPROC: getConcreteValue(): 0 0

When I use BEFORE_SYMPROC, the two APIs still get different results. It looks getCurrentRegisterValue() always get the same results whenever you use INSERT_POINT.BEFORE  or INSERT_POINT.BEFORE_SYMPROC. However, getConcreteValue() API will get the empty the result in INSERT_POINT.BEFORE_SYMPROC, and will get the result that is after the processing of instruction in INSERT_POINT.BEFORE.

**Comment by JonathanSalwan** [comment]
Are you up-to-date on the master?

**Comment by JonathanSalwan** [comment]
Check the output, looks good for me.

```
$ cat pfsun.py
#!/usr/bin/env python2
## -*- coding: utf-8 -*-

import sys

from pintool import *
from triton  import *


def mycb1(inst):
    print
    print inst
    print 'RAX BEFORE_SYMPROC Concrete:', getConcreteRegisterValue(REG.RAX)
    print 'RAX BEFORE_SYMPROC Current :', getCurrentRegisterValue(REG.RAX)
    return

def mycb2(inst):
    print 'RAX BEFORE Concrete        :', getConcreteRegisterValue(REG.RAX)
    print 'RAX BEFORE Current         :', getCurrentRegisterValue(REG.RAX)
    return

def mycb3(inst):
    print 'RAX AFTER Concrete         :', getConcreteRegisterValue(REG.RAX)
    print 'RAX AFTER Current          :', getCurrentRegisterValue(REG.RAX)
    return


if __name__ == '__main__':
    # Set arch
    setArchitecture(ARCH.X86_64)

    # Start JIT at the entry point
    startAnalysisFromSymbol('check')

    # Add callback
    insertCall(mycb1, INSERT_POINT.BEFORE_SYMPROC)
    insertCall(mycb2, INSERT_POINT.BEFORE)
    insertCall(mycb3, INSERT_POINT.AFTER)

    # Run Program
    runProgram()

$ ./triton ./pfsun.py ./src/samples/crackmes/crackme_xor a
[...]
400567: mov eax, dword ptr [rbp - 4]
RAX BEFORE_SYMPROC Concrete: 140722581046789
RAX BEFORE_SYMPROC Current : 140722581046789
RAX BEFORE Concrete        : 140722581046789
RAX BEFORE Current         : 140722581046789
RAX AFTER Concrete         : 0
RAX AFTER Current          : 0

40056a: movsxd rdx, eax
RAX BEFORE_SYMPROC Concrete: 0
RAX BEFORE_SYMPROC Current : 0
RAX BEFORE Concrete        : 0
RAX BEFORE Current         : 0
RAX AFTER Concrete         : 0
RAX AFTER Current          : 0

40056d: mov rax, qword ptr [rbp - 0x18]
RAX BEFORE_SYMPROC Concrete: 0
RAX BEFORE_SYMPROC Current : 0
RAX BEFORE Concrete        : 0
RAX BEFORE Current         : 0
RAX AFTER Concrete         : 140722581046789
RAX AFTER Current          : 140722581046789

400571: add rax, rdx
RAX BEFORE_SYMPROC Concrete: 140722581046789
RAX BEFORE_SYMPROC Current : 140722581046789
RAX BEFORE Concrete        : 140722581046789
RAX BEFORE Current         : 140722581046789
RAX AFTER Concrete         : 140722581046789
RAX AFTER Current          : 140722581046789

400574: movzx eax, byte ptr [rax]
RAX BEFORE_SYMPROC Concrete: 140722581046789
RAX BEFORE_SYMPROC Current : 140722581046789
RAX BEFORE Concrete        : 140722581046789
RAX BEFORE Current         : 140722581046789
RAX AFTER Concrete         : 97
RAX AFTER Current          : 97

400577: movsx eax, al
RAX BEFORE_SYMPROC Concrete: 97
RAX BEFORE_SYMPROC Current : 97
RAX BEFORE Concrete        : 97
RAX BEFORE Current         : 97
RAX AFTER Concrete         : 97
RAX AFTER Current          : 97

40057a: sub eax, 1
RAX BEFORE_SYMPROC Concrete: 97
RAX BEFORE_SYMPROC Current : 97
RAX BEFORE Concrete        : 97
RAX BEFORE Current         : 97
RAX AFTER Concrete         : 96
RAX AFTER Current          : 96

40057d: xor eax, 0x55
RAX BEFORE_SYMPROC Concrete: 96
RAX BEFORE_SYMPROC Current : 96
RAX BEFORE Concrete        : 96
RAX BEFORE Current         : 96
RAX AFTER Concrete         : 53
RAX AFTER Current          : 53

400580: mov ecx, eax
RAX BEFORE_SYMPROC Concrete: 53
RAX BEFORE_SYMPROC Current : 53
RAX BEFORE Concrete        : 53
RAX BEFORE Current         : 53
RAX AFTER Concrete         : 53
RAX AFTER Current          : 53

400589: mov eax, dword ptr [rbp - 4]
RAX BEFORE_SYMPROC Concrete: 53
RAX BEFORE_SYMPROC Current : 53
RAX BEFORE Concrete        : 53
RAX BEFORE Current         : 53
RAX AFTER Concrete         : 0
RAX AFTER Current          : 0

40058c: cdqe 
RAX BEFORE_SYMPROC Concrete: 0
RAX BEFORE_SYMPROC Current : 0
RAX BEFORE Concrete        : 0
RAX BEFORE Current         : 0
RAX AFTER Concrete         : 0
RAX AFTER Current          : 0

40058e: add rax, rdx
RAX BEFORE_SYMPROC Concrete: 0
RAX BEFORE_SYMPROC Current : 0
RAX BEFORE Concrete        : 0
RAX BEFORE Current         : 0
RAX AFTER Concrete         : 4195988
RAX AFTER Current          : 4195988

400591: movzx eax, byte ptr [rax]
RAX BEFORE_SYMPROC Concrete: 4195988
RAX BEFORE_SYMPROC Current : 4195988
RAX BEFORE Concrete        : 4195988
RAX BEFORE Current         : 4195988
RAX AFTER Concrete         : 49
RAX AFTER Current          : 49

400594: movsx eax, al
RAX BEFORE_SYMPROC Concrete: 49
RAX BEFORE_SYMPROC Current : 49
RAX BEFORE Concrete        : 49
RAX BEFORE Current         : 49
RAX AFTER Concrete         : 49
RAX AFTER Current          : 49

400597: cmp ecx, eax
RAX BEFORE_SYMPROC Concrete: 49
RAX BEFORE_SYMPROC Current : 49
RAX BEFORE Concrete        : 49
RAX BEFORE Current         : 49
RAX AFTER Concrete         : 49
RAX AFTER Current          : 49

[...]

40059b: mov eax, 1
RAX BEFORE_SYMPROC Concrete: 49
RAX BEFORE_SYMPROC Current : 49
RAX BEFORE Concrete        : 49
RAX BEFORE Current         : 49
RAX AFTER Concrete         : 1
RAX AFTER Current          : 1

[...]
fail
$
```

**Comment by JonathanSalwan** [comment]
Feel free to open it again if you consider it's necessary.
