### ISSUE TITLE
mov{l,h}p{d,s} causes an exception in ExtractNode::init() on specific cases

### ISSUE THREAD

**Issue by mermakov** [JonathanSalwan/Triton#407]
Hello!

We've ran into the following situation with the `movlpd` instruction while testing Triton on x86 machine (although I don't think that's 32-bit-specific problem).

According to specs (http://x86.renejeschke.de/html/file_module_x86_id_190.html) it is supposed to move m64 to XMM register without changing it's high bits (works normal in Triton) or move low bits from XMM to m64 (and here is the problem).

x86Semantics implementation constructs a 128-bit wide destination range from unchanged high bits and changed low bits regardless of instruction direction. When copying to memory this results in a node that tries to take [127:64] of a 64-bit bitvector which in turn throws an exception in ExtractNode::init().

Here's a short output (prints instructions, `dst`, `src`, `op1` and `op2` from x86Semantics::movlpd_s):

```
; ffffffffb6e8a1b7: jmp ecx

// This works fine
; ffffffffb6e8a300: movlpd xmm0, qword ptr [esi]
dst = xmm0:128 bv[127..0] src = [@0xb6f58a18]:64 bv[63..0]
op1 = (_ bv340282366920628978453553262363043430400 128) op2 = (concat ((_ extract 7 0) (_ bv114 8)) ((_ extract 7 0) (_ bv111 8)) ((_ extract 7 0) (_ bv116 8)) ((_ extract 7 0) (_ bv99 8)) ((_ extract 7 0) (_ bv101 8)) ((_ extract 7 0) (_ bv114 8)) ((_ extract 7 0) (_ bv105 8)) ((_ extract 7 0) (_ bv100 8)))


; ffffffffb6e8a304: mov dx, word ptr [esi + 8]

// This crashes
; ffffffffb6e8a308: movlpd qword ptr [eax], xmm0
dst = [@0x804a7eb]:64 bv[63..0] src = xmm0:128 bv[127..0]
op1 = (concat ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8)) ((_ extract 7 0) (_ bv0 8))) op2 = (_ bv340282366920628978461799199776034679140 128)
terminate called after throwing an instance of 'triton::exceptions::Ast'
  what():  ExtractNode::init(): The size of the extraction is higher than the child expression.
```

So at https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/arch/x86/x86Semantics.cpp#L5267 it creates [127:64] extract from `op1` which is `dst` and only has [63:0].

**Comment by JonathanSalwan** [comment]
Thanks for this report!

I fixed:

* **movhpd**
* **movhps**
* **movlpd**
* **movlps**

Can you `git pull master` and tell me if everything is OK?

Cheers

**Comment by mermakov** [comment]
Hello!

I have tested on my example (features only movlpd, so can't say about other instructions) and it works fine. Thanks!
