### ISSUE TITLE
Taint spread issues in some logic instructions

### ISSUE THREAD

**Issue by mkbl126** [JonathanSalwan/Triton#408]
Hi, @JonathanSalwan 
I found some inaccurate cases for the taint spread operations for some logic instructions, such as and, or and xor, even sub and sbb. They are sometimes used as the semantic of constant assignment instred of their original meanings. 
The internal api of taintUnion() is used here to spread taint for the instructions above. The basic concept lies on the idea that tanited src operand would spread taint to the dst operand.
However, the complexities for the instructions may lead to some special cases. such as xor/sub/sbb eax, eax. No matter eax is tainted or not, the dst operand would finally be untainted.
Also for and instruction, and eax, 0, provided that the concrete value of src operand be zero, the dst would  be untained no matter it was tainted before. The similar cases happened in or instruction too.
Maybe some untaint rules should be added for taint engine during taint spread to handle the constant assignment semantics.

Thanks,
qiang

**Comment by JonathanSalwan** [comment]
That's why we use symbolic execution to know what value or range of values can holds a register or memory cells at a specific program point. Taint analysis should only be used to determine if instruction operands may be controllable by the user input then use symbolic execution for precision.
