### ISSUE TITLE
Error for Simplification via Z3

### ISSUE THREAD

**Issue by pfsun** [JonathanSalwan/Triton#409]
@JonathanSalwan When I use enableSymbolicZ3Simplification(True) to simplify the expression. I meet one error.
import sys
from pintool import *
from triton  import *

def mainAnalysis(threadId):
    print "[+] In main"
    rdi = getCurrentRegisterValue(REG.RDI) # argc
    rsi = getCurrentRegisterValue(REG.RSI) # argv
    argv0_addr = getCurrentMemoryValue(getCurrentRegisterValue(REG.RSI), CPUSIZE.REG) # argv[0] pointer
    argv1_addr = getCurrentMemoryValue(rsi + CPUSIZE.REG, CPUSIZE.REG)                # argv[1] pointer
    convertMemoryToSymbolicVariable(MemoryAccess(argv1_addr, CPUSIZE.BYTE))     
def cafter(inst):
    if inst.getAddress() == 0x40057a:
        eaxid = getSymbolicRegisterId(REG.EAX)#(REG.XMM0)
        partialTree = getSymbolicExpressionFromId(eaxid).getAst()
        print partialTree
        #a = simplify(partialTree)
        #print a
        fullTree = getFullAst(partialTree)
        #simply_fulltree = simplify(fullTree)
        #print simply_fulltree
        print fullTree
if __name__ == '__main__':
    setArchitecture(ARCH.X86_64)
    setupImageWhitelist(['crackme_xor'])
    #enableSymbolicZ3Simplification(True)
    startAnalysisFromSymbol('main')
    insertCall(mainAnalysis,   INSERT_POINT.ROUTINE_ENTRY, "main")
    insertCall(cafter,   INSERT_POINT.BEFORE)
    # Run Program
    runProgram()

crackme_xor is the same with your code.  The output will be the following without enableSymbolicZ3Simplification(True):
n$ ./triton ./src/examples/pin/test_z3_triton_ast.py ./src/samples/crackmes/crackme_xor a
[+] In main
((_ zero_extend 32) (bvsub ((_ extract 31 0) ref!127) (_ bv1 32)))
((_ zero_extend 32) (bvsub ((_ extract 31 0) ((_ zero_extend 32) ((_ sign_extend 24) ((_ extract 7 0) ((_ zero_extend 32) ((_ zero_extend 24) ((_ extract 7 0) ((_ extract 7 0) SymVar_0)))))))) (_ bv1 32)))
fail

However, when I enable enableSymbolicZ3Simplification(True), output will be:
[+] In main
terminate called after throwing an instance of 'triton::exceptions::AstTranslations'
  what():  Z3ToTritonAst::visit(): 'iff' AST node not supported yet
C: Tool (or Pin) caused signal 11 at PC 0x7feee7c6a227
./triton: line 20: 10402 Segmentation fault      (core dumped) LD_BIND_NOW=1 $PIN_BIN_PATH -t $PINTOOL_PATH -script $1 -- ${@:2}

I check that "Z3_OP_IFF" is not supported in  [AbstractNode* Z3ToTritonAst::visit(z3::expr const& expr)](http://triton.quarkslab.com/documentation/doxygen/z3ToTritonAst_8cpp_source.html). So if I want to make triton support Z3_OP_IFF, I also need to add trition:ast:iff, right? Also, in the main function, I don't find where is using iff.
Will you later add more z3's AST nodes support?

Thanks,
Pengfei

**Comment by JonathanSalwan** [comment]
Hi @pfsun, yes I know this issue and I still don't know how to support `IFF` in python (dunno if it's possible actually).

`IFF` is SMT2-Lib specific and means `if and only if`. As you probably know, Triton provides two representations of its AST, in Python and and SMT2-Lib. So, we need to be able to print a node in Python **and** SMT2.

Now the problem is: **How can we print a `IFF` SMT2-Lib node in Python?**. The constraint is that it must be a ternary and not a statement.

As `IFF` never be comes from assembly convertion, it's not a problem to the DSE engine. So, a potential  solution (if you want to convert a Z3's AST to a Triton's AST) should be to force Z3 to not use this kind of node (but dunno if it's possible too).

**Comment by pfsun** [comment]
Hi @JonathanSalwan, Thanks for your detail for this issue. I also don't have any idea about IFF.

I was wondering how to get the clean AST with only arithmetic and logic operations. For example, in the following expression:
`((_ zero_extend 32) (bvsub ((_ extract 31 0) ((_ zero_extend 32) ((_ sign_extend 24) ((_ extract 7 0) ((_ zero_extend 32) ((_ zero_extend 24) ((_ extract 7 0) ((_ extract 7 0) SymVar_0)))))))) (_ bv1 32)))
`
I want to simply the expression and remove `extract, sign_extend and zero_extend` and so on. And get the final expression: bvsub (SymVar_0) (_ bv_1 32). 

I also wonder if it is possible to replace bitvector with real/integer? I know the whole triton is based on bitvector theory. For AST part, is it possible to hack trition to use real/integer not bitvector.

Thanks.

**Comment by JonathanSalwan** [comment]
> I want to simply the expression and remove extract, sign_extend and zero_extend and so on. And get the final expression: bvsub (SymVar_0) (_ bv_1 32).

You have to record your own rules using [SMT simplification passes](http://triton.quarkslab.com/documentation/doxygen/SMT_simplification_page.html).

> I also wonder if it is possible to replace bitvector with real/integer? I know the whole triton is based on bitvector theory. For AST part, is it possible to hack trition to use real/integer not bitvector.

I don't think that it's possible. Why would you use real/integer instead of bitvector?

**Comment by JonathanSalwan** [comment]
Feel free to open it again if you consider it's necessary.
