### ISSUE TITLE
Semantics for 3-operand SHLD/SHRD missing

### ISSUE THREAD

**Issue by newgre** [JonathanSalwan/Triton#413]
The framework is unable to process 3-operand SHLD/SHRD instructions.

The following python snippet demonstrates the issue:

```python
instr = Instruction()
instr.setOpcodes("\x66\x44\x0F\xA4\xDD\x3C")  # shld bp, r11w, 0x3c
instr.setAddress(0x1000)
if not processing(instr):
  raise Exception("Unsupported instruction: %s" % (instr))
```

Same goes for the SHRD equivalent, e.g.,

```python
instr = Instruction()
instr.setOpcodes("\x66\x0F\xAC\xD8\x46")  # shrd ax, bx, 46h
instr.setAddress(0x1000)
if not processing(instr):
  raise Exception("Unsupported instruction: %s" % (instr))
```

**Comment by JonathanSalwan** [comment]
Indeed. Let me few days to dev this. Next week I will be a little bit busy without internet.

**Comment by JonathanSalwan** [comment]
`SHLD` done via 84d110bdf3a3b54d53e48d757dc19fd6193b4e5e and 5a384f9d082ede7deeb5147aca204de35ad08f59
