### ISSUE TITLE
[Python example] - A condition problem in "src/examples/python/simplification.py"

### ISSUE THREAD

**Issue by idear1203** [JonathanSalwan/Triton#419]
Hi,

I am a new comer to Triton and still try hard to understand it.

I find a problem when I am running python examples.

See code here: <https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/simplification.py#L58-L68>

```python
58    if node.getKind() == AST_NODE.BVOR:
59       c1 = node.getChilds()[0]
60        c2 = node.getChilds()[1]
61        if c1.getKind() == AST_NODE.BVAND and c2.getKind() == AST_NODE.BVAND:
62            c1_not    = getNot(c1)
63            c2_not    = getNot(c2)
64            c1_nonNot = getNonNot(c1)
65            c2_nonNot = getNonNot(c2)
66            if c1_not == ~c2_nonNot and c1_not == ~c2_nonNot:
67                return c1_nonNot ^ c2_nonNot
68    return node
```

I think code at line 66 should be like this:

```python
66            if c1_not == ~c2_nonNot and c2_not == ~c1_nonNot:
```

I don't know if I have a misunderstanding here.

**Comment by JonathanSalwan** [comment]
Indeed you're right, my condition makes no sense :). Thanks for this report and welcome to this project.
