### ISSUE TITLE
About ARM Support

### ISSUE THREAD

**Issue by pfsun** [JonathanSalwan/Triton#420]
Hi Jonathan, 

I really enjoy your great work about Triton. I has tried different test cases for X86. I wonder whether you have any plan to support ARM?  

Based on thread #226, you mentioned "If you want to add the ARM semantics, you have to keep the same structure as x86". So if I want to add ARM support, I need to add one arm folder in /arch/, and also keep four files: arm64cpu.cpp, armcpu.cpp, armsemantics.cpp, armspecifications.cpp, right? For taint tracking in ARM architecture, I think I cannot use the PIN. Do you have any tips about how to use DynamoRIO and IDApro debuggers for ARM?

I am preparing to add ARM support. Hope to get your more tips and suggestions :-)

Thanks,
Pengfei

**Comment by JonathanSalwan** [comment]
Hey @pfsun, sorry for the lag.

> I wonder whether you have any plan to support ARM?

About ARM it's planned but not for soon.

> Based on thread #226, you mentioned "If you want to add the ARM semantics, you have to keep the same structure as x86". So if I want to add ARM support, I need to add one arm folder in /arch/, and also keep four files: arm64cpu.cpp, armcpu.cpp, armsemantics.cpp, armspecifications.cpp, right?

Yeah sure, you have to keep the same design that the arch/x86 directory but there are also some fix to do in `SymbolicEngine.cpp`

> For taint tracking in ARM architecture, I think I cannot use the PIN.

Yep.

> Do you have any tips about how to use DynamoRIO and IDApro debuggers for ARM?

Nop sorry =(

> I am preparing to add ARM support.

\o/

> Hope to get your more tips and suggestions :-)

The harder things will be to verify your semantics!

**Comment by pfsun** [comment]
> About ARM it's planned but not for soon.

Just curious, have you started for ARM support? Now I start to work on some ARM-based application, I need taint and symbolic feature like your Triton. That is why I ask about ARM support. 
>I am preparing to add ARM support.
\o/

This emoji let me feel upset. Haha~  I will learn about your Triton further and may need more help from you. Sorry for future questions.

**Comment by JonathanSalwan** [comment]
> Just curious, have you started for ARM support?

Not yet

> This emoji let me feel upset. 

This emoji means something like "hourra", a french word to describe the happiness =).

> I will learn about your Triton further and may need more help from you.

Don't hesitate.

> Sorry for future questions.

No worries :)
