### ISSUE TITLE
Build fails with mingw, missing hypot in Python.h/cmath

### ISSUE THREAD

**Issue by gyorokpeter** [JonathanSalwan/Triton#432]
[ 18%] Building CXX object CMakeFiles/triton.dir/src/libtriton/bindings/python/init.cpp.obj
In file included from D:/MinGW/mingw32/lib/gcc/i686-w64-mingw32/6.2.0/include/c++/math.h:36:0,
                 from D:/Utility/Python27/include/pyport.h:325,
                 from D:/Utility/Python27/include/Python.h:58,
                 from D:/Projects/c++/Triton/src/libtriton/includes/pythonBindings.hpp:17,
                 from D:\Projects\c++\Triton\src\libtriton\bindings\python\init.cpp:12:
D:/MinGW/mingw32/lib/gcc/i686-w64-mingw32/6.2.0/include/c++/cmath:1133:11: error: '::hypot' has not been declared
   using ::hypot;
           ^~~~~
CMakeFiles\triton.dir\build.make:662: recipe for target 'CMakeFiles/triton.dir/src/libtriton/bindings/python/init.cpp.obj' failed

Suggested fix: in src\libtriton\bindings\python\init.cpp, update the following lines:
#elif _WIN32
  #include <Python.h>
  #include <longintrepr.h>
#endif

to:

#elif _WIN32
  #include <cmath>
  #define _hypot hypot
  #include <Python.h>
  #include <longintrepr.h>
#endif

**Comment by JonathanSalwan** [comment]
Fixed with #433
