### ISSUE TITLE
PE format documentation

### ISSUE THREAD

**Issue by JonathanSalwan** [JonathanSalwan/Triton#439]
Hey @gyorokpeter,

Can you please improve these following documentations:

* [doc 1](https://github.com/JonathanSalwan/Triton/blob/513eba602d47f11f8ac93bb56cd5ee71caeed9ad/src/libtriton/includes/peExportDirectory.hpp#L44-L50)
* [doc 2](https://github.com/JonathanSalwan/Triton/blob/513eba602d47f11f8ac93bb56cd5ee71caeed9ad/src/libtriton/includes/peHeader.hpp#L49-L54)
* [doc 3](https://github.com/JonathanSalwan/Triton/blob/513eba602d47f11f8ac93bb56cd5ee71caeed9ad/src/libtriton/includes/peHeader.hpp#L72-L75)
* [doc 4](https://github.com/JonathanSalwan/Triton/blob/513eba602d47f11f8ac93bb56cd5ee71caeed9ad/src/libtriton/includes/peImportDirectory.hpp#L43-L45)
* [doc 5](https://github.com/JonathanSalwan/Triton/blob/513eba602d47f11f8ac93bb56cd5ee71caeed9ad/src/libtriton/includes/peOptionalHeader.hpp#L43-L72)
* [doc 6](https://github.com/JonathanSalwan/Triton/blob/513eba602d47f11f8ac93bb56cd5ee71caeed9ad/src/libtriton/includes/peOptionalHeader.hpp#L77-L105)

After these changes, I will merge into `master`. Thanks and great job about the PE support :)

**Comment by JonathanSalwan** [comment]
After these changes, I will merge into `master`.

**Comment by gyorokpeter** [comment]
For PE32_OptionalHeader and PE32Plus_OptionalHeader, each field has the same function as in PeOptionalHeader. Should I copy the field descriptions one by one, or is it enough to mention this before the two structs?

**Comment by JonathanSalwan** [comment]
> Should I copy the field descriptions one by one, or is it enough to mention this before the two structs?

It's ok if you described it into the struct description but it must be mentioned over the doxygen.
