### ISSUE TITLE
trouble when compiling on centos7

### ISSUE THREAD

**Issue by KnoooW** [JonathanSalwan/Triton#443]
I notice your environment is ubuntu15.
it is hard to compile on centos7.
(1). boost version not match
   I download and compile & install
   I need manualy fix CMakeLists.txt to set boost include/lib path
(2) I also tried Dockerfile. but it cannot apt-get update normally.
     seems dns problem, so I back to compile on my host.
(3) cmake searchs python lib, but it find libpython.a not libpython.so
     I manually change it in export env.
hope it can help someone.

**Comment by JonathanSalwan** [comment]
> I notice your environment is ubuntu15.

Well, probably one of us use ubuntu but I personally use gentoo. 

> (1). boost version not match
> I download and compile & install
> I need manualy fix CMakeLists.txt to set boost include/lib path

Why not use:

```
BOOST_ROOT or BOOSTROOT      - Preferred installation prefix
BOOST_INCLUDEDIR             - Preferred include directory e.g. <prefix>/include
BOOST_LIBRARYDIR             - Preferred library directory e.g. <prefix>/lib
```

> (2) I also tried Dockerfile. but it cannot apt-get update normally.
> seems dns problem, so I back to compile on my host.

Well, maybe, I never tried docker.

> (3) cmake searchs python lib, but it find libpython.a not libpython.so
> I manually change it in export env.

Export variables are:

```
PYTHON_INCLUDE_DIRS
PYTHON_LIBRARIES
```

> hope it can help someone.

Thanks!
