### ISSUE TITLE
setConcreteRegisterValue broken in dev-next

### ISSUE THREAD

**Issue by gyorokpeter** [JonathanSalwan/Triton#449]
I just pulled the latest version of dev-next and apprently it broke this code:
`
    for (int i=0; i<256; ++i) {
            api.setConcreteRegisterValue(Register(triton::arch::x86::ID_REG_EAX,i));
            api.concretizeAllRegister();
            cout << "eax=" << hex << api.getConcreteRegisterValue(triton::arch::x86::ID_REG_EAX) << endl;
    }
`

After "git checkout 952a9088f5ed39a0c58cdfd65a9aa0f819d2a5c8" this prints all the numbers from 0 to 255.
After "git checkout 2aca36b33c04cbefbab779c8b80f6dc628ae8fc7" it prints 0 on every line.

**Comment by JonathanSalwan** [comment]
Theoretically using `int i` should be ambiguous due to our prototype of `Register` which uses `triton::uint512`.

**Comment by JonathanSalwan** [comment]
Wait there is still some issues.

**Comment by gyorokpeter** [comment]
Changing to uint512(i) fixes the problem.

**Comment by JonathanSalwan** [comment]
Yep but there is still an issue about polymorphic constructor with `bool` and `triton::uint512`.
