### ISSUE TITLE
Python binding not work with virtualenv

### ISSUE THREAD

**Issue by bananaappletw** [JonathanSalwan/Triton#462]
Before installing Triton, I switch to python virtual environment.
After that, I try to `import triton` from my virtual environment. 
It succeed once. ( The same session I install triton )
After closed the terminal, switch to virtual environment, and try to `import triton` again.
It failed.
I am not sure it's triton's problem, or the way I install triton is wrong.
Thanks.

**Comment by JonathanSalwan** [comment]
The problem is clearly not related to Triton. The problem is related to your setup or how you use your virtual environment.

**Comment by bananaappletw** [comment]
@JonathanSalwan I think this existed.
https://github.com/JonathanSalwan/Triton/blob/master/CMakeLists.txt#L329
If you replace these code to
```
    find_package(PythonInterp REQUIRED)
    if(UNIX)
            install (CODE "execute_process(COMMAND ${PYTHON_EXECUTABLE} ${CMAKE_BINARY_DIR}/setup.py install)")
    endif()
```
Then you will failed in `setup.py.in`
Because the virtualenv doesn't have `site.getsitepackages()` function.
That means previous code doesn't use `virtualenv`
After `cmake ..`
Begin from 152 lines In `build/cmake_install.cmake` file.
```
 if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
   execute_process(COMMAND /usr/bin/env python2 /home/apple/Triton/build/setup.py install)
 endif()
```
Because install with command `sudo make install`, the python path will be wrong.
I take a simple patch, then `build/cmake_install.cmake` turns into
```
if(NOT CMAKE_INSTALL_COMPONENT OR "${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified")
  execute_process(COMMAND /home/apple/test/qisa/venv/bin/python2.7 /home/apple/test/qisa/Triton/build/setup.py install)
endif()
```
Python binding for virtualenv works now.
Would you like to take a look https://github.com/bananaappletw/Triton/commit/f3bf1aae3440ebfcb93ed5fb6952835774bec2a3
But, I don't know the meaning of this line.
https://github.com/JonathanSalwan/Triton/blob/master/src/scripts/setup.py.in#L56
Thanks.

**Comment by JonathanSalwan** [comment]
> But, I don't know the original meaning of this line.

OSX hack.

Please do a PR and we will see if it breaks the OSX build.

**Comment by bananaappletw** [comment]
@JonathanSalwan It seems good.
