### ISSUE TITLE
Question for taintRegister()

### ISSUE THREAD

**Issue by pfsun** [JonathanSalwan/Triton#469]
@JonathanSalwan  I just use the API taintRegister() to taint one Register. I feel a little bit confuse for the result. I do taint taintRegister(REG.RDX).
The below is the assemble code:

`
  403d80:       48 89 d7                mov    %rdx,%rdi
  403d83:       e8 de 12 00 00          callq  405066 <_ZN13PIDController4calcEd>
  ....

0000000000405066 <_ZN13PIDController4calcEd>:
  405066:       55                      push   %rbp
  405067:       48 89 e5                mov    %rsp,%rbp
  40506a:       48 83 ec 70             sub    $0x70,%rsp
  40506e:       48 89 7d a8             mov    %rdi,-0x58(%rbp)
  405072:       f2 0f 11 45 a0          movsd  %xmm0,-0x60(%rbp)
  405077:       48 8b 45 a8             mov    -0x58(%rbp),%rax
  40507b:       0f b6 40 08             movzbl 0x8(%rax),%eax
  40507f:       83 f0 01                xor    $0x1,%eax
  405082:       84 c0                   test   %al,%al
`

The taint result is as following:
`0x403d80: mov rdi, rdx
	 -> ((_ zero_extend 0) ((_ extract 63 0) ref!1769))
0x40506e: mov qword ptr [rbp - 0x58], rdi
	 -> (concat ((_ extract 63 56) ((_ extract 63 0) ref!1785)) ((_ extract 55 48) ((_ extract 63 0) ref!1785)) ((_ extract 47 40) ((_ extract 63 0) ref!1785)) ((_ extract 39 32) ((_ extract 63 0) ref!1785)) ((_ extract 31 24) ((_ extract 63 0) ref!1785)) ((_ extract 23 16) ((_ extract 63 0) ref!1785)) ((_ extract 15 8) ((_ extract 63 0) ref!1785)) ((_ extract 7 0) ((_ extract 63 0) ref!1785)))
**0x405072: movsd qword ptr [rbp - 0x60], xmm0**
	 -> ((_ zero_extend 0) (ite (= (_ bv0 1) (_ bv0 1)) (bvadd ((_ extract 63 0) ref!1785) (_ bv4 64)) (bvsub ((_ extract 63 0) ref!1785) (_ bv4 64))))
0x405077: mov rax, qword ptr [rbp - 0x58]
	 -> ((_ zero_extend 0) (concat ((_ extract 7 0) ref!1819) ((_ extract 7 0) ref!1820) ((_ extract 7 0) ref!1821) ((_ extract 7 0) ref!1822) ((_ extract 7 0) ref!1823) ((_ extract 7 0) ref!1824) ((_ extract 7 0) ref!1825) ((_ extract 7 0) ref!1826)))

`
I don't understand why `0x405072: movsd qword ptr [rbp - 0x60], xmm0` is also tainted. Whether the reason is that rbp register has been tainted in `0x40506e: mov qword ptr [rbp - 0x58], rdi`? If I use taintRegister(), will all related register be tainted?

Thanks.

**Comment by JonathanSalwan** [comment]
[movsd](http://www.felixcloutier.com/x86/MOVS:MOVSB:MOVSW:MOVSD:MOVSQ.html) uses `RDI` as implicit register.

**Comment by JonathanSalwan** [comment]
Note that your tainted expression:

```
-> ((_ zero_extend 0) (ite (= (_ bv0 1) (_ bv0 1)) (bvadd ((_ extract 63 0) ref!1785) (_ bv4 64)) (bvsub ((_ extract 63 0) ref!1785) (_ bv4 64))))
```

is basically this part of the [movsd](http://www.felixcloutier.com/x86/MOVS:MOVSB:MOVSW:MOVSD:MOVSQ.html) semantics:

```
    [...]
    ELSE IF (Doubleword move)
         THEN IF DF = 0
              [...]
              (R|E)DI ← (R|E)DI + 4;
              FI;
         ELSE
              [...]
              (R|E)DI ← (R|E)DI – 4;
         FI;
```

**Comment by pfsun** [comment]
Thanks @JonathanSalwan. I got it.
