### ISSUE TITLE
Taint analysis in Double-Precision Floating-Point instruction

### ISSUE THREAD

**Issue by pfsun** [JonathanSalwan/Triton#471]
@JonathanSalwan For taint analysis in double-precisson floating-point instruction (e.g. subsd, mulsd, addsd, divsd), I must firstly provide the correct semantics, and then I can do taint analysis in these instructions, right?

**Comment by JonathanSalwan** [comment]
Right but i'm very curious about how you will provide the good semantics :). If you have ideas go ahead!

**Comment by pfsun** [comment]
Actually, I don't have good idea now. I just want to confirm with you firstly. And then exploring and trying the possible way. I also wonder whether you have any tips to share with me? I see you have build the semantic for movsd.

**Comment by JonathanSalwan** [comment]
actually, if you only want taint you can only call `taintAssignement`, taintUnion` etc... But if you want the symbolic execution you have to define the semantics. The problem is described [here](https://github.com/illera88/Ponce/issues/59#issuecomment-253730762).

**Comment by pfsun** [comment]
I know the problem for symbolic execution. Currently, I just need to do taint and no symbolic execution. I will try taintAssignment and taintUnion. Thanks Jonathan.

**Comment by JonathanSalwan** [comment]
Okay. Below an example for the addsp tainting:

```patch
+      void x86Semantics::addsd_s(triton::arch::Instruction& inst) {
+        auto& dst = inst.operands[0];
+        auto& src = inst.operands[1];
+
+        /* Spread taint */
+        this->taintEngine->taintUnion(dst, src);
+
+        /* Upate the symbolic control flow */
+        this->controlFlow_s(inst);
+      }
+
+
```

**Comment by pfsun** [comment]
Great. I just go to one class. I will try them and then let you know. But it looks that isTainted() also need to check the symbolic expression, and need the semantic, right?

**Comment by JonathanSalwan** [comment]
Indeed. You have to define `instruction->tainted` to `true`. There is probably a patch to do out there.

**Comment by JonathanSalwan** [comment]
Please `git pull origin dev-next`. Then:

```patch
+      void x86Semantics::addsd_s(triton::arch::Instruction& inst) {
+        auto& dst = inst.operands[0];
+        auto& src = inst.operands[1];
+
+        /* Spread taint */
+        inst.setTaint(this->taintEngine->taintUnion(dst, src));
+
+        /* Upate the symbolic control flow */
+        this->controlFlow_s(inst);
+      }
+
+
```

**Comment by pfsun** [comment]
The taint works prefect now. Thanks for you help.

**Comment by pfsun** [comment]
Thanks Jonathan. Now I can taint the four float-point instruction. One more thing, I don't need the symbolic execution for float-point instruction. But I do need the semantic expression for them. Do you plan to add them in some point? I am also exploring them now.

**Comment by JonathanSalwan** [comment]
> Do you plan to add them in some point?

It's a long term goal but it's a bit complex to do and I have so much easy things to do before :)

**Comment by JonathanSalwan** [comment]
Past your code.
