### ISSUE TITLE
Memory consumption with Python binding

### ISSUE THREAD

**Issue by commial** [JonathanSalwan/Triton#482]
Hi,

I'm using the Python binding Pin / Triton, but I experienced some trouble regarding memory consumption.
I've probably miss something.

To reproduce:
```Python
from triton import *
from pintool import *

setArchitecture(ARCH.X86_64)

# Start JIT at the entry point
startAnalysisFromEntry()

# Add callback
insertCall(lambda x: None, INSERT_POINT.BEFORE_SYMPROC)

runProgram()
```

And run `pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton/triton mini.py /bin/ls`

The process quickly asks for several GB of RAM.
I'm using Triton in commit ce49ce9ba49965a5e7f814f2b46e50cc74b704de

Thanks in advance :)

**Comment by JonathanSalwan** [comment]
Hey @commial,

Yep, without enabled modes, triton uses lot of memory. Below some basic modes for specific uses:

* **if you don't need instruction semantics but only the tracing feature (pintool)**

```python
enableSymbolicEngine(False)
```

* **if you need instruction semantics but only on symbolized inputs```

```python
enableMode(MODE.ONLY_ON_SYMBOLIZED, True)
```

* **if you need instruction semantics but don't allocate nodes already allocated**

```python
enableMode(MODE.AST_DICTIONARIES, True)
```

**Comment by commial** [comment]
Thanks for this quick & precise answer. It works like a charm ;)
