### ISSUE TITLE
Question about Symbolic 

### ISSUE THREAD

**Issue by pfsun** [JonathanSalwan/Triton#483]
Hi @JonathanSalwan, I have one question about symbolic expression and current value. When I convert one register to one symbolic variable, its symbolic expression can be SymVar_0. But when I output the current value of register, it will keep the same concrete value before symbolic. For example:
` if inst.getAddress() == 0x463e84:
        var1 = convertRegisterToSymbolicVariable(REG.RDX)
        print var1
        print "current value", hex(getCurrentRegisterValue(REG.RDX))

  
  SymVar_0:64
  current value 0x7ffc1b1d4058L
`
So whether it means that the execution will go through one path based on the concrete value, and only the symbolic expression will have a related symbolic reference?

I also find one thing, when I symbolic one memory address, the later instruction will access the memory value by the memory address. When I output the symbolic expression for the memory value, I cannot find any symbolic reference of the memory address?

Let me know whether you catch my question. Thanks.

**Comment by JonathanSalwan** [comment]
Hey @pfsun,

> But when I output the current value of register, it will keep the same concrete value before symbolic. For example:

Yes, because `getCurrentRegisterValue` is part of Pin and gets the real cpu value.

> So whether it means that the execution will go through one path based on the concrete value, and only the symbolic expression will have a related symbolic reference?

Yes. A DSE builds the symbolic expressions based on a concrete trace. Which means that the path taken is based on the concrete value.

> I also find one thing, when I symbolic one memory address, the later instruction will access the memory value by the memory address. When I output the symbolic expression for the memory value, I cannot find any symbolic reference of the memory address?

Yes. We don't symbolize `STORE` and `LOAD` dereferencing. This kind of policy is described in this [paper](http://www.robindavid.fr/publications/issta-2016.pdf). Based on this paper, we use the `CC` policy which means concrete stores and concrete loads.

**Comment by pfsun** [comment]
Thanks @JonathanSalwan. Now it makes sense to me. 
Based on you mention you don't symbolize STORE and LOAD dereferencing. Do you have any API to recognize whether one value is memory address or memory value. For example, one register may hold one value or memory address, if it is one memory address, how can I recognize it is one memory address？ So I can symbolize the corresponding memory value not the memory address.

**Comment by JonathanSalwan** [comment]
> Do you have any API to recognize whether one value is memory address or memory value. For example, one register may hold one value or memory address, if it is one memory address, how can I recognize it is one memory address？ So I can symbolize the corresponding memory value not the memory address.

What about:

```python
addCallback(mycb, CALLBACK.GET_CONCRETE_MEMORY_VALUE)
```

Or:

```python
processing(inst)

for memory, node in inst.getLoadAccess():
    print memory

for memory, node in inst.getStoreAccess():
    print memory
```

**Comment by JonathanSalwan** [comment]
Is it ok? Can we close?

**Comment by pfsun** [comment]
Hi @JonathanSalwan, I do try your suggestion about getLoadAccess and getStoreAccess. For example,
` mov     rcx, [rbp+this]`
`print "memory", inst.getLoadAccess()
 print "memory address:", hex(inst.getOperands()[1].getAddress())
 print "memory value:", hex(getCurrentMemoryValue(inst.getOperands()[1].getAddress(), CPUSIZE.QWORD))

output:
memory [([@0x7fff9d483e18]:64 bv[63..0], (((((((((ref_43 & 0xFF)) << 8 | (ref_44 & 0xFF)) << 8 | (ref_45 & 0xFF)) << 8 | (ref_46 & 0xFF)) << 8 | (ref_47 & 0xFF)) << 8 | (ref_48 & 0xFF)) << 8 | (ref_49 & 0xFF)) << 8 | (ref_50 & 0xFF)))]
memory address: 0x7fff9d483e18L
memory value: 0x7fff9d4841b0L

`
It looks I only can get the memory address.

**Comment by JonathanSalwan** [comment]
that's not what you are looking for?

**Comment by pfsun** [comment]
I want to symbolic all input value for one function. For example, the input for one function can be function parameters and global value. So I cannot simply symbolize all function parameters. What I am doing now is first to recognize all input (it can be value or memory address). When I symbolize some memory address, there will be the problem which you mentioned.

> Yes. We don't symbolize STORE and LOAD dereferencing. This kind of policy is described in this paper. Based on this paper, we use the CC policy which means concrete stores and concrete loads.

So I hope I can find some way to recognize the value and memory address. When I meet the memory address, I can directly symbolic the memory value. Especially, in my case, there may be one situation that one memory address holds another memory address, so I must figure out the final memory value and then symbolize the memory value.

**Comment by JonathanSalwan** [comment]
> So I hope I can find some way to recognize the value and memory address.

* **bool isMemoryMapped(integer baseAddr, integer size=1)**
Returns true if the range [baseAddr:size] is mapped into the internal memory representation.

?

**Comment by pfsun** [comment]
@JonathanSalwan 
For `463E6B mov     rax, [rbp+this]`

if inst.getAddress() == 0x463E6B:
       ` print "memory", inst.getLoadAccess()`
        **Output: memory [([@0x7ffc4087c8b8]:64 bv[63..0], (((((((((ref_43 & 0xFF)) << 8 | (ref_44 & 0xFF)) << 8 | (ref_45 & 0xFF)) << 8 | (ref_46 & 0xFF)) << 8 | (ref_47 & 0xFF)) << 8 | (ref_48 & 0xFF)) << 8 | (ref_49 & 0xFF)) << 8 | (ref_50 & 0xFF)))]**
        `print "memory address:", hex(inst.getOperands()[1].getAddress())`
        **Output:memory address: 0x7ffc4087c8b8L**
        `print "memory value:", hex(getCurrentMemoryValue(inst.getOperands()[1].getAddress(), CPUSIZE.QWORD))`
        **Output:memory value: 0x7ffc4087cc50L**
        `print "Memory map:", isMemoryMapped(inst.getOperands()[1].getAddress(), CPUSIZE.QWORD)`
        **Output: Memory map: True**
       ` mem = MemoryAccess(getCurrentMemoryValue(inst.getOperands()[1].getAddress(), CPUSIZE.QWORD), CPUSIZE.QWORD)`
        `print "Next Mem Address:", hex(mem.getAddress())`
        **Output:Next Mem Address: 0x7ffc4087cc50L**
        `print "Next Mem Value:", hex(getCurrentMemoryValue(mem.getAddress(), CPUSIZE.DWORD))`
        **Output:Next Mem Value: 0x24ca110L**
        `print "Memory map:", isMemoryMapped(mem.getAddress(), CPUSIZE.DWORD)`
        **Output:Memory map: False**


Based on the results, the value of rbp+this is 0x7ffc4087c8b8, the API isMemoryMapped can recognize it as one memory representation. The value which is in memory address(0x7ffc4087c8b8) is 0x7ffc4087cc50. 0x7ffc4087cc50 is still one memory address, but isMemoryMapped cannot recognize it as one memory representation.

**Comment by JonathanSalwan** [comment]
Well, because `0x7ffc4087cc50` was never used yet. I think the best way to do what you are looking for is to get all mapped areas of you process and check if a value is into these maps. I cannot provide API to determine if a value is an address because it is so much related to a mapping memory manager which is not into the Triton's philosophy yet.

**Comment by pfsun** [comment]
Yes. Just as you said that `0x7ffc4087cc50` was never used yet. Thanks for your help and suggestion. I will figure out it. :-)

**Comment by JonathanSalwan** [comment]
we are welcome :)
