### ISSUE TITLE
Python bindings compilation issue on ArchLinux

### ISSUE THREAD

**Issue by archey** [JonathanSalwan/Triton#484]
I am working on packaging this for ArchStrike, I am facing issues with a lot of the hardcoded paths to /usr/bin/python. On ArchLinux python3 is the default python interpreter, the hardcoded python paths are causing us issues. 

Is there  any way to correct the cmake_install.cmake file under src/Triton-0.4/build/ to call python2 with --rootdir=$(destdir) --optimize=1, if not I will keep working on a way to patch it. We are pulling the src code from the 0.4 tag currently, but I'm willing to apply any missing patches in git to fix this issue.

**Comment by JonathanSalwan** [comment]
> I am facing issues with a lot of the hardcoded paths to /usr/bin/python.

Where?

> but I'm willing to apply any missing patches in git to fix this issue.

What about this [patch](https://github.com/JonathanSalwan/Triton/pull/467/files)

**Comment by archey** [comment]
My apologies Im losing my mind today, the issue is after cmake compiles it. The cmake_install.cmake file tries to call python directly not python2  or python2.7. Let me try that patch and see if  I can get it working.

**Comment by JonathanSalwan** [comment]
Is it ok? Can we close?

**Comment by archey** [comment]
Let's close it for now,  the patch fixes the issues but I still have to modify the --root dir to install it in a fakeroot. Otherwise it will try to install directly into /usr/lib/python2.7/blah. I will see if I can solve this issue in my own patch locally.

**Comment by JonathanSalwan** [comment]
Mmmh, I will keep this issue open then, let me know when your patch is ok and we will see if we add your patch into our cmake :)

**Comment by archey** [comment]
Sounds good, I will keep working on the patch, I have been trying to use CMAKE_INSTALL_PREFIX but so far its conflicting with the needed DESTDIR var on the make install.

**Comment by JonathanSalwan** [comment]
Probably fixed with the new model. If it's not, feel free to re-open it.
