### ISSUE TITLE
"triton::api.buildSemantics" consumes memory too fast

### ISSUE THREAD

**Issue by majinxin2003** [JonathanSalwan/Triton#486]
Hi,

Thanks for the powerful triton.
Howerver, It seems that "triton::api.buildSemantics" consumes memory too fast. Is there any way to free memory at time?

By the way, I am using  pintools on windows , which compiled with the libtrion's static lib.

**Comment by JonathanSalwan** [comment]
#482 ?

**Comment by majinxin2003** [comment]
Thanks for the quick reply.  I have already read #482 .  Sure we can use 'EnableMode' to enable or disable the symbolic / taint engine. However, When it comes to the real world programs, If I turn on the symbolic mode all the time, that means it uses 'api.processing' for every single instruction, is there any way to avoid the fast increasement of memory.

**Comment by majinxin2003** [comment]
I see. While it is enabled the 'symbolic only' mode, it start processing the symbolic expression only if there exists symbols. So the memory increasement speed depends on the size and number of the symbols. Should be  more careful with the realworld programs. And yes, we can close the issue now.

**Comment by JonathanSalwan** [comment]
Just to say that: doing a symbolic execution on a whole real world program makes no sense for me. Generally, we target specific components / zones to analyze with a minimum of knowledges about what to symbolize.
