### ISSUE TITLE
Inconsistent PYTHON_INCLUDE_DIRS and PYTHON_LIBRARIES

### ISSUE THREAD

**Issue by gyorokpeter** [JonathanSalwan/Triton#505]
The following setup worked until recently but now it fails with the above error.

`cmake -G "MinGW Makefiles" -DBOOST_ROOT="D:/Projects/lib/boost_1_62_0" -DPYTHON_INCLUDE_DIRS="D:/Utility/Python27-32bit/include" -DPYTHON_LIBRARIES="D:/Utility/Python27-32bit/libs/libpython27.a" -DZ3_INCLUDE_DIRS="D:/Projects/lib/z3/src/api/c++;D:/Projects/lib/z3/src/api" -DZ3_LIBRARIES="D:/Projects/lib/z3/build/libz3.a" -DCAPSTONE_INCLUDE_DIRS="D:/Projects/lib/capstone-v4/include/capstone" -DCAPSTONE_LIBRARIES="D:/Projects/lib/capstone-v4/build/libcapstone.a" -DINSTALL_PREFIX=D:/Projects/c++/Triton-v4/install -DSTATICLIB=False ..`

**Comment by JonathanSalwan** [comment]
cc @pbrunet

**Comment by JonathanSalwan** [comment]
may also be related to #504

**Comment by gyorokpeter** [comment]
If I remove the line that creates the fatal error from CMakeLists.txt, it goes through but prints this:
`CMake Warning (dev) at src/libtriton/CMakeLists.txt:257 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "gen-syscall32" of target "triton" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/libtriton/CMakeLists.txt:257 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "gen-syscall64" of target "triton" does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.`

Furthermore, once I try to do mingw32-make it fails with:
`g++.exe: error: /MT: No such file or directory
src\libtriton\CMakeFiles\triton.dir\build.make:62: recipe for target 'src/libtriton/CMakeFiles/triton.dir/api/api.cpp.obj' failed
mingw32-make[2]: *** [src/libtriton/CMakeFiles/triton.dir/api/api.cpp.obj] Error 1
CMakeFiles\Makefile2:1067: recipe for target 'src/libtriton/CMakeFiles/triton.dir/all' failed
mingw32-make[1]: *** [src/libtriton/CMakeFiles/triton.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
mingw32-make: *** [all] Error 2`

**Comment by 55-AA** [comment]
You may not set Python include and libs. cmake can search them. If you need set. refer #504 .

**Comment by gyorokpeter** [comment]
I always get that error, no matter if I have either or both of those variables on the command line.

**Comment by gyorokpeter** [comment]
So the fix that works for me (although the warning about the syscall dependencies is still there):
`diff --git a/CMakeLists.txt b/CMakeLists.txt
index 366d85e..be281e8 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -113,8 +113,8 @@ if(PYTHON_BINDINGS)
     endif()
     if(NOT PYTHON_INCLUDE_DIRS AND NOT PYTHON_LIBRARIES)
         find_package(PythonLibs 2.7 REQUIRED)
-      else()
-        message(FATAL_ERROR "Inconsistent PYTHON_INCLUDE_DIRS and PYTHON_LIBRARIES")
+      #else()
+      #  message(FATAL_ERROR "Inconsistent PYTHON_INCLUDE_DIRS and PYTHON_LIBRARIES")
     endif()
   endif()
   include_directories(${PYTHON_INCLUDE_DIRS})
diff --git a/src/libtriton/CMakeLists.txt b/src/libtriton/CMakeLists.txt
index 291a37a..2dfa5f1 100644
--- a/src/libtriton/CMakeLists.txt
+++ b/src/libtriton/CMakeLists.txt
@@ -7,7 +7,7 @@ endif()

 # Default flags
 # To fix old python version bug http://bugs.python.org/issue21958
-if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
+if(${CMAKE_SYSTEM_NAME} MATCHES "Windows" AND NOT "${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU")
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DHAVE_ROUND /MT")
 endif()

@@ -282,7 +282,7 @@ if(PYTHON_BINDINGS)
     add_dependencies(test-python python-triton)

     execute_process (COMMAND python -c "from distutils.sysconfig import get_python_lib; print get_python_lib()" OUTPUT_VARIABLE PYTHON_SITE_PACKAGES OUTPUT_STRIP_TRAILING_WHITESPACE)
-    if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
+    if(${CMAKE_SYSTEM_NAME} MATCHES "Windows" AND NOT "${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU")
         install (FILES ${CMAKE_CURRENT_BINARY_DIR}/\${CMAKE_INSTALL_CONFIG_NAME}/triton${PYTHON_SUFFIX} DESTINATION ${PYTHON_SITE_PACKAGES})
     else()
         install (FILES ${CMAKE_CURRENT_BINARY_DIR}/triton${PYTHON_SUFFIX} DESTINATION ${PYTHON_SITE_PACKAGES})`

**Comment by JonathanSalwan** [comment]
Is #506 working for you?

**Comment by gyorokpeter** [comment]
Yes but only for the first error.

**Comment by JonathanSalwan** [comment]
What about #507?

**Comment by gyorokpeter** [comment]
That's much better.
