### ISSUE TITLE
Some feature suggestions for python API

### ISSUE THREAD

**Issue by Jinmo** [JonathanSalwan/Triton#512]
Recently I tried to use triton in my project, and thought these can be useful for triton. So I made this issue.

1. SymbolicExpression.getOriginRegister as getOriginRegisters

- ex. `add eax, ebx` has `eax` & `ebx` as origin registers, so I think this API can be modified to `getOriginRegisters` to obtain all registers of it.

~~2. Instruction.getFirst/Second/ThirdOperand() as getOperands()~~

~~- gonna be a little bit cool~~

(Sorry, I just found it)

**Comment by Jinmo** [comment]
(removed get top registers suggestion after finding getParentRegisters)

**Comment by JonathanSalwan** [comment]
`getOperands()` already exists.

**Comment by JonathanSalwan** [comment]
A symbolic expression has only one origin. It makes no sense for me to provide several origins. I think what you are looking for are:

* instruction::getReadRegisters()
* instruction::getWrittenRegisters()
* API::sliceExpressions()

**Comment by Jinmo** [comment]
Ah, thanks! I think I misunderstood origin as source references.

**Comment by JonathanSalwan** [comment]
yeah indeed, `origin` is related to the destination assignment of an expression.
