### ISSUE TITLE
PyInstance_Check to PyInstruction_Check in tritonCallbacks.hpp (python binding)

### ISSUE THREAD

**Issue by Jinmo** [JonathanSalwan/Triton#513]
In triton_createSymbolicRegisterExpression (see <--).

```cpp
      static PyObject* triton_createSymbolicRegisterExpression(PyObject* self, PyObject* args) {
        PyObject* inst          = nullptr;
...
        if (inst == nullptr || (!PyInstance_Check(inst))) // <-- must be PyInstruction_Check
          return PyErr_Format(PyExc_TypeError, "createSymbolicRegisterExpression(): Expects an Instruction as first argument.");
```

Since Instruction class makes PyInstance_Check as false, it causes error on any valid instruction.
Other functions doesn't have this error. ex. triton_processing (see <--):

```cpp
      static PyObject* triton_processing(PyObject* self, PyObject* inst) {
        /* Check if the architecture is definied */
        if (triton::api.getArchitecture() == triton::arch::ARCH_INVALID)
          return PyErr_Format(PyExc_TypeError, "processing(): Architecture is not defined.");

        if (!PyInstruction_Check(inst)) // <-- valid check
          return PyErr_Format(PyExc_TypeError, "processing(): Expects an Instruction as argument.");
```

PyInstance_Check is in

- triton_createSymbolicFlagExpression
- triton_createSymbolicMemoryExpression
- triton_createSymbolicRegisterExpression
- triton_createSymbolicVolatileExpression

**Comment by Jinmo** [comment]
woah, so many commit logs.. Just created a PR without unittest. Unittest for it would be cool.

**Comment by JonathanSalwan** [comment]
Nice shot, [will be merged](https://github.com/JonathanSalwan/Triton/pull/514#issuecomment-292724819)
