### ISSUE TITLE
Specific nopw instruction not understood

### ISSUE THREAD

**Issue by mikebentley15** [JonathanSalwan/Triton#516]
I tried the disassemble example with instructions from my binary compiled with g++.  I am using the python interface with Triton from git sha 3473fb580c896e519b04b4f239b4eda9d467213f.

The instruction it chokes on is:
  404ac7:	66 0f 1f 84 00 00 00 	nopw   0x0(%rax,%rax,1)
This output is from objdump -d <binary>.  The simplest example that can reproduce the problem is attached.

    #!/usr/bin/env python2
    '''
    Script that demonstrates the bug within Triton with a particular nopw
    instruction.
    
    The instruction it chokes on is:
      404ac7:	66 0f 1f 84 00 00 00 	nopw   0x0(%rax,%rax,1)
    This output is from objdump -d <binary>.
    
    I see that Triton can handle other nopl and nopw instructions, and for some
    reason, does not handle this one well.
    '''
    import triton as T
    
    def main():
        'Main test'
        inst_addr = 0x404ac7
        inst_bin = '\x66\x0f\x1f\x84\x00\x00\x00'
        T.setArchitecture(T.ARCH.X86_64)
        inst = T.Instruction()
        inst.setOpcodes(inst_bin)
        inst.setAddress(inst_addr)
        print(inst)
        T.processing(inst)
    
    if __name__ == '__main__':
        main()

**Comment by mikebentley15** [comment]
I actually let it continue and log each problem instruction contained in my binary.  There is an extensive list of 10889 instances of exceptions thrown from T.processing(), 1710 of them are unique.  I'm starting to wonder if I'm using this correctly.

Here is the code I use and all of the 1710 unique problem instructions that were found.  Please let me know if I'm using this tool correctly so far.

    #!/usr/bin/env python2
    '''
    Script to extract assembly instructions for each test from the FLiT test
    executable
    '''
    
    import triton as T
    
    import argparse
    import subprocess as subp
    import sys
    from collections import namedtuple
    
    Instr = namedtuple('Instr', 'addr bin instr args')
    
    def objdump_line_to_instr(line):
        addr, remaining = line.split(':', 1)
        instr_name = None
        args = None
    
        addr = int(addr, base=16)
        remsplit = remaining.strip().split('\t', 1)
        instruction_string = remsplit[0]
        if len(remsplit) > 1:
            remaining = remsplit[1]
            remsplit = remaining.split(' ', 1)
            instr_name = remsplit[0]
            if len(remsplit) > 1:
                args = remsplit[1].strip()
    
        instr = bytes()
        for elem in instruction_string.split():
            instr += chr(int(elem, base=16))
    
        return Instr(addr, instr, instr_name, args)
    
    def get_binary(exe, start=None, stop=None):
        '''
        Returns the binary as a list of tuples, each tuple being a single assembly
        instruction.  The tuples are (int address, bytes instruction)
        '''
        binary = []
        command = ['objdump', '-d', exe]
        if start is not None:
            command.append('--start-address={0}'.format(hex(start)))
        if stop is not None:
            command.append('--stop-address={0}'.format(hex(stop)))
        objdump = subp.check_output(command).decode()
        start_parsing = False
        for line in objdump.splitlines():
            if not start_parsing:
                start_parsing = line.startswith('0')
                continue
            elif line == '':
                start_parsing = False
                continue
            binary.append(objdump_line_to_instr(line))
        return binary
    
    def try_triton(binary):
        T.setArchitecture(T.ARCH.X86_64)
        problem_instructions = []
        problem_map_unique = {}
        for elem in binary:
            #print(elem)
            inst = T.Instruction()
            inst.setOpcodes(elem.bin)
            inst.setAddress(elem.addr)
            #print(inst)
            try:
                T.processing(inst)
            except TypeError:
                problem_instructions.append((elem, inst))
                problem_map_unique[elem.bin] = (elem, inst)
        print('Problem instructions:')
        i = 0
        #for elem, inst in problem_instructions:
        for elem, inst in problem_map_unique.values():
            i += 1
            print('  Problem #{0}'.format(i))
            print('    instr:  ' + str(inst))
            print('    addr:   ' + hex(elem.addr))
            print('    opcode: ' + elem.bin.__repr__())
            print('    type:   ' + str(elem.instr))
            print('    args:   ' + str(elem.args))
    
    def main(arguments):
        'Main entry point'
        parser = argparse.ArgumentParser()
        parser.add_argument('test_executable', help='Executable to extract from')
        args = parser.parse_args(arguments)
        full_binary = get_binary(args.test_executable)
        try_triton(full_binary)
    
    if __name__ == '__main__':
        main(sys.argv[1:])
    
And for the output can be seen in this uploaded file: [tmp-report-uniq.txt](https://github.com/JonathanSalwan/Triton/files/911213/tmp-report-uniq.txt)

**Comment by JonathanSalwan** [comment]
@mikebentley15 regarding second script, how can you handle multilines of opcode in the objdump output?

**Comment by mikebentley15** [comment]
I'm sorry, I don't know what you mean.  Could you give me an example?

**Comment by JonathanSalwan** [comment]
```console
$ objdump -d /usr/bin/id | grep nop -A 2
  402358:       0f 1f 84 00 00 00 00    nop    DWORD PTR [rax+rax*1+0x0]
  40235f:       00 
  402360:       31 ed                   xor    ebp,ebp
--
  40238a:       66 0f 1f 44 00 00       nop    WORD PTR [rax+rax*1+0x0]
  402390:       b8 df 92 60 00          mov    eax,0x6092df
  402395:       55                      push   rbp
--
  4023b7:       66 0f 1f 84 00 00 00    nop    WORD PTR [rax+rax*1+0x0]
  4023be:       00 00 
  4023c0:       5d                      pop    rbp
--
  4023c2:       0f 1f 40 00             nop    DWORD PTR [rax+0x0]
  4023c6:       66 2e 0f 1f 84 00 00    nop    WORD PTR cs:[rax+rax*1+0x0]
  4023cd:       00 00 00 
  4023d0:       be d8 92 60 00          mov    esi,0x6092d8
[...]
```

Take a look to the instruction `402358`, `4023b7` and `4023c6`. Basically, for each opcode size > 7 bytes, the dump is on 2 lines.

**Comment by mikebentley15** [comment]
Aw, I see.  Well, I guess I'm not handling that, which would account for the problems that list "type: None".  I'll work on updating the script.  Do you think that's what's causing this problem to appear?  I'll see if all of the 1710 instances are due to this.  Thanks!

**Comment by JonathanSalwan** [comment]
> Do you think that's what's causing this problem to appear?

I'm pretty sure. I tested your script on my `/usr/bin/id`. For example I got this issue: 

```
  Problem #82
    instr:  0x405bb8: 
    addr:   0x405bb8
    opcode: 'H\x8d4\x8d\x00\x00\x00'
    type:   lea
    args:   rsi,[rcx*4+0x0]
```

but a `lea rsi,[rcx*4+0x0]` is `H\x8d4\x8d\x00\x00\x00\x00` (one `\x00` is missing)

**Comment by mikebentley15** [comment]
Alright, I've investigated and found that you are correct.  Nice one!  Every single one of the 1710 unique instances was due to my script not handling multi-line instruction output.  I'll fix that in the script.  If after I fix that in the script, the Triton tool behaves well, then this ticket can close.  Thanks!

**Comment by JonathanSalwan** [comment]
> If after I fix that in the script, the Triton tool behaves well, then this ticket can close. 

if not and if you are 100% sure of your opcodes. The issue comes from [capstone](https://github.com/aquynh/capstone) which cannot disassemble the given opcode. So, I suggest to open an issue on their github page :)

**Comment by mikebentley15** [comment]
I've put in a hack, and it seems that Triton behaved wonderfully (or as you say the capstone component).  So we're good.  The workaround I have in place now is simply to specify `--insn-width=<large number>` to force instructions to be on a single line.  The large number I chose is 100.  I might go in later and make my script truly handle multiple line instructions.

Thanks, this was a false alarm.

**Comment by JonathanSalwan** [comment]
. Thanks, this was a false alarm.

woot.

> The large number I chose is 100

Just for your information, the max opcode size of an x86 instruction is 15 bytes :).
