### ISSUE TITLE
"setArchitecture" is not defined 

### ISSUE THREAD

**Issue by Hearmen** [JonathanSalwan/Triton#533]
when I use the file download from “https://ci.appveyor.com/project/JonathanSalwan/triton/build/job/40y5aeajs8xha41w/artifacts” directly，there is always an error said "name 'setArchitecture‘ is not defined ". Is anybody knows why it happend

**Comment by JonathanSalwan** [comment]
download the artifact of the `dev-next` or the `master` branches.

**Comment by Hearmen** [comment]
Oh ! thank you, Its my fault~
