### ISSUE TITLE
How can I specify to use python2 instead of python3 when build?d

### ISSUE THREAD

**Issue by Escapingbug** [JonathanSalwan/Triton#537]
This is a great project. But I found something troubling me when I am building this. My default python version is 3, it seems this project just support python2 for now, but I don't know how to set this to use python2 instead of default version python, which is python3.

Seems if I don't do this, I will get this error when building:
```
-- Found Z3 
-- Found CAPSTONE 
-- Boost version: 1.63.0
  File "<string>", line 1
    from distutils.sysconfig import get_python_lib; print get_python_lib()
                                                                                                             ^
SyntaxError: invalid syntax
CMake Error at src/libtriton/CMakeLists.txt:294 (install):
  install FILES given no DESTINATION!


-- Configuring incomplete, errors occurred!
See also "/home/anciety/temp/Triton/build/CMakeFiles/CMakeOutput.log".
```
Since this problem is due to the difference usage of print in python2 and 3, I think the first mentioned problem caused this. I truly need some ideas t make this run, thanks~ :)

**Comment by JonathanSalwan** [comment]
Erf, it was fixed into `dev-pb` over c120c4ddddc88a82129804ac38c8b2c66af86180 but not pushed into `master`. I just merged the patch into master. Is it ok now?

**Comment by Escapingbug** [comment]
I just saw this message, I'm gonna try this later. Thanks for such quick response :)

**Comment by Escapingbug** [comment]
Yup, it worked. So I close this issue now.
