### ISSUE TITLE
Multiple Values for AST?

### ISSUE THREAD

**Issue by Owlz** [JonathanSalwan/Triton#539]
I'm trying to figure out how to use Triton to get multiple values for a single ast. Trying the following doesn't work:

```python
triton.getModels(triton.ast.assert_(ast == ast) ,2)
```

It just gives back an empty list (though it would seen ast == ast is tautologically true). How do I ask for multiple values of an ast back?

Related, the values that I get back in the models expose a symbolic variable name. However, I didn't get these asts (directly at least) through using a symbolic variable. How do I match them up with the input asts?

EDIT: I should say that my use case here is effectively from looking up memory locations. So basically, I would want to evaluate what's at memory 0x1000 and 0x10001 for instance, and would want to be able to get those back from the model to understand what values they could be. Getting them directly from `triton.getSymbolicMemory()` -> getAst -> getModels appears to be how this is done. However, even if I get the model to return, it's not clear to me how to put the pieces back together to know what was at 0x1000 and 0x10001. Especially if that memory area was create as a large chunk and I'm only interested in a byte here and there.

**Comment by Owlz** [comment]
Perhaps one solution for this would be to allow extra asts/expressions to be added to the `evaluate` call. Also, add a `number` param if I want to find more than one. The key is that I want to be able to add more expressions to the model (for example, adding the path constraints and some more of my own), and find as many possibilities for a value as I need to.

**Comment by JonathanSalwan** [comment]
> The key is that I want to be able to add more expressions to the model (for example, adding the path constraints and some more of my own), and find as many possibilities for a value as I need to.

You can use the [compound](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/pin/crackme_hash_collision.py#L70) node to do this.
