### ISSUE TITLE
AST extract on byte-length variables

### ISSUE THREAD

**Issue by Owlz** [JonathanSalwan/Triton#542]
I created an example byte-length symbolic variable, and I see the following:

```python
In [33]: print(ast)
((_ extract 7 0) SymVar_1)
In [35]: symvar.getBitSize()
Out[35]: 8L
```

Given the byte is as large as it ever will be (and I don't see any specific methods for bit level instead of byte level operations), it seems that the initial ```(_ extract 7 0)``` is superfluous. Not clear how much of an impact this would have on the solver, but it certainly couldn't hurt to put in a check:

Pseudo
```
if SymVar.getBitSize() == 8:
    return SymVar
else:
    return <extract> SymVar
```

**Comment by JonathanSalwan** [comment]
This is exactly kinds of things you have to do by yourself using [SMT simplification passes](https://triton.quarkslab.com/documentation/doxygen/SMT_simplification_page.html). We do this to be generic in so many cases and don't have to do your pseudocode everywhere for so many cases :). Maybe one day we will release a list of simplifications or add some simplifications by default but currently you have to do it by yourself.

**Comment by Owlz** [comment]
Interesting. Haven't looked into the simplification stuff. I'll take a look at it. Thanks!
