### ISSUE TITLE
State serialization/deserialization?

### ISSUE THREAD

**Issue by Owlz** [JonathanSalwan/Triton#543]
To follow on with my previous ticket about state splits, it would be helpful to have some way to serialize Triton's state. My guess is this would happen on the Context objects that you're working on. I'd like to be able to take a context, write it to disk for later use, delete it (and free associated memory), then later load it from disk and restore the state that I was at.

**Comment by JonathanSalwan** [comment]
Did you saw the `dev-pb` branch (which is the new API)? There is now a [Triton's context](https://github.com/JonathanSalwan/Triton/blob/dev-pb/src/examples/python/ir.py#L55). You may also see the #532 issue.

**Comment by Owlz** [comment]
So saw that there's a Triton context object. Wasn't clear if state copying (in memory) also meant it would be serializable to disk.

**Comment by JonathanSalwan** [comment]
Oh I misunderstood your question. Yeah there is no feature about to serialize on disk and I don't know if we will add this feature in a near future.
