### ISSUE TITLE
AST Evaluate Confusion?

### ISSUE THREAD

**Issue by Owlz** [JonathanSalwan/Triton#547]
Maybe I'm misunderstanding the point of `ast.evaluate`. I'm creating an ast object on-the-fly using python operators. When calling evaluate, I'm not getting the results I would expect.

Example:
```python
In [1]: import triton

In [2]: triton.setArchitecture(triton.ARCH.X86_64)

In [3]: triton.convertMemoryToSymbolicVariable(triton.MemoryAccess(0x400238,32))
Out[3]: <SymbolicVariable at 0x7f1eab7cdf90>

In [4]: exp = triton.getSymbolicMemory()[0x400238]

In [5]: exp
Out[5]: <SymbolicExpression at 0x7f1ea9737060>

In [6]: ast = exp.getAst()

In [7]: ast
Out[7]: <AstNode at 0x7f1ea97443d8>

In [8]: str(ast)
Out[8]: '((_ extract 7 0) SymVar_0)'

In [9]: ast.evaluate()
Out[9]: 0L

In [10]: str(ast != 0)
Out[10]: '(not (= ((_ extract 7 0) SymVar_0) (_ bv0 8)))'

In [11]: (ast != 0).evaluate()
Out[11]: 0L
```

My assumption would be that the last one there would not return 0 as a possibility (given I just put a constraint saying it was not equal to zero). I've tried it with assert as well:

```python
In [13]: print(triton.ast.assert_(ast != 0))
(assert (not (= ((_ extract 7 0) SymVar_0) (_ bv0 8))))

In [14]: triton.ast.assert_(ast != 0).evaluate()
Out[14]: 0L
```

**Comment by JonathanSalwan** [comment]
`evaluate` just computes the tree. In your case, the value of your symbolic variable is 0, so for me the formula is correct `0 != 0 returns false`.

**Comment by Owlz** [comment]
Ok. Think I get it.. Thanks!
