### ISSUE TITLE
Tutorial on Triton

### ISSUE THREAD

**Issue by vancaho** [JonathanSalwan/Triton#556]
I find triton is suitable for my requirement of analyzing binaries, but I'm new to Triton. Is there any tutorials or detailed examples that explain how to use triton to do taint analysis, symbolic execution, or vulnerability analysis as that have been done in Angr platform.   Thanks very much

**Comment by JonathanSalwan** [comment]
* https://github.com/JonathanSalwan/Triton/tree/master/src/examples
* https://triton.quarkslab.com/documentation/doxygen/py_triton_page.html
* https://triton.quarkslab.com/blog
