### ISSUE TITLE
AST Type Definition

### ISSUE THREAD

**Issue by Owlz** [JonathanSalwan/Triton#557]
Two related issues/questions. First, I get a python garbage collection error sometimes based around AST garbage collector being undefined:

```python
__________________________________________________________________________ ERROR collecting tests/state/plugins/memory/test_memory.py ___________________________________________________________________________
tests/state/plugins/memory/test_memory.py:4: in <module>
    import larissa.State.plugins.memory
larissa/State/plugins/memory.py:5: in <module>
    from .SolverEngine import Byte
larissa/State/plugins/SolverEngine/__init__.py:213: in <module>
    from .Byte import Byte
larissa/State/plugins/SolverEngine/Byte.py:156: in <module>
    Ast = type(triton.ast.bv(1,1))
E   TypeError: API::checkAstGarbageCollector(): AST garbage collector is undefined.
====================================================================================== 87 passed, 1 error in 6.14 seconds =======================================================================================
```

While that is likely something that need to be fixed of it's own, i'm currently using that hack because I cannot find a place in the Triton API that exposes the class directly. For example, I would rather use something like `triton.ast_type` instead of using the `type` python command to get the type definition. However, I cannot find the type definition exposed anywhere.

**Comment by JonathanSalwan** [comment]
Yep, I think it's the only way to expose the type of a AST node. About the raise, you must define an architecture before `setArchitecture(ARCH.X86)`, it doesn't matter if it's `X86` or `X86_64`.

**Comment by Owlz** [comment]
Ah. Ok. Yeah that fixed it. Thanks!
