### ISSUE TITLE
Simulating the execution of a trace

### ISSUE THREAD

**Issue by vancaho** [JonathanSalwan/Triton#560]
Hi,  I want to use triton to analysis a trace which is collected with a pintool.  In the trace, I recorded the instructions, register values, memory accesses, and stored it into a sqlite db. I want to do taint analysis and symbolic execution on the trace with triton.

   By referring the tutorial: https://triton.quarkslab.com/documentation/doxygen/Tracer_page.html, I added functions to acquire opcodes, register values and memory accesses. However, after using the codes in the trace, I have the following question:  when processing sysenter, wait or some specific  instructions, the register values after processing the instructions are not matched with the values recorded in the trace. So how to do with above instructions? Do I have to set the values of the mismatched registers to the trace with concretizeRegisterValue() or something else?
 
Thanks very much

**Comment by JonathanSalwan** [comment]
Indeed, sometime you may have some desynchronization due to unsupported instructions (`processing()` returns `False` if the instruction is not supported). When it occurs, you have to do:

1) `concretizeRegisterValue()`
2) `setConcreteRegisterValue()`

**Comment by vancaho** [comment]
Thanks Jonathan. But for syscalls  (e.g. sysenter), as it may modify some memory areas in the kernel mode, how can I know which memory cell is read/written by the syscall?  Should I model  the behavior for each syscall?

**Comment by JonathanSalwan** [comment]
> Should I model the behavior for each syscall?

Yep.
