### ISSUE TITLE
Annotating taints

### ISSUE THREAD

**Issue by bntejn** [JonathanSalwan/Triton#561]
Hi, I'm a testing researcher who's interested in extending **Triton**'s taint analysis engine. I skimmed through **Triton**'s code in the past few days (while comparing it with other open-sourced projects) and was impressed with its beauty. Thank you for sharing a great project!

What I need to implement is **a capability to annotate the taints**, so that the *tags* (additional information) assigned to each taint on memory-byte/register can propagate along with the *taints*. This is necessary for my research since my application requires an additional information (tag) to be generated in the middle of the program (not from the user-provided input) so that at the end of the program execution, only the propagated tags can be collected. I think the tagging feature can also be useful for typical taint analysis, allowing the user to annotate extra information on the taints.

My questions are:

1. Would this feature be a useful contribution to **Triton**?
2. If so, what would be the best way to implement such feature while not breaking the integrity and elegance of the existing codebase?
3. How can I generate Python bindings for additional methods/classes I implement?

**p.s.** In case you're interested, here is an [initial prototypical implementation](https://github.com/bntejn/Triton/commit/08acc203e515aa4996502eb76309e14359420c0e) in my fork. I added an interface class `TagType` inside `triton::engines::taint`, added two maps `reg -> tags` and `mem -> tags` inside `triton::engines::taint::TaintEngine`,  and modified the internal propagation functions (such as `TaintEngine::assignmentMemoryRegister`) to propagate the tags accordingly.

Thanks,
-TJ

**Comment by JonathanSalwan** [comment]
Thanks for this proposal. Let me few time to think about it.

**Comment by bntejn** [comment]
Thank you for your interest! Until you fix the branch, I will implement and experiment this feature on my own fork.

**Comment by JonathanSalwan** [comment]
#596

**Comment by JonathanSalwan** [comment]
#596
