### ISSUE TITLE
Symbolic Registers Question

### ISSUE THREAD

**Issue by Owlz** [JonathanSalwan/Triton#563]
It's not clear to me how symbolic registers might be handled. I'm running the following instructions to symbolize AX:

```python
convertRegisterToSymbolicVariable(REG.AX)
```

This works fine. However, when I attempt to read `ax` and `eax`, they appear to come back as the same thing:

```python
x = getSymbolicExpressionFromId(getSymbolicRegisterId(REG.AX))
y = getSymbolicExpressionFromId(getSymbolicRegisterId(REG.EAX))
print(x)
#ref!0 = SymVar_0
print(y)
#ref!0 = SymVar_0
x.getAst().getBitvectorSize()
# 16L
y.getAst().getBitvectorSize()
# 16L <-- EAX is 32 bits, not 16.
```

What I'm taking from this is that `AX` was indeed symbolized. However, if I then wanted to interact with `EAX`, instead of getting `EAX` back, I would get `AX`. Expected output would be a partially symbolic variable or something.

Example:

1. I initialize EAX == 0
2. I symbolize AX
3. I ask for possible values of EAX (which would be any 16 bit value)

Obviously that example is trivial, but I hope it gets my question across.

**Comment by JonathanSalwan** [comment]
Thanks for this issue. Actually there is a bug but not the one you think. You should get a 32-bits expressions and not a 16-bits one. Why? Because Triton always assign expressions to the parent register and `getSymbolicRegisterId` returns the parent register id. So, `x` and `y` hold the same expression (the `EAX` one).

If you want to create child expressions, please use `buildSymbolicRegister()`. Regarding your example, below a potential workaround (if you are working on the `master` branch maybe the code must be updated).

```python
from triton import *                                           

ctx = TritonContext()                                          
ctx.setArchitecture(ARCH.X86)                                  
                                                               
ctx.convertRegisterToSymbolicVariable(ctx.Register(REG.X86.AX))
                                                               
eax = ctx.buildSymbolicRegister(ctx.Register(REG.X86.EAX))     
ast = ctx.getAstContext()                                      
                                                               
constraint1 = ast.assert_(eax == 0x1337)                       
print ctx.getModel(constraint1) # sat

constraint2 = ast.assert_(eax == 0x31337)                      
print ctx.getModel(constraint2) # unsat
```

**Comment by Owlz** [comment]
Haven't been able to test this on the development branch, but on Master getting `EAX` when you have symbolized `AX` seems to give errors:

```python
In [44]: ast = triton.buildSymbolicRegister(triton.REG.AX)

In [45]: print(ast)
((_ extract 15 0) ref!0)

In [46]: ast = triton.buildSymbolicRegister(triton.REG.EAX)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-46-f6af8c34405c> in <module>()
----> 1 ast = triton.buildSymbolicRegister(triton.REG.EAX)

TypeError: ExtractNode::init(): The size of the extraction is higher than the child expression.
```
