### ISSUE TITLE
compiling c++ examples on windows

### ISSUE THREAD

**Issue by chq007** [JonathanSalwan/Triton#568]
Hi Triton team,

I compiled Triton on windows and everything goes well. I can successfully run the python examples without any problems. However,  when I tried to compile c++ examples from Triton project using Visual Studio 2015 and added triton.lib, I got many Link errors as follows:

    Error LNK2001: unresolved external symbol "public: void __cdecl triton::API::setArchitecture(unsigned int)" (?setArchitecture@API@triton@@QEAAXI@Z)
    ErrorLNK2001	unresolved external symbol "class triton::API triton::api" (?api@triton@@3VAPI@1@A)	
	

I also tried to compile the c++ example using vs 2015 native tools command prompt using the following command and still got the same problem:

    cl ir.cpp /I path_to_triton\src\libtriton\includes /I path_to_boost\boost_1_64_0 /I path_to_z3\include triton.lib libz3.lib triton.lib

Would you please tell me how to compile the cpp examples?

**Comment by JonathanSalwan** [comment]
I'm not really comfortable with the Windows OS. Maybe someone else may help?

**Comment by JonathanSalwan** [comment]
Is it ok? Can I close it?

**Comment by douggard** [comment]
I'm having the same problem with `triton.lib` trying to integrate it into a project. Comparing it (in a hex editor) with `xed.lib`, it is very short. It appears there are no entries for functions.

It also doesn't open as an AR archive (in 7z), which I guess is what `lib` files are. I will post any updates I figure out.

**Comment by douggard** [comment]
There is a single export in the lib and the DLL, `inittriton` which seems related to the Python API. I don't really see any references to that in the C++ API.

**Comment by douggard** [comment]
I think the code needs a bunch of `__declspec(dllexport)` to export functions on Windows. The reason the `inittriton` was exported was the `PyMODINIT_FUNC` is defined to that on Windows.

[An example PyMODINIT_FUNC definition.](https://github.com/python/cpython/blob/c06c22e9a9fb9326e79fcf1551601eacc1fd457d/Include/pyport.h#L640)

Maybe a solution like below, then pollute the code with `EXPORT` on every API function. Or maybe a script to fix it up on Windows. 

```c
#if defined(WIN32)
#define EXPORT __declspec(dllexport) 
#else
#define EXPORT __attribute__((visibility("default"))) 
#endif
```

**Comment by JonathanSalwan** [comment]
Is there a flag on windows which allows us to export all functions at the compile time?

**Comment by JonathanSalwan** [comment]
@douggard i've pushed a [patch](https://github.com/JonathanSalwan/Triton/commit/1c468a0839f762b4c4e62aaca5048899aeb80b6c) using dllexport. Can you try this [branch](https://github.com/JonathanSalwan/Triton/tree/dev-dllexport) and tell me if it's ok?

**Comment by JonathanSalwan** [comment]
It's really funny to dev in blind =). Opening the `triton.dll` provided by appveyor into my IDA, I can see exported functions now. As I don't have a Windows OS under the elbow, if you can tell me if it's ok, I will really appreciate :)

![2017-12-05-145651_1600x900_scrot](https://user-images.githubusercontent.com/991046/33610788-a96e5512-d9cc-11e7-8f15-58deba5c6aaa.png)

**Comment by douggard** [comment]
My project builds with the new lib, thanks for the quick fix!

>As I don't have a Windows OS under the elbow

This is the right way to live, the kernel gets its power from developer confusion and pain.

**Comment by JonathanSalwan** [comment]
@chq007 is it ok for you too?

**Comment by douggard** [comment]
Since this issue is related to Windows examples, I get a crash with a stripped down version of the `ir` example. This fails with a stack cookie check on Windows (`Unhandled exception at 0x00007FF78E9B2370 in prog.exe: Stack cookie instrumentation code detected a stack-based buffer overrun.`)

```cpp
#include "stdafx.h"
#include <iostream>
#include <triton/api.hpp>
#include <triton/x86Specifications.hpp>

using namespace triton;
using namespace triton::arch;

int main(int ac, const char **av) {

	triton::API api;
	/* Set the arch */
	api.setArchitecture(ARCH_X86_64);
	uint8_t buf[4] = { 0x47, 0x83, 0xec, 0x28 };

	/* Build an instruction */
	Instruction inst;

	/* Setup opcode */
	inst.setOpcode(buf, 4);

	/* Process everything */
	api.processing(inst);

	return 0;
}
```

Integrating it into my code I get a failure on `api->processing(inst)`.

![image](https://user-images.githubusercontent.com/982598/33631149-9e1aa9c6-d9d7-11e7-8819-61ac5c283430.png)

The exact crashing address (`*98be`). Which is in `IrBuilder::buildSemantics` called from `processing`.

![image](https://user-images.githubusercontent.com/982598/33631202-d23ec818-d9d7-11e7-91e2-8908799b494f.png)

**Comment by JonathanSalwan** [comment]
Well, i finally installed a windows 10... I've installed `boost 1.63`, `python2.7`, VS 2017 community, downloaded the last [artifact](https://ci.appveyor.com/project/JonathanSalwan/triton/build/0.6.2455/job/n0hj3iuhqmi99yi8/artifacts) of appveyor to get `triton.dll` and `triton.lib`. After generating the solution of your example with VS it seems to work =/. 
![1](https://user-images.githubusercontent.com/991046/33652560-3792da1e-da6a-11e7-93d6-0cf1b9fd39f6.png)

**Comment by douggard** [comment]
I do not see a `triton.dll` in those artifacts, it has a `libz3.dll`.

**Comment by JonathanSalwan** [comment]
the .pyd is a dll file. Just rename it.

**Comment by JonathanSalwan** [comment]
Btw, we can now choose artifacts from different VS versions (2015 or 2017).

https://ci.appveyor.com/project/JonathanSalwan/triton/build/0.6.2476

**Comment by douggard** [comment]
It is probably build issues on my end. The compiled code does a `memset` for the `API` object for size `0x3d8`.

![image](https://user-images.githubusercontent.com/982598/33676453-c2dd289a-da83-11e7-9445-a8b1f30bd85d.png)

However, in the API constructor, it accesses the object at offset `0x3e0` which is actually the stack cookie.

![image](https://user-images.githubusercontent.com/982598/33676530-f43166ae-da83-11e7-94d2-ed14b25a2423.png)

I will clean and reconfigure everything. Thanks for all the help.

**Comment by douggard** [comment]
I had some old includes (didn't point the project to the Triton dir but instead copied them in). It's working now. 👍

**Comment by JonathanSalwan** [comment]
Yeah ! I'm closing this issue then. Thanks for feedback! Feel free to open any issues in the future, we miss windows beta testers :)

**Comment by JonathanSalwan** [comment]
I will merge the `dev-dllexport` branch into the `dev-v0.6` as soon as i've done some tests.
