### ISSUE TITLE
Register: conrete->symbolic->concrete behavior

### ISSUE THREAD

**Issue by Owlz** [JonathanSalwan/Triton#569]
So I made the switch to the devpb branch. Playing around with registers more and I'm discovering an unexpected behavior. My steps are:

- Instantiate a triton context (registers have a base value of 0)
- `ctx.convertRegisterToSymbolicVariable` for some variable (for example: `AX`)
- `setConcreteRegisterValue` for that same register

I would expect that after setting concrete again, i would have a concrete value returned. However, this does not appear to be the case:

```python
In [5]: print(state.regs.ax._triton_symbolic_register)
(_ bv0 16)

In [6]: state.regs.ax.make_symbolic()

In [7]: print(state.regs.ax._triton_symbolic_register)
((_ extract 15 0) ref!0)

In [8]: state.regs.ax.set(12)

In [9]: print(state.regs.ax._triton_symbolic_register)
((_ extract 15 0) ref!0)
```

However, simply setting directly works before making symbolic.

```python
In [11]: print(state.regs.bx._triton_symbolic_register)
(_ bv0 16)

In [12]: state.regs.bx.set(12)

In [13]: print(state.regs.bx._triton_symbolic_register)
(_ bv12 16)
```

My expected output in the first case would be ```(_ bv12 16)```

**Comment by JonathanSalwan** [comment]
Yeah. If something is already symbolic you have to use `concretizeRegister` before setting a concrete value.

**Comment by Owlz** [comment]
Gotcha. Is there a use case for setting a concrete value without concretizing the register? Wondering why those two steps are separate.

**Comment by JonathanSalwan** [comment]
> Is there a use case for setting a concrete value without concretizing the register? 

Nop you cannot. You must concretize it. However, if you want to concretize a symbolic variable, you can do `setConcreteSymbolicVariableValue(symvar, value)`.

**Comment by JonathanSalwan** [comment]
> Wondering why those two steps are separate.

Historically, it was for the Pin tracer's design to keep a good synchronization between Triton and Pin. In a long term goal, I will redesign the Pin Tracer (like we did with the `dev-pb`) and merge this two steps into only one.

**Comment by Owlz** [comment]
Alright. Not a big deal. I basically just automated the `concretizeRegister` call which fixed it. Thanks!
