### ISSUE TITLE
TypeError: SymbolicEngine::buildSymbolicOperand(): Invalid operand

### ISSUE THREAD

**Issue by chq007** [JonathanSalwan/Triton#574]
Hi,

I used pintool to record the whole instruction trace of a simple program, and then tried to do symbolic emulation for the recorded instruction trace using python binding. And I found that the python binding will always raise an exception when handling the instruction as shown in the following python code:

    from triton import *
    
    eip = 0x7c80af21
    opcodes = '\xa0\x28\x57\x88\x7c'  # mov al, byte ptr[0x7c885728]

    setArchitecture(ARCH.X86)
    inst = Instruction()
    inst.setOpcodes(opcodes)
    inst.setAddress(eip)
    processing(inst)

The exception is as follows:
TypeError: SymbolicEngine::buildSymbolicOperand(): Invalid operand.

Could anybody help me to figure out the problem?

**Comment by JonathanSalwan** [comment]
Looks like it's a Capstone issue. Capstone decodes the instruction as unique operand (the second one) and seems to miss the `al` register =(.

```python
from capstone import *                                                
                                                                      
CODE = b'\xa0\x28\x57\x88\x7c'                                        
                                                                      
md = Cs(CS_ARCH_X86, CS_MODE_32)                                      
md.detail = True                                                      
for inst in md.disasm(CODE, 0x1000):                                  
    print("0x%x:\t%s\t%s" %(inst.address, inst.mnemonic, inst.op_str))
    for op in inst.operands:                                          
        print op                                                      
```

**Comment by chq007** [comment]
The capstone team confirmed this problem and fixed it yesterday.

**Comment by JonathanSalwan** [comment]
Great!

**Comment by StablelJay** [comment]
I also try to use Dynamic Symbolic Engine of triton and I record instruction trace of a program using pin-2.14-71313, what should I do first?
