### ISSUE TITLE
E: bad swFree of ptr 0x7ffdd6a4b008 chunkSize=0

### ISSUE THREAD

**Issue by gaa-cifasis** [JonathanSalwan/Triton#583]
Hi,

I'm using Triton 0796f943f89470d022aed145a7ff6405de5005c1 and sometimes when I'm trying to execute getModel of some big formula, I'm getting:

`E: bad swFree of ptr 0x7ffdd6a4b008 chunkSize=0`

and the triton/python process ends.

**Comment by JonathanSalwan** [comment]
Yep. It's an out of memory issue. We fixed this issue via the pull request #582. We still have to test it before merging. Can you try it in your case and provide feedback?

**Comment by gaa-cifasis** [comment]
Uhm, I will need some time to port the changes in the new API to adapt our tool, since Triton now needs to keep a global context and we are using an isolated python process to execute all the discovered test cases. :-(

**Comment by JonathanSalwan** [comment]
Okay. However, i'm closing this issue cause it's fixed and will be merged into `dev-v0.6`. Anyway, i really suggest to switch into the `v0.6` branch, 'cause it will be merged very soon in master.

**Comment by gaa-cifasis** [comment]
It seems to be fixed in #582. 

Btw, the new code is significantly faster. Great work!

**Comment by JonathanSalwan** [comment]
Thanks!
