### ISSUE TITLE
How to locate the source register when diagnosing a crash instruction 

### ISSUE THREAD

**Issue by vancaho** [JonathanSalwan/Triton#586]
Hi, recently I am using triton to diagnose the crash. However I find some problems in locating the source registers when analyzing the crashed instruction. 
For example, the crashed instruction is: 
```
0x64866b2e: cmp byte ptr [ecx], 0
```
where `ecx`  is `0x41414141` and the memory at `0x41414141`  is not mapped. So it is a read violation at `0x41414141`.

Firstly I think maybe I can use the read registers of the instruction to find where `0x41414141` came from. However I find that the read registers of the `cmp` instruction is empty. 

So my question are does the `cmp` instruction read `ecx` register? How can I find the source of `0x41414141` using triton?

**Comment by JonathanSalwan** [comment]
Don't process the instruction at `0x64866b2e` and use `sliceExpressions` on the `ecx` register.

**Comment by vancaho** [comment]
How can I know `0x41414141` comes from `ecx` with triton?

**Comment by JonathanSalwan** [comment]
> Firstly I think maybe I can use the read registers of the instruction to find where 0x41414141 came from. However I find that the read registers of the cmp instruction is empty.

Mmmmh, are you using the `v0.5`?

**Comment by JonathanSalwan** [comment]
```python
>>> ctx = TritonContext()
>>> ctx.setArchitecture(1)
>>> 
>>> ctx.setConcreteRegisterValue(ctx.registers.ecx, 0x41414141)
>>> inst = Instruction("\x80\x39\x00") # cmp byte ptr [ecx], 0
>>> ctx.processing(inst)
True
>>> 
>>> for x in inst.getReadRegisters():
...     print x
... 
(ecx:32 bv[31..0], (_ bv1094795585 32))
>>> hex(1094795585)
'0x41414141'
```

**Comment by vancaho** [comment]
Yeap， I'm using triton 0.5. I will have a try on 0.6. Thanks very much.

**Comment by JonathanSalwan** [comment]
you're welcome.
