### ISSUE TITLE
how to set the value of symbolic reg?

### ISSUE THREAD

**Issue by delphi0127** [JonathanSalwan/Triton#587]
I want to collect the constraints of some specified path. so, I symbolize a reg, like REG.RAX. During processing, the default value of this symbolic variable is 0x0, the first taken path is not what I want. I hope it is 0x02. Even I initialize context like this:
`setConcreteRegisterValue(Register(REG.RAX, 0x2))`
it doesn't work.
how to fix it? Thanks.

**Comment by JonathanSalwan** [comment]
```python
var = convertRegisterToSymbolicVariable(REG.RAX)
var.setConcreteValue(0x2)
[...]
```

**Comment by delphi0127** [comment]
```
setConcreteRegisterValue(Register(RET.RAX, 0x2))
convertRegisterToSymbolicVariable(RET.RAX)
print getSymbolicRegisterValue(REG.RAX)
```
