### ISSUE TITLE
How to retrieve the source registers in memory loading

### ISSUE THREAD

**Issue by vancaho** [JonathanSalwan/Triton#588]
I want to get the source registers when processing instructions like ` cmp byte ptr [ecx], 1` where `ecx == 0x41414141` and it the memory address in this instruction comes from ecx. With the help of triton 0.6, I can use `getReadRegisters` to relate `0x41414141` with `ecx`. 

However if the instruction is `cmp dowrd ptr [ecx + esi + 4],  ebx` and `ecx+esi+4 == 0x41414141`, the registers returned by `getReadRegisters` will be `[ecx, esi, ebx]`, how can I relate `0x41414141` with `ecx` and `esi`?

I searched capstone for some help, and find the post [https://github.com/aquynh/capstone/issues/772](https://github.com/aquynh/capstone/issues/772) says that capstone can give information on which registers contribute to the read memory operand. So, how can I get this information with the help of triton?

Thanks very much!

**Comment by JonathanSalwan** [comment]
```python
>>> from triton import *
>>> 
>>> ctx = TritonContext()
>>> ctx.setArchitecture(1)
>>> 
>>> inst = Instruction("\x39\x5c\x31\x04") # cmp dword ptr [ecx + esi + 4], ebx
>>> ctx.processing(inst)
True
>>> 
>>> print inst
0x0: cmp dword ptr [ecx + esi + 4], ebx
>>> 
>>> op0 = inst.getOperands()[0]
>>> print op0
[@0x4]:32 bv[31..0]
>>> 
>>> print op0.getBaseRegister()
ecx:32 bv[31..0]
>>>
>>> print op0.getIndexRegister()
esi:32 bv[31..0]
>>>
>>> print op0.getDisplacement()
0x4:32 bv[31..0]
>>>
>>> print op0.getLeaAst()
(bvadd (_ bv0 32) (bvadd (bvmul (_ bv0 32) (_ bv1 32)) (_ bv4 32)))
>>>
>>> print op0.getLeaAst().evaluate()
4
>>>
```

**Comment by vancaho** [comment]
That is very very helpful. Thanks very much!
