### ISSUE TITLE
 `Pin is out of memory: MmapChecked` Error

### ISSUE THREAD

**Issue by vancaho** [JonathanSalwan/Triton#591]
Hi, I want to use libtriton to record and analyze the execution of an 32 bit binary on ubuntu 16.04 64bit. 
After installing `libboost-dev:1386`, `libcapstone-dev:i386`, `libpython-dev:i386`, `libcapstone-dev:i386`,  setting the architecture to `i386` and modifying the loading path of `libpython2.7.so` to `/usr/lib/i386-linux-gnu/libpython2.7.so`, I was able to compile the 32 bit version of `libtriton.so`.
 
Then I use the script `callback_signals.py` which is modified to match the `x86`architecture to catch an exception of the attached binary with the following command: `cat input | ./build/triton ./src/examples/pin/callback_signals.py ./binary`. Originally the `input` will trigger an exception of `binary.
[binary.tar.gz](https://github.com/JonathanSalwan/Triton/files/1223962/binary.tar.gz)

However, during the recording, I find that pin consumes lots of memory and finally reports the following error: `Pin is out of memory: MmapChecked` without reporting any exception caught. The memory size in my os is 32G. 

To find why the errors occur, I did two experiments. In the first experiment, I modify the `input` file  with contents `AAAAAAA` which will not crash the `binary` and run the `count_inst.py` script, and the script works correctly. But if I use the attached input file, `count_inst.py` complained `Pin is out of memory: MmapChecked` again.

In the second experiment, I modify the `count_inst.py` by  making it do no analysis and run it with the attached input.
```
#!/usr/bin/env python2
## -*- coding: utf-8 -*-

from pintool import *
from triton  import *

count = 0

def mycb(inst):
    global count
    count += 1

def fini():
    print count

if __name__ == '__main__':
    setArchitecture(ARCH.X86)
    startAnalysisFromEntry()
    #insertCall(mycb, INSERT_POINT.BEFORE)
    #insertCall(fini, INSERT_POINT.FINI)
    runProgram()

```
However, `Pin is out of memory: MmapChecked` still exists.

How to solve this problem? Is there any memory leak problem in triton? Thanks very much.

**Comment by vancaho** [comment]
After debugging, I find that in the crashed execution, there is a loop(from address `0x8048eda`) which is executed more than `2900` times, whereas in the normal execution, the loop is only executed `9` times. So may be this is the reason that `libtriton.so` consumes so much memory.  Is there any way to work around this problem?

**Comment by JonathanSalwan** [comment]
Pull the `dev-v0.6`, then you may disable the taint and the sym engine if they are not used in order to preserve RAM.
