### ISSUE TITLE
Where to obtain pin-2.14-71313 for Mac OSX?

### ISSUE THREAD

**Issue by bntejn** [JonathanSalwan/Triton#598]
The Mac version of Pin2 (71313) is not available on [PIN's download page](https://software.intel.com/en-us/articles/pin-a-binary-instrumentation-tool-downloads) anymore. I could neither find it anywhere online. Could someone share the tarball or a pointer to it?

**Comment by JonathanSalwan** [comment]
OSX: http://software.intel.com/sites/landingpage/pintool/downloads/pin-2.14-71313-clang.4.2-mac.tar.gz
Linux: http://software.intel.com/sites/landingpage/pintool/downloads/pin-2.14-71313-gcc.4.4.7-linux.tar.gz
