### ISSUE TITLE
Implicit flow analysis in the Taint Engine?

### ISSUE THREAD

**Issue by bntejn** [JonathanSalwan/Triton#599]
I'm interested in implementing an implicit flow analysis on top of the current `TaintEngine`. (In case you are not familiar with the term, implicit flow analysis tracks the sensitive information flowing implicitly through control-dependent assignments (i.e. `if (H) then L := true; else L := false`) [1]). To my understanding, this feature can increase the power of taint analysis by taking implicit flows into account. At the same time, however, it could introduce a huge number of false alarms for some program, which may require costly manual analysis effort afterward. Considering these pros and cons, I think it would be the best if a user can optionally enable implicit flow analysis when the explicit-flow-only result was not satisfactory.

What do you think? If you're interested, I would also like to discuss more on its usefulness and the architectural decisions we'll have to make. FYI, [1, 2].

[1] King, D. et al.: **Implicit Flows: Can’t Live with “Em, Can”t Live without ‘Em.** In: Information Systems Security. pp. 56–70 Springer, Berlin, Heidelberg (2008).
[2] Kang, M.G. et al.: **DTA++ - Dynamic Taint Analysis with Targeted Control-Flow Propagation.** NDSS. (2011).

**Comment by JonathanSalwan** [comment]
> however, it could introduce a huge number of false alarms for some program

That's why I didn't introduce such concept. However, if it can be enabled by the user as a `MODE`, that may be interesting.

**Comment by bntejn** [comment]
Thank you for your reply. I am thinking of only implementing a core feature that is necessary for implicit-flow propagation while letting users implement any implicit-flow policies they desire. We'd only need to introduce *program counter* (PC) and some APIs for tagging and untagging the PC. As long as tags (taints) remain on the PC, those will propagate through unions and assignments until they are removed (by an explicit API call). I think this will be a useful addition to those who are interested in playing with different tainting policies.

**Comment by JonathanSalwan** [comment]
Sounds good to me.
