### ISSUE TITLE
Required library CAPSTONE NOT FOUND

### ISSUE THREAD

**Issue by carterMgj** [JonathanSalwan/Triton#603]
Blow is the error message：
#-------------------------------------------------------------------------------------------------------
-- Found Z3 
CAPSTONE_INCLUDE_DIR=CAPSTONE_INCLUDE_DIR-NOTFOUND
CAPSTONE_INCLUDE_DIRS=
CAPSTONE_LIBRARY=CAPSTONE_LIBRARY-NOTFOUND
CAPSTONE_LIBRARIES=
CMake Error at CMakeModules/LibFindMacros.cmake:74 (message):
  Required library CAPSTONE NOT FOUND.

  Install the library (dev version) and try again.  If the library is already
  installed, use ccmake to set the missing variables manually.
Call Stack (most recent call first):
  CMakeModules/FindCAPSTONE.cmake:32 (libfind_process)
  src/libtriton/CMakeLists.txt:253 (find_package)
#--------------------------------------------------------------------------------------------------------
    I can import capstone in python environment. I don't know how to deal with the problem.

**Comment by JonathanSalwan** [comment]
What about the `dev-v0.6` branch?

**Comment by carterMgj** [comment]
Unfortunately, the dev-v0.6 branch has the same error messages. I want to know the required libcapstone should install by "pip install" or "download source code and compile ". I do both of them, but can't be solve the problem.

**Comment by JonathanSalwan** [comment]
Where is located your capstone directory? Is `-DCAPSTONE_LIBRARIES=...` and  `-DCAPSTONE_INCLUDE_DIRS=...` working during the cmake?

**Comment by carterMgj** [comment]
I paste my command line. Hope you can help me~
#------------------------------------------------------------------------
carter@ubuntu:~/tools/Triton$ pwd
/home/carter/tools/Triton
carter@ubuntu:~/tools/Triton$ whereis capstone
capstone:
carter@ubuntu:~/tools/Triton$ which capstone
#-------------------------------------------------------------------------
  


 I install capstone in 2 ways:
1. pip install capstone:
#----------------------------------------------
pip list      --->     capstone(3.0.4)
#----------------------------------------------
2. Download capstone's source code in http://www.capstone-engine.org/ , and run make.sh to compile it 
   



 I don't konw how to set -DCAPSTONE_LIBRARIES=... and -DCAPSTONE_INCLUDE_DIRS=.... Should I modify the cmake file ?

**Comment by JonathanSalwan** [comment]
`pip install capstone` only installs the bindings where you need to install the native library... After make.sh run `sudo make install` to install the compiled source. Then, reinstall Triton in the normal way.
