### ISSUE TITLE
Capstone 4 Release Candidate Breaks Build

### ISSUE THREAD

**Issue by andrewcalvano** [JonathanSalwan/Triton#604]
This is not so much an issue as the latest stable version of capstone does not cause this problem but figured it was something to be aware of for the future. 

The issue is that if you were to have the capstone 4 release candidate installed the Triton build will break due to changes in the enum names for the X86 instructions in the capstone header.

**Comment by JonathanSalwan** [comment]
The problem is not really the enum changes. Last time that I tested the v4 of capstone, there were lots of bugs about the disass information (like operand size issue, operand kind issue...).

**Comment by JonathanSalwan** [comment]
However, maybe you can give a try to support the v4 and send us a PR :).
