### ISSUE TITLE
Register object could only set with unsigned value

### ISSUE THREAD

**Issue by mustakcsecuet** [JonathanSalwan/Triton#608]
It seems from following attempt:
api.setConcreteRegisterValue(Register(triton::arch::x86::ID_REG_RAX, ret_value));
ret_value could be only triton::uint512 type means unsigned. But I would definitely like to set RAX with negative value too. Like for strcmp() the return could be -1, and I should set register RAX with -1; which is defintitely signed and will not work here.
What we have to do overcome this?

**Comment by JonathanSalwan** [comment]
> What we have to do overcome this?

0xffffffffffffffff
