### ISSUE TITLE
Question about setupImageBlacklist and IMAGE_LOAD

### ISSUE THREAD

**Issue by pfsun** [JonathanSalwan/Triton#609]
Hi @JonathanSalwan,

I try callback_image.py example. When I add  ```setupImageBlacklist(["libc", "ld-linux"]) ``` to block libc and ld-linux image, but the output is still the same.  Whether setupImageBlacklist cannot block the image load?
```
----------
Image path:  /home/project/coreutils-8.28/src/groups
Image base:  0x400000L
Image size:  2126912
----------
Image path:  /lib64/ld-linux-x86-64.so.2
Image base:  0x7ffff7dda000L
Image size:  2245064
----------
Image path:  /lib/x86_64-linux-gnu/libc.so.6
Image base:  0x7fffe11a7000L
Image size:  3965632

```

**Comment by JonathanSalwan** [comment]
They are loaded but not instrumented.

**Comment by pfsun** [comment]
Hi @JonathanSalwan, I also try callback_routine.py to instrument malloc and free. I am trying to figure two questions: 

1. If I add setupImageBlacklist(["libc", "ld-linux"]), whether I cannot instrument malloc and free which were called by libc funtions?
2. For the number of instrumenting malloc and free, I also compare with valgrind result.

I use one very simple code to test. In this code, there are one malloc() and one free(). But libc function textdomain() will also call malloc(). 
```
#include <stdio.h>      /* printf, scanf, NULL */
#include <stdlib.h>     /* malloc, free, rand */
#include <libintl.h>
int main ()
{
  int i,n;
  char * buffer;

  i = 10;
  textdomain("Try LIBC Malloc");

  buffer = (char*) malloc (i+1);
  if (buffer==NULL) exit (1);

  for (n=0; n<i; n++)
    buffer[n]=rand()%26+'a';
  buffer[i]='\0';

  printf ("Random string: %s\n",buffer);
  free (buffer);

  return 0;
}

```
I use your callback_routine.py example but adding free() instrumentation. 
```
from triton  import ARCH
from pintool import *

Triton = getTritonContext()

def mallocEntry(threadId):
    sizeAllocated = getCurrentRegisterValue(Triton.registers.rdi)
    print '-> malloc(%#x)' %(sizeAllocated)


def mallocExit(threadId):
    ptrAllocated = getCurrentRegisterValue(Triton.registers.rax)
    print '<- %#x' %(ptrAllocated)


def freeEntry(threadId):
    ptrFreed = getCurrentRegisterValue(Triton.registers.rdi)
    print '-> free(%#x)' %(ptrFreed)


if __name__ == '__main__':

    # Set the architecture
    Triton.setArchitecture(ARCH.X86_64)

    setupImageBlacklist(["libc.so.6", "ld-linux"])

    # Start the symbolic analysis from the Entry point
    startAnalysisFromEntry()

    # Add a callback.
    insertCall(mallocEntry, INSERT_POINT.ROUTINE_ENTRY, "malloc")
    insertCall(mallocExit, INSERT_POINT.ROUTINE_EXIT, "malloc")
    insertCall(freeEntry, INSERT_POINT.ROUTINE_ENTRY, "free")

    # Run the instrumentation - Never returns
    runProgram()

```
Whether or not I add ``` setupImageBlacklist(["libc.so.6", "ld-linux"])```, the result always as below. **Whether setupImageBlacklist doesn't work for insertCall or I have some mistakes**?
```
-> malloc(0x10)
-> malloc(0x10)
<- 0x10ad010
-> malloc(0xb)
<- 0x10ad030
Random string: nwlrbbmqbh
-> free(0x10ad030)

```
I also use valgrind to test the number of malloc() and free(). 
```
$ valgrind --leak-check=full ./malloc
==9479== Memcheck, a memory error detector
==9479== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==9479== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==9479== Command: ./malloc
==9479== 
Random string: nwlrbbmqbh
==9479== 
==9479== HEAP SUMMARY:
==9479==     in use at exit: 0 bytes in 0 blocks
==9479==   total heap usage: 2 allocs, 2 frees, 27 bytes allocated
==9479== 
==9479== All heap blocks were freed -- no leaks are possible
==9479== 
==9479== For counts of detected and suppressed errors, rerun with: -v
==9479== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)

```
Valgrind's result shows **2 allocs and 2 frees**. But callback_routine.py returns **2 mallocs and 1 free**.  So I also go to check [textdomain() source code ](https://github.com/lattera/glibc/blob/master/intl/textdomain.c). It looks it should not have free. But I also try CoreUtils **ls**. Valgrind's result shows **63 allocs and 35 frees**. Triton callback_routine.py returns **63 mallocs and 8 frees**. Now I feel very confusion for this result. Do you have any suggestion? Thanks.
