### ISSUE TITLE
How to feed command-line arguments to a (Pin) Python script

### ISSUE THREAD

**Issue by bntejn** [JonathanSalwan/Triton#611]
Is there a way to feed some command-line arguments when running a custom Python script?

```
$ triton
You need to specify a target binary
Syntax: ./triton <your_script.py> <target binary> [target binary args]
```

I could only find how to specify args for the target binary.

**Comment by JonathanSalwan** [comment]
Nop, it's not possible. To understand why, let's see the triton script:

```sh
LD_BIND_NOW=1 $PIN_BIN_PATH -ifeellucky -t $PINTOOL_PATH -script $1 -- ${@:2}
```
As we use pin as a process, the python arguments must be known and understood by the pin binary.
