### ISSUE TITLE
consistency symbolic variable after doing concrete execution

### ISSUE THREAD

**Issue by mustakcsecuet** [JonathanSalwan/Triton#613]
Hi
I wonder if there is any way to solve the following problem:
Consider I have a memory which is already converted to symbolic. Now, after some time; the symbolic variable is used for strlen() method, so I hooked this call and do a concrete execution (that means I read the string from memory using RDI register, and calculate the length of the string; later set the concrete value to RAX register). Now, the problem is my symbolic variable and RAX register are not connected anymore because of the concrete execution in middle. Although I convert the RAX register to symbolic will now have no impact on my previous symbolic variable although they should have. Can you suggest a way to resolve this problem?
In details, it looks like following:
```
Symbolic Memory:
[0x26][0x27][0x28][0x29][0x30]
   H    E     L     L    O
RDI points to 0x26 called strlen()
my hooked function received this:
Read memory string "HELLO" from RDI; do strlen("HELLO"); return 5;
And the hooker set concrete value, 5 to RAX register (simulate return from strlen)
I also do convert RAX to a symbolic variable after that.
It helps me to see path constraints depends on RAX, but that should also mean the path constraints should also depend on the symbolic variable (memory 0x26-0x30).
```
But, my system lost the connection due to the concrete execution in middle. So if there is any way to connect them, it will be great.

**Comment by JonathanSalwan** [comment]
The problem is that you want an array logic (QF_ABV) while Triton only supports bitvector logic (QF_BV). Your case is not trivial to resolve =/.

**Comment by mustakcsecuet** [comment]
Is there any way that I could keep the symbolic relationship of memory address 0x26 and register RAX manually? Like constraints based on RAX register will also consider as constraints based on memory address 0x26. Kinds of forcing the system to make a bonding between them.
If there is no way; you can close the issue :+1:
