### ISSUE TITLE
PIN crash due to invalid register 

### ISSUE THREAD

**Issue by SeanHeelan** [JonathanSalwan/Triton#615]
Hey,

I've just pulled Triton onto a fresh VM and when I went to check if everything had installed correctly I got the following:

```
user@ubuntu:~/git/pin-2.14-71313-gcc.4.4.7-linux/source/tools/Triton$ ./build/triton ./src/examples/pin/ir.py /usr/bin/id
terminate called after throwing an instance of 'std::runtime_error'
  what():  tracer::pintool::context::getCurrentRegisterValue(): Invalid register.
C: Tool (or Pin) caused signal 11 at PC 0xb747ab93
./build/triton: line 20: 16180 Segmentation fault      (core dumped) LD_BIND_NOW=1 $PIN_BIN_PATH -ifeellucky -t $PINTOOL_PATH -script $1 -- ${@:2}
```

The VM is Ubuntu 14.04 with kernel 3.13.0-24 on an x86 (the reason for the old VM being it was the most convenient way to get a kernel version which PIN would play nicely with).

The error appears to be coming from `src/tracer/pin/context.cpp` due to a switch on `reg.getParent().getId()` not matching any of the expected cases. Printing out the value of `getId()` gives 7. Assuming the correct enum to inspect is `registers_e` from `src/libtriton/includes/triton/x86Specifications.hpp` then that is the value associated with `ID_REG_RBP`. Why the RBP version of the register identifier is cropping up here instead of the EBP version, I have no idea. Everything involved appears to be 32-bit, including `/usr/bin/id` and the tracer (`libpintool.so`). It has been a while since I've used PIN though and I don't recall what would trigger this. 

Any thoughts on what might be going wrong?  Let me know if there is other system info which would be useful to track down the problem.

Sean

**Comment by 0ca** [comment]
Hi Sean, I think you need to modify this line:
https://github.com/JonathanSalwan/Triton/blob/master/src/examples/pin/ir.py#L20

to change the architecture to x86.

**Comment by SeanHeelan** [comment]
Correct! ... Probably should have checked the script before looking for a complicated solution ;) Thanks

**Comment by JonathanSalwan** [comment]
Hey sean, btw I recommend to use the branch `dev-v0.6` which is stable and have better features.

**Comment by SeanHeelan** [comment]
Thanks for the info!
