### ISSUE TITLE
Triton consuming a lot of memory.

### ISSUE THREAD

**Issue by the-elves** [JonathanSalwan/Triton#620]
I am writing a simple python program to print the disassembly. When I ran on a large program my workstation ran out of memory. 
To investigate the issue further I re-ran the disassembly code on smaller programs but ran it in a loop and observed system resources. 
Within seconds the triton process had consumed 5 GB of memory and increasing. When I left it running, my workstation froze and the whole of 16 GB of memory was used by the process. 
I also tried to call gc.collect at the end of every iteration. It didn't help. 
For iterative analysis, we often need to emulate a program multiple times and the analysis can halt due to memory exhaustion. I guess there should be some API to clear all internal state.

My code: https://pastebin.com/4j73VwVq

Specs of my PC are
16 GB of ram and 2 octacore xeon.

**Comment by JonathanSalwan** [comment]
Use the `dev-v0.6` and disable engines not used.

* **enableSymbolicEngine(bool flag)**
* **enableTaintEngine(bool flag)**

See https://github.com/JonathanSalwan/Triton/issues/482#issuecomment-277297336.
