### ISSUE TITLE
About Dwarf information

### ISSUE THREAD

**Issue by pfsun** [JonathanSalwan/Triton#622]
Hi @JonathanSalwan,

If my binary is compiled with debug information, is it possible to get dwarf information on some execution point when executing the binary with Triton pintools? Do you have any API or could you share some possible tips?  Thanks.

**Comment by JonathanSalwan** [comment]
You have no API about getting information from DWARF. Maybe you should ask to the [LIEF](https://github.com/lief-project/LIEF/) team if they provide such information.
