### ISSUE TITLE
fail to import pintool on latest triton

### ISSUE THREAD

**Issue by KnoooW** [JonathanSalwan/Triton#625]
I use this to conduct my compiling:
https://triton.quarkslab.com/documentation/doxygen/#install_sec

and finally I see this , when I try to 'import pintool' in python:

>>> import triton
>>> print triton
<module 'triton' from '/usr/lib64/python2.7/site-packages/triton.so'>
>>> import pintool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
**ImportError**: /usr/lib64/python2.7/site-packages/pintool.so: undefined symbol: _ZN6triton8bindings6python18PyTritonContextRefERNS_3APIE
>>> 

there's an import error..

**Comment by JonathanSalwan** [comment]
You have to run `triton` to load the pinool module.

`./build/triton your_script.py binary.bin`

**Comment by KnoooW** [comment]
Thanks a lot !
