### ISSUE TITLE
Solver timeout and more Z3's built-in simpfications

### ISSUE THREAD

**Issue by rainoftime** [JonathanSalwan/Triton#633]
1.  In `solverEngine.cpp`, I noticed that the SMT solver is not set to a cut-off time. In some cases, the symbolic engine may get sucked. 
~~~~
      std::list<std::map<triton::uint32, SolverModel>> SolverEngine::getModels(triton::ast::AbstractNode* node, triton::uint32 limit) const {
        std::list<std::map<triton::uint32, SolverModel>> ret;
        triton::ast::TritonToZ3Ast z3Ast{this->symbolicEngine, false};

        z3::expr      expr = z3Ast.convert(node);
        z3::context&  ctx  = expr.ctx();
        z3::solver    solver(ctx);
       
       // .....
~~~~

2. In `Z3Interfce.cpp`, Triton uses the `simplify()` method of a Z3's expression. 

~~~~
      /* From Triton to Z3 */
      z3::expr expr = z3Ast.convert(node);

      /* Simplify and back to Triton's AST */
      node = tritonAst.convert(expr.simplify());

      return node;
    }
~~~~
In fact, we can set options to `simplify()`. In addition, Z3 also exposes several tactics that can be used.  For instance, 
~~~~
    z3::goal G(expr.ctx());
    G.add(expr);
    z3::tactic CP = z3::tactic(expr.ctx(), "propagate-values");  // constant propagation
    return CP.apply(G)[0].as_expr();
~~~~

What about exposing more APIs for formulas simplifications? I could add them later if needed.

**Comment by JonathanSalwan** [comment]
Sounds good to me to add options for z3's simplifications. However, we have to find a sexy way to add z3's simplifications and Triton's simplifications together. For example, in a long term goal we would like to add Triton's rules for expressions simplification (like constant propagation for instance). The user API have to be clear about what is z3's simplification and what is Triton's simplifications.

**Comment by rainoftime** [comment]
@JonathanSalwan I agree:) 
I also found an interesting repo https://github.com/JonathanSalwan/arybo. Will it be integrated into Triton later?

**Comment by JonathanSalwan** [comment]
Nop, we prefer to keep projects separated each others (it's clearer).
