### ISSUE TITLE
Build Errors on sln.file through VS2015

### ISSUE THREAD

**Issue by Xdecosee** [JonathanSalwan/Triton#634]
I followed the steps in the [Triton installation page](https://triton.quarkslab.com/documentation/doxygen/index.html) and was able to generate the .sln file. 

 <img src="https://user-images.githubusercontent.com/23446523/33544584-4f052a08-d916-11e7-90b3-92576a50c9ed.png" width="50%">

 <img src="https://user-images.githubusercontent.com/23446523/33544630-79bb874c-d916-11e7-81a6-905b9138ec56.png" width="50%">

I tried building the .sln file that was generated but there were build errors. Following is a screenshot of the error and output in a .pdf file. Is there a way to resolve them or am I missing a step?

<img src="https://user-images.githubusercontent.com/23446523/33544985-c1c52f10-d917-11e7-8ffc-cf0edf557af5.png" width="70%">

[Output.pdf](https://github.com/JonathanSalwan/Triton/files/1526393/Output.pdf)

**Comment by JonathanSalwan** [comment]
```patch
diff --git a/src/libtriton/ast/astContext.cpp b/src/libtriton/ast/astContext.cpp
index d3caec56..ab47ef39 100644
--- a/src/libtriton/ast/astContext.cpp
+++ b/src/libtriton/ast/astContext.cpp
@@ -487,7 +487,7 @@ namespace triton {
     void AstContext::updateVariable(const std::string& name, const triton::uint512& value) {
       for (auto& kv: this->astGarbageCollector.getAstVariableNodes()) {
         if (kv.first == name) {
-          assert(kv.second[0]->getType() == triton::ast::VARIABLE_NODE);
+          assert(kv.second[0]->getKind() == triton::ast::VARIABLE_NODE);
           this->valueMapping[dynamic_cast<VariableNode*>(kv.second[0])->getVar().getName()] = value;
           for (auto* N: kv.second)
             N->init();
```

Is this patch fixes your issue?

**Comment by Xdecosee** [comment]
Yes, it fixed the issue. Thank you for your help. I got the LNK1104 error after using the patch, but I read #363 and run the build in release mode instead. The dll file managed to be generated and there were no build errors.
