### ISSUE TITLE
triton not match the arybo

### ISSUE THREAD

**Issue by fr0zenrain** [JonathanSalwan/Triton#639]
i use dev-319-gc and arybo feature/exprs get this error

File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/arybo/tools/triton_.py", line 31, in tritonast2arybo
    children_ = e.getChilds()
AttributeError: 'AstNode' object has no attribute 'getChilds'

which version or branch i should use? thanks

**Comment by JonathanSalwan** [comment]
Regarding Triton you can use `master` or `dev-v0.6`, regardin Arybo you have to apply [this patch](https://github.com/quarkslab/arybo/pull/4/files).

 cc @aguinet.
