### ISSUE TITLE
First steps with Triton - Windows

### ISSUE THREAD

**Issue by m7nu3l** [JonathanSalwan/Triton#641]
Hi everyone

I'm willing to try Triton on Windows. I followed the instructions here https://triton.quarkslab.com/documentation/doxygen/#windows_install_sec with no luck.

test-python project fails when compiled from VS -> https://pastebin.com/f8aeuf3R

My second attempt consisted in downloading the binaries from AppVeyor. Where should I save those files in order to be able to run the examples on the repository?

Thanks in advance.

**Comment by JonathanSalwan** [comment]
Just use `PYTHONPATH` on the `.pyd` file's directory.
