### ISSUE TITLE
ImportError: No module named pintool

### ISSUE THREAD

**Issue by m7nu3l** [JonathanSalwan/Triton#642]
Hi

Following your advice I could solve my last [issue](https://github.com/JonathanSalwan/Triton/issues/641#event-1413198133). 

Briefly, I had compile errors, so I decided to use the artifacts from AppVeyor (windows). Now the triton module can be loaded from python, but I have issues with the pintool module.

For instance I got the error when running:  python triton\src\examples\pin\strlen.py

If I understand correctly there is a pintool used as a tracer.  How could I solve the "ImportError: No module named pintool"? Do I have to run the python script within the pintool? Can the pintool be compiled in Windows?

I'm pretty sure these are dumb questions, however I trully tried to research before asking. I really want to run the examples in order to grasp and understand all this project.

Thanks in advance.

**Comment by JonathanSalwan** [comment]
> If I understand correctly there is a pintool used as a tracer. How could I solve the "ImportError: No module named pintool"? Do I have to run the python script within the pintool?

Yes. the `pintool` module is **only** loaded using the pintool tracer (`libpintool.so`). So, you cannot `import pintool` without the pintool. Basically you have to use the `triton` script as follow:

`./build/triton your_script.py binary.bin`

> Can the pintool be compiled in Windows?

Unfortunately not. The tracer is only available on Linux. However we will probably release a [QBDI tool](https://github.com/quarkslab/QBDI) which will use Triton.
