### ISSUE TITLE
Numerous functions are not implemented and therefore don't link

### ISSUE THREAD

**Issue by thorstent** [JonathanSalwan/Triton#644]
For example api.checkAstGarbageCollector() is not implemented, but defined in api.h
also operandWrapper.getConcreteValue() is defined but not implemented

Talking about version 6 here.

**Comment by JonathanSalwan** [comment]
Thanks!

I'm ok about `api.checkAstGarbageCollector()` but `operandWrapper.getConcreteValue()` seems to be removed at all. Are you up-to-date?

**Comment by thorstent** [comment]
Well, in the master branch, getConcreteValue() is defined in [https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/includes/triton/operandWrapper.hpp](https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/includes/triton/operandWrapper.hpp) line 108

**Comment by JonathanSalwan** [comment]
> Talking about version 6 here.

Version 6 is on `dev-v06`. It's merged into master anyway. Thanks
