### ISSUE TITLE
How to resolve the address of an imported functions for tainting?

### ISSUE THREAD

**Issue by vanhauser-thc** [JonathanSalwan/Triton#647]
I would like to code a generic tainter with Triton that e.g. hooks recv() and taints rsi when called/exit.

this works fine if I hardcode the memory location of recv, however a function that would automatically resolve the loading address within Triton would be great - I have not found something that does.

I could use pin functions maybe, but then I would be stuck with pin which would then not work when I do stuff on ARM etc.

Am I am missing an obvious way to do this?
Or is there no way currently to do this?

Thanks!

**Comment by JonathanSalwan** [comment]
I'm using the [LIEF](https://github.com/lief-project/LIEF/) library to provide binary information to Triton. You can get function addresses using these [three lines of code](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/small_x86-64_symbolic_emulator.py#L405-L407).

**Comment by vanhauser-thc** [comment]
Sorry if I ask a dumb question but the documentation is ... well there is not really one, just examples :)

1. To be able to taint something I must know what to taint at which address.
2. The address - if its from an imported library - will be loaded at a random location (if secure compilation was done etc) so the binary must actually be started to do so.
3. I must define insertCall() before runProgram, but runProgram is where the program would be started traced with e.g. PIN, so when I have to do insertCall I do not no the random address an important function is loaded to.

Did I get my problem correctly or is there actually an easy solution for this?
If so, how would lief help there?

Or could I do something like this:

``
def leaf_stuff:
    ... stuff ...
    for rel in binary.pltgot_relocations:
        if rel.symbol.name == 'recv':
            recvaddr = rel.address

def cb_beforeSymProc(instruction):
    if instruction.getAddress() == recvaddr:
        reg = getCurrentRegisterValue(Triton.registers.rdi)
        Triton.taintMemory(reg)

# main
startAnalysisFromEntry()
insertCall(cb_beforeSymProc, INSERT_POINT.BEFORE_SYMPROC)
leaf_stuff()
runProgram()

``

otherwise something like that would be great:
``
insertCall(recvExit, IDREF.CALLBACK.ROUTINE_EXIT, resolveImport("recv"))
``

**Comment by JonathanSalwan** [comment]
> Sorry if I ask a dumb question but the documentation is ... well there is not really one, just examples :)

examples ftw :)

> 1. To be able to taint something I must know what to taint at which address.
> 2. The address - if its from an imported library - will be loaded at a random location (if secure compilation was done etc) so the binary must actually be started to do so.
> 3. I must define insertCall() before runProgram, but runProgram is where the program would be started traced with e.g. PIN, so when I have to do insertCall I do not no the random address an important function is loaded to.

I didn't know you want to use the pintool module.

> otherwise something like that would be great:
insertCall(recvExit, IDREF.CALLBACK.ROUTINE_EXIT, resolveImport("recv"))

Pin already provides this kind of thing (they call that "RTN" (routine)). [Example ftw](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/pin/callback_routine.py#L36-L37) :).

**Comment by JonathanSalwan** [comment]
Btw if you want the API documentation related to the pintool module, check that [page](https://triton.quarkslab.com/documentation/doxygen/pintool_py_page.html). Then, if you want that one for Triton, it's just [here](https://triton.quarkslab.com/documentation/doxygen/py_TritonContext_page.html).

**Comment by JonathanSalwan** [comment]
Can I close this PR?

**Comment by vanhauser-thc** [comment]
I will close this for now and when I get stuck somewhere on the way I will reopen it :)
thanks for your effort so far!
