### ISSUE TITLE
Taint instructions if destination is tainted?

### ISSUE THREAD

**Issue by kenoph** [JonathanSalwan/Triton#662]
Hi,

I have this chunk of asm:

```asm
0x400680: movzx eax, byte ptr [rbp - 0x20]
0x400684: movsx eax, al
0x400687: cdqe
0x400689: mov byte ptr [rbp + rax - 0x20], 0
```

At the beginning, eax is both tainted and symbolic.
The last `mov` is not tainted, which sounds weird to me since on the left hand side I have an expression that depends on a tainted value. Being untainted, I also can't use symexOnlyOnTainted to speed up the execution (if I want to use `instr.getStoreAccess()[0][0].getLeaAst()`).

It also looks kinda weird that `rax` is symbolic but `instr.isSymbolized()` is `False`.

What I'm trying to do is something like:

```python
for every instr:
  if instr.isTainted(): # or symbolized
    get the mem src/dst expression and do stuff with them
```

I think I can work around the tainting behaviour by doing something like:

```python
for every instr:
  if any(operand is symbolic for operand in instr.getOperands()):
    reconstruct the src/dst address Ast and do stuff with them
```

But wouldn't it make sense to mark the instruction itself as tainted?

Thanks

**Comment by JonathanSalwan** [comment]
To scale Triton concretizes all LEA (`base+index*scale+disp`) of all `LOAD` and `STORE`, that's why you lost the taint and the symbolic flag during the process of `mov byte ptr [rbp + rax - 0x20], 0`.

I'm plan to provide different mode of concretization but that's not for soon =(.

**Comment by kenoph** [comment]
Ok thanks, that's what I thought. Different concretization strategies sound nice ;) for the time being, I'll manually check instruction operands as it should work for my use case.
