### ISSUE TITLE
Triton runtime library as MD instead of MT

### ISSUE THREAD

**Issue by illera88** [JonathanSalwan/Triton#669]
I'm pretty sure that your intention is to generate a project that compiles libtriton using /MT as stated in the [CMakeLists.txt](https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/CMakeLists.txt#L11) but for some reason CMake creates it as /MD.

**Comment by illera88** [comment]
Related: https://github.com/JonathanSalwan/Triton/issues/568

**Comment by JonathanSalwan** [comment]
some news about it?

**Comment by illera88** [comment]
That PR fixes the problem

**Comment by JonathanSalwan** [comment]
merged into `dev-v0.6-rebase-gc`
