### ISSUE TITLE
AttributeError:  'TritonContext' object has no attribute 'Register'

### ISSUE THREAD

**Issue by StablelJay** [JonathanSalwan/Triton#674]
To use the Symbolic Execution Engine of Triton, I try try script as followed, but there is something error. I use triton v0.6.
`from triton import *                                           
ctx = TritonContext()                                          
ctx.setArchitecture(ARCH.X86)                                             
ctx.convertRegisterToSymbolicVariable(ctx.Register(REG.X86.AX))
eax = ctx.buildSymbolicRegister(ctx.Register(REG.X86.EAX))     
`

Error:
File "/home/kumquat_cc/Symbolic_Execu/triton_t1.py", line 5, in <module>
  ctx.convertRegisterToSymbolicVariable(ctx.Register(REG.X86.AX))
AttributeError: 'TritonContext' object has no attribute 'Register'

How to fix it?

**Comment by JonathanSalwan** [comment]
Two solutions:

```python
ctx.getRegister(REG.X86.AX)
```

or

```python
ctx.registers.ax
```
