### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pigrecos** [JonathanSalwan/Triton#678]
why do you generate these errors? whether you are compiling the source code and whether you download the libraries from AppVeyor's artefacts.

    setArchitecture(ARCH.X86)
NameError: name 'setArchitecture' is not defined
 or 

enableTaintEngine(True) 
NameError: name 'enableTaintEngine' is not defined

I think you can not find  export

**Comment by Pigrecos** [comment]
use of triton in python

>> from triton import * does not produce errors

but it does not find the exported functions I think

**Comment by JonathanSalwan** [comment]
past code.

**Comment by Pigrecos** [comment]
for example

import  sys
from  triton import *

setArchitecture(ARCH.X86_64)

inst = Instruction()

 processing(inst)
-------------------------------
setArchitecture(ARCH.X86_64) and processing(inst)  ----> NameError

thank you.

**Comment by JonathanSalwan** [comment]
```python
ctx = TritonContext(ARCH.X86_64)
ctx.setArchitecture()
```
