### ISSUE TITLE
Is there a hack to boost the performance of taint analysis?

### ISSUE THREAD

**Issue by bntejn** [JonathanSalwan/Triton#683]
I saw that the DSE has to be enabled in order to use taint analysis. However, I also noticed that most of the CPU/memory overhead of running taint analysis is caused by building up symbolic expressions and abstract nodes, not so much by taint analysis itself; as a result, one execution took few minutes and few tens of gigabytes of memory, while it used to take a fraction of a second and a few megabytes of memory.

To mitigate this problem, I tried commenting out some unnecessary code (for my purpose) in `x86Semantics.cpp` with a hope to make the analysis consume less resource, and I was able to achieve my goal somewhat, but commenting out few thousand lines in 12k-line code seemed like too much of a work. I wonder if there would be a quick hack to make the taint analysis faster and totally disable other irrelevant features. Is there?

**Comment by sktt** [comment]
Hey there you can disable functionality that you don't need,

see for example https://github.com/JonathanSalwan/Triton/issues/620
https://github.com/JonathanSalwan/Triton/issues/482#issuecomment-277297336

**Comment by bntejn** [comment]
Super cool. Thanks!
