### ISSUE TITLE
Some variables are not declared in the scope

### ISSUE THREAD

**Issue by Blade94** [JonathanSalwan/Triton#684]
Good morning!
I'm trying to install this software following these [instructions](https://triton.quarkslab.com/documentation/doxygen/#install_sec) but i get some errors when launching the command `sudo make -j2 install` and this is the outcome of my terminal.

[http://i.imgur.com/2kkRzHZ.png](http://i.imgur.com/2kkRzHZ.png)

How do I fix this? I'm on Ubuntu 18.04.

Thanks in advance!

**Comment by JonathanSalwan** [comment]
You have to use the last version of z3.

**Comment by Blade94** [comment]
I installed the 4.4.1 version with the command `sudo apt install libz3-dev` but didn't work. Now i'v installed it from the github repo linked in the instruction and it worked. I also had to apply the patch from previous post in issues (fix #679) and now works perfectly, thanks for your help :)

**Comment by JonathanSalwan** [comment]
thanks to you ! :)
