### ISSUE TITLE
Add -DPINTOOL=on for AppVeyor builds

### ISSUE THREAD

**Issue by yoava333** [JonathanSalwan/Triton#687]
I saw that linux build has this option, It would be really nice to have the build artifacts with this option on

**Comment by JonathanSalwan** [comment]
Our Pintool module is not supported for the windows platform.

**Comment by yoava333** [comment]
What prevents this feature from being supported on Windows?

**Comment by JonathanSalwan** [comment]
Some conflicts including `Python.h`, `Windows.h` and `Pin.h`. If you manage to resolve these conflicts I will be more than happy to merge your pull request :)
