### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Bluekezhou** [JonathanSalwan/Triton#704]
I got error like this:
```
/home/test/Desktop/Triton/src/libtriton/ast/z3/tritonToZ3Ast.cpp: In member function ‘triton::__uint triton::ast::TritonToZ3Ast::getUintValue(const z3::expr&)’:
/home/test/Desktop/Triton/src/libtriton/ast/z3/tritonToZ3Ast.cpp:32:19: error: ‘const class z3::expr’ has no member named ‘get_numeral_uint64’
       return expr.get_numeral_uint64();
```

My environment is:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic

gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)
g++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0
ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
```

**Comment by Bluekezhou** [comment]
I am using the master branch.

**Comment by JonathanSalwan** [comment]
What is your z3's version?

**Comment by CodeByO** [comment]
I am using z3 4.7.1 but The same thing happend

**Comment by JonathanSalwan** [comment]
Are you sure you used the 4.7.1 version of Z3 during your compile process? According to the [source of this version](https://github.com/Z3Prover/z3/blob/z3-4.7.1/src/api/c%2B%2B/z3%2B%2B.h#L778-L787) it seems that `get_numeral_uint64()` is available.

**Comment by CodeByO** [comment]
I'm sorry I did not tell you well. During installation, I realize that I have installed libz3-dev and I think I get an error here. So the installed version of libz3-dev is 4.4.0-5 and is there any way to get the older version?
