### ISSUE TITLE
Question about python example

### ISSUE THREAD

**Issue by norrathep** [JonathanSalwan/Triton#706]
Hello,

Do you have any Python example on how to use Triton for taint analysis?
Specifically, my program contains a list of capstone instructions, which can be converted to assembly. Now I want to be able to perform a taint analysis on a register in a specific assembly instruction. How can I do that?

Best,

Edit1: I am aware of back slicing example (https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/backward_slicing.py) but am not aware of any taint analysis example.
Edit2: If not, do you have any pointer for API I can look into?

**Comment by JonathanSalwan** [comment]
Hey,

I've pushed a new [python example](https://github.com/JonathanSalwan/Triton/blob/dev-v0.6/src/examples/python/forward_tainting.py) illustrating a _forward tainting analysis_ on a small emulated function. Hope it can help :)

**Comment by norrathep** [comment]
Thanks! @JonathanSalwan
