### ISSUE TITLE
Extract symbolic variables from symbolized instruction

### ISSUE THREAD

**Issue by bochsler** [JonathanSalwan/Triton#711]
Currently, to extract the users symbolic variables from a symbolized instruction you must loop through the targeted instruction's symbolic expressions, slicing each expression and looping, now, through the sliced list to find the users symbolic variables. This presents some issues with speed and clarity because duplicates will frequently show up from the nature of the interconnected trees and some instructions have multiple symbolic variables contained within, so a double loop is required for each instruction to safely extract every symbolic variable referenced by that instruction. Maybe as the instruction has its formulas built to log a pointer or symbolic ID to the symbolic variables that instruction references? I am not familiar with Triton's sources so a solution that doesn't hog memory is above my head. 

Thanks everyone.

**Comment by JonathanSalwan** [comment]
```python
>>> from triton import *

>>> ctx = TritonContext()
>>> ctx.setArchitecture(ARCH.X86_64)

>>> ast = ctx.getAstContext()

>>> v1 = ast.variable(ctx.newSymbolicVariable(8))
>>> v2 = ast.variable(ctx.newSymbolicVariable(8))

>>> n = (((v1 + v2 * 3) + v2) - 1)
>>> print n
(bvsub (bvadd (bvadd SymVar_0 (bvmul SymVar_1 (_ bv3 8))) SymVar_1) (_ bv1 8))

# Looking for all VARIABLE nodes
>>> ast.lookingForNodes(n, AST_NODE.VARIABLE)
[SymVar_0, SymVar_1]

# Looking for all BV nodes
>>> ast.lookingForNodes(n, AST_NODE.BV)
[(_ bv3 8), (_ bv1 8)]

# Looking for all BVADD nodes
>>> ast.lookingForNodes(n, AST_NODE.BVADD)
[(bvadd SymVar_0 (bvmul SymVar_1 (_ bv3 8))), (bvadd (bvadd SymVar_0 (bvmul SymVar_1 (_ bv3 8))) SymVar_1)]

# Looking for all BVSUB nodes
>>> ast.lookingForNodes(n, AST_NODE.BVSUB)
[(bvsub (bvadd (bvadd SymVar_0 (bvmul SymVar_1 (_ bv3 8))) SymVar_1) (_ bv1 8))]

# Looking for all nodes
>>> ast.lookingForNodes(n, AST_NODE.ANY)
[SymVar_0, 3, 8, (_ bv3 8), (bvmul SymVar_1 (_ bv3 8)), (bvadd SymVar_0 (bvmul SymVar_1 (_ bv3 8))), SymVar_1, (bvadd (bvadd SymVar_0 (bvmul SymVar_1 (_ bv3 8))) SymVar_1), 1, 8, (_ bv1 8), (bvsub (bvadd (bvadd SymVar_0 (bvmul SymVar_1 (_ bv3 8))) SymVar_1) (_ bv1 8))]
```

**Comment by JonathanSalwan** [comment]
Then if you want to access to a `SymbolicVariable` from an `AstNode`, just use `AstNode::getValue()`.
