### ISSUE TITLE
make a returned object symbolic

### ISSUE THREAD

**Issue by mahmoudaghvami** [JonathanSalwan/Triton#714]
Hello Jonathan,
I had a function which returned an Object or a struct as a result(I mean not primitive types). 
In fact, in the x86 compiled code of this program, I can just see the address (reference) of this returned object but I don't know how should I make it symbolic? 
I know how to make memory and register symbolic by Triton but I have no idea, how to make a reference symbolic, as the schema of the returned object or struct is not clear for me.
How can I make a returned object symbolic?
Thanks in advance for your help and consideration

**Comment by JonathanSalwan** [comment]
You cannot symbolize a whole C++ object. I think that the best way is to symbolize the memory region of attributes of your structs/objects. Symbolize C++ stuffs is not really the easiest way =/
