### ISSUE TITLE
Compile problem with z3

### ISSUE THREAD

**Issue by natalie13m** [JonathanSalwan/Triton#715]
Hi Jonathan,

I had a problem compiling Triton with pintool on z3.

The error is as follows.

``` [ 25%] Building CXX object src/libtriton/CMakeFiles/triton.dir/ast/z3/tritonToZ3Ast.cpp.o
/home/natalie/Desktop/symbex-test/pin-2.14/source/tools/Triton/src/libtriton/ast/z3/tritonToZ3Ast.cpp: In member function ‘z3::expr triton::ast::TritonToZ3Ast::convert(const SharedAbstractNode&)’:
/home/natalie/Desktop/symbex-test/pin-2.14/source/tools/Triton/src/libtriton/ast/z3/tritonToZ3Ast.cpp:164:96: error: no matching function for call to ‘std::basic_string<char>::basic_string(triton::uint512)’
 pret_cast<triton::ast::DecimalNode*>(node.get())->getValue());
                                                             ^
In file included from /usr/include/c++/5/string:52:0,
                 from /home/natalie/Desktop/symbex-test/pin-2.14/source/tools/Triton/src/libtriton/includes/triton/exceptions.hpp:12,
                 from /home/natalie/Desktop/symbex-test/pin-2.14/source/tools/Triton/src/libtriton/ast/z3/tritonToZ3Ast.cpp:9:
/usr/include/c++/5/bits/basic_string.h:3030:9: note: candidate: template<class _InputIterator> std::basic_string<_CharT, _Traits, _Alloc>::basic_string(_InputIterator, _InputIterator, const _Alloc&)
         basic_string(_InputIterator __beg, _InputIterator __en
         ^
/usr/include/c++/5/bits/basic_string.h:3030:9: note:   template argument deduction/substitution failed:
/home/natalie/Desktop/symbex-test/pin-2.14/source/tools/Triton/src/libtriton/ast/z3/tritonToZ3Ast.cpp:164:96: note:   candidate expects 3 arguments, 1 provided
 pret_cast<triton::ast::DecimalNode*>(node.get())->getValue());
```

My machine is Ubuntu 14.04 64 bit with kernel 3.19. Gcc & g++ version is 5.5.0.
I tried with z3-4.6.0 and also z3.4.7.1 but both of them failed.
I also tried with both dev-0.6 and also master code of Triton.

**Comment by JonathanSalwan** [comment]
What is your boost version?

**Comment by natalie13m** [comment]
It's boost 1.68.0.

**Comment by natalie13m** [comment]
The same problem still exists at the same point.

**Comment by natalie13m** [comment]
Then it happens again at another location.
This time there are two errors.

> /home/natalie/Desktop/symbex-test/pin-2.14/source/tools/Triton/src/libtriton/ast/z3/tritonToZ3Ast.cpp: In member function ‘z3::expr triton::ast::TritonToZ3Ast::convert(const SharedAbstractNode&)’:
/home/natalie/Desktop/symbex-test/pin-2.14/source/tools/Triton/src/libtriton/ast/z3/tritonToZ3Ast.cpp:285:39: error: no matching function for call to ‘std::basic_string<char>::basic_string(triton::uint512&)’
             std::string strValue(value);
                                       ^
In file included from /usr/include/c++/5/string:52:0,
                 from /home/natalie/Desktop/symbex-test/pin-2.14/source/tools/Triton/src/libtriton/includes/triton/exceptions.hpp:12,
                 from /home/natalie/Desktop/symbex-test/pin-2.14/source/tools/Triton/src/libtriton/ast/z3/tritonToZ3Ast.cpp:9:
/usr/include/c++/5/bits/basic_string.h:3030:9: note: candidate: template<class _InputIterator> std::basic_string<_CharT, _Traits, _Alloc>::basic_string(_InputIterator, _InputIterator, const _Alloc&)
         basic_string(_InputIterator __beg, _InputIterator __en
         ^
/usr/include/c++/5/bits/basic_string.h:3030:9: note:   template argument deduction/substitution failed:
/home/natalie/Desktop/symbex-test/pin-2.14/source/tools/Triton/src/libtriton/ast/z3/tritonToZ3Ast.cpp:285:39: note:   candidate expects 3 arguments, 1 provided
             std::string strValue(value);
                                       ^
In file included from /usr/include/c++/5/string:52:0,
                 from /home/natalie/Desktop/symbex-test/pin-2.14/source/tools/Triton/src/libtriton/includes/triton/exceptions.hpp:12,
                 from /home/natalie/Desktop/symbex-test/pin-2.14/source/tools/Triton/src/libtriton/ast/z3/tritonToZ3Ast.cpp:9:
/usr/include/c++/5/bits/basic_string.h:3020:7: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::initializer_list<_Tp>, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
       basic_string(initializer_list<_CharT> __l, const _Alloc&
       ^
/usr/include/c++/5/bits/basic_string.h:3020:7: note:   no known conversion for argument 1 from ‘triton::uint512 {aka boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<512u, 512u, (boost::multiprecision::cpp_integer_type)0u, (boost::multiprecision::cpp_int_check_type)0u, void> >}’ to ‘std::initializer_list<char>’
/usr/include/c++/5/bits/basic_string.h:3002:7: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::basic_string<_CharT, _Traits, _Alloc>&&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
       basic_string(basic_string&& __str)
       ^
/usr/include/c++/5/bits/basic_string.h:3002:7: note:   no known conversion for argument 1 from ‘triton::uint512 {aka boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<512u, 512u, (boost::multiprecision::cpp_integer_type)0u, (boost::multiprecision::cpp_int_check_type)0u, void> >}’ to ‘std::basic_string<char>&&’
/usr/include/c++/5/bits/basic_string.h:2992:7: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::basic_string<_CharT, _Traits, _Alloc>::size_type, _CharT, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]
       basic_string(size_type __n, _CharT __c, const _Alloc& __
       ^
/usr/include/c++/5/bits/basic_string.h:2992:7: note:   candidate expects 3 arguments, 1 provided
/usr/include/c++/5/bits/basic_string.h:2985:7: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
       basic_string(const _CharT* __s, const _Alloc& __a = _All
       ^
/usr/include/c++/5/bits/basic_string.h:2985:7: note:   no known conversion for argument 1 from ‘triton::uint512 {aka boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<512u, 512u, (boost::multiprecision::cpp_integer_type)0u, (boost::multiprecision::cpp_int_check_type)0u, void> >}’ to ‘const char*’
/usr/include/c++/5/bits/basic_string.h:2978:7: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]
       basic_string(const _CharT* __s, size_type __n,
       ^
/usr/include/c++/5/bits/basic_string.h:2978:7: note:   candidate expects 3 arguments, 1 provided
/usr/include/c++/5/bits/basic_string.h:2966:7: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::basic_string<_CharT, _Traits, _Alloc>&, std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]
       basic_string(const basic_string& __str, size_type __pos,
       ^
/usr/include/c++/5/bits/basic_string.h:2966:7: note:   candidate expects 4 arguments, 1 provided
/usr/include/c++/5/bits/basic_string.h:2957:7: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::basic_string<_CharT, _Traits, _Alloc>&, std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]
       basic_string(const basic_string& __str, size_type __pos,
       ^
/usr/include/c++/5/bits/basic_string.h:2957:7: note:   candidate expects 3 arguments, 1 provided
/usr/include/c++/5/bits/basic_string.h:2950:7: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
       basic_string(const basic_string& __str);
       ^
/usr/include/c++/5/bits/basic_string.h:2950:7: note:   no known conversion for argument 1 from ‘triton::uint512 {aka boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<512u, 512u, (boost::multiprecision::cpp_integer_type)0u, (boost::multiprecision::cpp_int_check_type)0u, void> >}’ to ‘const std::basic_string<char>&’
/usr/include/c++/5/bits/basic_string.h:2943:7: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
       basic_string(const _Alloc& __a);
       ^
/usr/include/c++/5/bits/basic_string.h:2943:7: note:   no known conversion for argument 1 from ‘triton::uint512 {aka boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<512u, 512u, (boost::multiprecision::cpp_integer_type)0u, (boost::multiprecision::cpp_int_check_type)0u, void> >}’ to ‘const std::allocator<char>&’
/usr/include/c++/5/bits/basic_string.h:2932:7: note: candidate: std::basic_string<_CharT, _Traits, _Alloc>::basic_string() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
       basic_string()
       ^
/usr/include/c++/5/bits/basic_string.h:2932:7: note:   candidate expects 0 arguments, 1 provided
/home/natalie/Desktop/symbex-test/pin-2.14/source/tools/Triton/src/libtriton/ast/z3/tritonToZ3Ast.cpp:286:50: error: ‘std::string {aka class std::basic_string<char>}’ has no member named ‘c_strsymVar’
             return this->context.bv_val(strValue.c_strsymVar->
                                                  ^
make[2]: *** [src/libtriton/CMakeFiles/triton.dir/ast/z3/tritonToZ3Ast.cpp.o] Error 1
make[1]: *** [src/libtriton/CMakeFiles/triton.dir/all] Error 2
make: *** [all] Error 2

**Comment by natalie13m** [comment]
I think I can fix this one by using the same method with boost.

> std::string strValue(value);

However with the second error

> /usr/include/c++/5/bits/basic_string.h:2932:7: note: candidate expects 0 arguments, 1 provided
/home/natalie/Desktop/symbex-test/pin-2.14/source/tools/Triton/src/libtriton/ast/z3/tritonToZ3Ast.cpp:286:50: error: ‘std::string {aka class std::basic_string}’ has no member named ‘c_strsymVar’
return this->context.bv_val(strValue.c_strsymVar->

I don't really know what to do.

**Comment by JonathanSalwan** [comment]
your second error it's a typo. The line is ```return this->context.bv_const(symVar->getName().c_str(), symVar->getSize());```
