### ISSUE TITLE
Strategies to overcome reading from symbolized memory address

### ISSUE THREAD

**Issue by igogo-x86** [JonathanSalwan/Triton#717]
I have an instruction `mov rax, [rax]` where `rax` has complex symbolic expression like 
`some_boolean_magic(0x1 if SymVar == something esle 0)`
which produces two possible concrete values of register `rax`. The same situation could be if address was calculated as for example  `base + SymVar * 4`.
As I've seen Triton just calculates one possible address and reads memory from it. Could you suggest at which methods I should look at in order to get control over this situation? So that I could split control flow by generating models for each branch.

**Comment by igogo-x86** [comment]
The problem is that `ctx.processing(inst)` already updates registers values and symbolic engine state. (If we use `mov rax, [rax]` instruction we won't gain as good results as in your example).
So as I see it's possible to split this `processing` on its components:
```python
ctx.disassembly(inst)
# Check here if we have symbolized access to memory and whatever we like.
ctx.buildSemantics(inst) # Finally update state
```

By the way. I'm not sure whether it's a bug or a feature but should `triton::ast::newInstance` function produce deep copy of `SharedAbstractNode` with all tree it points to? Because it doesn't do that and may be i didn't understand the purpose of this function correctly.

**Comment by JonathanSalwan** [comment]
yes you can use `disassembly()` and then `buildSemantics()` for your specific case. Regarding `newInstance`, it only create a new instance of children nodes and do not resolve references. If you want a deep copy, maybe you have to use `unrollAst()` and then `newInstance()`?

**Comment by igogo-x86** [comment]
Yeah, I do it this way. But it produce a copy only of a root node and does nothing with children.  This is a row from `newInstance` function body:
```cpp
case BVNOT_NODE:                newNode = std::make_shared<BvnotNode>(*reinterpret_cast<BvnotNode*>(node)); break;
```
If i understand correctly it calls default copy constructor for `BvnotNode` and thus newInstance copy functionality from `AbstractNode::AbstractNode(const AbstractNode& other, AstContext& ctxt)` which could make recursive copy of children is never called.

**Comment by JonathanSalwan** [comment]
Mmmmh you're right, it's a bug. Can you open a new issue for that?
