### ISSUE TITLE
triton::ast::newInstance doesn't make deep copy of AST

### ISSUE THREAD

**Issue by igogo-x86** [JonathanSalwan/Triton#718]
Actually I almost fixed it by my only and could make pull request. I only need to ask if Is it suitable solution:
* turn new node creations into `newNode = std::make_shared<SOMENODE>(*reinterpret_cast<SOMENODE*>(node, ctxt)); break;`
* Add `using AbstractNode:AbstractNode;` to every trivial derived class
* Implement custom constructor for nontrivial derived class (like `DecimalNode`, `ConcatNode` etc)

**Comment by JonathanSalwan** [comment]
I was thinking about that but still searching for a better approach. However, you can push a PR if it's already working on your machine.

**Comment by JonathanSalwan** [comment]
See #761
