### ISSUE TITLE
Runtime Infinite loop in windows Debug version

### ISSUE THREAD

**Issue by BlackLuny** [JonathanSalwan/Triton#719]
I compile Triton master using VS 2017, z3 4.6.0, capstone 3.0.4.=, no python binding, boost 1.65.1.
But when i test Triton with the example 'constraint.cpp'. It will Infinite loop while deconstruct var 'mode'.But when i compile Triton with Release version. And run the same test,It's OK.

**Comment by JonathanSalwan** [comment]
Are you sure that there is no ABI issue between libs (capstone, z3, python, triton)?
