### ISSUE TITLE
Introducing a new rule for taint spreading

### ISSUE THREAD

**Issue by norrathep** [JonathanSalwan/Triton#725]
Is there an easy way (in Python) to add a new rule for taint spreading in Triton?
Specifically, I want a taint to be spread for a memory access whose address is tainted.
For example, if rax is tainted, then after instruction="movzx  rbx,BYTE PTR [rax]" is executed, rbx should be tainted too.

Below is the code I use and the current Trition implementation output RBX to be untainted.

```
from triton import *

ctx = TritonContext()
ctx.setArchitecture(ARCH.X86_64)

print 'Tainting RAX: ', ctx.taintRegister(ctx.registers.rax)
print 'RAX tainted?: ', ctx.isRegisterTainted(ctx.registers.rax)

inst = Instruction("\x48\x0F\xB6\x18") # movzx  rbx,BYTE PTR [rax]

inst.setAddress(0)
ctx.processing(inst)

print 'RBX tainted?: ', ctx.isRegisterTainted(ctx.registers.rbx)
```

Output:

```
Tainting RAX:  True
RAX tainted?:  True
RBX tainted?:  False
```

Thanks!

**Comment by JonathanSalwan** [comment]
What about if you have `movzx BYTE PTR [rax], rbx"` where `rax` is tainted. Do you consider the content of *rax as tainted?

**Comment by JonathanSalwan** [comment]
I think we must define a proper definition of these following behavior:

* `mov A, [B]` (`A` is tainted if `B` or `*B` are tainted)
* `mov [B], A` (`*B` is tainted if A is tainted)
* `xor A, [B]` (`A` is tainted if `A`, `*B` or `B` are tainted)
* `xor [B], A` (`*B` is tainted if `A` or `*B` is tainted)

Are you agree with that?

cc @pbrunet

**Comment by norrathep** [comment]
> What about if you have `movzx BYTE PTR [rax], rbx"` where `rax` is tainted. Do you consider the content of *rax as tainted?

For my usecase, I won't consider this (or rather I dont care if *rax is tainted or not). The usecase I'm considering is when a user controls a byte array and that byte array will be encoded and represented in some string format that is based on a constant look-up table (e.g., base64). I want to make sure that the encoded string is tainted.

**Comment by JonathanSalwan** [comment]
Okay but I cannot add rules for each specific use case, if we add this spread behavior we must be coherent in most cases. But never mind, just tell me if the patch is ok for your case.

**Comment by norrathep** [comment]
The patch works great for me. Thanks!

**Comment by norrathep** [comment]
Sorry, I just noticed a case that the patch won't work, i.e., if both registers are the same:

`movzx  rax,BYTE PTR [rax]`

**Comment by JonathanSalwan** [comment]
What is the problem? What was expected? Can you please provide a sample like your first comment?

**Comment by norrathep** [comment]
I just realized it was a problem with other parts of my code. Thanks again.
