### ISSUE TITLE
Invalid MemoryAccess size for x86_64 32 bit memory access

### ISSUE THREAD

**Issue by SweetVishnya** [JonathanSalwan/Triton#729]
```
mov [eax], rbx
```
https://github.com/JonathanSalwan/Triton/blob/df9d015aa5f3f924d9470c22d2ed479ace9d2e1d/src/libtriton/arch/x86/x8664Cpu.cpp#L420

`op->size` equals 4, but should be 8

**Comment by JonathanSalwan** [comment]
Are you saying that `mov [eax], rbx` performs a `qword` access and not a `dword` one?

**Comment by SweetVishnya** [comment]
Exactly.

**Comment by SweetVishnya** [comment]
Let me a few minutes to recheck this on real processor.

**Comment by SweetVishnya** [comment]
Tested that in gdb, it's actually QWORD:
```
mov    QWORD PTR [eax],rbx
```

**Comment by SweetVishnya** [comment]
Corresponding test can be found here:
https://github.com/JonathanSalwan/Triton/commit/4c73efd67d3233ea560680cb41e16626b3acd58c#diff-6b6f39a986842d3d541abe3f4b3c830bR159

**Comment by SweetVishnya** [comment]
elf64.asm:
```
bits 64

SECTION .mydata
resb 64

SECTION .text

global _start
_start:

MOV EAX, 0xffffffff
MOV RBX, 0x1234567812345678
MOV [EAX], RBX
RET
```
Compile:
```
nasm -f elf64 elf64.asm -o elf64.o
objcopy --set-section-flags .mydata=alloc,data,load elf64.o
ld --entry 0x400080 --section-start .text=0x400080 --section-start .mydata=0xffffffff -melf_x86_64 elf64.o -o elf64
```
