### ISSUE TITLE
Question about Triton's pintool

### ISSUE THREAD

**Issue by norrathep** [JonathanSalwan/Triton#733]
Hi,

I notice that the pintool for Triton only supports the version 71313 of Pin, which does not really work on Ubuntu 16.04.

So I'm wondering how hard is it to migrate the current code (only the taint engine part) to support a newer version of Pin? If it is not too complicated, I might be able to help too :D.

**Comment by JonathanSalwan** [comment]
The problem is that the newer version of Pin does not allow to link with external libs such that libTriton or libPython... However, I don't see the problem of using Pin 71313 on Ubuntu 16.04. Can you explain why?

**Comment by norrathep** [comment]
Ah I see. Sorry I mixed up the Ubuntu version with the kernel version. I'm using 4.xx kernel version and I suppose Pin does not support that kernel version. I can try to downgrade it.

**Comment by JonathanSalwan** [comment]
Don't worry, you can use Pin with a kernel version 4.x using the flag `pin -ifeellucky -t ...`. When you compile Triton with the Pin tracer, this flag is enabled by default :)
