### ISSUE TITLE
POP RSP - possibly wrong semantics

### ISSUE THREAD

**Issue by deresz** [JonathanSalwan/Triton#734]
I was trying to deobfuscate some code doing a lot of stack shifting/ stack pointer manipulations and while Triton did it suprisingly well (well, I only have comparison with BinaryNinja and IDA - which scores the worst in SP tracking), I noticed the POP RSP instruction behaved differently in emulation than during the real execution e.g. when executing the code on a real processor the final RSP value is always 8 bytes less than on the emulation. Maybe the "pop rsp" instruction should not increment the stack pointer ... ?

**Comment by JonathanSalwan** [comment]
Thanks for this feedback! I've pushed a fix. Can you tell me if the fix works for your use case?

Cheers,

**Comment by deresz** [comment]
Yep, thank you very much for a quick response !
