### ISSUE TITLE
installation error with basic_string

### ISSUE THREAD

**Issue by shabo1984** [JonathanSalwan/Triton#738]
sudo make -j install

/triton/triton/src/libtriton/ast/z3/tritonToZ3Ast.cpp: In member function ‘z3::expr triton::ast::TritonToZ3Ast::convert(const SharedAbstractNode&)’:

/triton/triton/src/libtriton/ast/z3/tritonToZ3Ast.cpp:164:96: **error**: no matching function for call to ‘**std::__cxx11::basic_string**<char>::basic_string(triton::uint512)’
           std::string value(reinterpret_cast<triton::ast::DecimalNode*>(node.get())->getValue());

What cause this problem?

**Comment by PMmuc** [comment]
Are you using the newest boost version 1.68? I had the same problem with this library.
When using boost 1.55 the problem went away.
I don't know the exact reason, but obviously in newer version of boost you are not allowed to convert from boost::multiprecision::number to const char*/string anymore.

**Comment by shabo1984** [comment]
what are gcc/g++ versions you used?

**Comment by JonathanSalwan** [comment]
Can you try the following patch with boost 1.68 and let me know if it works?

```patch
diff --git a/src/libtriton/ast/z3/tritonToZ3Ast.cpp b/src/libtriton/ast/z3/tritonToZ3Ast.cpp
index dd2aee69..b2c20a96 100644
--- a/src/libtriton/ast/z3/tritonToZ3Ast.cpp
+++ b/src/libtriton/ast/z3/tritonToZ3Ast.cpp
@@ -161,7 +161,7 @@ namespace triton {
         }
 
         case DECIMAL_NODE: {
-          std::string value(reinterpret_cast<triton::ast::DecimalNode*>(node.get())->getValue());
+          std::string value(reinterpret_cast<triton::ast::DecimalNode*>(node.get())->getValue().convert_to<std::string>());
           return this->context.int_val(value.c_str());
         }
 
@@ -277,7 +277,7 @@ namespace triton {
           /* If the conversion is used to evaluate a node, we concretize symbolic variables */
           if (this->isEval) {
             triton::uint512 value = reinterpret_cast<triton::ast::VariableNode*>(node.get())->evaluate();
-            std::string strValue(value);
+            std::string strValue(value.convert_to<std::string>());
             return this->context.bv_val(strValue.c_str(), symVar->getSize());
           }
```

**Comment by PMmuc** [comment]
Thanks, that fixes the above compile errors. But the Python bindings failures from issue #716 are still existing, so that I can't use Triton for python in windows.

**Comment by JonathanSalwan** [comment]
Mmmmh, what about using [Appeveyor's artefacts](https://ci.appveyor.com/project/JonathanSalwan/triton/builds/20207623) instead of compiling Triton on windows?

**Comment by JonathanSalwan** [comment]
Btw, i'm really not comfortable with Windows ecosystem so that I cannot figure out by myself what's the root cause of these issues.

**Comment by JonathanSalwan** [comment]
If you figure out how to solve them, I will be more than happy to accept your pull request :)

**Comment by PMmuc** [comment]
Apparently the Z3 Prover is linked dynamically with Triton, that's why I had to move the libz3.dll into the python2.7\Lib\site-packages directory as well for it to work. The tests still don't work as they seem to end up in an infinite loop but the python examples finally work.
