### ISSUE TITLE
It seems Triton.getModel can't give me right value of symbols.

### ISSUE THREAD

**Issue by JodieAllen** [JonathanSalwan/Triton#741]
Hi,
I try to avoid constraints of library function (`atoi`) , so I write a small testcase as following,
```
int func(char ptr[]){
    int tmp = atoi(ptr);
    if (tmp == 1000) {
        printf("OK\n");
    }
    return 0;
}
```
Then, I use `convertMemoryToSymbolicVariable` to symbolize `rdi` in the entry of `func(char ptr[])` as following,
```
rdi = getCurrentRegisterValue(Triton.registers.rdi)
Triton.convertMemoryToSymbolicVariable(MemoryAccess(rdi, 32))
```
In order to solve the last constraint (`tmp == 1000`) and avoid constraints in function `atoi`, I use commands as following ( `dstAddr` in `atoi` is larger than 100000000)
```
 if pc.isMultipleBranches():
       b1   =  pc.getBranchConstraints()[0]['constraint']
       b2   =  pc.getBranchConstraints()[1]['constraint']
          
       if ( pc.getBranchConstraints()[0]['dstAddr'] < 100000000 ):
              # Branch 1
              models  = Triton.getModel(b1)
              for k, v in models.items():
                    seed.append(v)

              # Branch 2
              models  = Triton.getModel(b2)
              for k, v in models.items():
                    seed.append(v)
``` 
However, the result is `B1: SymVar_0 = 0xC01E  |  B2: SymVar_0 = 0x3A93 ` , but I think  the symbol should be 0x3e8(1000) in one path , because the branch in testcase is ` if (tmp == 1000)` 
And the constraints as following:
```
b1: {'srcAddr': 4195832L, 'isTaken': True, 'dstAddr': 4195846L, 'constraint': (= (ite (= ref!757 (_ bv0 1)) (_ bv4195846 64) (_ bv4195834 64)) (_ bv4195846 64))}

b2: {'srcAddr': 4195832L, 'isTaken': False, 'dstAddr': 4195834L, 'constraint': (not (= (ite (= ref!757 (_ bv0 1)) (_ bv4195846 64) (_ bv4195834 64)) (_ bv4195846 64)))}

```
Can you give me some advice Why I can not get the right result (`1000`)?
Thanks a lot!

**Comment by JonathanSalwan** [comment]
Hi,

I see two issues in your method.

The first one is that `pc.getBranchConstraints()` returns the branch constraint of a single branch. Generally when you ask a model to take a specific branch you want to keep the previous path constraints and just change the last constraint to take the targeted branch. So, you have to forge a constraint which keep previous ones. The function `ctx.getPathConstraintsAst()` returns the complete path constraint (see [example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/ctf-writeups/defcon-2016-baby-re/solve.py#L207-L214)).

The second one is that using a DSE (symbolic execution on a trace) you just represent the current trace as symbolic expressions but it not means that you represent a whole function (like `atoi()`) as symbolic expression. In other words you only represent **one** path on the function `atoi()` as symbolic expressions. Which means that your symbolic representation is not complete (See definition 1 and 2 of terms [sound and complete](https://patricegodefroid.github.io/public_psfiles/pldi2011.pdf) by Patrice Godefroid). Asking a model like `atoi(ptr) == 1000` implies that you must have the whole symbolic expression of the `atoi()` function. The function `atoi()` has probably a lot of branches. With a single trace of your `atoi()`'s symbolic representation, maybe you cannot satisfy to the constraint `tmp == 1000`.

**Comment by JodieAllen** [comment]
Thanks for replying,
 I used `Triton.getModel` to solve a single trace of  `atoi()`'s symbolic representation, and as you said I did not get a satisfaction result (`tmp == 1000`).

Then, I try to find the  constraint (`SymVar_0 == 1000` or `SymVar_0 != 1000`) , but I only get the constraint `(= (ite (= ref!757 (_ bv0 1)) (_ bv4195846 64) (_ bv4195834 64)) (_ bv4195846 64))`.In this constraint,  I think `_ bv4195846` stands for a taken block address. 

So, is there any way I can get a constraint likes `SymVar_0 == 1000`. If I can, I could send it to SMT, maybe SMT can return me a satisfaction result.

**Comment by JonathanSalwan** [comment]
>but I only get the constraint (= (ite (= ref!757 (_ bv0 1)) (_ bv4195846 64) (_ bv4195834 64)) (_ bv4195846 64))

Use `ctx.unrollAst()` to see the whole constaint and find your constant 1000.

**Comment by JonathanSalwan** [comment]
what I would do in your case is to get `zf` expression at the `if (tmp == 1000)` instruction and ask a model like that `ast.land([ctx.getPathConstraintsAst(), zf == 1]`. That's all.

**Comment by JodieAllen** [comment]
Ok, Thanks a lot!
