### ISSUE TITLE
new triton::arch::x86::x8664Cpu() fails in 64-bit Triton

### ISSUE THREAD

**Issue by mxmssh** [JonathanSalwan/Triton#744]
Hi,
I am trying to implement a DynamoRIO's tracer based on existing Triton's Pin tracer. I have a problem with taking snapshots. The problem happens only for 64-bit build. This code raises exception:
```
 this->cpu = new triton::arch::x86::x8664Cpu(*dynamic_cast<triton::arch::x86::x8664Cpu*>(api->getCpuInstance()));
```
This code actually causes the problem:
```
Athena!triton::arch::x86::x86Specifications::x86Specifications:
00000000`cf8f6790 89542410        mov     dword ptr [rsp+10h],edx
00000000`cf8f6794 48894c2408      mov     qword ptr [rsp+8],rcx
00000000`cf8f6799 57              push    rdi
00000000`cf8f679a b830120100      mov     eax,11230h
00000000`cf8f679f e82c48efff      call    Athena!__chkstk (00000000`cf7eafd0)
00000000`cf8f67a4 482be0          sub     rsp,rax
00000000`cf8f67a7 488bfc          mov     rdi,rsp
00000000`cf8f67aa b98c440000      mov     ecx,448Ch
00000000`cf8f67af b8cccccccc      mov     eax,0CCCCCCCCh
00000000`cf8f67b4 f3ab            rep stos dword ptr [rdi]
```
```
b8.e4c): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
Athena!triton::arch::x86::x86Specifications::x86Specifications+0x24:
00000000`cf8f67b4 f3ab            rep stos dword ptr [rdi]
```

```rdi``` points out of stack boundary (unitialized area). rep stos is like ```memset(rdi, 0xCCCCCCCC, 0x448c);```. For some reason 0x448c causes memset to write into unitialized memory area. This code is just a stack initialization with 0xCC values used for debug purpose in Visual Studio. 

Have you guys seen such problems before ? I would really appreciate any advice how to address this issue because it doesn't look like Triton or tracer. It is more likely some linkage/compilation problem. I tried to disable stack checking, security options and etc but it didn't work. It looks weird that it happens only for 64-bit build.

**Comment by mxmssh** [comment]
BTW, It is not a recursion.

**Comment by JonathanSalwan** [comment]
If you solved this issue please close the thread.

>Have you guys seen such problems before ? I would really appreciate any advice how to address this issue because it doesn't look like Triton or tracer. It is more likely some linkage/compilation problem.

I'm really not comfortable with Windows (last time I used a Windows machine it's when XP SP1 was the last release of MS), so I have no idea =/.

**Comment by mxmssh** [comment]
I haven't solve it yet. The problem is more likely related to our tool rather than to Triton itself. I am closing this issue. In case, someone get the same problem we can reopen it.
