### ISSUE TITLE
Missing "undefined state" in semantics.

### ISSUE THREAD

**Issue by TehRick** [JonathanSalwan/Triton#750]
For instance, OR and AND should set the AF flag as undefined.
Backward taints and junk code removal can be incorrect without this behavior.
The relevant table is available in Intel's manual Vol.1 A.1 EFLAGS AND INSTRUCTIONS.
(It should be available in capstone too)
Depending on how you would like the "undefined" value to be defined in Triton, I can code the changes.

**Comment by JonathanSalwan** [comment]
Can you provide an example of what you want to do with this kind of information? Because I cannot add an AST node which represents the undefined behavior. Why? because Triton is also a dynamic symbolic emulator and the emulation works by evaluating AST node. Currently, undefined behaviors are handled using the last value assigned to the register.

**Comment by TehRick** [comment]
Using prior value makes it a pass-through in term of dependencies.
Currently I face a junk instruction which sets the AF flag, followed by an AND. As I do a local pass meant to speed up the processing of heavily junked blocks (in loops) I consider every register alive at the end of the block and compute def/uses. Problem is the AF flag is considered dependent on a big sequence of junk code with the current Triton semantic of AND.
The simplest solution without creating a new symbolic variable would be to simply reset the concerned flag with a comment "Undefined flag, arbitrarily set to 0." as for always cleared flags.

**Comment by JonathanSalwan** [comment]
I pushed a patch on the `dev-750` branch. Tell me what do you think about that. Now AbstractNode can be tagged as _undefined_ without breaking the symbolic reasoning.

**Comment by JonathanSalwan** [comment]
I'm not comfortable with the idea to modify the symbolic reasoning based on the undefined behavior. However, I add a new mode `CONCRETIZE_UNDEFINED_NODE` which will concretize every nodes tagged as undefined Then, an `Instruction` can provide information about what registers it tagged as undefined. 

See example below:

```python
#!/usr/bin/env python2
## -*- coding: utf-8 -*-
##
## $ python ./test.py
## 0x0: mov rax, 0x10
##
## 0x7: mov rbx, 0x20
##
## 0xe: inc rax
##
## 0x11: xor rax, rbx
## af:1 bv[0..0]
##
## 0x14: mul rbx
## af:1 bv[0..0]
## pf:1 bv[0..0]
## sf:1 bv[0..0]
## zf:1 bv[0..0]
##

from triton import *

ctx = TritonContext()
ctx.setArchitecture(ARCH.X86_64)
ctx.enableMode(MODE.CONCRETIZE_UNDEFINED_NODE, True)


trace = [
    "\x48\xc7\xc0\x10\x00\x00\x00", # mov rax, 0x10
    "\x48\xc7\xc3\x20\x00\x00\x00", # mov rbx, 0x20
    "\x48\xff\xc0",                 # inc rax
    "\x48\x31\xd8",                 # xor rax, rbx
    "\x48\xf7\xe3",                 # mul rbx
]

for op in trace:
    inst = Instruction(op)
    ctx.processing(inst)
    print inst
    for r in inst.getUndefinedRegisters():
        print r
    print
```

**Comment by TehRick** [comment]
Simple access to undefined registers let me complete the local defs easily. I can get rid of the symbolic exprs with the new mode, and the forward taint is working as expected so it's a perfect solution.
Thanks.

**Comment by JonathanSalwan** [comment]
Don't hesitate to reopen this thread if you see some issues during your tests.
