### ISSUE TITLE
TypeError: x8664Cpu::disassembly(): Invalid operand

### ISSUE THREAD

**Issue by windy1946** [JonathanSalwan/Triton#752]
I setArchitecture(), set x86_64, and then run processing(), there is an error of invalid operand.(src/examples/cpp/ir.cpp)
   is there any thing wrong?

**Comment by windy1946** [comment]
I try to use the example you provide in "Triton/src/examples/cpp/". the process is that:
1. make all (in example/cpp direction, after I install triton) 
2. ./constraint.bin.
the error log is:
terminate called after throwing an instance of 'triton::exceptions::Disassembly'
  what():  x8664Cpu::disassembly(): Invalid operand.
Aborted (core dumped)

and I found it crash in api.disassembly(); 
I use ubuntu18.

**Comment by JonathanSalwan** [comment]
what is your arch? what is the target arch ? what version of capstone did you used ?

**Comment by JonathanSalwan** [comment]
```
$ cd build/src/examples/cpp
$ ./constraint
RAX expr: (bvxor SymVar_0 (_ bv287454020 64))
constraint: (= (bvxor SymVar_0 (_ bv287454020 64)) (_ bv0 64))
Model:
  - Variable id  : 0
  - Variable name: SymVar_0
  - Value        : 11223344
```

**Comment by windy1946** [comment]
> ```
> $ cd build/src/examples/cpp
> $ ./constraint
> RAX expr: (bvxor SymVar_0 (_ bv287454020 64))
> constraint: (= (bvxor SymVar_0 (_ bv287454020 64)) (_ bv0 64))
> Model:
>   - Variable id  : 0
>   - Variable name: SymVar_0
>   - Value        : 11223344
> ```
> 
> > Can you reproduced this crash?
> 
> nop

This problem is fix after I re-install Triton.
Thanks.

**Comment by njayinthehouse** [comment]
I'm getting this error as well. A reinstall did not solve the issue. I'm using the Python bindings.
```
» python3.8 ir.py
Traceback (most recent call last):
  File "ir.py", line 72, in <module>
    Triton.processing(inst)
TypeError: x8664Cpu::disassembly(): Invalid operand.
```
