### ISSUE TITLE
Questions about Taint engine and Python binding

### ISSUE THREAD

**Issue by rainkin1993** [JonathanSalwan/Triton#756]
Hi,
I want to use Triton on Windows and I have several questions about Triton.

1. Does taint engine really execute the program in a computer or just emulate the execution of the program? 
How do you handle external API calls, like system call? 
Without Pin, does taint engine still work?

2. Triton has a Python binding to Pin. My question is does Triton have a Python binding to libtrion.dll/so and can I build this binding without Pin binding because I hear that Triton pintool does not work on Windows?

**Comment by JonathanSalwan** [comment]
> Does taint engine really execute the program in a computer or just emulate the execution of the program?

The `libTriton` symbolically emulates opcodes provided by an user. It does not execute the code.

> How do you handle external API calls, like system call?

That's the user's responsibility to handle the the behavior for any kind of external calls.

> Without Pin, does taint engine still work?

The `libTriton` takes as inputs an initial context and opcodes. They can be provided by many ways such that: gdb, ida, a database, Pin, Qemu, Dynamorio or by yourself parsing the file format. We provided Pin as an example but the `libTriton` does not depends to Pin.

> My question is does Triton have a Python binding to libtrion.dll/so 

Yes.

> and can I build this binding without Pin binding because

They are not related. The `libpintool` has its own bindings and the `libTriton` has its own bindings too.

> I hear that Triton pintool does not work on Windows?

You're right, the pintool does not works on Windows but you are free to chose what you want in order to provide opcodes to the `libTriton`.

**Comment by rainkin1993** [comment]
Thanks for your reply.

> The libTriton symbolically emulates opcodes provided by an user. It does not execute the code.

Just curious. In my understanding, PIN has already emulated opcodes, why does Triton not reuse PIN-like tools instead of emulating by yourselves.

And Does Triton can analyze complext applications, like chrome, firefox?

> That's the user's responsibility to handle the the behavior for any kind of external calls.

Do you have some example codes about handling external calls?  I cannot imagine how I handle external calls.


> You're right, the pintool does not works on Windows but you are free to chose what you want in order to provide opcodes to the libTriton.

What is the purpose of Pin-like tool? Just provide  initial context and opcodes to libtriton? or any other things?

**Comment by JonathanSalwan** [comment]
> Just curious. In my understanding, PIN has already emulated opcodes, why does Triton not reuse PIN-like tools instead of emulating by yourselves.

Pin does not emulate the code. It's a DBI based analysis, so it really executes the code on your CPU.  Then, `libTriton` provides a semantics information while Pin does not.

> And Does Triton can analyze complext applications, like chrome, firefox?

Tools that can analyze programs like chrome or firefox in their whole integrity are rare (to not say a myth). The state of the art of program analysis is so much far away to deal with complexes programs such that chrome in its whole integrity. But if you know what you are looking for, you can analyze some parts of its components easily.

> Do you have some example codes about handling external calls? I cannot imagine how I handle external calls.

[Example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/small_x86-64_symbolic_emulator.py)

> What is the purpose of Pin-like tool? Just provide initial context and opcodes to libtriton? or any other things?

Just to provide a context and opcodes at each program point, yes.

**Comment by rainkin1993** [comment]
Sorry for the late reply.

> Pin does not emulate the code. It's a DBI based analysis, so it really executes the code on your CPU. Then, libTriton provides a semantics information while Pin does not.

Yes. Triton is a DBA. Let me make my question more clear.
In my understanding, DBI (like PIN) can insert analysis code between opcodes of an executable file and execute codes on CPU. Thus DBI is efficient because directly run on CPU. 

For `libtrion`, it also inserts analysis routines (like taint engine) into codes of an executable and emulates these codes.

Thus the question is why `libtriton` does not directly insert analysis routines based on PIN and directly execute codes on CPU. The benefit is high performance.

> Tools that can analyze programs like chrome or firefox in their whole integrity are rare (to not say a myth). The state of the art of program analysis is so much far away to deal with complexes programs such that chrome in its whole integrity. But if you know what you are looking for, you can analyze some parts of its components easily.

I hear some products based on Panda, a taint engine based on Qemu ( a system-level DBI, that's why I have the above first question, why Triton not based on PIN), which can perform system-level taint analysis.

Some papers based on Panda also shows that they can perform taint-analysis on browsers.

1. FAROS
paper: http://www.daniela.ece.ufl.edu/Research_files/dsn18.pdf
open source tool: https://github.com/mnavaki/FAROS

2. PIITracker
paper: https://dl.acm.org/citation.cfm?id=3193114
open source tool: https://github.com/mnavaki/PIITracker

**Comment by JonathanSalwan** [comment]
> Thus the question is why libtriton does not directly insert analysis routines based on PIN and directly execute codes on CPU. The benefit is high performance.

Yes. Thing is that we don't want to depend on others frameworks. For example, if we are Pin dependent we cannot analyse ARM64 binaries.
