### ISSUE TITLE
No Modules Named Triton

### ISSUE THREAD

**Issue by nyanhacker** [JonathanSalwan/Triton#757]
When it tests to UnicornAArch64Semantics it gives error no modules named triton. what should i do ?

**Comment by JonathanSalwan** [comment]
install Triton?

**Comment by nyanhacker** [comment]
yes, im building into my ppa. and it error no modules named triton

**Comment by nyanhacker** [comment]
You can see my logs on here: https://launchpadlibrarian.net/408778774/buildlog_ubuntu-bionic-amd64.triton_0.6-3_BUILDING.txt.gz

**Comment by JonathanSalwan** [comment]
You should do a `make install` before a `make check`.
