### ISSUE TITLE
TritonToZ3Ast convertation works too long and does redundant work

### ISSUE THREAD

**Issue by igogo-x86** [JonathanSalwan/Triton#762]
Running symbolic execution on binary obfuscated by one prominent virtualizer it's impossible to wait until expression at some stage gets converted to z3. After investigating a problem I found out that expression usually contains a lot of identical sub-expressions that are actually the same `AbstractNodes`. So it leads to triton converting the same nodes again and again.

Here's a simple piece of code with essence of the problem:
```python
import triton

N = 20

t = triton.TritonContext()
t.setArchitecture(triton.ARCH.X86_64)
t.convertRegisterToSymbolicVariable(t.registers.rax)

inst = triton.Instruction()
inst.setAddress(0x100)
inst.setOpcode("\x48\x01\xc0")      # add   rax, rax

for _ in range(N):
    t.processing(inst)
    inst.setAddress(inst.getAddress() + inst.getSize())


print t.simplify((t.getSymbolicRegister(t.registers.rax).getAst()), True)
```

With N = 20 this script works 0.481s on my machine and with N = 25 it takes 15.780s. 

I've added `std::unordered_map<SharedAbstractNode, z3::expr *> cache` field to TritonToZ3Ast and everything started work nice and fast. But I'm not sure this commit is good enough for being included in the library. Instance of `TritonToZ3Ast` can be used several times and cache needs to be invalidated between converts. So I would like to hear how you see solving this issue and what think about cache implementation.

**Comment by JonathanSalwan** [comment]
I know about this bug and you are right we have to make a cache of `<SharedAbstractNode, z3::expr>` for improvement. Also, `TritonToZ3Ast` and `Z3ToTritonAST` must not have recursion calls (see #655. btw I will accept your PR about `newInstance` improvement but we must keep in mind the we have to remove all recursion calls in the Triton library).

Halvar started to add a patch for the non recursion calls (see [#659](https://github.com/JonathanSalwan/Triton/pull/659/files) and [this line](https://github.com/JonathanSalwan/Triton/pull/659/files#diff-6984ad0f43b2a56e9eb9eff0404af45dR92)), maybe we can combine both features, non-recursion and cache nodes.

**Comment by JonathanSalwan** [comment]
I just pushed a new method which can help for AST traversal without recursive calls:

```cpp
void nodesExtraction(std::list<SharedAbstractNode>* output,
                     const SharedAbstractNode& node,
                     bool unroll,
                     bool revert);
```

If `unroll` is true, we unroll all references. If `revert` is true, children are on top of the list.

**Comment by JonathanSalwan** [comment]
@igogo-x86, I pushed the no-recursive `TritonToZ3` function into the `dev-655` branch. I tried to add a cache mechanism to reduce the traversal AST but without success... Also, i'm not 100% sure of my `nodesExtraction` algorithm... But, we have the same results as before (according to unittests) and I think it's a good start the AST traversal improvement.

**Comment by JonathanSalwan** [comment]
With `N = 100`:

```
$ time python test.py
(_ bv0 64)
python test.py  0.02s user 0.01s system 99% cpu 0.031 total
```

With `N = 1000`:

```
$ time python test.py
(_ bv0 64)
python test.py  0.12s user 0.01s system 99% cpu 0.135 total
```


With `N = 10000`:

```
$ time python test.py
(_ bv0 64)
python test.py  2.19s user 0.07s system 99% cpu 2.253 total
```

**Comment by igogo-x86** [comment]
I'm not sure it's a good idea to use `std::find function` on `std::list` container as it has O(n) complexity. Also I think it's better to make two methods (or add boolean parameter) for prebuilding AST visitor - something like `nodesExtraction` and `uniqueNodesExtraction`. For converters and `newInstance` method it's better to go only through unique nodes. In your implementation same nodes from different levels of a tree are considered to be different and there could arise issues with big ASTs.

It's a bit late for me to create pull request since you've already implemented the basis but here's the example of how I did it:

```cpp
//! Creates stack with unique nodes collected with Depth-first Pre Order Traversal over AST tree
std::stack<triton::ast::SharedAbstractNode> uniqueNodeExtraction(const triton::ast::SharedAbstractNode& node) {
  std::stack<triton::ast::AbstractNode *> todo;
  std::stack<triton::ast::SharedAbstractNode> result;
  std::set<const triton::ast::AbstractNode *> visited;

  todo.push(node.get());
  while (!todo.empty()) {
    auto current = todo.top();
    todo.pop();

    // This means that node is already in work_stack and we will not need to convert it second time
    if (visited.find(current) != visited.end()) {
      continue;
    }

    visited.insert(current);
    result.push(current->shared_from_this());

    if (current->getType() == REFERENCE_NODE) {
      todo.push(reinterpret_cast<triton::ast::ReferenceNode *>(current)->getSymbolicExpression()->getAst().get());
    } else {
      for (const auto &child : current->getChildren())
        todo.push(child.get());
    }
  }
  return result;
}
```

This function returns `std::stack` which highlights the fact that processing should go from the end

**Comment by JonathanSalwan** [comment]
Thanks for this function. Just a question, when/where will we use the `uniqueNodeExtraction`?

**Comment by igogo-x86** [comment]
In any conversion (if anything else except z3 is planned). The algorithm is following - we pop a node from stack, convert it and store inside cache. The order in which stack is filled guarantees that for every popped node its children will be already converted.

Also we can use it for `newInstance`. We create a copy of a node and store it in cache (original_node_ptr -> new_node_ptr). All children of a node will be already copied and we just take them, assign them to a node and add them a parent.

The same is for `unrollAst`.

By the way what is the point for AbstractNode to have information about parents?

**Comment by JonathanSalwan** [comment]
>  The order in which stack is filled guarantees that for every popped node its children will be already converted.

Yes I got the algorithm but this is false for children of references =/. For example, you can test it with this [example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/proving_opaque_predicates.py).

**Comment by JonathanSalwan** [comment]
I'm closing this as we pushed a fix which provides a relevant increase of speed for AST conversion from Triton to Z3 (even if it's not still perfect).
