### ISSUE TITLE
Question about how jmp dwod ptr [address] works

### ISSUE THREAD

**Issue by SoonwonPark** [JonathanSalwan/Triton#768]
I've been using the Triton python binding library to analyze a simple witch case program on IDA pro.

My goal is to demonstrate how a switch case works with different register values.
I modified Triton/src/examples/python/forward_tainting.py to write my own script.

![switch_case](https://user-images.githubusercontent.com/35434064/53279921-52b6e880-36da-11e9-9ddf-c2a41b4f5e62.png)
- This is a part where I want to demonstrate, it is captured on IDA.
- What I want to do is to demenstrate  "jmp     dword ptr ds:off_412D54[edx*4]" at 0x00412BF8 with different edx values.

![edx_value_change](https://user-images.githubusercontent.com/35434064/53279989-22bc1500-36db-11e9-908b-cda600719c93.png)
- I tried to change the edx value as 0x1
- I expected that "jmp     dword ptr ds:off_412D54[edx*4]"-> jmp dword ptr [edx*4 + 0x412d54] -> jmp dword ptr [0x412d58]

![hex_values](https://user-images.githubusercontent.com/35434064/53280032-aa098880-36db-11e9-9556-d43ef547db99.png)
 - When I saw the hex value at 0x412d58, 
 - From 0x412d58 to 0x412d5b, the value was 2d 2c 41 00
 - I expected jmp dword ptr [0x412d58] would be jmp 412c2d

![first_case](https://user-images.githubusercontent.com/35434064/53280089-1f755900-36dc-11e9-8c31-3b117bc6fc33.png)
- Instead of jumping to 0x412c2d, it jumped to 0x412bff

![first_case_hex](https://user-images.githubusercontent.com/35434064/53280134-885cd100-36dc-11e9-894a-2dae4667d6e7.png)
- 0x412bff was "jmp dword ptr[0x412d54]
- I thought the edx value change didn't work for "jmp     dword ptr ds:off_412D54[edx*4]" although I manually changed the value using my script.
- Same result happened when I used different values for edx.
- Can you tell me what was the problem? 

I attach the program and the python script.
[switch_case.zip](https://github.com/JonathanSalwan/Triton/files/2896374/switch_case.zip)

Thank you.

**Comment by JonathanSalwan** [comment]
> My goal is to demonstrate how a switch case works with different register values.

I didn't understand. Did you mean that you wanted to list all destination addresses of a switch cases?

**Comment by SoonwonPark** [comment]
Thank you for your reply.

I understand how a swich case works with different register values theoretically.
I want to see how Triton processes an instruction, which has a swich case, with different register values.

For example "jmp dword ds:off_412D54[edx*4]", this jmp instruction works depending on the value of the edx.

If the value of the edx is 0x0, the instruction would be "jmp dword ptr[0x412D54]".

If the value of the edx is 0x1, the instruction would be "jmp dword ptr[0x412D58]."

But when I tried to make Triton process the instruction with different edx values, 
![edx_value_change](https://user-images.githubusercontent.com/35434064/53291178-d6251800-3774-11e9-88a8-642fbaa95180.png)

I tired ctx.setConcreteRegisterValue(ctx.registers.edx, 0x1), 
After ctx.processing(inst), the next instruction was the result of "jmp dword ptr[0x412D54]", not the result of "jmp dword ptr[0x412D58", meaning that the the [edx*4] part was not processed properly.

After changing the value of edx, I checked the value using ctx.getConcreteRegisterValue(ctx.registers.edx). The edx value was changed but "jmp dword ds:off_412D54[edx*4]" had no change. 

Can you tell me what the problem was? Was there any mistake I made?
I uploaded my program and a python script on the previous question.

Thank you.
Soonwon
