### ISSUE TITLE
Question about the taint rules

### ISSUE THREAD

**Issue by SoonwonPark** [JonathanSalwan/Triton#772]
I have a question about the taint rules.

Please loot at the image below.
 - I used IDA and triton to analyze a malicious program.
 - I changed the background color of instructions which were processed by triton to pink.
 - If an instruction is tainted, I changed the background color to blue.
 - This image is a part of my analysis and tainting started before this function, sub_4063C4.
 - I tainted ebx register before this function.

![taint](https://user-images.githubusercontent.com/35434064/53920297-4dd72a80-4032-11e9-9af1-fa07f22df935.png)

My question is : 
 - Why is the instruction "mov     al, byte_4063EA[eax]" at CODE:004063DD not tainted?
 - At CODE:004063CF and CODE:004063D2, the eax register and the al (half of eax) register were tainted.
 - I expected that "mov     al, byte_4063EA[eax]"  and " jmp     dword ptr off_406471[eax*4]" would be tainted, because these instructions depend on the eax register.
 - Is it the triton's rule that this instruction not to be tainted?
 - #725 would be about a similar question, I want to know the taint rule.

Thank you.
Soonwon

**Comment by JonathanSalwan** [comment]
To spread taint over array indexes, you have to enable the following mode:

```python
enableMode(MODE.TAINT_THROUGH_POINTERS, True)
```
