### ISSUE TITLE
Required library Z3 NOT FOUND

### ISSUE THREAD

**Issue by Abhijeet1990** [JonathanSalwan/Triton#778]
I have an issue with the installation of Z3. I pip installed Z3 still the problem exist.

Error Output:
Z3_INCLUDE_DIR=Z3_INCLUDE_DIR-NOTFOUND
Z3_INCLUDE_DIRS=
Z3_LIBRARY=Z3_LIBRARY-NOTFOUND
Z3_LIBRARIES=
CMake Error at CMakeModules/LibFindMacros.cmake:75 (message):
  Required library Z3 NOT FOUND.

  Install the library (dev version) and try again.  If the library is already
  installed, use ccmake to set the missing variables manually.
Call Stack (most recent call first):
  CMakeModules/FindZ3.cmake:32 (libfind_process)
  CMakeLists.txt:153 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by JonathanSalwan** [comment]
Use `-DZ3_INCLUDE_DIR=<path of your includes dir> -DZ3_LIBRARY=<path of your libz3.so>` if the your path library is not found. Also, verify if there is not a mismatch between 2.7 (triton) and 3.x (z3).
