### ISSUE TITLE
a liitle problem about the getModel function()

### ISSUE THREAD

**Issue by hguone** [JonathanSalwan/Triton#780]
Hi, I recently do some experimental tests with the excellect tool -- triton. I encountered one problem, when I try to implement the code_coverage function targeting at one function based on the tool  code_coverage.py this [commit](https://github.com/JonathanSalwan/Triton/commit/f6c66ba81a56262a54931bd12b296b3809025952) . But, I don't know why the getModel() function can't receive the para past to it.

```py

        if instruction.getAddress() == TritonExecution.exitPoint:
            print "[+] Exit point"
            ast = ctx.getAstContext()
            #for pc in TritonExecution.myPC:
            #    print (pc[0])
            # SAGE algorithm
            # http://research.microsoft.com/en-us/um/people/pg/public_psfiles/ndss2008.pdf
            for j in range(TritonExecution.input.bound, len(TritonExecution.myPC)):
                #print (TritonExecution.input.bound)
                expr = []
                for i in range(0, j):
                    ripId = TritonExecution.myPC[i][0]
                    #symExp = ctx.getSymbolicRegister(ripId).getAst()
                    addr = TritonExecution.myPC[i][1]
                    expr.append((ast.assert_(ast.equal(ripId, ast.bv(addr,  CPUSIZE.QWORD_BIT)))))
                    #self.assertEqual(ast.equal(symExp, ast.bv(addr,  CPUSIZE.QWORD_BIT)))

                ripId  = TritonExecution.myPC[j][0]
                #print (ripId)
                #symExp = ast.unrollAst(ctx.getSymbolicVariableFromName(ripId).getAst())#ctx.getSymbolicMemory(ripId)
                addr   = TritonExecution.myPC[j][2]
                #expr.append(ast.assert_((ast.equal(symExp, ast.bv(addr, CPUSIZE.QWORD_BIT)))))
                expr.append(ast.assert_((ast.equal(ripId, ast.bv(addr, CPUSIZE.QWORD_BIT)))))
                #print (expr)
                expr = ast.compound(expr)
                print (expr)
                model = ctx.getModel((expr))
```

and, the following is the output
![image](https://user-images.githubusercontent.com/48470946/56596914-fdd51700-6623-11e9-92ba-78887bb95905.png)

I thought the expr type is bool, it looks like I'm wrong. Can you help me, thank you very much!!

**Comment by JonathanSalwan** [comment]
Why are you not using an up-to-date version of Triton?

**Comment by hguone** [comment]
I use the lastest Triton, my code_coverage.py is based on the version in the [commit](https://github.com/JonathanSalwan/Triton/commit/f6c66ba81a56262a54931bd12b296b3809025952), because actually I'm not familiar with how can I coverage a function on my own. Some API changed, I modified them to the lastest version, but I can't get the correct result.

**Comment by JonathanSalwan** [comment]
Try without the node `ast.assert_()`.
