### ISSUE TITLE
External Function Call

### ISSUE THREAD

**Issue by hxuhack** [JonathanSalwan/Triton#782]
Hi, Jonathan,

I noticed that Triton has changed a lot. In particular, it does not rely on Pin now. Do the older (concoclic execution) scripts based on Pin still work? I cannot find such examples in the current repository. Can you provide some samples?

Regarding the new symbolic execution sample provide in python/code_coverage_crackme_xor.py, may I  know is there any convenient way to support external function calls (e.g., atoi) ? 

Thanks!

**Comment by JonathanSalwan** [comment]
> Do the older (concoclic execution) scripts based on Pin still work?

It never worked properly. If you want to bench Triton against other DSE tools, please don't use this script. Triton is not a tool but a library and users have to write their own _tritontool_ focusing on their goals.

> Regarding the new symbolic execution sample provide in python/code_coverage_crackme_xor.py, may I know is there any convenient way to support external function calls (e.g., atoi) ?

[Here](https://github.com/JonathanSalwan/Triton/blob/3f95e54f076308d6885071a21ae71eb2123771d2/src/examples/python/small_x86-64_symbolic_emulator.py) is an example about how you can handle external calls.

I'm currently working on a DSE tool relaying on `libTriton` but it's not ready to be released yet.

**Comment by hxuhack** [comment]
Thanks, Jonathan. I'll look into the example you mentioned.
By the way, Triton is a great project. Please let me know if anything we can contribute.

**Comment by JonathanSalwan** [comment]
Thanks! :), These last months the project growing slowly 'cause I'm finishing a thesis but after that (hope in September) I will be back actively on the Triton development.
