### ISSUE TITLE
Loader feature request

### ISSUE THREAD

**Issue by the-elves** [JonathanSalwan/Triton#785]
while doing some analysis using triton, the analysis gets stuck whenever it reaches library functions. which also makes sense, since library code is not loaded. Is there functionality to do that if not is there a reason why is it not there? I have seen the hooks example am not talking about summaries but user space library functions being symbolically executed

**Comment by JonathanSalwan** [comment]
> I have seen the hooks example am not talking about summaries but user space library functions being symbolically executed

It's the same way. Load the program and its libraries using Lief and setup your GOT/PLT with your mapping.

**Comment by the-elves** [comment]
Can this be made an feature of triton, thus user won't have to setup his own GOT/PLT entries ?

**Comment by JonathanSalwan** [comment]
Currently it is not our philosophy to provide loaders for different binary formats. We prefer provide very specific features but reliable ones and let users to setup things for their use cases. Loaders are hard to maintain and have some kind of voodoo behaviors in some cases.
