### ISSUE TITLE
node.evaluate() on an integer node returns always zero

### ISSUE THREAD

**Issue by werew** [JonathanSalwan/Triton#790]
I don't know if this is a bug or I misunderstood the purpose of `evaluate`.
When calling `node.evaluate()` on a integer node this always returns zero despite the actual value of the node.

```python
from triton import *
ac = TritonContext().getAstContext()
ast = ac.zx(32, ac.bv(42, 16))
print(ast.getChildren()[0])                  # prints 32
print(ast.getChildren()[0].evaluate())       # prints  0
```

**Comment by JonathanSalwan** [comment]
`evaluate()` evaluates only _typed_ node in term of bitvector-based types. Nodes which cannot be evaluated are:

* INTEGER
* STRING

For those two nodes, if you want to get their content, you have to call respectively `node.getInteger()` and `node.getString()`.
