### ISSUE TITLE
Triton QEMU emulator and AES ISA

### ISSUE THREAD

**Issue by mustakcsecuet** [JonathanSalwan/Triton#793]
Hi
I write a triton tool that uses QEMU emulator. I was trying to emulate a project that uses AES-NI instructions and my emulator seems cannot process those instructions. Is that the Triton QEMU do not support those instructions?

**Comment by JonathanSalwan** [comment]
Triton does not support the AES-NI extension. Btw, I'm not sure there exist a symbolic engine which supports those instructions. For more information about what we support, [here](https://triton.quarkslab.com/documentation/doxygen/SMT_x86_Semantics_Supported_page.html) is the list of supported instructions.

**Comment by mustakcsecuet** [comment]
Thank you.
