### ISSUE TITLE
vpermd instruction support

### ISSUE THREAD

**Issue by Daniele-B** [JonathanSalwan/Triton#798]
is vpermd AVX-256 instruction supported?

I've encountered this: `[-] Instruction not supported: 0xf000337d: vpermd ymm0, ymm0, ymmword ptr [r8 + rcx + 0x800]`.

The python code is just:
```
[...]
inst = Instruction()
op = ctx.getConcreteMemoryAreaValue(pc, 16)
inst.setOpcode(op)
inst.setAddress(pc)
if ctx.processing(inst) == False:
			debug('[-] Instruction not supported: %s' %(str(inst)))
			break
[...]
```

**Comment by JonathanSalwan** [comment]
Sadly no. [Here](https://triton.quarkslab.com/documentation/doxygen/SMT_x86_Semantics_Supported_page.html) are the list of supported instructions. Btw, you can still add its semantics in this [file](https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/arch/x86/x86Semantics.cpp) :)
