### ISSUE TITLE
AstNode.equalTo failing because of hash collision

### ISSUE THREAD

**Issue by werew** [JonathanSalwan/Triton#803]
The hash algorithm is not very robust against collisions. Consequentially this may cause the method `equalTo` to return faulty results. Here is an example where two different ASTs give the same hash and are considered equal despite being different:

```python
from triton import TritonContext, ARCH

ctx = TritonContext()
ctx.setArchitecture(ARCH.X86_64)
ac = ctx.getAstContext()

# Create two different symbolic variables
other_vars = [ctx.newSymbolicVariable(64, 'myvar1') for _ in range(4)] # Unused vars (ignore this)
var1 = ctx.newSymbolicVariable(64, 'myvar1')
other_vars2 = [ctx.newSymbolicVariable(64, 'myvar1') for _ in range(3)] # Unused vars (ingore this)
var2 = ctx.newSymbolicVariable(64, 'myvar2')

# Create two different variable nodes
ast1 = ac.variable(var1)
ast2 = ac.variable(var2)

# Make variables have the same value (optional)
ctx.setConcreteVariableValue(var1, 42)
ctx.setConcreteVariableValue(var2, 42)

print(f"EVAL {ast1.evaluate()} == {ast2.evaluate()}")
print(f"HASH ast1: {ast1.getHash()}")
print(f"HASH ast2: {ast2.getHash()}")
print(f"ID {var1.getId()} != {var2.getId()}")
print(ast1.equalTo(ast2))
```

Output:
```
EVAL 42 == 42
HASH ast1: 5422260411841997021281208543007119826811670799627441236266270739690799860817374512700263447961384686134468906522758777373115772670237551433478634774127769
HASH ast2: 5422260411841997021281208543007119826811670799627441236266270739690799860817374512700263447961384686134468906522758777373115772670237551433478634774127769
ID 4 != 8
True
```
Here the names "SymVar_4" and "SymVar_8" produce the same hash.
I know that collisions are inevitable, however in a space of 512 bits they should not be so easy.
Having symbolic variables that easily collide can in turn cause bigger ASTs to collide.

This is not an isolated case. According to my experience collisions happens regularly enough when working on sub-trees searches on big trees full of similar operations.

I don't know if this can be solved using a better non-cryptographic hash function (e.g. FVN-1a) given that hashing an AST has some special requirements (#237).
Maybe a little workaround is to include the symbolic variable ID as part of the hash (e.g. lower 64 bits). Since IDs are unique this should assure no collisions up to 2^64 variables. 

EDIT: 
After further thinking about this issue I think that using FVN-1a (or any good and fast hash function) combined with a merkle-tree structure is probably the best solution.

**Comment by JonathanSalwan** [comment]
And what about just iterating on each node of the tree and compare them each others?

**Comment by werew** [comment]
This would assure the correctness of the result for `equalTo` but would not solve the hash problem.
I also strongly support the idea of having a (pretty reliable) method to compare trees in constant time.
Maybe both methods could be implemented, something like `equalTo` and `equalToFast`.
