### ISSUE TITLE
Check if the value conforms with the AstNode

### ISSUE THREAD

**Issue by MingxuanYao** [JonathanSalwan/Triton#807]
I'm not sure how to check if a concrete value conforms with the AstNode or not.

For example,
```python
from triton import *

ctxt = TritonContext()
ctxt.setArchitecture(ARCH.X86)
inst = Instruction('\x83\xc0\x07') # add eax, 7
ctxt.convertRegisterToSymbolicVariable(ctxt.registers.eax)

ctxt.processing(inst)

eaxAst = ctxt.getSymbolicRegister(ctxt.registers.eax).getAst()

c = eaxAst >= 10
```

Now I have the AstNode `c`. Meanwhile, I also have a concrete value `14`. I'm wondering if there's a way to check if the integer `14` conforms with the AstNode `c`.

Any reply will be appreciated!

Thanks

**Comment by JonathanSalwan** [comment]
```python
ast = ctxt.getAstContext()                    
print(ctxt.isSat(ast.land([c, eaxAst == 14])))
```

**Comment by MingxuanYao** [comment]
Thank you so much! However, I met a little problem in the following case. I have a branch constraint `b` by marking memory access in instruction `cmp byte ptr [esi+eax], 0x68` and that should be solved as 0x68. And another AstNode of symbolic memory access.
```Python
print(ctxt.isSat(ast.land([b, var_ast==104]))) # True
print(ctxt.isSat(ast.land([b, var_ast <= 256]))) # False
```
I'm not sure why the second AstNode can't be satisfied?

Any reply will be appreciated!

Thanks!

**Comment by JonathanSalwan** [comment]
256 = 0x100 = 9 bits. As it's a `cmp byte ptr`, the 8-bit extraction of 0x100 is 0x00. So you, constraint is like:

```python
print(ctxt.isSat(ast.land([b, var_ast <= 0x00]))) 
```

Try with 255 :)

**Comment by MingxuanYao** [comment]
> 256 = 0x100 = 9 bits. As it's a `cmp byte ptr`, the 8-bit extraction of 0x100 is 0x00. So your constraint is like:
> 
> ```python
> print(ctxt.isSat(ast.land([b, var_ast <= 0x00]))) 
> ```
> 
> Try with 255 :)

LOL. My bad
