### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [JonathanSalwan/Triton#81]
[Extra null pointer checks are not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [AnalysisProcessor::updateCurrentCtxH](https://github.com/JonathanSalwan/Triton/blob/98ea571ef5bd3dfe250ae327da33a3b4b500796c/src/analysisProcessor/analysisProcessor.cpp#L17 "AnalysisProcessor::updateCurrentCtxH function")
* [SnapshotEngine::resetEngine](https://github.com/JonathanSalwan/Triton/blob/98ea571ef5bd3dfe250ae327da33a3b4b500796c/src/snapshotEngine/snapshotEngine.cpp#L76 "SnapshotEngine::resetEngine function")

**Comment by JonathanSalwan** [comment]
Thanks. Fixed

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/JonathanSalwan/Triton/commit/0d7b0fc066cfd4b66b922640ff754cdc9c95f825 "Deletion of a few unnecessary checks").
