### ISSUE TITLE
buildSemantics does not update operand's lea when called multiple times

### ISSUE THREAD

**Issue by PixelRick** [JonathanSalwan/Triton#810]
I am currently reusing instructions and call buildSemantics multiple times but the source memory operands are stuck to their first concretization.
It is due to the initLeaAst() call in buildSemantics not using FORCE_MEMORY_INITIALIZATION.
This is the only place this function is called with a 'false' (here default) argument.
What is the reason for this behavior and how could I avoid re-disassembling the same instruction just to reset the memory operand to 'not initialized' (address 0) ?
(I currently patched my build to use force_mem.)

**Comment by JonathanSalwan** [comment]
Actually, it's mainly used for implicit behaviors of Pin and its cache mechanism. I'm agreed that if it's Pin dependent, it should not be in `libtriton`... At this moment, you can force it to true if you want until I found a workaround for Pin.
