### ISSUE TITLE
Rename parts of API

### ISSUE THREAD

**Issue by JonathanSalwan** [JonathanSalwan/Triton#812]
In order to be more relevant, I suggest to rename these following methods:

* ~convertExpressionToSymbolicVariable -> symbolizeExpression~
* ~convertMemoryToSymbolicVariable -> symbolizeMemory~
* ~convertRegisterToSymbolicVariable -> symbolizeRegister~
* ~enableMode -> setMode~
* ~getSymbolicExpressionFromId -> getSymbolicExpression~
* ~getSymbolicVariableFromId -> getSymbolicVariable(integer)~
* ~getSymbolicVariableFromName -> getSymbolicVariable(string)~
* ~isSymbolicExpressionIdExists -> isSymbolicExpressionExists(integer)~
* ~taintUnion and taintAssignment with polymorphic properties~
* ~unrollAst -> unroll~
* ~lookingForNodes -> search~
* ~getPathConstraintsAst -> getPathPredicate~

**Comment by RobinDavid** [comment]
For a more compact API it would also be nice to change a little the two fonctions:

TritonContext()  -> TritonContext(architecture)

and:

Instruction(opcode) -> Instruction(opcode, address)

We cant really do anything without having initialized the architecture and respectively having given the address so it does not seems useful having setArchitecture and setAddress as separate functions.

**Comment by JonathanSalwan** [comment]
Thx, we will add theses prototypes.

> and respectively having given the address

btw, the address of the instruction is defined via the current rip.
