### ISSUE TITLE
Suggestion on saving TritonContext or AstNode?

### ISSUE THREAD

**Issue by MingxuanYao** [JonathanSalwan/Triton#824]
Considering that I already have the TritonContext which has constraints on some memory addresses, how can I dump it into a local file so that we can load it into python later?

Any reply will be appreciated!

**Comment by JonathanSalwan** [comment]
The API does not exposes such feature at this moment. A potential solution could be to print `AbstractNode` in a file and then make your own SMT parser in order to build Triton objects with `AstContext`. Then, you also have to recreate and reassign all `SymbolicExpression`.
