### ISSUE TITLE
~Instruction - access violation on Windows

### ISSUE THREAD

**Issue by technateNG** [JonathanSalwan/Triton#828]
There is an issue witch triton::arch::Instruction on Windows. When destructor is called on vector\<SharedSymbolicExpressions\> we've got access violation.
Bug exists in examples/ir.cpp file in but can be minimized to:
```
int main(void)
{
    triton::arch::Instruction instr;
    return 0;
}
```
PR with fix on the way.

**Comment by JonathanSalwan** [comment]
Thx for the fix but i don't understand why we got an access violation when the destructor of an empty vector is called and why defining a destructor for `Instruction` solve this issue. Does adding a destructor for `Instruction` really solve this issue (why?) or does it just a side effect?
