### ISSUE TITLE
How to use Triton with multiproessing module

### ISSUE THREAD

**Issue by vancaho** [JonathanSalwan/Triton#834]
Hi, I want to use multiprocessing with triton. In the children process, there is a variable of triton.Instruction() type. How to access the variable in the father process? If I use multiprocessing.Manager(), it reports ```TypeError: can't pickle Instruction objects```.

**Comment by vancaho** [comment]
I found that the python objects in triton, e.g. TritonContext(), Instruction() does not support pickle protocol. How to add pickle for these C++ extention?

**Comment by JonathanSalwan** [comment]
I'm not sure it's possible to make Triton objects available by the `pickle` in an easy way. For that purpose, we have to serialize everything (`AbstractNode`, `SymbolicExpression`, etc.) which is an huge modification of the library (serialization of objects also means that we can initialize them from the serialization).

**Comment by vancaho** [comment]
That are bad news. If I want to use multi processes to process Instructions() and TritonContext(), do you have any suggestion? Thanks very much

**Comment by JonathanSalwan** [comment]
I don't really know what you are trying to do, but maybe this can help you:
```python
#!/usr/bin/env python
## -*- coding: utf-8 -*-

from triton import *
from multiprocessing import Process, Manager
from multiprocessing.managers import BaseManager


def f(tt):
    tt.setArchitecture(ARCH.X86_64)
    return

if __name__ == '__main__':
    BaseManager.register('TritonContext', TritonContext)
    manager = BaseManager()
    manager.start()

    tt = manager.TritonContext()

    p1 = Process(target=f, args=(tt,))
    p1.start()
    p1.join()

    print(tt.getArchitecture())
```
