### ISSUE TITLE
AST simplification on bitvector Extract

### ISSUE THREAD

**Issue by RobinDavid** [JonathanSalwan/Triton#835]
Some AST simplification can be performed in the ``AstContext::extract``. Especially an extract on a constant value can be simplified.

This can be easily implemented in : https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/ast/astContext.cpp#L594

I will implement it and do the PR. *(creating the issue for the record)*

**Comment by JonathanSalwan** [comment]
Maybe add a new mode `CONSTANT_FOLDING` for that purpose.

**Comment by RobinDavid** [comment]
Yes that would make sense. Need to see if it does not overlap with ``AST_OPTIMIZATIONS``.

**Comment by RobinDavid** [comment]
Nice commit. However I have a suggestion. Your optimization does not perform anything if there is at least on symbolic variable in the expression which prevents folding any foldable sub-expressions. 

Thus something like bvadd(bvadd(4, 5), x) will never get simplified. By construction it seems unlikely that such expressions will get created, but by means of constant propagation that will likely happen.

After, is it worth implementing it, I don't know.

**Comment by JonathanSalwan** [comment]
I give you one beer if you are able to make this happen with the `CONSTANT_FOLDING` mode enabled.
