### ISSUE TITLE
Taint analysis on aarch64 binaries?

### ISSUE THREAD

**Issue by rocahe** [JonathanSalwan/Triton#837]
Hello, 

I noticed that Triton relies on Pin/Pintools to do dynamic taint anlaysis on x86/x86-64 binaries.  I wonder if it is possible to rely on other DBA tools like DynamoRIO to provide the same functionality for aarch64 binaries?

As a taint engine, does Triton currently handle shadow regeisters/memories and taint propagation automatically?

Thanks!
-Boyuan

**Comment by JonathanSalwan** [comment]
Triton does not rely on Pin to perform DTA. Taint engine and symbolic execution are totally independent of any kind of DBI. We just provide a pintool tracer as example. So yes, you can use DynamoRIO as a tracer if you want. For example, [here](http://shell-storm.org/repo/Notepad/qbdi_with_triton.txt) is another example using [QBDI](https://github.com/QBDI/QBDI) as tracer. Note that it is not mandatory to use a tracer to analyse a binary. Triton can emulate binaries. [Here](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/ctf-writeups/custom-crackmes/aarch64-hash/solve.py) is an example of an AArch64 emulation.

**Comment by rocahe** [comment]
Thanks for your quick response!  
So you mean that Triton can either work with a DBI tool, or simply emulates the binary?

In the first case, I assume Triton is plugged into the DBI tool by registering callbacks for each instruction and therefore runs with concrete memory/register. Does Triton maintain shadow memory/register and handle the taint propogation or relies on DBI tools to intrument additional instructions back to the binary in order to propogate taint labels?  

In the second case, it runs with emulated memory/register.  Is it possible to emulate AARCH64 instructions on X86 host like qemu?

BTW, I'm currently working on DTA for aarch64 binaries. 

Thanks!
-Boyuan

**Comment by JonathanSalwan** [comment]
> So you mean that Triton can either work with a DBI tool, or simply emulates the binary?

Yes. Triton takes as input the current instruction to execute. This instruction may comes from a DBI or directly by opening and parsing a binary file.

> In the first case, I assume Triton is plugged into the DBI tool by registering callbacks for each instruction and therefore runs with concrete memory/register.

Yes. As explained before, Triton takes as input the current instruction to execute and a potential initial context. In this case, a callback (in the DBI tool) is defined before each instruction and then the instruction is provided to Triton.

> Does Triton maintain shadow memory/register and handle the taint propogation

Yes.

> or relies on DBI tools to intrument additional instructions back to the binary in order to propogate taint labels?

No. In Triton we defined all instruction semantics (over an IR) for i686, x64 and AArch64 (ARM32 is in progress), taint rules and symbolic execution rely on this IR. In this case, the DBI is only used to provide the initial context and the execution ordering. 

> In the second case, it runs with emulated memory/register. Is it possible to emulate AARCH64 instructions on X86 host like qemu?

Yes.

**Comment by rocahe** [comment]
OK, I see. That's why you call DBI a tracer becasue Triton does not rely on it for intrumentation. 
What granulariry does Triton provide for DTA?  Byte level?

Also, does Triton support python3? I'm having a trouble to make it work with python3.  The Lief project has dropped python2 suppport.

Thanks!

**Comment by JonathanSalwan** [comment]
> What granulariry does Triton provide for DTA? Byte level?

Currently, the granularity is about the object level (register, memory cell). For example, if you taint 1-bit of the register `x0`, the whole register will be considered as tainted... This granularity will change in the future to perform a bit-level tainting.

> Also, does Triton support python3? I'm having a trouble to make it work with python3. The Lief project has dropped python2 suppport.

You have to compile with `-DPYTHON36=on`.

```
$ mkdir build ; cd build
$ cmake -DPYTHON36=on ..
$ make -j2
```
