### ISSUE TITLE
symbolizeMemory() with ALIGNED_MEMORY

### ISSUE THREAD

**Issue by akasong** [JonathanSalwan/Triton#840]
In C++ API, When I used to symbolizeMemory() with ALIGNED_MEMORY mode, the following codes getId() returned incresed by 2.

```
api.setMode(triton::modes::ALIGNED_MEMORY, true);

( ... )

for (unsigned int i = 0; i < size; i++)
  api.symbolizeMemory(triton::arch::MemoryAccess(address + i, 1));

auto mem = api.getSymbolicMemory();
for (auto iterator = mem.begin(); iterator != mem.end(); iterator++)
  printf("%d\n", iterator->second->getId());
```
--result--
1
3
5
7
9
11
( ... )

When unset ALIGNED_MEMORY, the result is 1,2,3,4,5, ...
I don't know triton internals well. maybe symbolizeMemory() makes two symbolic expression internally.
Is it correct operation?

**Comment by JonathanSalwan** [comment]
Hi @akasong,

Don't worry, this is a normal behavior. ALIGNED_MEMORY deals with its own expressions, that's why there are more than without the optimization.
