### ISSUE TITLE
relationship between taint engine and symbolic engine

### ISSUE THREAD

**Issue by akasong** [JonathanSalwan/Triton#841]
When only using taint engine, it's not doing getReadRegisters(), getLoadAccess(), and other methods in every instructions.
These methods only works when symbolic engine was enabled.
It seems that these are related to symbolic engine.
Do I need to always enable symbolic engine if I only use taint engine? or only enable taint engine then solve it with debugger/instrumentator's API?

**Comment by JonathanSalwan** [comment]
Hey @akasong,

Sorry for the delay. Yes, currently those information are built by the symbolic engine and not the taint one.

> Do I need to always enable symbolic engine if I only use taint engine?

Actually it depends on your needs. If you want to only keep information related to the taint state, you can do something like this:

```python
ctx = TritonContext(ARHC.X86_64)
ctx.setMode(MODE.ONLY_ON_TAINTED, True)
```
