### ISSUE TITLE
Does pintool support multi-process or multi-threaded programs?

### ISSUE THREAD

**Issue by windxuemo** [JonathanSalwan/Triton#842]
I used triton for the taint tracking proftpd program, but unfortunately, there was a signal 11 error

`
terminate called after throwing an instance of 'std::runtime_error'
  what():  tracer::pintool::context::getCurrentMemoryValue(): Page not readable.
C: Tool (or Pin) caused signal 11 at PC 0x7f58306a9177
`

proftpd is a multi-process program, so I want to know if pintool supports multi-process or multi-thread

**Comment by JonathanSalwan** [comment]
Our pintool does not support multi-process or multi-thread application.
