### ISSUE TITLE
can't pickle AstNode objects

### ISSUE THREAD

**Issue by d4em0n** [JonathanSalwan/Triton#843]
while trying to save AstNode object using pickle, pickle can't dump it. Any other ways to save AstNode objects in file for caching?

**Comment by JonathanSalwan** [comment]
Yep, i can confirm that `AstNode` and others objects from Triton are not pickable.

> Any other ways to save AstNode objects in file for caching?

Nop =/. Or maybe making your own text parser from the `str` output of objects...
