### ISSUE TITLE
getModel should return "no solution" like z3, instead of empty dict

### ISSUE THREAD

**Issue by d4em0n** [JonathanSalwan/Triton#844]
this is confusing
```
>>> type(rax)
<class 'AstNode'>
>>> ctx.getModel(rax == rax)
{}
>>> ctx.getModel(astCtxt.land([rax == 2, rax == 3]))
{}
```
z3 handle no solution like this
```
>>> rax = BitVec('rax', 64)
>>> solve(rax == rax)
[]
>>> solve(rax == 2, rax == 3)
no solution
```

**Comment by d4em0n** [comment]
is this a relevant code?
https://github.com/JonathanSalwan/Triton/blob/ab90e0155b919ab814f341e624fc101250112af0/src/libtriton/engines/solver/z3/z3Solver.cpp#L66

**Comment by d4em0n** [comment]
found ctx.isSat can solve this

**Comment by JonathanSalwan** [comment]
Yep. In fact, in a near future `getModel` will return a tuple `<sat, model>`. In order to avoid a second call to `isSat` if model is empty.
