### ISSUE TITLE
How to accelerate Triton's execution? 

### ISSUE THREAD

**Issue by kingsleyluoxin** [JonathanSalwan/Triton#849]
Hello, I am trying to use Triton combined with Pin to record instruction execution traces. However, I found it ran quite slowly even with simple applications such as /bin/ls. I am wondering how can I accelerate its execution? Will it be better to use its C++ version to write an Pin tool?

Thanks!

**Comment by JonathanSalwan** [comment]
Hi @kingsleyluoxin, unfortunately I think you can do nothing to accelerate the instrumentation and symbolic part =/. Those two analysis imply an overhead not negligible compared to a concrete execution.
