### ISSUE TITLE
Introduction of namespaces

### ISSUE THREAD

**Issue by elfring** [JonathanSalwan/Triton#85]
I suggest to add more [namespaces](https://en.wikipedia.org/w/index.php?title=Namespace#Use_in_common_languages "Use of namespaces") to the source files of your class library.

Examples:
* [AnalysisProcessor](https://github.com/JonathanSalwan/Triton/blob/9f796931c2d688f11af3f579ed8b3b39c3eee613/src/includes/AnalysisProcessor.h#L15)
* [Trigger](https://github.com/JonathanSalwan/Triton/blob/9f796931c2d688f11af3f579ed8b3b39c3eee613/src/includes/Trigger.h#L4)

Would you like to [reduce the probability for name clashes](http://www.drbio.cornell.edu/pl47/programming/TICPP-2nd-ed-Vol-one-html/Chapter10.html#Heading303 "Namespaces")?

**Comment by elfring** [comment]
Do you reject this improvement request?

**Comment by JonathanSalwan** [comment]
I don't think that these classes will get collisions with others one :) but I will use namespace when it's necessary :)

**Comment by JonathanSalwan** [comment]
If you think it's vital to use namespaces at some place, you're welcome for any PR :)
