### ISSUE TITLE
Windows 7 - Specified module not found

### ISSUE THREAD

**Issue by hackingump** [JonathanSalwan/Triton#853]
Hello, I compiled the Triton 0.7 release with a success and now I try to load the triton.pyd module and I get the following error  : 

```
C:\Users\blackbeard\Desktop\triton\Triton-0.7\out\build\x64-Debug\src\libtriton>
python test.py
['C:\\Users\\blackbeard\\Desktop\\triton\\Triton-0.7\\out\\build\\x64-Debug\\src
\\libtriton', 'C:\\Users\\blackbeard\\AppData\\Local\\Programs\\Python\\Python36
\\python36.zip', 'C:\\Users\\blackbeard\\AppData\\Local\\Programs\\Python\\Pytho
n36\\DLLs', 'C:\\Users\\blackbeard\\AppData\\Local\\Programs\\Python\\Python36\\
lib', 'C:\\Users\\blackbeard\\AppData\\Local\\Programs\\Python\\Python36', 'C:\\
Users\\blackbeard\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-package
s']
Test
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    import triton
ImportError: DLL load failed: The specified module could not be found.
```

I ran the script in the same folder the pyd file lies in.  The script simply prints the `sys.path` variable for better error finding.

Is there something I am missing ? 

I will provide additional information if needed. Thanks in advance!

**Comment by JonathanSalwan** [comment]
Mmmmh,

Can you check if z3 is also available with `sys.path`?

**Comment by hackingump** [comment]
Yes, I already tried putting the z3.lib file into the same folder as well as other paths which are in the `sys.path` variable.

I also tried using the pre built binaries and also got the same error so far.

**Comment by JonathanSalwan** [comment]
I know nothing about Windows but maybe is it related to the need to [Visual C++ redistributable](https://www.microsoft.com/en-US/download/details.aspx?id=30679) packages?

**Comment by JonathanSalwan** [comment]
Did you found the solution?

**Comment by hackingump** [comment]
My bad, I totally forgot this here :-(. I will give it a try on the weekend again and inform you in this issue about it.

**Comment by hackingump** [comment]
Well I switched to using it on Linux for now. The problem still exists though.

**Comment by JonathanSalwan** [comment]
Ok. I'm closing this but feel free to update the thread if you found the solution on Windows :)

**Comment by charlesnathansmith** [comment]
I had the same problem and found a workaround

The current AppVeyor triton.pyd binary is dependent on "python36.dll"
It's hardcoded into the import table

You have to make sure you're using Python 3.6.* specifically and that the directory with python36.dll is in your Windows PATH and it works fine.  You may just be able to copy python*.dll from later versions to python36.dll assuming it's compatible but I haven't tried it yet
