### ISSUE TITLE
Fail running libtriton with pin

### ISSUE THREAD

**Issue by s0i37** [JonathanSalwan/Triton#857]
Hello.
I am trying to run simple script with pintool tracer (win7 64, all tools compiled in 32):

`\path\to\pin-2.14-71313\pin.exe -script \windows\syswow64\triton.dll -script \users\admin\desktop\test.py -- \users\admin\desktop\test.exe`

But I have the following error:

```
E: Failure to initialize DLL C:\Windows\SysWOW64\VCRUNTIME140.dll
E:       System error 182 : %1.
E: Failure to initialize DLL C:\Windows\SysWOW64\python36.dll
E:       See preceding message to find out the reasonE: Failure to initialize DL
L C:\Windows\SysWOW64\triton.dll
E:       See preceding message to find out the reason
```
Btw I have the vcredists2015 for x86.
In same time my pintool successfully runs with pin-2.14.
`Z3` was compiled with VS2015 and `capstone` with VS2013

Thank you

**Comment by JonathanSalwan** [comment]
I cannot help on you the Windows side =/ but i'm interested to the answer, so if you find the solution please let us know :)
