### ISSUE TITLE
Running triton on Windows

### ISSUE THREAD

**Issue by cssaheel** [JonathanSalwan/Triton#863]
Hello,

I successfully compiled triton.dll for windows and successfully ran backward_slicing.py. However I am trying to run other python scripts like this:
./build/triton ./src/examples/pin/runtime_memory_tainting.py ./src/samples/crackmes/crackme_xor a

the problem is that I don't have ./build/triton, please help. Thanks!

**Comment by JonathanSalwan** [comment]
The pintool is not available for Windows. See https://github.com/JonathanSalwan/Triton/issues/269 for more information.
