### ISSUE TITLE
isMemoryMapped need a batter name

### ISSUE THREAD

**Issue by JonathanSalwan** [JonathanSalwan/Triton#866]
Should be something like `isConcreteValueDefined()`.

**Comment by RobinDavid** [comment]
If modifying isMemoryMapped, would it also make sense to also rename its sibling `unmapMemory()` ?

**Comment by JonathanSalwan** [comment]
ofc

**Comment by JonathanSalwan** [comment]
Maybe something like this:

* `Architecture::isConcreteValueDefined(triton::uint64 baseAddr, triton::usize size)`
* `Architecture::isConcreteValueDefined(const triton::arch::MemoryAccess& mem)`
* `Architecture::isConcreteValueDefined(const triton::arch::Register& reg)`
* `Architecture::clearConcreteValue(triton::uint64 baseAddr, triton::usize size)`
* `Architecture::clearConcreteValue(const triton::arch::MemoryAccess& mem)`
* `Architecture::clearConcreteValue(const triton::arch::Register& reg)`

**Comment by RobinDavid** [comment]
Sounds very nice! Maybe having the same function name overloaded with different parameters number is a bit misleading so for `isConcreteValueDefined` and `clearConcreteValue` switching to `isConcreteMemoryValueDefined` and `clearConcreteMemoryValue`?

**Comment by JonathanSalwan** [comment]
Ok, go for that then :)
