### ISSUE TITLE
Parallel processing for software components

### ISSUE THREAD

**Issue by elfring** [JonathanSalwan/Triton#87]
The implementation of your class library does not use the technique "multi-threading" so far.
I guess that it contains enough software components and processing phases which could benefit from [parallelisation](https://en.wikipedia.org/wiki/Parallel_computing "Working in parallel").

**Comment by JonathanSalwan** [comment]
Thanks to suggest this but use multi-threading inside a callback JITed when you apply an instrumentation is (imho) not a good idea. Actually, I never tried to JIT a multi-threading callback but I think it will produce some weird behaviors :s
