### ISSUE TITLE
Undefined behavior while proccessing exception

### ISSUE THREAD

**Issue by archercreat** [JonathanSalwan/Triton#872]
Hello, I'm having trouble understanding how triton processes exceptions.
For example, in the code below the devision by 0 should yield an exception:
```python
from triton import *


code = {
    0x400000 : b"\xB8\x05\x00\x00\x00",  # mov eax, 5
    0x400005 : b"\xBA\x00\x00\x00\x00",  # mov edx, 0
    0x40000A : b"\xF7\xF2",                       # div edx
    0x40000C : b"\x90"
}


ctx = TritonContext()
ctx.setArchitecture(ARCH.X86)
ctx.concretizeAllMemory()
ctx.concretizeAllRegister()
ctx.setMode(MODE.ALIGNED_MEMORY, True)
ctx.setAstRepresentationMode(AST_REPRESENTATION.PYTHON)

pc = 0x400000

while pc in code:
    inst = Instruction()
    inst.setOpcode(code[pc])
    inst.setAddress(pc)
    if ctx.processing(inst) == False:
        print('error at', hex(pc))
        break
    print(inst)
    pc = ctx.getConcreteRegisterValue(ctx.registers.eip)

eax = ctx.getSymbolicRegister(ctx.registers.eax)
print(eax)
eax = ctx.getConcreteRegisterValue(ctx.registers.eax)
print('eax = %s' % hex(eax))
```
returns
```
0x400000: mov eax, 5
0x400005: mov edx, 0
0x40000a: div edx
0x40000c: nop
ref_4 = ((((ref_2) << 32 | ref_0) / ref_2) & 0xFFFFFFFF) # DIV operation
eax = 0xffffffff
```

But if we change `    0x40000A : b"\xF7\xF2",  # div edx`  to `"\xCC", int3` it breaks on error

```
error at 0x40000a
ref_0 = 0x5 # MOV operation
0x5
```

**Comment by archercreat** [comment]
It looks like int3 is not implemented, but div is.

**Comment by JonathanSalwan** [comment]
> Hello, I'm having trouble understanding how triton processes exceptions.

This is pretty easy to explain, we do not support exceptions :)). So, in your case of the div by 0, it provides an undefined result in term of concrete value but the execution continue without alerting the user...

What do you think we should do?

**Comment by archercreat** [comment]
It is probably a good idea to somehow notify user about exceptions, so he could process it manually..
Perhaps an exception state?
It will also allow someone to write os like behavior when exception occurs. 

```
if ctx.processing(inst) == STATE.EXCEPTION:
```

**Comment by JonathanSalwan** [comment]
> It is probably a good idea to somehow notify user about exceptions, so he could process it manually..

I agree with this. I let this issue open to think about it and provide such feature.

**Comment by JonathanSalwan** [comment]
Should be fixed. For your `div 0` use case, `processing` returns `EXCEPTION.FAULT_DE`. For your `int3` use case, it returns `EXCEPTION.FAULT_BP`.
