### ISSUE TITLE
Triton header files depend on Z3_INTERFACE

### ISSUE THREAD

**Issue by SweetVishnya** [JonathanSalwan/Triton#883]
Hi!
I recently found out that one should build his tool using Triton with -DZ3_INTERFACE if he wants to use `isSat` method. Is there any way to make it little bit clearer to end user? Maybe we should define Z3_INTERFACE in header by default?

**Comment by JonathanSalwan** [comment]
Mmmh, Z3_INTERFACE is [enabled by default](https://github.com/JonathanSalwan/Triton/blob/master/CMakeLists.txt#L22)?

**Comment by JonathanSalwan** [comment]
Oh, i see your point!

**Comment by SweetVishnya** [comment]
Yeah, it's enabled in cmake, but not in header files.

**Comment by SweetVishnya** [comment]
Do you know a correct way to do it? Is it some kind of modification of header files from cmake?

**Comment by JonathanSalwan** [comment]
I will do it.

**Comment by JonathanSalwan** [comment]
Should be ok now :)

**Comment by JonathanSalwan** [comment]
I let you try and close this issue if it's works :)
