### ISSUE TITLE
Setting concrete values of xmm registers

### ISSUE THREAD

**Issue by SweetVishnya** [JonathanSalwan/Triton#884]
Why should I use [this](https://github.com/JonathanSalwan/Triton/blob/dev-v0.8/src/libtriton/utils/coreUtils.cpp#L44) function if I want to set XMM register concrete value?

Isn't it better to just dereference 128 bit value?

**Comment by JonathanSalwan** [comment]
I don't remember why I did these functions. We have to verify if boost can cast an array into its multiprecision integer object (i'm not 100% sure we can cast from an array).

**Comment by SweetVishnya** [comment]
We will try and I let you know if we can cast.

**Comment by JonathanSalwan** [comment]
A [thread](https://stackoverflow.com/questions/50465041/how-to-convert-boostmultiprecisioncpp-int-tofrom-an-array-of-byte) related to this.

**Comment by SweetVishnya** [comment]
I got some new. You can cast 128 bit values, but not 256 and 512.
