### ISSUE TITLE
[Question] Triton Taint analysis

### ISSUE THREAD

**Issue by mauricesvp** [JonathanSalwan/Triton#887]
Hello there,

I have a question about implementing a taint analysis using the python bindings.

In short, I want to taint the input of a program (i.e. files for cat) and generate boundaries (i.e. list of addresses), after which the input is not used anymore (for cat: input has been written).

I have tried an approach similar to the `small_x86-64_symbolic_emulator.py` example, however after a few minutes of running, the process just gets killed by my Linux. Is loading a whole binary not feasable with Titron?

I'd be happy about any help, thanks in advance.

**Comment by JonathanSalwan** [comment]
> I have tried an approach similar to the small_x86-64_symbolic_emulator.py example, however after a few minutes of running, the process just gets killed by my Linux. Is loading a whole binary not feasable with Titron?

Can you share your Triton tool? Because `small_x86-64_symbolic_emulator.py` is just an example of how to do an emulator with Triton not an emulator usable on real program. If you based on this example, you have to implement all external functions that uses your target (cat).

> however after a few minutes of running, the process just gets killed by my Linux.

This is basically because you did not supported all external functions and at one point you call a function which is not supported and so not mapped and the `small_x86-64_symbolic_emulator.py` jump on zero and fetch opcodes : 0x00 0x00 0x00 0x00 ... which is a valid instruction in x86 and your program never finish which consumes all you memory.

```
0x0000000000000000:  00 00    add byte ptr [rax], al
0x0000000000000002:  00 00    add byte ptr [rax], al
0x0000000000000004:  00 00    add byte ptr [rax], al
0x0000000000000006:  00 00    add byte ptr [rax], al
0x0000000000000008:  00 00    add byte ptr [rax], al
0x000000000000000a:  00 00    add byte ptr [rax], al
```

To be sure of that you can print the instruction processed in your Triton tool.

**Comment by mauricesvp** [comment]
> If you based on this example, you have to implement all external functions that uses your target (cat).

I didn't actually really base it on the example, as in I didn't hook all (or any that is) function. Using /bin/cat my script just exits after the first null byte is encountered. However I am actually using a custom (statically) compiled cat, for which the analysis seems to work. It runs into an endless loop though, most likely because I did not configure arguments and so it tries to read stdin ... will do that now and test if it works.

Here is my script so far:
```
from __future__ import print_function
from triton import *

import sys
import lief

BASE_STACK = 0x9fffffff

if __name__ == '__main__':
    ctx = TritonContext()
    ctx.setArchitecture(ARCH.X86_64)
    ctx.setMode(MODE.ALIGNED_MEMORY, True)
    ctx.setAstRepresentationMode(AST_REPRESENTATION.PYTHON)
    binary = lief.parse("/path/to/custom/cat")
    phdrs = binary.segments
    for phdr in phdrs:
        size = phdr.physical_size
        vaddr = phdr.virtual_address
        ctx.setConcreteMemoryAreaValue(vaddr, phdr.content)

    ctx.setConcreteRegisterValue(ctx.registers.rbp, BASE_STACK)
    ctx.setConcreteRegisterValue(ctx.registers.rsp, BASE_STACK)
    pc = binary.entrypoint

    while pc:
        inst = Instruction()
        op = ctx.getConcreteMemoryAreaValue(pc, 16)

        inst.setOpcode(op)

        inst.setAddress(pc)

        ctx.processing(inst)

        some_addr = 0x1234567  # Actual value differs
        if inst.getAddress() == some_addr:
            ctx.taintRegister(ctx.registers.rsi)

        if inst.isTainted():
            print('[tainted] %s' % (str(inst)))

        pc = ctx.getConcreteRegisterValue(ctx.registers.rip)
```

PS: This runs into a loop both with a valid taint address (that gets hit) or an invalid one.

**Comment by JonathanSalwan** [comment]
Any new on this?

**Comment by mauricesvp** [comment]
First of all, sorry for not updating this.

I have tried to setup the argv manually, however I didn't really manage to do so. I also tried to use the pintools bindings, however I ran into issues similar to #859 , which is weird as I tried it within a docker as well as a VM, installing the 4.0.1 version of capstone from source. Perhaps there were other problems with required libraries ...

Going back to my use case, maybe you could point me into the direction of a better way of approaching this. I am also looking into other frameworks that can do Taint-Analysis, however I am yet to find a working, let alone _reasonably simple_, solution.

**Comment by JonathanSalwan** [comment]
> Going back to my use case, maybe you could point me into the direction of a better way of approaching this.

Loop are many caused due to unsupported Triton instruction. You should do something like:

```
if ctx.processing(inst) == False:
    print("Unsupported instruction")
    break
```

Btw, if you emulate a whole static binary, you have to support syscalls.
