### ISSUE TITLE
Iterating Triton Instruction getReadRegisters()

### ISSUE THREAD

**Issue by cssaheel** [JonathanSalwan/Triton#890]
Hello,

I am trying to iterate through getReadRegisters() for every executed instruction.
I am able to disassemble the instructions using api.disassembly(), so I think I have properly initialized the instruction instances.
However, when I try to iterate through the instruction operands it never goes into the loop!

this is my code:
 auto it = triton_inst->getReadRegisters().begin();
 while (it != triton_inst->getReadRegisters().end()) {
     dr_fprintf(STDERR, "it->first.getId() = %d\n", it->first.getId());
     ++it;
 }

Thanks.

**Comment by JonathanSalwan** [comment]
And what was the instruction you processed?

**Comment by cssaheel** [comment]
Hello Jonathan, actually I tested with many instructions with the following code:
dr_fprintf(STDERR, "Triton instruction at %#llx: %s\n", pc, tritonInst->getDisassembly().c_str());

Output:
....
Triton instruction at 0x7ffb391dabd6: mov rcx, qword ptr [rbx + 8]
Triton instruction at 0x7ffb391dabdf: call qword ptr [rip + 0x12c09b]
Triton instruction at 0x7ffb391dabdf: call qword ptr [rip + 0x12c09b]
Triton instruction at 0x7ffb391dabe5: and qword ptr [rbx + 8], 0
Triton instruction at 0x7ffb391dabe5: and qword ptr [rbx + 8], 0
Triton instruction at 0x7ffb391dabd1: test rbx, rbx
Triton instruction at 0x7ffb391dabd1: test rbx, rbx
Triton instruction at 0x7ffb391dabef: mov qword ptr [rip + 0x17440a], rdi
Triton instruction at 0x7ffb391dabef: mov qword ptr [rip + 0x17440a], rdi
Triton instruction at 0x7ffb3919d517: jmp 0x7ffb3919d3a3
Triton instruction at 0x7ffb3919d517: jmp 0x7ffb3919d3a3
Triton instruction at 0x7ffb3919d3a3: mov eax, r12d
Triton instruction at 0x7ffb3919d3a3: mov eax, r12d
....


none of these instructions can be iterated with getReadRegisters()

**Comment by JonathanSalwan** [comment]
I think you used `ctx.disassembly()` and not `ctx.processing()`. In order to determine what are the implicit and explicit behaviors of an instruction we have to build its IR. Disassembly just translates a given opcode to a string representation but in any way gives information about its implicit/explicit read/write.

**Comment by cssaheel** [comment]
Thank you Jonathan, I figured the problem was due to the fact that I mistakenly setup Triton modes: ONLY_ON_SYMBOLIZED and ONLY_ON_TAINTED.

**Comment by JonathanSalwan** [comment]
Oh I see. Just to notify users which may have the same issue, when using ONLY_ON_SYMBOLIZED or ONLY_ON_TAINTED, information in `Instruction` like read/write register/memory are cleared if they are not symbolic or tainted.
