### ISSUE TITLE
API to process multiple instructions at once

### ISSUE THREAD

**Issue by XVilka** [JonathanSalwan/Triton#892]
For example, if you have a code chunk, currently you have to call:
```python
while off < limit:
    inst = triton.Instruction()
    inst.setOpcode(data[off])
    inst.setAddress(off)
    ctx.processing(inst)
    off = off + inst.getSize()
```
or something like that. Because of the FFI bottlenecks between Python and C it slows down the processing when you have a lot of such chunks. Is it possible to introduce a block-level API for the same, and produce/process a list of instructions from a given data chunk?

**Comment by JonathanSalwan** [comment]
Something like that?

```python
ctx.processing([
    Instruction(addr, opcode),
    Instruction(addr, opcode),
    Instruction(addr, opcode),
    Instruction(addr, opcode)
])

**Comment by XVilka** [comment]
No, I was thinking more about block disassembly, where you don't need to create the instruction manually every time, so it would be done in the C++ code without calls back and forth.

**Comment by JonathanSalwan** [comment]
Mmmh, ok so you means something like that:

```python
ctx.block_processing(b"\x48\xff\xc0\x48\x89\xc2\xff\xd2\x48\xff\xc0\xc9\xc3")
```

Let's discuss about something and let's disassemble the previous block:

```asm
0x0000000000000000:  48 FF C0    inc   rax
0x0000000000000003:  48 89 C2    mov   rdx, rax
0x0000000000000006:  FF D2       call  rdx
0x0000000000000008:  48 FF C0    inc   rax
0x000000000000000b:  C9          leave 
0x000000000000000c:  C3          ret   
```

What should we do when processing the `call rdx`. Same thing, what should we do if there is a `jnz` where the destination jump is not in the given block?

**Comment by XVilka** [comment]
I think at this stage it's not required to split to the basic blocks, and just run "plain" disassembly. The same that would have been done if you run them separately:
```python
ctx.processing([
    Instruction(0, b"\x48\xff\xc0"),
    Instruction(3, b"\x48\x89\xc2"),
    Instruction(6, b"\xff\xd2"),
    Instruction(8, b"\x48\xff\xc0"),
    Instruction(11, b"\xc9"),
    Instruction(12, b"\xc3"),
])
```

**Comment by XVilka** [comment]
@JonathanSalwan have you decided anything? Maybe I can help if we determine the API first.

**Comment by JonathanSalwan** [comment]
Hi @XVilka,

I'm a little bit busy these days and I don't have much times to work on Triton. A first draft of API prototype will help for sure :),
