### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by devguyplus** [JonathanSalwan/Triton#899]
Sorry if im being a noob, 
I've downloaded the 64 bit python 36 release, extracted it and then tried to execute import triton in python while being on the same folder.
It returned an error:
ImportError: DLL load failed while importing triton: The specified module could not be found.

**Comment by JonathanSalwan** [comment]
Did you try to move the `libtriton.pyd` in your `sys.path`?

**Comment by devguyplus** [comment]
I tried now moving libtriton.pyd to C:\Users\$user\AppData\Local\Programs\Python\Python38\DLLs
It resulted with the same error.

**Comment by JonathanSalwan** [comment]
`Python38` is not `Python36`?

**Comment by JonathanSalwan** [comment]
This error is typically because the `libtriton.pyd` is not in your `sys.path`.

**Comment by JonathanSalwan** [comment]
Btw `libz3.dll` should also be in your `sys.path` and you also may need to install [Visual C++ redistributable](https://www.microsoft.com/en-US/download/details.aspx?id=30679) packages.

**Comment by devguyplus** [comment]
Installing python 3.6.0 solved the issue, thanks.

**Comment by bu-shuo** [comment]
I am using python37 and had the same problem.
`>>> import triton`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`ImportError: DLL load failed: The specified module could not be found.`
After trial and error, I found that not only need to put `triton.pyd` and `libz3.dll` in `sys.path`, but also put these two files in the same folder.
