### ISSUE TITLE
z3ToTriton API issue

### ISSUE THREAD

**Issue by RobinDavid** [JonathanSalwan/Triton#903]
The API ``z3ToTriton`` seem's to take an ExprRef object but I can't figure out how to create a valid one for the API. Let's consider the following snippet:

```python
from triton import TritonContext, ARCH
import z3

ctx = TritonContext(ARCH.X86_64)
ast = ctx.getAstContext()

e = z3.BitVec("x", 64) + z3.BitVec("y", 64)
print(isinstance(e, z3.ExprRef))  # is true

n = ast.z3ToTriton(e)
```
The call to z3ToTriton yields the error below while ``e`` seems to be an ExprRef instance:

> TypeError: z3ToTriton(): expected an ExprRef as argument

The only examples shown in the documentation are expressions coming from Triton which are indeed ExprRef objects. I am not especially familiar with Z3 internal structures (refs, contexts etc) thus hopefully it is a dumb question :).

**Comment by JonathanSalwan** [comment]
Nice catch. In fact, in your example `e` is a `BitVecRef` which inherits from `ExprRef` (and also from `AstRef` and `Z3PPObject`), that's why `isinstance` returns true. I've pushed a fix allowing to convert from a `BitVecRef`.
