### ISSUE TITLE
Update Dockerfile - it uses very outdated software

### ISSUE THREAD

**Issue by XVilka** [JonathanSalwan/Triton#906]
It relies on very old versions of:
- Ubuntu 16.04 - latest LTS is [20.04](https://wiki.ubuntu.com/FocalFossa/ReleaseNotes)
- Z3 4.6.0 - latest is [4.8.8](https://github.com/Z3Prover/z3/releases/tag/z3-4.8.8) (https://github.com/JonathanSalwan/Triton/issues/904 would need to be fixed first though)
- capstone 4.0.1 - latest is [4.0.2](https://github.com/aquynh/capstone/releases/tag/4.0.2)
- pintool 2.14 - latest is [3.13](https://software.intel.com/sites/landingpage/pintool/docs/98189/README)

**Comment by JonathanSalwan** [comment]
Who want to update the Dockerfile? cc @Manouchehri :). 

Regarding the Pintool we cannot move on 3.13 because of their PinCRT.
