### ISSUE TITLE
CONSTANT_FOLDING issues on various expressions

### ISSUE THREAD

**Issue by RobinDavid** [JonathanSalwan/Triton#907]
While examining, ASTs it seem's that there is many expressions which are not folded even though the mode `CONSTANT_FOLDING` mode is activated. As far as I remember the folding is performed at construction. The following snippet shows an example where I an expressions should have been folded:

```python
from triton import TritonContext, ARCH, Instruction, MODE

ctx = TritonContext(ARCH.X86_64)
ctx.setMode(MODE.ALIGNED_MEMORY, True)
ctx.setMode(MODE.CONSTANT_FOLDING, True)

i = Instruction(b"\x55")  # push rbp
ctx.processing(i)

s = i.getSymbolicExpressions()[-2]

print(s.isSymbolized())
# False
print(s)
# (define-fun ref!10 () (_ BitVec 64) (concat (_ bv0 8) (_ bv0 8) (_ bv0 8) (_ bv0 8) (_ bv0 8) (_ bv0 8) (_ bv0 8) (_ bv0 8))) ; Temporary concatenation reference - PUSH operation
```

The code creating such expressions seem's completely legit, so I don't understand why it is not folded. Is it done on purpose ? Any idea ?

**Comment by JonathanSalwan** [comment]
Nice catch. The `concat` from template was the only one missing... It's now fixed :)
