### ISSUE TITLE
Improve the taint analysis

### ISSUE THREAD

**Issue by JonathanSalwan** [JonathanSalwan/Triton#908]
I don't like the current taint analysis, I will probably rewrite the taint engine. If you have some recommendation / discussion, feel free to comment this thread. Other threads taking into account:

* #473
* #827
* #888

**Comment by SweetVishnya** [comment]
In #888 we decided to check whether instruction is symbolized like follows:

1. Get instruction operands from DynamoRIO.
2. Ask Triton if any registers or memory regions are symbolic.
3. If none of them are symbolized, then skip instruction processing (building AST).

But we didn't have time to try it out yet.

On the other hand, if one does not have a concolic engine, he should consider some mechanism to skip non-tainted instructions. Triton engine actually takes a lot time to build ASTs. IMHO, there should be a lightweight taint to select instructions for symbolic interpretation (reasoning/execution).

**Comment by SweetVishnya** [comment]
As far as I see now, taint engine is useless if you don't have an emulation (concolic execution).

**Comment by SweetVishnya** [comment]
What is your use case model for taint?

**Comment by archercreat** [comment]
Ability to track multiple sources would be good.

**Comment by SweetVishnya** [comment]
> Ability to track multiple sources would be good.

Do you want taint colors to distinguish multiple inputs?

**Comment by archercreat** [comment]
> > Ability to track multiple sources would be good.
> 
> Do you want taint colors to distinguish multiple inputs?

Yes.

**Comment by JonathanSalwan** [comment]
> What is your use case model for taint?

Actually, I never use the taint engine. I mainly use symbolic variable (we can consider that it's a kind of taint) and modes `ONLY_ON_SYMBOLIZED`, `ALIGNED_MEMORY`. Then, asking for a model we can deduct:

* No symbolic expression assigned to the reg/mem = untainted
* UNSAT = tainted but not controllable
* SAT = tainted and controllable

**Comment by JonathanSalwan** [comment]
The taint analysis could be applied on a standalone static IR (#473)
