### ISSUE TITLE
MemoryAccess on unaligned memory

### ISSUE THREAD

**Issue by RobinDavid** [JonathanSalwan/Triton#911]
It is not an issue but rather a question. While manipulating ``MemoryAccess``, I tried creating a MemoryAccess of 256 bits to symbolize it. However it raises a ``TypeError: MemoryAccess::MemoryAccess(): size must be aligned``. I am just wondering why such alignement is enforced ? Does it serve a specific purpose ?

**Comment by JonathanSalwan** [comment]
256 bits should be supported. I think you made a mistake using bits and not bytes in the constructor of the `MemoryAccess`?

```python
>>> from triton import MemoryAccess

>>> m = MemoryAccess(0x1000, 256)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: MemoryAccess::MemoryAccess(): size must be aligned.

>>> m = MemoryAccess(0x1000, 32)
>>> m.getBitSize()
256
```

**Comment by JonathanSalwan** [comment]
Regarding symbolizing 256 bytes over a `MemoryAccess`: It's not possible. By symbolizing a `MemoryAccess`, Triton will create a fresh symbolic variable with a size of the memory access and we cannot deal with symbolic expression more than 512 bits.
