### ISSUE TITLE
Compiling sample_1.c from examples

### ISSUE THREAD

**Issue by bghimis** [JonathanSalwan/Triton#912]
Hello! I have successfully installed Triton on Debian GNU/Linux 9 (stretch).
I can successfully run the command python3.6 hooking_libc.py sample_1. 
This command works if I use the given sample_1 binary (from Github).

I have tried to compile sample_1.c, but Triton exits prematurely:
(compiled with: gcc -g -fPIC -O0 -masm=intel -no-pie sample_1.c -o sample_1; $ gcc --version
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516)

Output:
[+] Loading 0x400040 - 0x400238
[+] Loading 0x400238 - 0x400254
[+] Loading 0x400000 - 0x40077c
[+] Loading 0x600e08 - 0x601038
[+] Loading 0x600e20 - 0x600ff0
[+] Loading 0x400254 - 0x400298
[+] Loading 0x400654 - 0x400688
[+] Loading 0x000000 - 0x000000
[+] Loading 0x600e08 - 0x601000
[+] Hooking strlen
[+] Hooking printf
[+] Starting emulation.
0x400450: xor ebp, ebp
0x400452: mov r9, rdx
0x400455: pop rsi
0x400456: mov rdx, rsp
0x400459: and rsp, 0xfffffffffffffff0
0x40045d: push rax
0x40045e: push rsp
0x40045f: mov r8, 0x400620
0x400466: mov rcx, 0x4005b0
0x40046d: mov rdi, 0x400546
0x400474: call qword ptr [rip + 0x200b76]
[+] Emulation done.

Disasm (compiled by me):
  40045f:       49 c7 c0 20 06 40 00    mov    $0x400620,%r8
  400466:       48 c7 c1 b0 05 40 00    mov    $0x4005b0,%rcx
  40046d:       48 c7 c7 46 05 40 00    mov    $0x400546,%rdi
  400474:       ff 15 76 0b 20 00       **callq  \*0x200b76(%rip)        # 600ff0** <__libc_start_main@GLIBC_2.2.5>
  40047a:       f4                      hlt    
  40047b:       0f 1f 44 00 00          nopl   0x0(%rax,%rax,1)

Disasm (from Github):
  4004af:       49 c7 c0 50 06 40 00    mov    $0x400650,%r8
  4004b6:       48 c7 c1 e0 05 40 00    mov    $0x4005e0,%rcx
  4004bd:       48 c7 c7 96 05 40 00    mov    $0x400596,%rdi
  4004c4:       e8 b7 ff ff ff          **callq  400480 <__libc_start_main@plt>**
  4004c9:       f4                      hlt    
  4004ca:       66 0f 1f 44 00 00       nopw   0x0(%rax,%rax,1)

Can you please provide the compilation flags needed to compile sample_1.c?

**Comment by JonathanSalwan** [comment]
I've not used flags. Try without fpic.

**Comment by bghimis** [comment]
If I don't use any flags ($ gcc sample_1.c -o sample_1), I get the following output:
[+] Loading 0x000040 - 0x000238
[+] Loading 0x000238 - 0x000254
[+] Loading 0x000000 - 0x00094c
[+] Loading 0x200dd8 - 0x201038
[+] Loading 0x200df0 - 0x200fd0
[+] Loading 0x000254 - 0x000298
[+] Loading 0x000804 - 0x000840
[+] Loading 0x000000 - 0x000000
[+] Loading 0x200dd8 - 0x201000
[+] Hooking strlen
[+] Hooking printf
[+] Starting emulation.
0x5d0: xor ebp, ebp
0x5d2: mov r9, rdx
0x5d5: pop rsi
0x5d6: mov rdx, rsp
0x5d9: and rsp, 0xfffffffffffffff0
0x5dd: push rax
0x5de: push rsp
0x5df: lea r8, [rip + 0x1ea]
0x5e6: lea rcx, [rip + 0x173]
0x5ed: lea rdi, [rip + 0x10c]
0x5f4: call qword ptr [rip + 0x2009de]
[+] Emulation done.

I get almost the same output if I compile with the previous command, without -fPIC ($ gcc -g -O0 -masm=intel -no-pie sample_1.c -o sample_1):
[+] Loading 0x400040 - 0x400238
[+] Loading 0x400238 - 0x400254
[+] Loading 0x400000 - 0x40077c
[+] Loading 0x600e08 - 0x601038
[+] Loading 0x600e20 - 0x600ff0
[+] Loading 0x400254 - 0x400298
[+] Loading 0x400654 - 0x400688
[+] Loading 0x000000 - 0x000000
[+] Loading 0x600e08 - 0x601000
[+] Hooking strlen
[+] Hooking printf
[+] Starting emulation.
0x400450: xor ebp, ebp
0x400452: mov r9, rdx
0x400455: pop rsi
0x400456: mov rdx, rsp
0x400459: and rsp, 0xfffffffffffffff0
0x40045d: push rax
0x40045e: push rsp
0x40045f: mov r8, 0x400620
0x400466: mov rcx, 0x4005b0
0x40046d: mov rdi, 0x400546
0x400474: call qword ptr [rip + 0x200b76]
[+] Emulation done.

**Comment by JonathanSalwan** [comment]
The problem, is just the hook of the symbol called at 0x400474. It's not hooked, so try to get a look on this.

**Comment by bghimis** [comment]
Thanks! Now it seems to be working.

I have modified this line to point to the problematic address: 
- "('__libc_start_main', libcMainHandler, 0x400474)".

Also I had to modify the break instruction (it would not find HLT...):
- "if instruction.getType() == OPCODE.X86.HLT or instruction.getType() == OPCODE.X86.RET"

**Comment by JonathanSalwan** [comment]
Nice!
