### ISSUE TITLE
Getting error "The Pin tracer needs Python 2.7." when Python version is 2.7

### ISSUE THREAD

**Issue by SKIIDK** [JonathanSalwan/Triton#915]

**Comment by JonathanSalwan** [comment]
`cmake -DPINTOOL=on -DPYTHON36=off`

**Comment by HahaLan97** [comment]
It doesn't work... Still showing the error "The Pin tracer needs Python 2.7". I'm using a Ubuntu 20.04 LTS virtual machine. I'm following every step this link down below says about Pintool: https://triton.quarkslab.com/documentation/doxygen/index.html
