### ISSUE TITLE
Compilation error on macOS

### ISSUE THREAD

**Issue by hot3eed** [JonathanSalwan/Triton#916]
For some reason when I try to build the source using `sudo make -j2 install` I get:
```
[  3%] Building CXX object src/libtriton/CMakeFiles/triton.dir/api/api.cpp.o
/Users/hot3eed/utils/Triton/src/libtriton/api/api.cpp:1109:55: error: no member named
      'SOLVER_Z3' in namespace 'triton::engines::solver'
    if (this->getSolver() == triton::engines::solver::SOLVER_Z3) {
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^
```
I followed the instructions [here](https://triton.quarkslab.com/documentation/doxygen/index.html#install_sec) and changed the `cmake` command to use Python 3: 
```
cmake $(echo 'from os.path import abspath, join; from distutils.sysconfig import get_python_inc, get_python_lib; print("-DPYTHON_INCLUDE_DIR=%s -DPYTHON_LIBRARY=%s" % (get_python_inc(), abspath(join(get_python_lib(), "../../libpython3.7.dylib"))))' | python3) ..
```

My setup:
- macOS 10.15.3
- Z3 4.8.8
- Capstone 4.0.2
- Boost 1.72.0

**Comment by JonathanSalwan** [comment]
Any new on this? I don't have an OSX on hand to test.

**Comment by vancaho** [comment]
You should clone and build Z3 from the scratch. Do not use the ```brew install``` command.
