### ISSUE TITLE
Architecture issues with Pin

### ISSUE THREAD

**Issue by SKIIDK** [JonathanSalwan/Triton#918]
When using with Pin, get the error:
`E: Unable to load triton.  Check the architecture type.`

All other tests and programs work, but not triton.
Same error occurs in 32 bit environment as well.

**Comment by JonathanSalwan** [comment]
Are you trying to execute 32bit binary with the 64bit compiled library?

**Comment by SKIIDK** [comment]
Am I correct to assume that this format `./../../pin -t ./triton.so -script script.py -- ./target` is outdated? I don't think this is an issue anymore since I'm guessing triton takes care of pin itself

**Comment by JonathanSalwan** [comment]
For a 32 bit binary the best is a 32-bits chroot. Or, compiling the libtriton and all its dependencies in 32bit.
