### ISSUE TITLE
Mismatching evaluation ROR between triton and SMT

### ISSUE THREAD

**Issue by RobinDavid** [JonathanSalwan/Triton#920]
I in fact found two little issues. The first one is:

```python
from triton import TritonContext, ARCH
ctx = TritonContext(ARCH.X86_64)
x = ctx.newSymbolicVariable(64, "x")

v = 11258300193617241473
ctx.setConcreteVariableValue(x, v)
# raise: TypeError: AstContext::updateVariable(): Variable does not exist.
```
Why is the symbolic variable not existing ? More interesting, if I do:
```python
ast = ctx.getAstContext()
vx = ast.variable(x)
# Then calling setConcreteVariableValue works
```
Do you have any idea of why is this behaving like this ?

Then the second issue is the rotate evaluation itself which returns a different result than Z3:
```python
e = ast.bvror(vx, vx)
print(e.evaluate())
4069856313524931331

import z3
e=z3.RotateRight(v, z3.BitVecVal(v, 64))
print(z3.simplify(e))
14852522133663396544
```

I think that the various semantics using ror never have had this issue as the integer value is small but when creating these ast's manually it might happen.
I quickly looked at the code, and the rotate integer is handled as a uint32 while here we are manipulating int64. I did not investigated further at the moment.

**Comment by JonathanSalwan** [comment]
I'm ok for the first one. For the second one, I cannot reproduce your value...

```python
>>> from triton import TritonContext, ARCH

>>> ctx = TritonContext(ARCH.X86_64)
>>> x = ctx.newSymbolicVariable(64, "x")
>>> ast = ctx.getAstContext()
>>> vx = ast.variable(x)
>>> v = 11258300193617241473
>>> ctx.setConcreteVariableValue(x, v)

>>> e = ast.bvror(vx, vx)
>>> print(e.evaluate())
14852522133663396544

>>> e = ast.bvror(ast.bv(11258300193617241473, 64), ast.bv(11258300193617241473, 64))
>>> print(e.evaluate())
14852522133663396544
```

**Comment by RobinDavid** [comment]
That is very weird.. :/ *(I have retried with exactly your snippet and I still obtain: 4069856313524931331)*

**Comment by JonathanSalwan** [comment]
Travis and Appveyor are also ok with the base code of this `ror` evaluation. Dunno why you have a different value and I think I cannot help you on that behavior. Maybe an old version of Triton?
