### ISSUE TITLE
MIPS architecture support

### ISSUE THREAD

**Issue by XVilka** [JonathanSalwan/Triton#922]
From most common architectures today, only MIPS and PowerPC are missing.
It's important for the analyzing embedded devices and IoT executables. Would be nice to have the support for those too.

**Comment by JonathanSalwan** [comment]
God. You will end up killing me with those supports. Adding a new architecture is about 25K/30K lines of code. And i'm not talking about the review of those lines :)

**Comment by SweetVishnya** [comment]
Maybe, it's time to support some IR ;)

**Comment by JonathanSalwan** [comment]
Mmmmh, we can consider that Triton already possess its ir and even with a "real IR" we have to translate each instruction to the IR form. However, maybe you are talking about using for example VEX instead of our AST?

**Comment by SweetVishnya** [comment]
I mean that Triton ASTs are not the same as instructions IR (VEX can be good to go). You can write a translation from IR to Triton ASTs once. And a new architecture supported in this IR can be easier implemented. Also, IR actually has less instructions than ISA. What I am trying to say is that AST and IR are two different abstraction layers. First is for symbolic and optimizations. Seccond one is for writing universal algorithms. Current Triton ASTs building actually simultaneously builds "IR" and updates symbolic state. On the other hand, with a true IR (like VEX) you can update symbolic memory just for memory load/store operators (kind of code locality).

**Comment by aguinet** [comment]
"There's not one problem that you can't solve with a new layer of abstraction" - many computer engineers

You're welcome :)

**Comment by JonathanSalwan** [comment]
> I mean that Triton ASTs are not the same as instructions IR (VEX can be good to go). You can write a translation from IR to Triton ASTs once. And a new architecture supported in this IR can be easier implemented. Also, IR actually has less instructions than ISA. What I am trying to say is that AST and IR are two different abstraction layers. First is for symbolic and optimizations. Seccond one is for writing universal algorithms. Current Triton ASTs building actually simultaneously builds "IR" and updates symbolic state. On the other hand, with a true IR (like VEX) you can update symbolic memory just for memory load/store operators (kind of code locality).

Related to #473.

**Comment by JonathanSalwan** [comment]
I'm closing this. I will not add new arch between #473 is done and reliable.
