### ISSUE TITLE
Is there any optimization in symolicExpressions for X86_64?

### ISSUE THREAD

**Issue by tiedaoxiaotubie** [JonathanSalwan/Triton#925]
I tried to perform backward slicing on a x86_64 program. From the result of slicing, I found that Triton seems to optimize the symbolicExpression to a certain extent. Specifically, Triton does not store all the intermediate taint propagation point, but only stores the optimized results. Here are part of my slicing result:
```
==================================
slicing for 0xa56218:
[Slicing Point] 
[Slicing Point] 0xa561f7: mov rdx, qword ptr [rbx + 0x990]
[Slicing Point] 0xa56218: mov qword ptr [rbx + 0x18], rdx
==================================
slicing for 0xa5621f:
[Slicing Point] 
[Slicing Point] 0xa561f7: mov rdx, qword ptr [rbx + 0x990]
[Slicing Point] 0xa56218: mov qword ptr [rbx + 0x18], rdx
==================================
slicing for 0xa394fe:
[Slicing Point] 
[Slicing Point] 0xa561f7: mov rdx, qword ptr [rbx + 0x990]
[Slicing Point] 0xa5621f: mov rax, qword ptr [rbx + 0x18]
[Slicing Point] 0xa3942f: mov r9, qword ptr [rbp + 0x10]
[Slicing Point] 0xa3947e: mov qword ptr [rbp - 0xc8], r9
==================================
slicing for 0xa62ab9:
[Slicing Point] 
[Slicing Point] 0xa561f7: mov rdx, qword ptr [rbx + 0x990]
[Slicing Point] 0xa5621f: mov rax, qword ptr [rbx + 0x18]
[Slicing Point] 0xa3942f: mov r9, qword ptr [rbp + 0x10]
[Slicing Point] 0xa394fe: mov r10, qword ptr [rbp - 0xc8]
[Slicing Point] 0xa39505: mov qword ptr [rsp], r10
==================================
[+]slcing for 0xa4ce93!
[Slicing crash] 
[Slicing crash] 0xa561f7: mov rdx, qword ptr [rbx + 0x990]
[Slicing crash] 0xa5621f: mov rax, qword ptr [rbx + 0x18]
[Slicing crash] 0xa3942f: mov r9, qword ptr [rbp + 0x10]
[Slicing crash] 0xa394fe: mov r10, qword ptr [rbp - 0xc8]
[Slicing crash] 0xa62ab9: mov rax, qword ptr [rbp + 0x10]
[Slicing crash] 0xa62efe: mov rdi, qword ptr [rbp - 0x60]
[Slicing crash] 0xa4cc68: mov rax, qword ptr [rbp - 0x40]
[Slicing crash] 0xa4cc78: mov rcx, qword ptr [rbp - 0x20]
[Slicing crash] 0xa4ce4d: mov rax, qword ptr [rbp - 0x30]
[Slicing crash] 0xa4ce51: add rax, 3
[Slicing crash] 0xa4ce65: mov qword ptr [rbp - 0x88], rax
```
Look at the bottom of the slicing result, at the address of 0xa4ce65, I wanted to know where the bad value in [rbp-0x88] comes from, so I did backward slicing, but as you can see, there is no obvious taint relationship between the result in "slicing for 0xa4ce93", the taint propagation was incomplete/break, so I also provided some slicing result, which began slicing from several address(the address in the slicing result of 0xa4ce93), I found that Triton cut part of the slicing result of them. 

For example, when we tried to slice for 0xa62ab9, the last slicing point is 0xa39505, whose instruction is mov qword ptr[rsp], r10. But if you check the slicing for 0xa4ce93, after the 0xa394fe, there is no symbolicExpression for 0xa39505, but only 0xa62ab9. So Triton lost 0xa39505 in its slicing result for 0xa4ce93.

Also, if you check the slicing for 0xa394fe, the instruction of 0xa56218 was lost between 0xa561f7 and 0xa5621f.

**Comment by JonathanSalwan** [comment]
This result makes no sense for me without the python code. Can you provide the binary and your python code?

**Comment by tiedaoxiaotubie** [comment]
Thank your for your reply, I have know the reason, for X86_64 binary, if the slicing is very long, the result of backward slicing will be incomplete when `ctx.setMode(MODE.ALIGNED_MEMORY, True)`. This incomplete slicing result will be solved if we set `ctx.setMode(MODE.ALIGNED_MEMORY, False)`.
