### ISSUE TITLE
Path predicate of multi-threaded programs

### ISSUE THREAD

**Issue by SweetVishnya** [JonathanSalwan/Triton#926]
I got some ideas how to support multi-threaded programs.

1. ASTs storage should be thread-safe.
2. Symbolic registers are stored for each thread.
3. Memory is common for all threads.
4. Path predicate is separate for each thread.

**Comment by JonathanSalwan** [comment]
Yep, this is working. It's what I did when analyzing threaded binaries. However, it was done in third party python script.

**Comment by SweetVishnya** [comment]
Can we add threading support to Triton?

**Comment by JonathanSalwan** [comment]
I don't know if multi-threading will be fully implemented into Triton but  will try to add some code in order to help for this kind of support.

**Comment by SweetVishnya** [comment]
I suppose we will try to implement symbolic interpretation of multi-threaded programs with vanilla Triton first.

1. One path predicate for all threads.
2. One symbolic context for all threads.
3. Symbolic registers (and registers concrete values) are switched when thread is changed.
