### ISSUE TITLE
Recovering LEA ASTs for MemoryAccess objects returned from SymbolicExpression.getOrigin()

### ISSUE THREAD

**Issue by notfoundry** [JonathanSalwan/Triton#927]
I recently started using Triton's Python interface to do some x86_64 binary analysis work involving finding the possible inputs and outputs for functions (it's been an excellent experience! thank you so much for making such a user-friendly tool), and I have been trying to generate a mapping of all registers/memory used in a function to their symbolic/concrete states at the end of the function, with all registers automatically being symbolized when they're first accessed. I've been getting the state data by going through `getSymbolicExpressions()` for every Instruction and mapping each expression's origin to the expression's AST.

It's documented that whenever a SymbolicExpression origin is a MemoryExpression, the LEA AST is not included in it, but without that AST I haven't been able to find any way of recording whether an instruction's memory access is absolute or dependant on some variable. For example, the instruction

`push rax`

being processed with a symbolic `rsp` and `rax` leads to

```python
rsp:64 bv[63..0] = (bvsub rsp_symvar (_ bv8 64)) # Register = AstNode
[@0xfffffffffffffff8]:64 bv[63..0] = rax_symvar # MemoryAccess = AstNode
```

being produced as its symbolic expressions (simplified and ignoring byte-level stores, etc). If that `[@0xfffffffffffffff8]:64 bv[63..0]` MemoryAccess had a LEA AST it would be easy to replace `0xfffffffffffffff8` with `[rip - 8]` in the output of the analysis, but without it, there's no way to see what the meaning of `0xfffffffffffffff8` is at that point.

Is there any way that this LEA information can be propagated to the user, since it has to exist in some form for a concrete address like `0xfffffffffffffff8` to exist? If not, is there some other way of accomplishing this MemoryAccess -> SymbolicExpression mapping?

**Comment by JonathanSalwan** [comment]
Hey,

It's been some 1 hour now I'm trying to find a workaround of this but I regret to announce that we cannot do it easily without having specific nodes of a LOAD and STORE (which is related to #806). I'm able to provide such information (what you are asking) only for STORE accesses but not for LOAD accesses. However, matter of harmony, I cannot provide this behavior only for STORE and not for LOAD. So I cannot fix this issue until solving #806. Solving #806 will naturally solve your issue (note for myslef: btw, solving #473, will naturally also solve #806).

Below my path if you want to take a look about spreading lea AST on STORE accesses.

```patch
diff --git a/src/libtriton/engines/symbolic/symbolicEngine.cpp b/src/libtriton/engines/symbolic/symbolicEngine.cpp
index d133ff3f..35fa32f3 100644
--- a/src/libtriton/engines/symbolic/symbolicEngine.cpp
+++ b/src/libtriton/engines/symbolic/symbolicEngine.cpp
@@ -569,7 +569,13 @@ namespace triton {
 
           /* Create a new symbolic expression containing the symbolic variable */
           const SharedSymbolicExpression& se = this->newSymbolicExpression(tmp, MEMORY_EXPRESSION, "Byte reference");
-          se->setOriginMemory(triton::arch::MemoryAccess(memAddr+index, triton::size::byte));
+
+          /* Set the origin of the symbolic expression */
+          triton::arch::MemoryAccess memOrigin = triton::arch::MemoryAccess(memAddr+index, triton::size::byte);
+          if (mem.getLeaAst() != nullptr) {
+            memOrigin.setLeaAst(this->astCtxt->bvadd(mem.getLeaAst(), this->astCtxt->bv(index, mem.getLeaAst()->getBitvectorSize())));
+          }
+          se->setOriginMemory(memOrigin);
 
           /* Assign the symbolic expression to the memory cell */
           this->addMemoryReference(memAddr+index, se);
@@ -906,6 +912,7 @@ namespace triton {
         /* Record the aligned memory for a symbolic optimization */
         if (this->modes->isModeEnabled(triton::modes::ALIGNED_MEMORY)) {
           const SharedSymbolicExpression& aligned = this->newSymbolicExpression(node, MEMORY_EXPRESSION, "Aligned Byte reference - " + comment);
+          aligned->setOriginMemory(mem);
           this->addAlignedMemory(address, writeSize, aligned);
         }
 
@@ -922,7 +929,11 @@ namespace triton {
           /* Assign each byte to a new symbolic expression */
           se = this->newSymbolicExpression(tmp, MEMORY_EXPRESSION, "Byte reference - " + comment);
           /* Set the origin of the symbolic expression */
-          se->setOriginMemory(triton::arch::MemoryAccess(((address + writeSize) - 1), triton::size::byte));
+          triton::arch::MemoryAccess memOrigin = triton::arch::MemoryAccess(((address + writeSize) - 1), triton::size::byte);
+          if (mem.getLeaAst() != nullptr) {
+            memOrigin.setLeaAst(this->astCtxt->bvadd(mem.getLeaAst(), this->astCtxt->bv(writeSize - 1, mem.getLeaAst()->getBitvectorSize())));
+          }
+          se->setOriginMemory(memOrigin);
           /* ret is the for the final expression */
           ret.push_back(tmp);
           /* add the symbolic expression to the instruction */
@@ -954,7 +965,7 @@ namespace triton {
         this->architecture->setConcreteMemoryValue(mem, tmp->evaluate());
 
         se = this->newSymbolicExpression(tmp, MEMORY_EXPRESSION, "Temporary concatenation reference - " + comment);
-        se->setOriginMemory(triton::arch::MemoryAccess(address, mem.getSize()));
+        se->setOriginMemory(mem);
 
         return inst.addSymbolicExpression(se);
       }
@@ -1104,7 +1115,11 @@ namespace triton {
           /* For each byte create a new symbolic expression */
           const SharedSymbolicExpression& byteRef = this->newSymbolicExpression(tmp, MEMORY_EXPRESSION, "Byte reference");
           /* Set the origin of the symbolic expression */
-          byteRef->setOriginMemory(triton::arch::MemoryAccess(((address + writeSize) - 1), triton::size::byte));
+          triton::arch::MemoryAccess memOrigin = triton::arch::MemoryAccess(((address + writeSize) - 1), triton::size::byte);
+          if (mem.getLeaAst() != nullptr) {
+            memOrigin.setLeaAst(this->astCtxt->bvadd(mem.getLeaAst(), this->astCtxt->bv(writeSize - 1, mem.getLeaAst()->getBitvectorSize())));
+          }
+          byteRef->setOriginMemory(memOrigin);
           /* Assign memory with little endian */
           this->addMemoryReference((address + writeSize) - 1, byteRef);
           /* continue */
```

**Comment by notfoundry** [comment]
Thank you so much for looking into this. It sounds like fully propagating the LEA data is a small piece of a much bigger puzzle with symbolic load/stores, but it’s definitely appreciated.

**Comment by SweetVishnya** [comment]
An Instruction operand has a LEA AST. Look [here](https://github.com/JonathanSalwan/Triton/blob/master/src/libtriton/arch/irBuilder.cpp#L72).

**Comment by notfoundry** [comment]
Right. But when the memory access is implicit and has nothing to do with any operands (like in the case of PUSH as described above, and POP, CALL, etc.), the LEA information one might be interested in isn't propagated in any way. It looks like it's implicit inside the the virtual CPU, which as I understand it operates on concrete values only.
