### ISSUE TITLE
Is it a bug when Triton.processing "syscall" instruction on x86 arch throws x86Cpu::getRegister():invalid register exception?

### ISSUE THREAD

**Issue by wjbsyc** [JonathanSalwan/Triton#928]
Although "syscall" is not be used on x86, but why invalid register exception?And ROPgadget or other gadget tools always treat '\x0f\x05' as "syscall" instruction when analysing x86 ELFs, and when I use Triton to process these instructions, it always throws x86Cpu::getRegister():invalid register exception when it comes to "syscall".

**Comment by JonathanSalwan** [comment]
> Although "syscall" is not be used on x86, but why invalid register exception?

Because it uses some registers not available of x86 (ex. RCX and R11). 

> And ROPgadget or other gadget tools always treat '\x0f\x05' as "syscall" instruction when analysing x86 ELFs

`0f 05` can be compiled and disassembled as a `syscall` instruction on both x86 and x86_64 but can only be executed on x86. In x86_64 it raises a `SIGILL`.
