### ISSUE TITLE
Allow an access to `.arch` field of API class

### ISSUE THREAD

**Issue by XVilka** [JonathanSalwan/Triton#929]
Currently the [`triton::API api.arch`](https://triton.quarkslab.com/documentation/doxygen/classtriton_1_1API.html) member is protected, so it's impossible to get more information from the [`triton::arch::Architecture`](https://triton.quarkslab.com/documentation/doxygen/classtriton_1_1arch_1_1Architecture.html) class. It would be awesome to be able to do just `ctx.getArchitecture()` to return the pointer to [`Architecture`](https://triton.quarkslab.com/documentation/doxygen/classtriton_1_1arch_1_1Architecture.html) class.

**Comment by JonathanSalwan** [comment]
What about [this method](https://github.com/JonathanSalwan/Triton/blob/1b1da1439e2fa8ed9af4962cb134c4952525b93f/src/libtriton/api/api.cpp#L296-L300)?

**Comment by XVilka** [comment]
Oh, I missed it. Looks like exactly what I need!

**Comment by JonathanSalwan** [comment]
:)
