### ISSUE TITLE
Parallel build in Docker

### ISSUE THREAD

**Issue by SweetVishnya** [JonathanSalwan/Triton#931]
Can we build tools (z3, capstone, Triton) in parallel (`-j`, `CMAKE_BUILD_PARALLEL_LEVEL=`) in Docker?

**Comment by JonathanSalwan** [comment]
Does "in Docker" means modifying [Dockerfile](https://github.com/JonathanSalwan/Triton/blob/master/Dockerfile)? If yes, feel free to improve this file :).

**Comment by SweetVishnya** [comment]
Yes, I mean Dockerfile. But I actually don't use it, so I am afraid to break something. So, this issue can be a note to one that uses a Dockerfile.

**Comment by JonathanSalwan** [comment]
Ok, I think we can close it then (I'm not using Docker too).

**Comment by JonathanSalwan** [comment]
Btw, if someone use Docker and want to implement this feature, feel free to reopen this thread and go ahead for a MR :)
