### ISSUE TITLE
How to judge whether  a register is concretized?

### ISSUE THREAD

**Issue by vancaho** [JonathanSalwan/Triton#933]
What is the default value for a register? If a register is not concretized explicitly, I find that the default value for it is 0 when I get the value by getConcreteRegisterValue.   If I want to judge whether a register is concretized, what can I do?
For example, there is an instruction `mov eax, 0x0`, and after executing it, `eax` will be changed to `0x0`.  But how do I recognize where a register is concretized by some instructions or by the default value?

**Comment by JonathanSalwan** [comment]
At this moment, there is no such feature for register =/. For memory there exists `API::isConcreteMemoryValueDefined`.

**Comment by JonathanSalwan** [comment]
A potential workaround

```python
#!/usr/bin/env python
## -*- coding: utf-8 -*-

import sys
from triton import *


regs_state = dict()


def cb(ctx, reg, v):
    regs_state.update({ctx.getParentRegister(reg).getName() : True})
    return


def what_regs_have_been_concretized():
    for k, v in regs_state.items():
        print(k) if v else print


if __name__ == '__main__':
    ctx = TritonContext(ARCH.X86_64)
    ctx.addCallback(cb, CALLBACK.SET_CONCRETE_REGISTER_VALUE)

    # Init regs_state
    for r in ctx.getParentRegisters():
        regs_state.update({r.getName() : False})

    code = [
        b"\x48\xc7\xc0\x00\x00\x00\x00",    # mov rax, 0
        b"\x48\x31\xc3",                    # xor rbx, rax
    ]

    for op in code:
        ctx.processing(Instruction(op))

    what_regs_have_been_concretized()
```

**Comment by vancaho** [comment]
OK, I have made a workaround similar with above solution. Thanks
