### ISSUE TITLE
Allow requesting registers by name in C++ API

### ISSUE THREAD

**Issue by XVilka** [JonathanSalwan/Triton#934]
Currently it's possible to [get the register by the enum id from CPU Instance](https://triton.quarkslab.com/documentation/doxygen/classtriton_1_1arch_1_1CpuInterface.html#aa107c13c968645d754d7f30f37298135). It would be nice to have the function for searching registers by name.

**Comment by JonathanSalwan** [comment]
What about directly access to the attribute like this : `api.registers.x86_eax` ?

**Comment by JonathanSalwan** [comment]
cf : https://github.com/JonathanSalwan/Triton/blob/master/src/examples/cpp/info_reg.cpp#L29-L35

**Comment by XVilka** [comment]
@JonathanSalwan I meant at runtime, not at the compile time.

**Comment by JonathanSalwan** [comment]
Available in Python and C++ 

```python
>>> ctx = TritonContext(ARCH.X86_64)

>>> ctx.getRegister('eax')
eax:32 bv[31..0]

>>> ctx.getRegister('eAx')
eax:32 bv[31..0]

>>> ctx.getRegister('EaX')
eax:32 bv[31..0]

>>> ctx.getRegister('EAX')
eax:32 bv[31..0]
```

Note that there are also other ways to get a Register class

```python
>>> ctx.getRegister(REG.X86.EAX) # from id
eax:32 bv[31..0]

>>> ctx.getRegister('eax') # from name
eax:32 bv[31..0]

>>> ctx.registers.eax # static shortcut
eax:32 bv[31..0]
```

**Comment by XVilka** [comment]
Thank you! It's very useful when you write multiarchitecture code.

**Comment by JonathanSalwan** [comment]
Np, indeed it may be useful :)
