### ISSUE TITLE
Could Triton run symbolic execution inside syscall?

### ISSUE THREAD

**Issue by yh570** [JonathanSalwan/Triton#943]
Hi, my understanding is when running the symbolic execution, Triton will get concrete value before syscall entry, and then convert the return value to symbolic again when exiting syscall. I'm not sure my understanding is correct, please let me know if I'm wrong. 

I know that syscall must have a concrete input but I'm very curious that Triton is able to run symbolic execution in syscall or not, like hooking a rewrite syscall, etc.

Thank you.

**Comment by JonathanSalwan** [comment]
Triton does not provide built-ins to support syscalls neither that any external calls. When a syscall instruction is executed by Triton, it's the user role to define the behavior he want (concrete or symbolic). [Here](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/small_x86-64_symbolic_emulator.py) an example of supporting external calls like `atoi`, `printf`, `malloc` etc. This is the same concept to simulate any syscall behavior.
