### ISSUE TITLE
Does getSymbolicRegisterId() equal to getSymbolicRegister()?

### ISSUE THREAD

**Issue by yh570** [JonathanSalwan/Triton#944]
Hi, I'm learning to use Triton to do the dynamic symbolic execution for code coverage. I'm trying to rewrite the old code_coverage.py based on the sage algorithm from your blog with the latest Triton. But I met a problem to get the symbolic rip value.

The current value of `Triton.registers.rip` is `rip:64 bv[63..0]`, but the value of `Triton.getSymbolicRegister(Triton.registers.rip)` is `None`, which I think it should return a symbolic constraint set.

I found in your old code the function is `getSymbolicRegisterId()`, but it looks like the `getSymbolicRegisterId` is not existing in the current version. May I ask what's the difference between `getSymbolicRegisterId()` and `getSymbolicRegisterId`?

BTW, I also interested in is there a built-in searching strategy for symbolic execution in Triton?

Thank you.

**Comment by JonathanSalwan** [comment]
`Triton.registers.rip` it's just a Register object, not a value.

> which I think it should return a symbolic constraint set.

What you are looking for is: getting the path predicate. For that, you should use `ctx.getPathPredicate()` which returns an AST, or `ctx.getPathConstraints()` which returns a list of constraints.

> I'm trying to rewrite the old code_coverage.py based on the sage algorithm from your blog with the latest Triton.

[Here](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/code_coverage_crackme_xor.py) is the up-to-date version of the code_coverage.py  from the old blog post.

> BTW, I also interested in is there a built-in searching strategy for symbolic execution in Triton?

Nop, the symbolic exploration and the path search strategy must be handled by the user.

**Comment by yh570** [comment]
Thank you for your quick reply. And I have another question that it looks like `Triton.getRegisterAst(Triton.registers.rip).evaluate()` can't get the correct entry/return address within function calls, I got the value 0 for the above instruction after execute function call or ret. I'm also interested in could Triton run pure symbolic execution for the whole program without concrete execution(pin)? 

Thank you for your help so much.

**Comment by JonathanSalwan** [comment]
> Triton.getRegisterAst(Triton.registers.rip).evaluate() can't get the correct entry/return address within function calls, I got the value 0 for the above instruction after executing function call or ret

Can't say why, it depends of your tritontool.

>  I'm also interested in could Triton run pure symbolic execution for the whole program(user-defined, no syscall or libc call) without concrete execution(pin)?

Triton do pure DSE without any external tools such as Pin. Your have to consider Triton as a symbolic emulator (at the instruction granularity). It has its own concrete state and symbolic state, when executing an instruction, it updates these two states respectively according to the instruction semantics. Tools like Pin, DR, QBDI or whatever, are just used sometime to drive/help the execution when using concretization at the return of external functions (syscalls, libcs, etc). However, in your tritontool you can simulate those behavior and thus avoid using DBI tools. For example, it's been 2 or 3 years now I'm using Triton without any external DBI tools and I'm able to fully emulate binary program. You just have to dev your own dataset of external behaviors (which are not provided into the Triton library).
