### ISSUE TITLE
Support Z3 tactics

### ISSUE THREAD

**Issue by SweetVishnya** [JonathanSalwan/Triton#949]
We issued low Z3 performance on some formulas Z3Prover/z3#4683. We got an idea that we can try to solve without tactics (with some timeout) first. And if timeout reached then solve with some tactics set. So, can we support tactics set parameter for `getModel()`?

**Comment by JonathanSalwan** [comment]
Could be interesting indeed

**Comment by SweetVishnya** [comment]
We still need some time to find out whether we should specify z3 tactics or use some better preset tactics set that works faster on Triton formulas.

**Comment by SweetVishnya** [comment]
After supporting Bitwuzla it is no longer relevant.
