### ISSUE TITLE
"symbolic expression is not available anymore" Error

### ISSUE THREAD

**Issue by vancaho** [JonathanSalwan/Triton#950]
Hi, I want to do symbolic execution on a long trace, and generate some symbolic expressions for some registers. After executing the trace, I try to get the symbolic expression of these registers. However it reports the 'symbolic expression is not available anymore' exception. 
How to do with this problem? Thanks!

**Comment by JonathanSalwan** [comment]
Let's consider a point `A` and `B` on a trace. `A` and `B` must have an input / output relationship for example : `b = secret(a)`. At the point `A` you can symbolize your registers or memory cells with `symbolizeRegiter()` or `symbolizeMemory()`. At the point `B` you can get the symbolic expression of a register (or memory) associated to the point `B`. For example, let's assume that the point `B` is the return of the `secret` function. So what I'm looking for is the symbolic expression of the `rax` register at the point `B`. For that i'm using `b_expr = ctx.getSymbolicRegister(ctx.registers.rax)`. Then, if `b_expr` is not symbolic (`b_expr.isSymbolized()` == False), it means that the `b_expr` is not in relationship with the point `A`. If it's symbolic, you can ask for a constraint with: `ctx.getModel(b_expr.getAst() == 1234)`. If there is no model it means that it's `UNSAT`.

**Comment by vancaho** [comment]
Sorry, maybe I didn't make the question clear. 
For example I have a trace with 10000 instructions. At the 8000th instruction, I generate a symbolize the xmm0 register with the ```symbolizeRegister()``` function,  get the symbolic expression of the register with the function ```getSymbolicRegister``` and get the ```id``` of the symbolic expression with the ```getId()``` function. 
After simulating all the 10000 instructions, I want the get the symbolic expression for the symbolic id. I use the ```getSymbolicExpression()``` function. However it throws the ```symbolic expression is not available anymore``` exception.

**Comment by JonathanSalwan** [comment]
Ok got it. Expressions are not saved if there is no reference on it anymore (otherwise we will consume quickly the memory).

For example, let's condiser:

```asm
id_0. mov rbx, 1
id_1. mov rax, rbx
id_2. mov rax, 2
``` 

At the `id_1`, `rax` has a reference on `id_0`. At the `id_2`, the previous expression assigned to `rax` is overwritten by the new reference (constant `2`) which makes `id_1` unassigned anymore by any register (or memory cells). So, `id_1` is freed.

So, if you got `symbolic expression is not available anymore` exception, it means that the id you are looking for has been freed because no register nor memory cells point on it.

**Comment by vancaho** [comment]
Thanks for your reply. But if I want to do backslice on `rax` at the second instruction i.e. ```id_1. mov rax, rbx```, what should I do if the symbolic expression of `rax` is freed?

**Comment by vancaho** [comment]
Thanks for your reply. But if I want to do backslice on `rax` at the second instruction i.e. ```id_1. mov rax, rbx```, what should I do if the symbolic expression of `rax` is freed?

**Comment by JonathanSalwan** [comment]
At this step, `id_1`  is still available so you can. But you cannot slice rax after executing id_2

**Comment by JonathanSalwan** [comment]
Related to my first comment, slicing is from `B` to `A`. You don't need to save the `id` of `A`.

So, in my example, it's something like this: `ctx.sliceExpressions(ctx.getSymbolicRegister(ctx.registers.rax))` at the 1 id_1` instruction.

**Comment by vancaho** [comment]
If I want to slice `rax` at `id_1` after executing #all the 3 instructions#, how to do with it?

**Comment by JonathanSalwan** [comment]
you can do it as I said

**Comment by JonathanSalwan** [comment]
Or, you have to keep a reference on every SymbolicExpression somewhere in your tritontool.

**Comment by vancaho** [comment]
Yeah, I will try to make a reference on every SymbolicExpression. Thank you

**Comment by JonathanSalwan** [comment]
Something like this could work.

```python
refs = []

ctx.processing(inst)
for se in inst.getSymbolicExpressions():
    refs.append(se)
```

**Comment by vancaho** [comment]
Thanks. 
I tried another instruction with opcode '\x8a\x18` which has the disassembly 'mov    bl,BYTE PTR [eax]'. I found that the symbolic expression of the written registers are `eip` and `ebx`, while the names of the written registers are `bl` and `eip`.
Does that mean that the bit width of the symbolic expression is automatically extended?

**Comment by vancaho** [comment]
ok, thanks, I will try it.
