### ISSUE TITLE
The symbolic expressions for the xmm registers is not consistent with the instruction

### ISSUE THREAD

**Issue by vancaho** [JonathanSalwan/Triton#951]
Here are the codes I used:
```
ctx = TritonContext(ARCH.X86)
inst = Instruction()
inst.setOpcode(b'\xf3\x0f\x6f\x09')
ctx.processing(inst)
# Here we print the instruction 
print(inst)

# Here we print the symbolic expressions 
for expr in inst.getSymbolicExpressions():
    print(expr.getOrigin())

# Here we print the written registers
written_registers = inst.getWrittenRegisters()
for register. value in written_registers:
    print(reg)
```

Below are the output:
```
0x0: movdqu xmm1, xmmword ptr [ecx]
ymm1:256 bv[255..0]
eip:32 bv[31..0]
eip:32 bv[31..0]
xmm1:128 bv[127..0]
```
From the output we find that the symbolic expressions generated for the registers is not consistent with the semantics of the instruction.

**Comment by JonathanSalwan** [comment]
What the problem?

**Comment by vancaho** [comment]
What I want to do is to do backward slicing on `xmm1` register. I use the name of the register to find the symbolic expression of it. As the the symbolic expression generated is for `ymm1`, I cannot find it with register name matching

**Comment by JonathanSalwan** [comment]
```python

written_registers = inst.getWrittenRegisters()
for register, value in written_registers:
   ctx.sliceExpressions(ctx.getSymbolicRegister(register))

```

**Comment by vancaho** [comment]
I try a new instruction  `0:  8a 18                   mov    bl,BYTE PTR [eax]`. I find the symbolic expressions for the written registers are `ebx` and `eip`, while the names of the written registers are `bl` and `eip`. Does it mean that the bit width of the symbolic expressions are automatically extended?

**Comment by JonathanSalwan** [comment]
When using `getSymbolicExpression()` you have expressions assigned to parent register (with a correct semantics, automatic extend, extract, concat, whatever). When you do `for register, value in written_registers:`, here `register` are the real dst register and value its AST.
