### ISSUE TITLE
Code coverage (number and list of of basic blocks) reporting using Triton

### ISSUE THREAD

**Issue by AGAPIA** [JonathanSalwan/Triton#953]
Hello,

I would like to know what is the proper way to use Triton to evaluate the code coverage, i.e. number and list of basic blocks touched by an input evaluation. Is there any script/example that does this (without using Pin)?

**Comment by JonathanSalwan** [comment]
In this scenario what I would do is emulate the binary like we did with [this script](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/small_x86-64_symbolic_emulator.py) and for every instruction processed, I would use `instruction.isSymbolized()` to update my coverage counter.

**Comment by AGAPIA** [comment]
Thanks ! I tried it and it works fine. However i would have another two questions if you can advise me:

1. For the Triton context mode in this case,  I disabled the symbolic engine using enableSymbolicEngine(False). Is there anything else we can do to optimize further the tracing process ?

2. What is the recommended way to catch issues such as SIGSEGV  ? I was looking at the examples inside small_x86-64_symbolic_emulator and I think that I understand them, but I would still like to know if you have any advice on this topic.

**Comment by JonathanSalwan** [comment]
1) For speed up the execution you should keep the symbolic engine enabled and use the mode `ONLY_ON_SYMBOLIZED`. It will be faster than disabling the symbolic engine.

2) To handle a sigsegv you have to keep a map of valid memory regions (RWX). For example with LIEF you have this information for every segment / section of the binary. Then, you can add callbacks with Triton on every concrete LOAD and STORE and see if the memory access is on a valid region.
