### ISSUE TITLE
Dockerfile has problems with pintool and python3

### ISSUE THREAD

**Issue by nofiv** [JonathanSalwan/Triton#958]
Hello, according to the [cmakelists](https://github.com/JonathanSalwan/Triton/blob/master/CMakeLists.txt#L35) it seems that the pintool doesn't support python3, however the docker file installs python3 and [compiles](https://github.com/JonathanSalwan/Triton/blob/master/Dockerfile#L34) Triton with `-DPINTOOL=on` which naturally leads to the error "The Pin tracer needs Python 2.7.".

**Comment by JonathanSalwan** [comment]
This issue has been [fixed](https://github.com/JonathanSalwan/Triton/blob/dev-v0.9/Dockerfile) into `dev-v0.9`.
