### ISSUE TITLE
Triton with external function

### ISSUE THREAD

**Issue by yh570** [JonathanSalwan/Triton#960]
Hi, I'm interested in why Triton can't run symbolic execution with external functions call such as libc. I know that the syscalls must execute with the kernel so Triton can't do the symbolic execution with them, but why Triton can't run libc without user-defined behavior? Thank you.

**Comment by JonathanSalwan** [comment]
Where did you see that Triton cannot execute external functions? You probably misunderstood what Triton really is. Take a look at this [example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/small_x86-64_symbolic_emulator.py).

**Comment by yh570** [comment]
Hi, I read this example, and also I wrote some libc hooking functions by myself, that's why I asked this question. IMO, libc is only the application code which is the same as the function calls within a user-defined function, not like syscalls are the operating system functions. However, users must custom relocate and re-define(hook) these libc functions in triton which confuse me.

I will apologize if I misunderstand the progress.

**Comment by SweetVishnya** [comment]
Triton provides a symbolic execution engine. To perform a real (concolic) dynamic symbolic execution you need to use some concrete executor (dynamic binary instrumentation, like Pin):
1) Hook some functions to create initial symbolic variables.
2) Ask Triton to symbolically execute instruction (buildSemantics).
3) Provide callbacks for getting concrete register/memory values.
Also, Triton is not limited to Linux. It can be used even for embedded devices. Triton just provides API to implement such symbolic execution.

**Comment by JonathanSalwan** [comment]
Currently we will not provide semantics behavior of libc functions. Maybe one day we will but not for now :). Why? Because it will be hard to maintain and we prefer to focus on instruction semantics instead of function semantics :).

**Comment by yh570** [comment]
@SweetVishnya @JonathanSalwan Thank you for your answers, and I'm sorry that I think I really misunderstood Triton's work progress. I'm still a little confused about the user-defined function and external function call. Currently, IMO, for the function call, no matter it's a user-defined function or external function such as libc, the user must define how to deal with these functions with Triton. If a function(user-defined or external) is not supported by Triton, when executing this no-mapped function Triton will jump to zero. Is my understanding correct? Because in some of my experiments, Triton will lose the rip address of the return address of the user-defined function and jump to zero if I try running without using pin tool.

**Comment by JonathanSalwan** [comment]
When mapping a binary from [lief](https://github.com/lief-project/LIEF) for example, the `.got` will be initialized with zero (like in real execution). The `.got` section is filled by `ld.so` (Linux) on a real execution which means that if you want to emulate a binary with Triton you have to do the job of `ld.so`. It's pretty easy: iterate over the `.got` section, initialize predefined addresses for each entry (e.g: `strlen`) and during the execution, you just have to monitor the `rip`. For example, if you initialized the `strlen` got entry with the address 0x1234 and if, at one point, `rip` is equal to 0x1234, you know that you have to execute your `strlen` python function. After simulating the `strlen` behavior, just read the return address pushed on stack by the last `call` to continue the execution ([example](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/hooking_libc.py#L179-L190)). 

> Because in some of my experiments, Triton will lose the rip address of the return address of the user-defined function and jump to zero if I try running without using pin tool.

Keep in mind that Triton can works without any DBI. For example, It's been 3 years now I'm using Triton as standalone executor without usage of any external tools and I'm able to execute real world programs.

**Comment by yh570** [comment]
@JonathanSalwan Thank you again for your comments, I will read the blog of code coverage again for better understanding.

**Comment by JonathanSalwan** [comment]
Be careful, this blog post is pretty outdated `Triton v0.2` (2015) and use a DBI (Pin) for the concrete execution part. While now, the concrete execution can be performed by Triton itself. Except the methodology to perform online code coverage over a DBI, this blog post is pretty useless regarding the core of Triton which is now totally different.
