### ISSUE TITLE
Strange semantic for movsd instruction

### ISSUE THREAD

**Issue by vancaho** [JonathanSalwan/Triton#965]
Hi, I find the semantics for `movsd` instruction maybe not correct:
```
In [1]: from  triton import *

In [2]: ctx = TritonContext()

In [3]: ctx.setArchitecture(ARCH.X86)

In [4]: ins = Instruction()

In [5]: ins.setOpcode(b'\xf3\xa5')

In [6]: ctx.processing(ins)
Out[6]: True

In [7]: ins.getDisassembly()
Out[7]: 'rep movsd dword ptr es:[edi], dword ptr [esi]'

In [8]: ins.isMemoryRead()
Out[8]: False

In [9]: ins.isMemoryWrite()
Out[9]: False

In [10]: ins.getLoadAccess()
Out[10]: []

In [11]: for exp in ins.getSymbolicExpressions():
    ...:     print(exp)
    ...:
(define-fun ref!0 () (_ BitVec 32) (ite (= (_ bv0 32) (_ bv0 32)) (_ bv0 32) (bvsub (_ bv0 32) (_ bv1 32)))) ; Counter operation
(define-fun ref!1 () (_ BitVec 32) (ite (= (ite (= (_ bv0 32) (_ bv0 32)) (_ bv0 32) (bvsub (_ bv0 32) (_ bv1 32))) (_ bv0 32)) (_ bv2 32) (_ bv0 32))) ; Program Counter
```
```movsd```is an instruction that transfers data from memory to memory, however I find that the semantics for this instruction does not contain the memory read or write actions. 
My triton is v0.8.1

**Comment by JonathanSalwan** [comment]
So, there is no bug right?

**Comment by jordan9001** [comment]
I don't think so.
I think `isMemoryRead/Write` can be a bit confusing at first. It is easy to assume they mean an instruction **can** read/write memory. But they actually are closer to saying an instruction **did** read/write memory.

**Comment by JonathanSalwan** [comment]
Yes, those information come from the runtime.

**Comment by vancaho** [comment]
Yes, I was confused by the name `isMemoryRead/Write` by thinking them as static behavior. The runtime semantics is correct
