### ISSUE TITLE
Error pushfq semantic

### ISSUE THREAD

**Issue by AcousGit** [JonathanSalwan/Triton#973]
Hi,

I think there is an error in the semantic of pushfq. According to the [Intel's Architectures Software Developer's Manual](https://software.intel.com/content/dam/develop/external/us/en/documents-tps/325462-sdm-vol-1-2abcd-3abcd.pdf), the second bit of EFLAGS is reserved and set to 1. However, when performing pushfq, Triton sets it to 0.
https://github.com/JonathanSalwan/Triton/blob/e4649fe9fdde90f83516e4a774d6fe02a1930a7d/src/libtriton/arch/x86/x86Semantics.cpp#L11517

I think that a patch would be to change it to:
```cpp
eflags.push_back(this->astCtxt->bvtrue()); /* Reserved */
```

I don't know if there is some more work to do.

**Comment by JonathanSalwan** [comment]
Nice catch!

**Comment by AcousGit** [comment]
Thanks :)
So can I close this issue?

**Comment by JonathanSalwan** [comment]
Yep :)
