### ISSUE TITLE
Python bindings in Manjaro

### ISSUE THREAD

**Issue by ReichertL** [JonathanSalwan/Triton#979]
Hello,
I am trying to install Triton on my Arch-based Linux distro Manjaro. 
When executing `sudo make -j2 install` I run into the following error: 
~~~
10: fatal error: Python.h: No such file or directory
   11 | #include <Python.h>
~~~
It is not a major issue, but all online resources I found on this problem suggest to change the build path (which after looking at the cmake and make files is something I really do not want  to do).
Do you have any suggestions how to fix this issue?

**Comment by SweetVishnya** [comment]
Does `cmake` locate Python?

**Comment by JonathanSalwan** [comment]
> Does `cmake` locate Python?
> 
> P.S. libpython development package should be installed.

+1. Also you can try a `$ locate Python.h` to see if you have the `libpython` installed somewhere on your system.

**Comment by ReichertL** [comment]
I believe there is no extra libpython development  package for Arch/ Manjaro. 


`$ locate Pyhton.h` gave me this, among other things: 

~~~
/usr/include/python2.7/Python.h
/usr/include/python3.9/Python.h
~~~

**Comment by ReichertL** [comment]
I also installed python-devtools from the AUR, but that did't solve the problem.

**Comment by JonathanSalwan** [comment]
Can you git clone `dev-v0.9` and past the output of the `cmake` ?

**Comment by ReichertL** [comment]
I get the same error now as in the other issue that was mentioned: 

~~~
.../Triton/src/libtriton/bindings/python/objects/pyAstContext.cpp:1779:7: error: too many initializers for ‘PyTypeObject’ {aka ‘_typeobject’}
 1779 |       };
      |       ^
make[2]: *** [src/libtriton/CMakeFiles/triton.dir/build.make:898: src/libtriton/CMakeFiles/triton.dir/bindings/python/objects/pyAstContext.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
.../Triton/src/libtriton/bindings/python/objects/pyAstNode.cpp:965:7: error: too many initializers for ‘PyTypeObject’ {aka ‘_typeobject’}
  965 |       };
      |       ^

~~~ 

At least it seems like finding python is not a problem anymore.

**Comment by SweetVishnya** [comment]
This is a `make` output, not `cmake`.

**Comment by JonathanSalwan** [comment]
You have to git clone the dev-v0.9. The fix had been pushed this morning to
support python3.9

**Comment by ReichertL** [comment]
Hello, 
Sorry, I thought i was already on dev-v0.9, but apparently I wasn't. 
Now installation completes successfully.
Thanks for your help! :)
