### ISSUE TITLE
Flaw in Python AST conversion

### ISSUE THREAD

**Issue by patacca** [JonathanSalwan/Triton#984]
The python AST representation syntax is incorrect.
Consider the following asm code:
```asm
mov ecx, 0 ; 0xb9 0x00 0x00 0x00 0x00
; ECX = 0
inc cl     ; 0xfe 0xc1
; ECX = 0x00000001
neg cl     ; 0xf6 0xd9
; ECX = 0x000000ff
ror cl, 1  ; 0xd0 0xc9
; ECX = 0x000000ff
```

As showed above the execution would set cl to 0xff and ecx to 0x000000ff accordingly.
The python representation of the AST would be this:
```python
ref_2 = SymVar_0
ref_3 = ((((ref_2 >> 8) & 0xffffff)) << 8 | (((ref_2 & 0xff) + 0x1) & 0xff)) # INC operation - 0x5: inc cl
ref_10 = ((((ref_3 >> 8) & 0xffffff)) << 8 | -(ref_3 & 0xff)) # NEG operation - 0x7: neg cl
ref_18 = ((((ref_10 >> 8) & 0xffffff)) << 8 | ror((ref_10 & 0xff), 0x1)) # ROR operation - 0x9: ror cl, 1
```

The first issue here is that if we want to implement the ror (as well as the rol) operation we need to know the size of the register because python won't tell us.
We need something like `ror(register, shift_bits, reg_size_in_bits)` so the AST would become `ror(ref_10 & 0xff, 0x1, 0x8)`

If we use the mode `SYMBOLIZE_INDEX_ROTATION` this is what we obtain
```python
ref_2 = SymVar_0
ref_3 = ((((ref_2 >> 8) & 0xffffff)) << 8 | (((ref_2 & 0xff) + 0x1) & 0xff)) # INC operation - 0x5: inc cl
ref_10 = ((((ref_3 >> 8) & 0xffffff)) << 8 | -(ref_3 & 0xff)) # NEG operation - 0x7: neg cl
ref_18 = ((((ref_10 >> 8) & 0xffffff)) << 8 | (((ref_10 & 0xff) >> (((0x1 & 0x1f) % 0x8) % 0x8)) | (((ref_10 & 0xff) << ((0x8 - (((0x1 & 0x1f) % 0x8) % 0x8)) & 0xff)) & 0xff))) # ROR operation - 0x9: ror cl, 1
```

As we can see the ror issue is solved but there is another one:
when we do `neg cl` the result is -1 or 0xff, unfortunatelly python won't convert -1 to 0xff because int type is not limited to 8 bit.
So ref_10 would become
```python
ref_10 = 0x0 | -(1 & 0xff)
ref_10 = 0x0 | -1
ref_10 = -1
```
Note that in this case -1 is not 0xff, in fact when doing `((ref_10 >> 8) & 0xffffff)` we obtain 0xffffff instead of 0x0 (-1 >> N is always -1 in python)
I think every time we perform a neg operation we have to specify a constraint for the int size so the `neg cl` should become:
```python
ref_10 = ((((ref_3 >> 8) & 0xffffff)) << 8 | (-(ref_3 & 0xff) & 0xff)) # NEG operation - 0x7: neg cl
```

I am not familiar with the code but I am going to try to submit a pull request for this

**Comment by patacca** [comment]
You can use the following code to reproduce my examples
```python
from triton import *

op = [b'\xb9\x00\x00\x00\x00', b'\xfe\xc1', b'\xf6\xd9', b'\xd0\xc9']

ctx = TritonContext()
ctx.setArchitecture(ARCH.X86)
ctx.setMode(MODE.SYMBOLIZE_INDEX_ROTATION, True)
ctx.setAstRepresentationMode(AST_REPRESENTATION.PYTHON)

for k in range(len(op)):
    i = Instruction()
    i.setOpcode(op[k])
    ctx.processing(i)

    if k == 0:
        ctx.symbolizeRegister(ctx.registers.ecx)

    print(i)
    print(f'ecx = {hex(ctx.getConcreteRegisterValue(ctx.registers.ecx))}')

print('\nPython AST representation\n')
exprs = ctx.sliceExpressions(ctx.getSymbolicRegister(ctx.registers.ecx))

for k,v in exprs.items():
    print(v)
```

**Comment by JonathanSalwan** [comment]
Thanks, I will merge the MR.
