### ISSUE TITLE
symbolic expression wrong when memory access involved

### ISSUE THREAD

**Issue by anaivebird** [JonathanSalwan/Triton#988]
Consider following code snip:
```
push ss:[ecx]  ("\x36\xFF\x31")
pop eax  ("\x58")
```

```
ctx.setConcreteRegisterValue(ctx.registers.ecx, 0x66)
ctx.setConcreteRegisterValue(ctx.registers.ss, 0x55)
executeAsm(b"\x36\xFF\x31")
executeAsm(b"\x58")
eaxExpr = ctx.getSymbolicRegister(ctx.registers.eax)
eaxSlice = ctx.sliceExpressions(eaxExpr)
print(eaxSlice)
```

result is
`{311472: ref_311472 = ((((0x0) << 8 | 0x0) << 8 | 0x0) << 8 | 0x0) # POP operation - 0xff66fff: pop eax}
`
which totally ignore ss:[ecx] value in expression

P.s. executeAsm function used above:
```
def executeAsm(opcode):
  addr = 0xFF66FFF
  inst = Instruction()
  inst.setOpcode(opcode)
  inst.setAddress(addr)
  eip_bak = ctx.getConcreteRegisterValue(ctx.getRegister('eip'))
  ctx.processing(inst)
  ctx.setConcreteRegisterValue(ctx.getRegister('eip'), eip_bak)
```

**Comment by anaivebird** [comment]
I found simple push and pop will lead to this error:
```
push [ecx]  ("\xFF\x31")
pop eax  ("\x58")
```

got

`{20597: ref_20597 = ((((0x0) << 8 | 0x0) << 8 | 0x0) << 8 | 0x0) # POP operation - 0xff66fff: pop eax}
`
```
ctx.setConcreteRegisterValue(ctx.registers.ecx, 0x66)
ctx.setConcreteRegisterValue(ctx.registers.ss, 0x55)
executeAsm(b"\xFF\x31")
executeAsm(b"\x58")
eaxExpr = ctx.getSymbolicRegister(ctx.registers.eax)
eaxSlice = ctx.sliceExpressions(eaxExpr)
print(eaxSlice)
```

**Comment by anaivebird** [comment]
I have known that that's because I didn't symbolizeMemory before do that. 

So the correct solution if some memory value influence the output you are analyzing is checking the slicing of expression of your output, and pay attention to mov or push operators in your slicing, which access memory but triton treats as reading const.

such as:
```
 ref_82311 = 0x0 # Byte reference - PUSH operation - 0x109c95b8: push dword ptr [eax],
 ref_98897 = ((((ref_81981) << 8 | ref_81982) << 8 | ref_81983) << 8 | ref_82311) # MOV operation - 0x10950013: mov eax, dword ptr [esp]]

```
P.s. setComment is needed to comment instructions on symbolic expr computation so that we could track that by printing slicing of output variable

```
for se in instruction.getSymbolicExpressions():
    se.setComment(str(instruction))
```

**Comment by anaivebird** [comment]
By the way, it seems that for tiron, push ss:[eax] is just equivalent to push [eax] since triton never read ss register(Known from inst.getReadRegisters()).

And push ss:[eax] will never appear on comment of symbolicexpressions(shown on my above reply) since triton will treat memory load as const if that memory address not symbolized.

Some when symbolic execution result differs from real trace, we need to tracking all consts in slicing expression, some of them may different from real programming running trace.

**Comment by anaivebird** [comment]
Totally solved, after ctx.setMode(MODE.ONLY_ON_SYMBOLIZED, True) is used.

**Comment by JonathanSalwan** [comment]
> P.s. setComment is needed to comment instructions on symbolic expr computation so that we could track that by printing slicing of output variable

This feature as been [added](https://github.com/JonathanSalwan/Triton/commit/449689a2ee7c65228db47d1d2706bf058516fee0) few days ago.

> By the way, it seems that for tiron, push ss:[eax] is just equivalent to push [eax] since triton never read ss register(Known from inst.getReadRegisters()).

Indeed, it's a bug. Actually, the `ss` value is read but not shown by `getReadRegisters` (i will fix this). However, be careful, we use segment value as base address and not as selector. For example, `ss:[eax + ebx * 1 + 10]` is handle like `ss + eax + ebx * 1 + 10`.

**Comment by anaivebird** [comment]
> However, be careful, we use segment value as base address and not as selector. For example, ss:[eax + ebx * 1 + 10] is handle like ss + eax + ebx * 1 + 10.

Yeap, I also found that. Thanks a lot.
