### ISSUE TITLE
Adjust flag not set to 0 after and instruction

### ISSUE THREAD

**Issue by anaivebird** [JonathanSalwan/Triton#989]
When EAX=36FD9906, execute and eax,000000FF
on real x86 32bit machine, Adjust flag will changed to 0, but triton not set it.

and eax,000000FF
EAX=36FD9906
EBX=1095DD47
ECX=109C5AA5
EDX=10942E99
ESI=1096D7CA
EDI=0016D000
EBP=00000000
ESP=00194674
EIP=109C5AAD

EFLAGS=00200217

-
mov ebx,ebx
EAX=00000006
EBX=1095DD47
ECX=109C5AA5
EDX=10942E99
ESI=1096D7CA
EDI=0016D000
EBP=00000000
ESP=00194674
EIP=109C5AB3

EFLAGS=00200206

see the EFLAGS changes from 1 to 0, that is adjust flag

**Comment by JonathanSalwan** [comment]
According to the ISA manual (quick see [here](https://www.felixcloutier.com/x86/and), the state of the AF flag is undefined.

**Comment by anaivebird** [comment]
So I won't influence program's any branch or output? 
I want to compare triton's emulation with real trace by their all registers except eflags.
But the program I'm analyzing use pushfd to push flags into stack, and mov them to register later.

So difference in AF will lead to different registers later.

If I only compare EIP of emulation with real trace, I will be harder to find why program branch differently because registers' different will be pushed into stack and moved later to register, and used by cmp to dicide whether to branch. But triton's backslicing couldn't tracking memory store and load.

**Comment by anaivebird** [comment]
Update: I'm currently work around this AF inconsistent problem by this ugly way:
```
set_AF_prefix = ['xor', 'and']
for prefix in set_AF_prefix:
  if prefix in instruction.getDisassembly():
    ctx.setConcreteRegisterValue(ctx.getRegister('AF'), 0)
```
P.s. I don't know whether all 'xor' and 'and' instructions set AF to zero(undefined behavior), but I patch this to make all register same with trace of real program.(any wrong attemps to set AF to zero will be found by comparing emulation register value with real one.)

B.t.w. I really couldn't figure out why should Intel make AF changed for xor and and instruction, it seems meaningless.

**Comment by JonathanSalwan** [comment]
> B.t.w. I really couldn't figure out why should Intel make AF changed for xor and and instruction, it seems meaningless.

Actually, there is no undefined behavior in CPUs. Every behavior have a precise spec defined. However, for Intel the term _undefined behavior_ means that they do not know on what CPU version the program is executed. For example, let's say that for a CPU version A, the AF is defined as 0, and then for a CPU version B, the AF is defined as 1. As they do not know on what CPU you are executing the code, the ISA says that it's undefined behavior. However, I've seen some code using `cpuid` to get the CPU version and to determine if the code is under emulation according to value of those _undefined behaviors_

**Comment by anaivebird** [comment]
> However, I've seen some code using cpuid to get the CPU version and to determine if the code is under emulation according to value of those undefined behaviors
Thanks. That's crazy. But for most of program, they won't rely on that CPU version dependent flag, right?

**Comment by JonathanSalwan** [comment]
> Thanks. That's crazy. But for most of program, they won't rely on that CPU version dependent flag, right?

Yep, it was a very specific case. Generally, compilers does not rely on undefined behavior to define the control flow. In most of _normal_  programs you can ignore the value of those undefined behavior in you want to compare a Triton and a concrete trace.
