### ISSUE TITLE
Hard to find value in memory cell which influence output value

### ISSUE THREAD

**Issue by anaivebird** [JonathanSalwan/Triton#990]
For some cases, the output value we are interested in is dependent on value in some memory address.But it's hard to find that critical memory address due to load or store is not supported in symbolic execution backward slicing(it will just treats that memory value as a const).

One example:
```
push [ecx] (ecx=0x550044)
....(100 instructions irrelevant)
mov edx, [esp+4]([esp+4] here is just [ecx] we pushed above)
push edx (indirect call)
ret 3
```

On this point, edx in trion emulation differs from real trace, and after ret 3, my emulation is crashed, because edx is the address the control flow jumps to (by call push and then ret implicitly).

I found it really time consuming to find that it is value in ecx=0x550044 that causes my emulation's code path differs from real trace. So is there any other way to work around these when symbolic backward slicing for load and store operation is hard?

**Comment by JonathanSalwan** [comment]
> For some cases, the output value we are interested in is dependent on value in some memory address.But it's hard to find that critical memory address due to load or store is not supported in symbolic execution backward slicing(it will just treats that memory value as a const).

Indeed, in some case concretizing memory accesses have an impact but keep in mind that symbolizing every load and store do not scale at all...

Maybe something like below may help.

```python
#!/usr/bin/env python

# Output:
#
# (define-fun ref!256 () (_ BitVec 8) stack_0x7ffb0100) ; Byte reference
# (define-fun ref!257 () (_ BitVec 8) stack_0x7ffb0101) ; Byte reference
# (define-fun ref!258 () (_ BitVec 8) stack_0x7ffb0102) ; Byte reference
# (define-fun ref!259 () (_ BitVec 8) stack_0x7ffb0103) ; Byte reference
# (define-fun ref!131079 () (_ BitVec 32) (concat ref!259 ref!258 ref!257 ref!256)) ; MOV operation - 0x2: mov edx, dword ptr [esp + 4]
# (define-fun ref!131082 () (_ BitVec 8) ((_ extract 31 24) ref!131079)) ; Byte reference - PUSH operation - 0x6: push edx
# (define-fun ref!131083 () (_ BitVec 8) ((_ extract 23 16) ref!131079)) ; Byte reference - PUSH operation - 0x6: push edx
# (define-fun ref!131084 () (_ BitVec 8) ((_ extract 15 8) ref!131079)) ; Byte reference - PUSH operation - 0x6: push edx
# (define-fun ref!131085 () (_ BitVec 8) ((_ extract 7 0) ref!131079)) ; Byte reference - PUSH operation - 0x6: push edx
# (define-fun ref!131088 () (_ BitVec 32) (concat ref!131082 ref!131083 ref!131084 ref!131085)) ; Program Counter - 0x7: ret 3

from triton import *

ctx = TritonContext(ARCH.X86)

base_stack = 0x7ffb0000
base_heap =  0x90000000

# symbolize the stack area you want to analyze
for i in range(0x10000):
    ctx.symbolizeMemory(MemoryAccess(base_stack + i, 1), f'stack_{base_stack + i:#x}')

# symbolize the hear area you want to analyze
for i in range(0x10000):
    ctx.symbolizeMemory(MemoryAccess(base_heap + i, 1), f'heap_{base_heap + i:#x}')


ctx.setConcreteRegisterValue(ctx.registers.ecx, 0x550044)
ctx.setConcreteRegisterValue(ctx.registers.esp, 0x7ffb0100)

code = [
    b"\xff\x31", # push [ecx]
    b"\x8b\x54\x24\x04", # mov edx, [esp+4]
    b"\x52", # push edx
    b"\xc2\x03\x00", # ret 3
]

for op in code:
    ctx.processing(Instruction(op))

# Print sliced expression
eip = ctx.getSymbolicRegister(ctx.registers.eip)
for k, v in sorted(ctx.sliceExpressions(eip).items()):
    print(v)
```

Perhaps using Triton in pure emulation is not the good choice in your case. For example, to compare Triton semantics against real executions, I use a DBI and at each program point i'm comparing the Triton's state with the DBI state's. An example using [Pin](https://github.com/JonathanSalwan/Triton/blob/master/src/testers/pin/check_semantics.py) which gives this following [output](http://shell-storm.org/repo/Notepad/triton-semantics-testing.txt). Another [example](http://shell-storm.org/repo/Notepad/qbdi_with_triton.txt) using [QBDI](https://qbdi.quarkslab.com/).

**Comment by anaivebird** [comment]
Thanks, that works for it.
Still two questions to ask:
1. Is ctx.symbolizeMemory(MemoryAccess(base_heap + i, 1))  different from ctx.symbolizeMemory(MemoryAccess(base_heap + i, 4))? If some assembly only access byte ptr of it, symbolizing 4 bytes won't work, right?

2. Using your code, I could only get these output:
ref_4372049 = stack_0x7ffb0100 # Byte reference
ref_4372051 = stack_0x7ffb0101 # Byte reference
ref_4372053 = stack_0x7ffb0102 # Byte reference
ref_4372055 = stack_0x7ffb0103 # Byte reference
ref_4387943 = ((((ref_4372055) << 8 | ref_4372053) << 8 | ref_4372051) << 8 | ref_4372049) # MOV operation - 0xa: mov edx, dword ptr [esp + 4]
ref_4387953 = ref_4387943 # Program Counter - 0xf: ret 3

these 4 lines are missing:
```
# (define-fun ref!131082 () (_ BitVec 8) ((_ extract 31 24) ref!131079)) ; Byte reference - PUSH operation - 0x6: push edx
# (define-fun ref!131083 () (_ BitVec 8) ((_ extract 23 16) ref!131079)) ; Byte reference - PUSH operation - 0x6: push edx
# (define-fun ref!131084 () (_ BitVec 8) ((_ extract 15 8) ref!131079)) ; Byte reference - PUSH operation - 0x6: push edx
# (define-fun ref!131085 () (_ BitVec 8) ((_ extract 7 0) ref!131079)) ; Byte reference - PUSH operation - 0x6: push edx
```
Is it related to my version of triton?

3. In real world, [0x550044] will be stored by other value, is it possible to backward tracking them? Or we could understand it as for symbolic value stored to memory and load out, we will loss track of its data flow, right?

For example,  just add two assembly to calulate a value and store it to [ecx], will 
```
and ebx, edx+0xFF
mov [ecx], ebx
push [ecx] (ecx=0x550044)
....(100 instructions irrelevant)
mov edx, [esp+4]([esp+4] here is just [ecx] we pushed above)
push edx (indirect call)
ret 3
```

change code to:
```
from triton import *


ctx.concretizeAllMemory()
ctx.concretizeAllRegister()

base_stack = 0x7ffb0000
base_heap =  0x90000000

# symbolize the stack area you want to analyze
for i in range(0x1000):
    ctx.symbolizeMemory(MemoryAccess(base_stack + i, 1), f'stack_{base_stack + i:#x}')

# symbolize the heap area you want to analyze
for i in range(0x1000):
    ctx.symbolizeMemory(MemoryAccess(base_heap + i, 1), f'heap_{base_heap + i:#x}')

ctx.symbolizeRegister(ctx.registers.ebx, 'ebx')
ctx.setConcreteRegisterValue(ctx.registers.ecx, 0x550044)
ctx.setConcreteRegisterValue(ctx.registers.esp, 0x7ffb0100)

code = [
    b"\x81\xE3\xEF\x00\x00\x00", # and ebx, edx+0xFF
    b"\x89\x19", # mov [ecx], ebx
    b"\xff\x31", # push [ecx]
    b"\x8b\x54\x24\x04", # mov edx, [esp+4]
    b"\x52", # push edx
    b"\xc2\x03\x00", # ret 3
]

for op in code:
    ctx.processing(Instruction(op))

# Print sliced expression
eip = ctx.getSymbolicRegister(ctx.registers.eip)
for k, v in sorted(ctx.sliceExpressions(eip).items()):
    print(v)
```
still got output:
```
ref_4372049 = stack_0x7ffb0100 # Byte reference
ref_4372051 = stack_0x7ffb0101 # Byte reference
ref_4372053 = stack_0x7ffb0102 # Byte reference
ref_4372055 = stack_0x7ffb0103 # Byte reference
ref_4387943 = ((((ref_4372055) << 8 | ref_4372053) << 8 | ref_4372051) << 8 | ref_4372049) # MOV operation - 0xa: mov edx, dword ptr [esp + 4]
ref_4387953 = ref_4387943 # Program Counter - 0xf: ret 3
```

**Comment by anaivebird** [comment]
And DBI won't work if I'm analyzing an dll injected into one process on windows, and that dll also has multiple threads?

**Comment by anaivebird** [comment]
B.t.w, when analyzing stacked-based vm protected code, almost all the intermidiate results will be pushed to stack, and then pop out, so will backslicing possible for tracking data going into stack and then out of it?

**Comment by anaivebird** [comment]
Progress:
> B.t.w, when analyzing stacked-based vm protected code, almost all the intermidiate results will be pushed to stack, and then pop out, so will backslicing possible for tracking data going into stack and then out of it?

For this case, symbolizedMemory before running will be replaced by things like push [ecx] during execution, then trace of source of that memory cell losed, so my fix is:

```
def processInstructionWrapper(instruction):
  global memoryLoads
  global firstExecuteToCollectMemoryLoads


  if not firstExecuteToCollectMemoryLoads:
    for reg_name in set_registers:
      reg = ctx.getRegister(reg_name)
      if not ctx.isRegisterSymbolized(reg):
        #debug('{} is not symbolized'.format(reg_name))
        ctx.symbolizeRegister(reg, '{} generated at idx={}'.format(reg_name, len(totalInstructions)))

  if not firstExecuteToCollectMemoryLoads and len(totalInstructions) < len(memoryLoads):
    for instMemoryAccess in memoryLoads[len(totalInstructions)]:
      if not ctx.isMemorySymbolized(instMemoryAccess):
        ctx.symbolizeMemory(instMemoryAccess, '{} first loaded at idx={}'.format(instMemoryAccess.getAddress(), len(totalInstructions)))

  return_value = ctx.processing(instruction)

  if firstExecuteToCollectMemoryLoads:
    MemoryAccesses = []
    for access in instruction.getLoadAccess():
      instMemoryAccess = access[0]
      MemoryAccesses.append(instMemoryAccess)
    memoryLoads.append(MemoryAccesses)

  if not firstExecuteToCollectMemoryLoads:
    for access in instruction.getStoreAccess():
      instMemoryAccess = access[0]
      if not ctx.isMemorySymbolized(instMemoryAccess):
        ctx.symbolizeMemory(instMemoryAccess, '{} stored at idx={}'.format(instMemoryAccess.getAddress(), len(totalInstructions)))

  return return_value
```

symbolizeMemory before instruction that loads memory(if that memory is not symbolized), and symbolizeMemory after instruction that stores into memory.

The code is ulgy due to .getLoadAccess() is only available before ctx.processing(instruction), but it will be too late to symbolize the  loaded access after execute it.

So it that any api do the same with ctx.processing but not actually execute code(no influence on registers and memory but enable .getLoadAccess()) 

ctx.buildSematics() seems not works, after call it, .getLoadAccess() still empty.

I think that api should be possible, if all registers are set correctly. If we have that api, we could do like this:

```
ctx.fakeProcessing(inst) # only to make .getLoadAccess() possible
for access in instruction.getLoadAccess():
  instMemoryAccess = access[0]
  if not ctx.isMemorySymbolized(instMemoryAccess):
    ctx.symbolizeMemory(instMemoryAccess, '{} first loaded at idx={}'.format(instMemoryAccess.getAddress(), len(totalInstructions)))

ctx.processing(inst)

for access in instruction.getStoreAccess():
  instMemoryAccess = access[0]
  if not ctx.isMemorySymbolized(instMemoryAccess):
    ctx.symbolizeMemory(instMemoryAccess, '{} stored at idx={}'.format(instMemoryAccess.getAddress(), len(totalInstructions)))

```

**Comment by anaivebird** [comment]
```
code = [
    b"\x81\xE3\xEF\x00\x00\x00", # and ebx, edx+0xFF
    b"\x89\x19", # mov [ecx], ebx
    b"\xff\x31", # push [ecx]
    b"\x8b\x54\x24\x04", # mov edx, [esp+4]
    b"\x52", # push edx
    b"\xc2\x03\x00", # ret 3
]
```
For this case, the above fix could tell us, it is stack value influence edx, and then lead to final eip, but it could not backtrack to "and ebx, edx+0xFF", "mov [ecx], ebx", with is the source of the value on the stack

**Comment by anaivebird** [comment]
> Using your code, I could only get these output:
> ref_4372049 = stack_0x7ffb0100 # Byte reference
> ref_4372051 = stack_0x7ffb0101 # Byte reference
> ref_4372053 = stack_0x7ffb0102 # Byte reference
> ref_4372055 = stack_0x7ffb0103 # Byte reference
> ref_4387943 = ((((ref_4372055) << 8 | ref_4372053) << 8 | ref_4372051) << 8 | ref_4372049) # MOV operation - 0xa: mov edx, dword ptr [esp + 4]
> ref_4387953 = ref_4387943 # Program Counter - 0xf: ret 3
> 
> these 4 lines are missing:
> 
> (define-fun ref!131082 () (_ BitVec 8) ((_ extract 31 24) ref!131079)) ; Byte reference - PUSH operation - 0x6: push edx
> (define-fun ref!131083 () (_ BitVec 8) ((_ extract 23 16) ref!131079)) ; Byte reference - PUSH operation - 0x6: push edx
> (define-fun ref!131084 () (_ BitVec 8) ((_ extract 15 8) ref!131079)) ; Byte reference - PUSH operation - 0x6: push edx
> (define-fun ref!131085 () (_ BitVec 8) ((_ extract 7 0) ref!131079)) ; Byte reference - PUSH operation - 0x6: push edx
> Is it related to my version of triton?


ctx.setMode(MODE.ALIGNED_MEMORY, False) solves it
