### ISSUE TITLE
disassembly error when disassembling "\x66\xF2\xAF"

### ISSUE THREAD

**Issue by vancaho** [JonathanSalwan/Triton#993]
Hi, when I using to simulate executing the instructions in windows `ntdll.dll`, I found that the disassembly is different with that  disassembled by IDA pro. The opcode is `\x66\xF2\xAF`.
Here is the disassembly returned by ida pro：

![image](https://user-images.githubusercontent.com/15372990/108614470-aa0d0200-7435-11eb-8454-095522481eb3.png)

I tried that with https://defuse.ca/online-x86-assembler.htm#disassembly2, it also returns `0:  66 f2 af                repnz scas ax,WORD PTR es:[edi]`

But when disassemble it with triton, it returns `repne scasd eax, dword ptr es:[edi]`.

**Comment by SweetVishnya** [comment]
Triton uses capstone to disassemble instructions. Try to build the newest capstone from [github](https://github.com/aquynh/capstone) and disassemble your instruction with capstone.

**Comment by JonathanSalwan** [comment]
Indeed, I also get `0x0: repne scasd eax, dword ptr es:[edi]` with the Capstone version `4.0.2`. I can't do anything right know because this issue is not related to Triton =/. We have to see and wait for a fix in the next release of Capstone.
