### ISSUE TITLE
Analyzing a binary with external function calls

### ISSUE THREAD

**Issue by edi33416** [JonathanSalwan/Triton#995]
I'm trying to run Triton to do a taint analysis on a binary that also performs external function calls.

The problem that I encounter is that Triton doesn't seem to be able to resolve the got+plt relocation addresses.
Because of this, when it reaches a call to an external function the `pc` will reach the value `0x0` and it will terminate the execution.

I started from the [small symbolic emulator](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/small_x86-64_symbolic_emulator.py) example.

If we remove [strlen](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/small_x86-64_symbolic_emulator.py#L327) from the `customRelocation` array then the code won't hook to the python [implementation](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/small_x86-64_symbolic_emulator.py#L166) and will use the `strlen` function from `glibc`.

When the code is executed, the `call strlen` will jump into `plt`, but since there was no dynamic linker invoked, the pc will eventually find the address `0x0`, instead of the actual address of `strlen`, and it will terminate the execution.

I've also gone through the discussion from issue #960.
Based on the discussion there, I tried to manually patch the relocations with [lief](https://lief.quarkslab.com//doc/latest/tutorials/05_elf_infect_plt_got.html)

I tried to do this by changing [loadBinary](https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/small_x86-64_symbolic_emulator.py#L382)s implementation with the one below
```
def loadBinary(path):
    import lief
    # Map the binary into the memory
    binary = lief.parse(path)

    libc = lief.parse("/usr/lib/x86_64-linux-gnu/libc.so.6")                                                                                                                                        
    segment_added = binary.add(libc.segments[0])

    libc_strlen = libc.get_symbol("strlen")
    libc_strlen_addr = segment_added.virtual_address + libc_strlen.value
    binary.patch_pltgot("strlen", libc_strlen_addr)

    phdrs  = binary.segments
    for phdr in phdrs:
        size   = phdr.physical_size
        vaddr  = phdr.virtual_address
        debug('Loading 0x%06x - 0x%06x' %(vaddr, vaddr+size))
        Triton.setConcreteMemoryAreaValue(vaddr, phdr.content)
    return binary
```

This "patch" doesn't correctly patch my got+plt and will cause the program to run without stopping.

This brings us to my question:

- How can I analyze a binary without writing my own python implementation for library function calls?
Manually writing implementations doesn't scale: we have to know the implementation of the functions that we call, write it correctly, it will take a considerable amount of time, etc. I also want to use Triton in a black-box approach, on proprietary binaries for which I don't have access to the source code (to see what the function that I'm calling does an how I can implement it in python).

- What I want is to be able to "call" (load the library code and emulate it) external functions and return to my call site. How could I do this?

**Comment by JonathanSalwan** [comment]
> This "patch" doesn't correctly patch my got+plt

My first intuition at the first read without testing by myself: What if you call `patch_pltgot` after loading all segments? Maybe you just overwritten your patched `pltgot`.

> and will cause the program to run without stopping.

This behavior is often caused by executing the opcodes [00 00 00 00 00 ...](http://shell-storm.org/online/Online-Assembler-and-Disassembler/?opcodes=%5Cx00%5Cx00%5Cx00%5Cx00%5Cx00%5Cx00%5Cx00%5Cx00&arch=x86-64&endianness=little&dis_with_addr=True&dis_with_raw=True&dis_with_ins=True#disassembly) which are mainly located in a virgin area (like a clean plt/got).

> Manually writing implementations doesn't scale:

It's partially true. Once it's done, you do not have to write them anymore.

> we have to know the implementation of the functions that we call, write it correctly, it will take a considerable amount of time, etc.

That's 110% true. Based on my experiences, it's time consuming and you always have some corner cases that make your function partially correct! However the principal advantage that it gives:

* You fully control the behavior of the function and you choose what the function must return. E.g: concrete values, full symbolic values, a trade off  between concrete and symbolic values, AST summaries, etc.

Also, keep in mind that if you redirect the execution flow into shared libraries, you still have to define the behavior of syscalls and your formulas (if you are interested in symbolic execution) will be bigger. 

> What I want is to be able to "call" (load the library code and emulate it) external functions and return to my call site. How could I do this?

If calling `patch_pltgot` after loading segments still does not works, I will try to provide an example.

**Comment by edi33416** [comment]
> > This "patch" doesn't correctly patch my got+plt
> 
> My first intuition at the first read without testing by myself: What if you call `patch_pltgot` after loading all segments? Maybe you just overwritten your patched `pltgot`.

I modified my patch as below:
```
def loadBinary(path):
    import lief
    # Map the binary into the memory
    binary = lief.parse(path)

    libc = lief.parse("/usr/lib/x86_64-linux-gnu/libc.so.6")
    segment_added = binary.add(libc.segments[0])

    phdrs  = binary.segments
    for phdr in phdrs:
        size   = phdr.physical_size
        vaddr  = phdr.virtual_address
        debug('Loading 0x%06x - 0x%06x' %(vaddr, vaddr+size))
        Triton.setConcreteMemoryAreaValue(vaddr, phdr.content)

    libc_strlen = libc.get_symbol("strlen")
    libc_strlen_addr = segment_added.virtual_address + libc_strlen.value
    binary.patch_pltgot("strlen", libc_strlen_addr)

    return binary
```
Applying the `patch_pltgot` after the `for` loop seems to have no effect on the behaviour. By this I mean that the program behaves the same with or without the patch.

> 
> > Manually writing implementations doesn't scale:
> 
> It's partially true. Once it's done, you do not have to write them anymore.

That is true, but we want to be able to also analyze black-box binaries so we won't always have access to the implementation of the library functions to write our own. Being able to patch the got would be the desired approach.


> 
> Also, keep in mind that if you redirect the execution flow into shared libraries, you still have to define the behavior of syscalls and your formulas (if you are interested in symbolic execution) will be bigger.

Do you see any way of avoiding having to define the behaviour of the syscalls?

> 
> > What I want is to be able to "call" (load the library code and emulate it) external functions and return to my call site. How could I do this?
> 
> If calling `patch_pltgot` after loading segments still does not works, I will try to provide an example.

It would be great if you could provide an example. Thank you

**Comment by JonathanSalwan** [comment]
```python
#!/usr/bin/env python3
## -*- coding: utf-8 -*-

from __future__ import print_function
from triton     import TritonContext, ARCH, MemoryAccess, CPUSIZE, Instruction, OPCODE, MODE

import sys
import os

# Script options
TARGET = os.path.join(os.path.dirname(__file__), 'samples/sample_2')
LIBC   = os.path.join(os.path.dirname(__file__), 'samples/libc.so.6')

# Memory mapping
BASE_ARGV  = 0x10000000
BASE_STACK = 0x7fffffff
BASE_LIBC  = 0x80000008


# Emulate the binary.
def emulate(ctx, pc):
    while pc:
        # Fetch opcode
        opcode = ctx.getConcreteMemoryAreaValue(pc, 16)

        # Create the Triton instruction
        instruction = Instruction()
        instruction.setOpcode(opcode)
        instruction.setAddress(pc)

        # Process
        ctx.processing(instruction)
        print(instruction)
        if instruction.getType() == OPCODE.X86.HLT:
            break

        # Next
        pc = ctx.getConcreteRegisterValue(ctx.registers.rip)

    return


def loadBinary(ctx):
    import lief

    # Map the binary into the memory
    binary = lief.parse(TARGET)
    phdrs  = binary.segments
    for phdr in phdrs:
        size   = phdr.physical_size
        vaddr  = phdr.virtual_address
        print('Loading 0x%06x - 0x%06x' %(vaddr, vaddr+size))
        ctx.setConcreteMemoryAreaValue(vaddr, phdr.content)

    # Map the libc into the memory
    libc  = lief.parse(LIBC)
    phdrs = libc.segments
    for phdr in phdrs:
        size   = phdr.physical_size
        vaddr  = BASE_LIBC + phdr.virtual_address
        print('Loading 0x%06x - 0x%06x' %(vaddr, vaddr + size))
        ctx.setConcreteMemoryAreaValue(vaddr, phdr.content)

    # Functions that you want to bind
    let_bind = [
        "strlen",
        # ...
    ]

    relocations = [x for x in binary.pltgot_relocations]
    relocations.extend([x for x in binary.dynamic_relocations])

    # Fill the plt/got
    for rel in relocations:
        symbolName = rel.symbol.name
        symbolRelo = rel.address
        if symbolName in let_bind:
            print('Hooking %s' %(symbolName))
            libc_sym_addr = libc.get_symbol(symbolName).value
            ctx.setConcreteMemoryValue(MemoryAccess(symbolRelo, CPUSIZE.QWORD), BASE_LIBC + libc_sym_addr)

    return binary


if __name__ == '__main__':
    # Set the architecture
    ctx = TritonContext(ARCH.X86_64)

    # Set a symbolic optimization mode
    ctx.setMode(MODE.ALIGNED_MEMORY, True)

    # Load the binary
    binary = loadBinary(ctx)

    # Define a stack
    ctx.setConcreteRegisterValue(ctx.registers.rbp, BASE_STACK)
    ctx.setConcreteRegisterValue(ctx.registers.rsp, BASE_STACK)

    # Define argvs
    ctx.setConcreteMemoryAreaValue(BASE_ARGV + 0x100, b'sample/sample_2')
    ctx.setConcreteMemoryAreaValue(BASE_ARGV + 0x200, b'hello world')
    ctx.setConcreteMemoryValue(MemoryAccess(BASE_ARGV + 0, CPUSIZE.QWORD), BASE_ARGV + 0x100) # argv[0] = 'sample/sample_2'
    ctx.setConcreteMemoryValue(MemoryAccess(BASE_ARGV + 8, CPUSIZE.QWORD), BASE_ARGV + 0x200) # argv[1] = 'hello world'
    ctx.setConcreteRegisterValue(ctx.registers.rdi, 2)
    ctx.setConcreteRegisterValue(ctx.registers.rsi, BASE_ARGV)

    # Let's emulate the binary from the entry point
    print('Starting emulation')
    emulate(ctx, binary.get_symbol('main').value)
    print('Emulation done')

    sys.exit(0)
```

However, the libc and others shared libraries may contain some unsupported instructions and syscalls must be supported by your side. The list of supported instructions by Triton is [here](https://triton.quarkslab.com/documentation/doxygen/SMT_x86_Semantics_Supported_page.html).

**Comment by edi33416** [comment]
Thank you very much for your help.

Based on your example I've changed the patch to
```
def loadBinary(path):
    import lief
    # Map the binary into the memory
    binary = lief.parse(path)
    phdrs  = binary.segments
    for phdr in phdrs:
        size   = phdr.physical_size
        vaddr  = phdr.virtual_address
        debug('Loading 0x%06x - 0x%06x' %(vaddr, vaddr+size))
        Triton.setConcreteMemoryAreaValue(vaddr, phdr.content)


    libc = lief.parse("/usr/lib/x86_64-linux-gnu/libc.so.6")
    phdrs  = libc.segments
    for phdr in phdrs:
        size   = phdr.physical_size
        vaddr  = phdr.virtual_address
        debug('Loading 0x%06x - 0x%06x' %(vaddr, vaddr+size))
        Triton.setConcreteMemoryAreaValue(vaddr, phdr.content)

    # Functions that you want to bind
    let_bind = [
        "strlen",
        # ...
    ]

    relocations = [x for x in binary.pltgot_relocations]
    relocations.extend([x for x in binary.dynamic_relocations])

    # Fill the plt/got
    for rel in relocations:
        symbolName = rel.symbol.name
        symbolRelo = rel.address
        if symbolName in let_bind:
            print('Hooking %s' %(symbolName))
            libc_sym_addr = libc.get_symbol(symbolName).value
            Triton.setConcreteMemoryValue(MemoryAccess(symbolRelo, CPUSIZE.QWORD), BASE_LIBC + libc_sym_addr)

    return binary
```

With this change I'm able to run `./small_x86-64_symbolic_emulator.py samples/sample_1 aaa`, but instead of `strlen` returning `3`, it returns `2148224312`.
Just to be clear, I was expecting the program to print
```
Input size = 3
```
but it prints
```
Input size = 2148224312
```

Another surprise I've encountered is that if I also remove `printf` from the `customRelocations` list, the program keeps on going.
I was expecting it to reach a syscall and exit. Am I wrong in my assumption?

Would it be possible to run this same example with QBDI and have QBDI handle the syscalls?
I'm thinking about having Triton do the symbolic execution and QBDI handle library calls and/or syscalls. Sort of a ping-pong between the two.
I've discovered [this post](https://malware.news/t/android-native-library-analysis-with-qbdi/30155) that got me thinking.

Thank you again for your help and I'm looking forward to your answer

**Comment by JonathanSalwan** [comment]
Take a look to this [bootstrap](http://shell-storm.org/repo/Notepad/qbdi_with_triton.txt) if you want to mix QBDI and Triton
