### ISSUE TITLE
/usr/bin/ld: cannot find -lpin | -lxed | -lpindwarf

### ISSUE THREAD

**Issue by BMorgan1296** [JonathanSalwan/Triton#998]
Hi,

I have installed using Pin 2.14, latest version of Triton, capstone v4.0.2.

I clone Triton under Pin, make the build directory and run `cmake -DPINTOOL=on -PYTHON36=off ..`

This configures properly. When I compile using `sudo make -j2` I get the following, showing that the libraries to be linked are unable to be found. Here is the paste:

```$ sudo make -j2
[  2%] Built target gen-syscall64
[  2%] Built target gen-syscall32
[ 79%] Built target triton
[ 80%] Linking CXX shared library libpintool.so
[ 80%] Built target python-triton
[ 82%] Built target ctest_api
/usr/bin/ld: cannot find -lpin
/usr/bin/ld: cannot find -lxed
/usr/bin/ld: cannot find -lpindwarf
collect2: error: ld returned 1 exit status
make[2]: *** [src/tracer/pin/CMakeFiles/pintool.dir/build.make:208: src/tracer/pin/libpintool.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:1205: src/tracer/pin/CMakeFiles/pintool.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 83%] Built target constraint
make: *** [Makefile:141: all] Error 2
```

Any hints as to how I should install differently? I am on Ubuntu 20.04.

**Comment by JonathanSalwan** [comment]
Did you cloned Triton into `./pin-2.14-71313-gcc.4.4.7-linux/source/tools/` ([see](https://github.com/JonathanSalwan/Triton/blob/master/.travis.yml#L93-L94))?

**Comment by BMorgan1296** [comment]
I did not, that clears up the issue, I had only copied it into the top level dir of Pin mistakenly.

Thank you.
